---
permalink: a1k/install-prepare.html 
sidebar: sidebar 
keywords: aff a1k, prepare installation 
summary: 準備好安裝 AFF A1K 平台。 
---
= 準備安裝 - AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
準備好安裝 AFF A1K 平台。

.開始之前
* 使用 https://docs.netapp.com/us-en/ontap/software_setup/index.html["叢集設定工作表"] 記錄設定叢集時所需的值。如果提供預設值、您可以使用該值或輸入自己的值。
* 確認您擁有完成硬體安裝所需的所有其他設備和工具。
+
** 2號十字螺絲起子
** 手電筒
** 防靜電繫帶
** 用於設定 NS224 機櫃 ID 的迴紋針或窄尖圓珠筆
** 具備 USB/ 序列連線的筆記型電腦或主控台
** 存取網頁瀏覽器以設定儲存系統


* 您應注意與平台重量相關的安全考量。
+
完全負載的 A1K 平台可重達 62.83 磅（ 28.5 公斤）、需要兩個人抬起或使用液壓舉升設備。

+
image::../media/drw_a1k_weight_caution_ieops-1698.svg[AFF A1K 提升注意事項圖示]

* 您應注意與機櫃重量相關的安全考量。
+
滿載的機櫃可重達 66.78 磅（ 30.29 公斤）、需要兩個人才能抬起或使用液壓起重。避免移除機櫃元件（從機櫃正面或背面）、以降低機櫃重量、因為機櫃重量會不平衡。

+
image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 舉升注意事項]

* 透過儲存系統的氣流會從安裝擋板或端蓋的前端進入、並排出連接埠所在的後端。




== 步驟 1 ：準備網站

請確定您打算使用的站台和機櫃或機架符合儲存系統的規格。

.步驟
. 確認您的站台符合平台的環境和電力需求、如所示 https://hwu.netapp.com["NetApp Hardware Universe"^]。
. 請確定您有足夠的機架空間：
+
** 適用於平台的 HA 組態中的 4U
** 2U 適用於每個 NS224 機櫃


. 在平台附近安裝任何必要的網路交換器。
+
如需安裝說明及相容性資訊、請參閱 https://docs.netapp.com/us-en/ontap-systems-switches/index.html["交換器文件"] link:https://hwu.netapp.com["NetApp Hardware Universe"^] 。





== 步驟 2 ：打開包裝盒

打開所有包裝箱的包裝、並將內容物與裝箱單上的物品進行比較。

. 小心打開所有包裝盒、並以井然有序的方式配置內容物。
. 請比較裝箱單上的清單內容。
+

NOTE: 您可以掃描運送紙箱側邊的 QR 碼、以取得裝箱清單。

+
下列項目是您可能會在方塊中看到的部分內容。

+
確保包裝箱內的所有物品都符合裝箱單上的清單。如果有任何差異、請記下這些差異以採取進一步行動。

+
[cols="12,9,4"]
|===


| *硬體* | * 纜線 * |  


 a| 
** 平台
** 機櫃
** 軌道套件附說明（選用）
** 纜線管理裝置
** 擋板

 a| 
** 電源線
** 網路纜線
** 管理乙太網路纜線（ RJ-45 纜線）
** USB-C 序列連接埠纜線
** 儲存纜線（如果訂購額外儲存設備）

|  
|===




== 步驟 3 ：註冊您的硬體

註冊您的平台可提供支援效益。

.步驟
. 找出平台的系統序號。
+
您可以在裝箱單、確認電子郵件或控制器的系統管理模組中找到編號、然後再將其解壓縮。

+
image::../media/drw_ssn_label.svg[顯示號碼位置的系統序號範例]

. 前往 NetApp 支援網站： http://mysupport.netapp.com/["mysupport.netapp.com"^]。
. 註冊硬體：
+
[role="tabbed-block"]
====
.選項 1 ：現有 NetApp 客戶
--
.步驟
.. 使用您的使用者名稱和密碼登入。
.. 選擇 * 系統 * > * 我的系統 * 。
.. 確認已列出新的系統序號。



NOTE: 如果未列出新的系統序號、請遵循適用於新 NetApp 客戶的指示。

--
.選項 2 ：新的 NetApp 客戶
--
.. 按一下*立即註冊*、然後建立帳戶。
.. 選擇 * 系統 * > * 註冊系統 * 。
.. 輸入產品系統序號和要求的詳細資料。


註冊核准後、您可以下載任何必要的軟體。核准程序可能需要24小時。

--
====

