---
permalink: a1k/install-power-hardware.html 
sidebar: sidebar 
keywords: aff a1k, power controllers 
summary: 將電源線連接到機櫃和控制器上、並為其供電。 
---
= 開啟儲存系統電源 - AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
連接網路和任何機架纜線之後、您就可以為控制器和機櫃供電了。



== 步驟 1 ：開啟機櫃電源並指派機櫃 ID

在 ONTAP 儲存系統中、每個 NS224 機櫃都以獨特的機櫃 ID 加以區分。此 ID 可確保儲存系統設定中的機櫃各有不同。根據預設、機櫃 ID 會指派為「 00 」和「 01 」、但您可能需要調整這些 ID 、以維持整個儲存系統的唯一性。

.關於這項工作
* 有效的機櫃ID為00至99。
* 您必須將機櫃關機後再開機（拔下兩條電源線、等待適當的時間、然後重新插入）、機櫃 ID 才會生效。


.步驟
. 先將電源線連接至機櫃、然後使用電源線固定器將電源線固定到位、再將電源線連接至不同電路上的電源、以開啟機櫃電源。
+
機櫃在插入電源時會自動開機和開機。

. 取下左端蓋、即可存取面板後面的機櫃 ID 按鈕。
+
image:drw_a900_oie_change_ns224_shelf_id_ieops-836.svg["變更 NS224 機櫃 ID 、寬度 = 300px"]

+
[cols="20%,80%"]
|===


 a| 
image:legend_icon_01.svg["編號 1 、寬度 = 20"]
 a| 
機櫃端蓋



 a| 
image:legend_icon_02.svg["[ 編號 2 、寬度 = 20"]
 a| 
機櫃面板



 a| 
image:legend_icon_03.svg["[ 編號 3 、寬度 = 20"]
 a| 
機櫃 ID 號碼



 a| 
image:legend_icon_04.svg["[ 編號 4 、寬度 = 20"]
 a| 
機櫃 ID 存取按鈕

|===
. 變更機櫃ID的第一個編號：
+
.. 將迴紋針或窄尖圓珠筆的拉直端插入小孔中。
.. 按住按鈕、直到數位顯示器上的第一個數字開始閃爍、然後釋放按鈕。
+
此數字可能需要15秒的時間才能開始閃爍。這會啟動機櫃ID程式設定模式。

+

NOTE: 如果ID需要15秒以上的時間才能開始閃燈、請再次按住按鈕、確定一定要完全按下。

.. 按下並釋放按鈕、將號碼往前移、直到達到所需的0到9。
+
每個新聞稿和發佈持續時間可短至一秒。

+
第一個數字會持續閃爍。



. 變更機櫃ID的第二個編號：
+
.. 按住按鈕、直到數位顯示器上的第二個數字開始閃爍。
+
最多可能需要三秒時間、才能讓號碼開始閃燈。

+
數位顯示器上的第一個數字會停止閃爍。

.. 按下並釋放按鈕、將號碼往前移、直到達到所需的0到9。
+
第二個數字會持續閃爍。



. 鎖定所需的號碼、然後按住按鈕、直到第二個數字停止閃爍、結束程式設定模式。
+
此數字可能需要三秒鐘才能停止閃爍。

+
數位顯示器上的兩個數字都會開始閃爍、ODP上的黃色LED會在約五秒後亮起、提醒您擱置中的機櫃ID尚未生效。

. 將機櫃關機至少 10 秒、使機櫃 ID 生效。
+
.. 從機櫃上的兩個電源供應器拔下電源線。
.. 等待10秒。
.. 將電源線插回機櫃電源供應器、以完成電源循環。
+
電源線插入時、電源供應器即會立即開啟。其雙色LED應會亮綠燈。



. 更換左端蓋。




== 步驟 2 ：開啟控制器電源

. 將筆記型電腦連接到序列主控台連接埠、以便在控制器通電時監控開機順序。
+
.. 將筆記型電腦上的序列主控台連接埠設為 115200 傳輸速率（ N-8-1 ）。
+

NOTE: 如需如何設定序列主控台連接埠的說明、請參閱筆記型電腦的線上說明。

.. 將主控台纜線連接至筆記型電腦、然後使用平台隨附的主控台纜線連接控制器上的序列主控台連接埠。
.. 將筆記型電腦連接到管理子網路上的交換器。
+
image:drw_a1k_70-90_console_connection_ieops-1702.svg["主控台連線"]

.. 使用位於管理子網路上的 TCP/IP 位址、將其指派給筆記型電腦。


. 將電源線插入控制器電源供應器、然後將電源線連接至不同電路上的電源。
+
image:drw_affa1k_power_source_icon_ieops-1700.svg["一般電源連線圖表"]

+
** 平台開始開機。初始開機最多可能需要八分鐘。
** LED 會亮起、風扇會啟動、表示控制器正在開機。
** 風扇第一次啟動時可能會很吵。開機期間風扇噪音很大是正常現象。


. 使用每個電源供應器上的固定裝置固定電源線。

