---
permalink: a70-90/drive-replace.html 
sidebar: sidebar 
keywords: aff a70, aff a90, replace the drives 
summary: 當平台將警告訊息記錄到系統主控台、指出磁碟機故障時、您必須更換磁碟機。此外、操作員顯示面板上的故障LED和故障磁碟機上的故障LED都會亮起。 
---
= 更換 SSD 磁碟機 - AFF A70 和 AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead lead"]
您可以在I/O進行期間、不中斷營運地更換故障的SSD磁碟機。

當磁碟機故障時、平台會將警告訊息記錄到系統主控台、指出哪個磁碟機故障。此外、操作員顯示面板上的故障LED和故障磁碟機上的故障LED都會亮起。

.開始之前
* 在更換磁碟機之前、請遵循最佳實務做法並安裝目前版本的磁碟認證套件（DQP）。
* 從系統主控台執行「shorage disk show -disf肯」命令、以識別故障的磁碟機。
+
故障磁碟機出現在故障磁碟機清單中。如果沒有、您應該稍候、然後再次執行命令。

+

NOTE: 磁碟機可能需要數小時才能出現在故障磁碟機清單中。

* 確定是否已啟用SED驗證。
+
磁碟的更換方式取決於磁碟機的使用方式。如果已啟用SED驗證、您必須使用中的SED替換指示 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/home.html["《NetApp加密電源指南》（英文）ONTAP"]。這些指示說明更換SED之前和之後、您必須執行的其他步驟。

* 請確定您的平台支援更換磁碟機。請參閱 https://hwu.netapp.com["NetApp Hardware Universe"]。
* 請確定系統中的所有其他元件都正常運作；如果沒有、您必須聯絡技術支援部門。


.關於這項工作
磁碟機韌體會自動更新（不中斷營運）、以安裝非最新韌體版本的新磁碟機。

更換數個磁碟機時、每個故障磁碟機的移除與插入替換磁碟機之間、您必須等待 70 秒、讓儲存系統能夠識別每個新磁碟的存在。

.步驟
. 請妥善接地。
. 實體識別故障磁碟機。
+
當磁碟機故障時、系統會將警告訊息記錄到系統主控台、指出哪個磁碟機故障。此外、磁碟機櫃操作員顯示面板上的警示（黃色）LED和故障磁碟機也會亮起。

+

NOTE: 故障磁碟機上的活動（綠色）LED可亮起（持續亮起）、表示磁碟機已開機、但不應閃爍、這表示I/O活動。故障磁碟機沒有I/O活動。

. 移除故障磁碟機：
+
.. 按下磁碟機面上的釋放按鈕、以開啟CAM握把。
.. 使用CAM握把將磁碟機滑出磁碟櫃、並用另一隻手支撐磁碟機。


. 請等待至少70秒、再插入替換磁碟機。
+
這可讓系統辨識磁碟機已移除。

. 插入替換磁碟機：
+
.. 在CAM握把處於開啟位置時、請用兩隻手插入更換的磁碟機。
.. 推動直到磁碟機停止。
.. 關閉 CAM 把手、使磁碟機完全插入中間背板、把手卡入定位。
+
請務必緩慢關閉CAM握把、使其與磁碟機正面正確對齊。



. 確認磁碟機的活動（綠色）LED亮起。
+
當磁碟機的活動LED持續亮起時、表示磁碟機已有電力。當磁碟機的活動LED燈在閃爍時、表示磁碟機已開機且I/O正在進行中。如果磁碟機韌體正在自動更新、LED會開始閃爍。

. 如果您要更換另一個磁碟機、請重複步驟2到6。
. 如套件隨附的RMA指示所述、將故障零件退回NetApp。
+
請聯絡技術支援人員： https://mysupport.netapp.com/site/global/dashboard["NetApp支援"]如果您需要RMA編號或更換程序的其他協助、請撥打888-463-8277（北美）、00-800-44-638277（歐洲）或+800-800-80-800（亞太地區）。


