---
permalink: a70-90/install-complete.html 
sidebar: sidebar 
keywords: aff a70, a90, prepare installation 
summary: 使用叢集探索來完成平台設定與組態、只需連線至交換器和筆記型電腦、或直接連線至儲存系統中的控制器、然後再連線至管理交換器。 
---
= 完整的儲存系統設定與組態： AFF A70 、 AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安裝硬體之後、請使用 ONTAP 軟體來設定及管理儲存系統。



== 步驟 1 ：收集叢集資訊

如果您尚未這麼做、請收集設定叢集所需的資訊、例如叢集管理介面連接埠和 IP 位址。

使用 https://docs.netapp.com/us-en/ontap/software_setup/index.html["叢集設定工作表"] 記錄叢集設定程序期間所需的值。如果提供預設值、您可以使用該值、或輸入自己的值。



== 步驟 2 ：探索叢集網路

探索程序可讓您探索網路上的儲存系統控制器。

[role="tabbed-block"]
====
.選項 1 ：已啟用網路探索
--
如果您的筆記型電腦已啟用網路探索、您可以使用自動叢集探索來完成平台設定與組態。

.步驟
. 將筆記型電腦連接到管理交換器、並存取網路電腦和裝置。
. 選取ONTAP 列出的功能表圖示以探索：
+
image::../media/drw_autodiscovery_controler_select.svg[如何使用 Windows 檔案總管探索控制器]

+
.. 開啟檔案總管。
.. 按一下左窗格中的*網路*。
.. 按一下滑鼠右鍵並選取*重新整理*。
.. 按兩下ONTAP 任一個「資訊」圖示、並接受畫面上顯示的任何憑證。
+

NOTE: xxxxx 是目標節點的平台序號。

+
系統管理程式隨即開啟。





--
.選項 2 ：未啟用網路探索
--
如果您的筆記型電腦未啟用網路探索、請使用 ONTAP 命令列介面（ CLI ）叢集設定精靈來完成組態和設定。

.開始之前
請確定您的筆記型電腦已連接至序列主控台連接埠、且控制器已開啟電源。如需相關指示、請參閱 link:install-power-hardware.html#step-2-power-on-the-controllers["開啟控制器電源"] 。

.步驟
將初始節點管理IP位址指派給其中一個節點。

[cols="1,2"]
|===
| 如果管理網路有DHCP ... | 然後... 


 a| 
已設定
 a| 
記錄指派給新控制器的IP位址。



 a| 
未設定
 a| 
. 使用Putty、終端機伺服器或您環境的等效產品來開啟主控台工作階段。
+

NOTE: 如果您不知道如何設定Putty、請查看筆記型電腦或主控台的線上說明。

. 連線至第一個節點的主控台。
+
節點會開機、然後從主控台啟動叢集設定精靈。

. 當叢集設定精靈提示時、請輸入節點的管理 IP 位址。


|===
--
====


== 步驟 3 ：設定叢集

NetApp 建議您使用系統管理員來設定新叢集。如需設定說明、請參閱 https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["使用系統管理員在新叢集上設定 ONTAP"] 。

System Manager 為叢集設定與組態提供簡單易用的工作流程、包括指派節點管理 IP 位址、初始化叢集、建立本機層、設定通訊協定、以及初始配置附加儲存設備。


NOTE: 叢集初始化之後、請下載並執行  https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"] 以確認您的設定。
