---
permalink: a70-90/io-module-add.html 
sidebar: sidebar 
keywords: aff a70, aff a90, add I/O module 
summary: 當有可用的空插槽或所有插槽都已滿時，您可以將 I/O 模組新增至 AFF A70 和 AFF A90 儲存系統。 
---
= 新增 I/O 模組 - AFF A70 和 AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當有可用的空插槽或所有插槽都已滿時，您可以將 I/O 模組新增至 AFF A70 和 AFF A90 儲存系統。



== 步驟 1 ：關閉受損的控制器模組

使用下列選項之一關閉或接管受損的控制器模組。

[role="tabbed-block"]
====
.選項1：大多數系統
--
若要關閉受損的控制器、您必須判斷控制器的狀態、並在必要時接管控制器、以便健全的控制器繼續從受損的控制器儲存設備提供資料。

.開始之前
如果叢集有兩個以上的節點、則叢集必須處於仲裁狀態。如果叢集未達到法定人數、或健全的控制器顯示為「假」、表示符合資格和健全狀況、則您必須在關閉受損的控制器之前修正問題；請參閱 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["將節點與叢集同步"^]。

.步驟
. 如果啟用 AutoSupport 、請叫用 AutoSupport 訊息命令來抑制自動建立個案： `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
下列 AutoSupport 命令會禁止自動建立案例兩小時： `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. 停用健全控制器主控台的自動恢復功能：「torage容錯移轉修改–節點本機-自動恢復錯誤」
. 將受損的控制器移至載入器提示：
+
[cols="1,2"]
|===
| 如果受損的控制器正在顯示... | 然後... 


 a| 
載入程式提示
 a| 
前往下一步。



 a| 
《等待贈品……》
 a| 
按Ctrl-C、然後在出現提示時回應「y」。



 a| 
系統提示或密碼提示（輸入系統密碼）
 a| 
從健全的控制器停止或接管受損的控制器： `storage failover takeover -ofnode _impaired_node_name_`

當受損的控制器顯示正在等待恢復...時、請按Ctrl-C、然後回應「y」。

|===


--
.選項 2 ： MetroCluster 組態
--

NOTE: 如果您的系統採用雙節點MetroCluster 的功能、請勿使用此程序。

若要關閉受損的控制器、您必須判斷控制器的狀態、並在必要時接管控制器、以便健全的控制器繼續從受損的控制器儲存設備提供資料。

* 如果叢集有兩個以上的節點、則叢集必須處於仲裁狀態。如果叢集未達到法定人數、或健全的控制器顯示為「假」、表示符合資格和健全狀況、則您必須在關閉受損的控制器之前修正問題；請參閱 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["將節點與叢集同步"^]。
* 如果您使用MetroCluster 的是功能不全的組態、則必須確認MetroCluster 已設定「功能不全」狀態、且節點處於啟用且正常的狀態（「MetroCluster 功能不全」）。


.步驟
. 如果啟用 AutoSupport 、請叫用 AutoSupport 命令來抑制自動建立個案： `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
下列 AutoSupport 命令會禁止自動建立案例兩小時： `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. 停用健全控制器主控台的自動恢復功能：「torage容錯移轉修改–節點本機-自動恢復錯誤」
. 將受損的控制器移至載入器提示：
+
[cols="1,2"]
|===
| 如果受損的控制器正在顯示... | 然後... 


 a| 
載入程式提示
 a| 
前往下一步。



 a| 
正在等待恢復...
 a| 
按Ctrl-C、然後在出現提示時回應「y」。



 a| 
系統提示或密碼提示（輸入系統密碼）
 a| 
從健全的控制器停止或接管受損的控制器： `storage failover takeover -ofnode _impaired_node_name_`

當受損的控制器顯示正在等待恢復...時、請按Ctrl-C、然後回應「y」。

|===


--
====


== 步驟 2 ：新增 I/O 模組

如果儲存系統有可用的插槽，請將新的 I/O 模組安裝到其中一個可用的插槽中。如果所有插槽都已佔用，請移除現有的 I/O 模組以騰出空間，然後安裝新的 I/O 模組。

.開始之前
* 檢查 https://hwu.netapp.com/["NetApp Hardware Universe"^] 以確定新的 I/O 模組與您執行的儲存系統和 ONTAP 版本相容。
* 如果有多個插槽可用、請檢查中的插槽優先順序 https://hwu.netapp.com/["NetApp Hardware Universe"^] 並使用適用於您I/O模組的最佳工具。
* 確定所有其他元件都正常運作。


[role="tabbed-block"]
====
.將 I/O 模組新增至可用的插槽
--
您可以在具有可用插槽的儲存系統中新增 I/O 模組。

.步驟
. 如果您尚未接地、請正確接地。
. 向下轉動纜線管理托盤、方法是拉動纜線管理托盤內部的按鈕、然後向下旋轉。
. 從載體中卸下目標插槽空白模組：
+
.. 按下目標插槽中遮光模組上的凸輪鎖扣。
.. 將 CAM 栓鎖儘量遠離模組。
.. 將手指連入凸輪桿開口處、然後將模組從機箱中拉出、即可將模組從機箱中取出。


. 安裝I/O模組：
+
.. 將 I/O 模組與機箱插槽開口的邊緣對齊。
.. 將模組一路滑入機箱中的插槽、然後將 CAM 栓鎖完全向上旋轉、將模組鎖定到位。


. 將 I/O 模組連接至指定的裝置。
+

NOTE: 請確定所有未使用的I/O插槽均已安裝空白、以避免可能的散熱問題。

. 將纜線管理承載器向上旋轉至關閉位置。
. 在 Loader 提示字元中，重新啟動節點：
+
`bye`

+

NOTE: 這會重新初始化 I/O 模組和其他元件，然後重新啟動節點。

. 從合作夥伴控制器中退回控制器：
+
`storage failover giveback -ofnode target_node_name`

. 對控制器B重複這些步驟
. 如果您停用自動恢復功能，請從健全的節點還原：
+
`storage failover modify -node local -auto-giveback _true_`

. 如果啟用 AutoSupport 、請還原自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
.將 I/O 模組新增至完全填入的系統
--
您可以移除現有的 I/O 模組，並在其所在位置安裝新的 I/O 模組，將 I/O 模組新增至完全安裝的系統。

.關於這項工作
請確定您瞭解下列案例，以便將新的 I/O 模組新增至完全填入的系統：

[cols="1,2"]
|===
| 案例 | 需要採取行動 


 a| 
NIC 對 NIC （相同數量的連接埠）
 a| 
當控制器模組關閉時、LIF會自動移轉。



 a| 
NIC 對 NIC （不同的連接埠數量）
 a| 
將選取的生命由永久重新指派至不同的主連接埠。如需詳細資訊、請參閱 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["移轉LIF"^] 。



 a| 
NIC 至儲存 I/O 模組
 a| 
使用System Manager將lifs永久移轉至不同的主連接埠、如所述 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["移轉LIF"^]。

|===
.步驟
. 如果您尚未接地、請正確接地。
. 拔下目標I/O模組上的任何纜線。
. 向下轉動纜線管理托盤、方法是拉動纜線管理托盤內部的按鈕、然後向下旋轉。
. 從機箱中移除目標I/O模組：
+
.. 按下 CAM LATCH 按鈕。
.. 將 CAM 栓鎖儘量遠離模組。
.. 將手指連入凸輪桿開口處、然後將模組從機箱中拉出、即可將模組從機箱中取出。
+
請務必追蹤I/O模組所在的插槽。



. 將 I/O 模組安裝至機箱中的目標插槽：
+
.. 將模組與機箱插槽開口的邊緣對齊。
.. 將模組一路滑入機箱中的插槽、然後將 CAM 栓鎖完全向上旋轉、將模組鎖定到位。


. 將 I/O 模組連接至指定的裝置。
. 重複執行移除和安裝步驟、以更換控制器的其他模組。
. 將纜線管理承載器向上旋轉至關閉位置。
. 從載入程式提示字元： _by_ 重新啟動控制器
+
這會重新初始化PCIe卡和其他元件、然後重新啟動節點。

+

NOTE: 如果您在重新開機期間遇到問題、請參閱 https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1494308["Burt 1494308 - 在 I/O 模組更換期間、可能會觸發環境關機"]

. 從合作夥伴控制器中退回控制器：
+
`storage failover giveback -ofnode target_node_name`

. 如果停用自動恢復功能，請啟用：
+
`storage failover modify -node local -auto-giveback true`

. 執行下列其中一項：
+
** 如果您移除 NIC I/O 模組並安裝新的 NIC I/O 模組，請針對每個連接埠使用下列 network 命令：
+
`storage port modify -node *_<node name>__ -port *_<port name>__ -mode network`

** 如果您卸下了 NIC I/O 模組並安裝了儲存 I/O 模組，請依照中所述link:../ns224/hot-add-shelf-overview.html["熱新增工作流程"]，安裝 NS224 機櫃並連接纜線。


. 對控制器B重複這些步驟


--
====