---
permalink: a900/controller_replace_complete_system_restoration_rma.html 
sidebar: sidebar 
keywords:  
summary: 若要完成更換程序並將系統還原至完整作業、您必須重新恢復儲存設備、還原NetApp儲存加密組態（如有必要）、以及安裝新控制器的授權。 
---
= 完整系統還原- AFF 還原為VA900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要完成更換程序並將系統還原至完整作業、您必須重新恢復儲存設備、還原NetApp儲存加密組態（如有必要）、以及安裝新控制器的授權。您必須先完成一系列工作、才能將系統還原至完整運作狀態。



== 步驟1：在ONTAP 更新版本中安裝更換控制器的授權

如果受損節點使用ONTAP 的是需要標準（節點鎖定）授權的功能、您必須為_replace_節點安裝新的授權。對於具有標準授權的功能、叢集中的每個節點都應該擁有自己的功能金鑰。

.關於這項工作
在您安裝授權金鑰之前、需要標準授權的功能仍可用於_replace_節點。但是、如果受損節點是叢集中唯一具有功能授權的節點、則不允許對功能進行組態變更。

此外、在節點上使用未獲授權的功能可能會使您違反授權合約、因此您應該盡快在_replace_節點上安裝替換授權金鑰或金鑰。

授權金鑰必須為28個字元的格式。

您有90天的寬限期可以安裝授權金鑰。寬限期過後、所有舊授權都會失效。安裝有效的授權金鑰之後、您有24小時的時間可以在寬限期結束之前安裝所有金鑰。

如果節點處於MetroCluster 不完整組態、且站台上的所有節點均已更換、則必須先在_replace_節點或節點上安裝授權金鑰、才能進行切換。

.步驟
. 如果您需要新的授權金鑰、請在上取得替換授權金鑰 https://mysupport.netapp.com/site/global/dashboard["NetApp 支援網站"] 在「軟體授權」下的「我的支援」區段中。
+

NOTE: 系統會自動產生您所需的新授權金鑰、並將其傳送至檔案上的電子郵件地址。如果您在30天內未收到附有授權金鑰的電子郵件、請聯絡技術支援部門。

. 安裝每個授權金鑰：「+系統授權新增-授權碼授權金鑰、授權金鑰...+」
. 視需要移除舊授權：
+
.. 檢查未使用的授權：「授權清理-未使用的-Simulate」
.. 如果清單看起來正確、請移除未使用的授權：「授權清理-未使用」






== 步驟2：驗證LIF並登錄序號

在將_replacement節點送回服務之前、您應該先確認該生命點是否位於其主連接埠上、如果AutoSupport 啟用了「BIOS」、請登錄_replacement節點的序號、然後重設自動恢復。

.步驟
. 驗證邏輯介面是否向其主伺服器和連接埠回報：「network interface show -is home-false」
+
如果有任何生命被列為假、請將其還原至其主連接埠： `network interface revert -vserver * -lif *`

. 向NetApp支援部門註冊系統序號。
+
** 如果啟用了「支援」功能、請傳送「支援」訊息來登錄序號。AutoSupport AutoSupport
** 如果AutoSupport 未啟用此功能、請致電 https://mysupport.netapp.com["NetApp支援"] 以登錄序號。


. 如果觸發 AutoSupport 維護時段、請使用結束 `system node autosupport invoke -node * -type all -message MAINT=END` 命令。
. 如果停用自動還原、請重新啟用：「儲存容錯移轉修改節點本機-自動恢復true」




== 步驟3：將故障零件歸還給NetApp

如套件隨附的RMA指示所述、將故障零件退回NetApp。如 https://mysupport.netapp.com/site/info/rma["零件退貨與更換"]需詳細資訊、請參閱頁面。
