---
permalink: asa800/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: asa a800, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: '若要將系統還原為完整運作、您必須還原NetApp儲存加密組態（如有必要）、並安裝新控制器的授權、然後將故障零件歸還給NetApp、如套件隨附的RMA指示所述。請聯絡技術支援人員： https://mysupport.netapp.com/site/global/dashboard["NetApp支援"]如果您需要RMA編號或更換程序的其他協助、請撥打888-463-8277（北美）、00-800-44-638277（歐洲）或+800-800-80-800（亞太地區）。' 
---
= 完整系統還原 - ASA A800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要將系統還原為完整運作、您必須還原NetApp儲存加密組態（如有必要）、並安裝新控制器的授權、然後將故障零件歸還給NetApp、如套件隨附的RMA指示所述。



== 步驟1：在ONTAP 更新版本中安裝更換控制器的授權

如果受損節點使用ONTAP 的是需要標準（節點鎖定）授權的功能、您必須為_replace_節點安裝新的授權。對於具有標準授權的功能、叢集中的每個節點都應該擁有自己的功能金鑰。

.關於這項工作
在您安裝授權金鑰之前、需要標準授權的功能仍可用於_replace_節點。但是、如果受損節點是叢集中唯一具有功能授權的節點、則不允許對功能進行組態變更。

此外、在節點上使用未獲授權的功能可能會使您違反授權合約、因此您應該盡快在_replace_節點上安裝替換授權金鑰或金鑰。

.開始之前
授權金鑰必須為28個字元的格式。

您有90天的寬限期可以安裝授權金鑰。寬限期過後、所有舊授權都會失效。安裝有效的授權金鑰之後、您有24小時的時間可以在寬限期結束之前安裝所有金鑰。


NOTE: 如果系統最初運行的是 ONTAP 9 ． 10.1 或更高版本，請使用中介紹的過程 https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Post_Motherboard_Replacement_Process_to_update_Licensing_on_a_AFF_FAS_system#Internal_Notes^["在AFF/FAS系統上更新授權的主機板更換程序"]。如果您不確定系統的初始 ONTAP 版本、請參閱link:https://hwu.netapp.com["NetApp Hardware Universe"^]以取得更多資訊。

.步驟
. 如果您需要新的授權金鑰、請在上取得替換授權金鑰 https://mysupport.netapp.com/site/global/dashboard["NetApp 支援網站"] 在「軟體授權」下的「我的支援」區段中。
+

NOTE: 系統會自動產生您所需的新授權金鑰、並將其傳送至檔案上的電子郵件地址。如果您在30天內未收到附有授權金鑰的電子郵件、請聯絡技術支援部門。

. 安裝每個授權金鑰：「+系統授權新增-授權碼授權金鑰、授權金鑰...+」
. 視需要移除舊授權：
+
.. 檢查未使用的授權：「授權清理-未使用的-Simulate」
.. 如果清單看起來正確、請移除未使用的授權：「授權清理-未使用」






== 步驟2：驗證LIF並登錄序號

在將_replacement節點送回服務之前、您應該先確認該生命點是否位於其主連接埠上、如果AutoSupport 啟用了「BIOS」、請登錄_replacement節點的序號、然後重設自動恢復。

.步驟
. 驗證邏輯介面是否向其主伺服器和連接埠回報：「network interface show -is home-false」
+
如果有任何生命被列為假、請將其還原至其主連接埠： `network interface revert -vserver * -lif *`

. 向NetApp支援部門註冊系統序號。
+
** 如果啟用了「支援」功能、請傳送「支援」訊息來登錄序號。AutoSupport AutoSupport
** 如果AutoSupport 未啟用此功能、請致電 https://mysupport.netapp.com["NetApp支援"] 以登錄序號。


. 檢查叢集的健全狀況。如需詳細資訊、請參閱 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["如何使用 ONTAP 中的指令碼執行叢集健全狀況檢查"^] 知識庫文章。
. 如果觸發 AutoSupport 維護時段、請使用結束 `system node autosupport invoke -node * -type all -message MAINT=END` 命令。
. 如果停用自動還原、請重新啟用：「儲存容錯移轉修改節點本機-自動恢復true」




== 步驟3：將故障零件歸還給NetApp

如套件隨附的RMA指示所述、將故障零件退回NetApp。如 https://mysupport.netapp.com/site/info/rma["零件退貨與更換"]需詳細資訊、請參閱頁面。
