---
permalink: asa800/overview.html 
sidebar: sidebar 
keywords: ASA A800 specifications, ASA A800 specs, NetApp ASA A800, ASA A800 hardware 
summary: ASA A800儲存系統的主要規格 
---
= ASA A800的主要規格
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下是ASA A800的部分規格。訪問 https://hwu.netapp.com["NetApp Hardware Universe"^]（HWU）取得ASA A800規格的完整清單。此頁面反映的是單一高可用性對。



=== ASA A800的主要規格

平台配置： ASA A800單機箱 HA 對

最大原始容量：6.6096 PB

記憶體：1280.0000 GB

外形尺寸：4U 機箱，配備 2 個 HA 控制器和 48 個驅動器插槽

ONTAP版本：b_startONTAP：9.16.1P2b_end

PCIe 擴充槽：10

最低ONTAP版本： ONTAP 9.13.1



=== 橫向擴展最大值

|===


| 類型 | HA 對 | 原始容量 | 最大記憶體 


| 網路儲存 |  |  |  


| 儲存區域網絡 | 6 | 39.7 PB / 35.2 PiB | 7680GB 


| HA 對 |  | 6.6 PB / 5.9 PiB | 1280.0000 
|===


=== 輸入輸出



==== 板載 IO

|===


| 協定 | 連接埠 


| 乙太網路 100 Gbps | 4 
|===


==== 總 IO

|===


| 協定 | 連接埠 


| 乙太網路 100 Gbps | 20 


| 乙太網路 25 Gbps | 16 


| 乙太網路 10 Gbps | 32 


| 光纖通道 32 Gbps | 32 


| NVMe/FC 32 Gbps | 32 


|  | 0 


|  | 0 


| SAS 12 Gbps | 32 
|===


==== 管理埠

|===


| 協定 | 連接埠 


| 乙太網路 1 Gbps | 4 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 4 
|===


=== 支援的儲存網絡

足球俱樂部； iSCSI； NVMe/FC； NVMe/TCP；



=== 系統環境規格

沒有可用的環境數據。



=== 遵守

* EMC/EMI 認證：AMCA、FCC、ICES、KC、摩洛哥、VCCI
* 安全認證：BIS、CB、CSA、G_K_U-SoR、IRAM、NOM、NRCS、SONCAP、TBS
* 安全/EMC/EMI認證：EAC、UKRSEPRO
* 認證安全/EMC/EMI/RoHS：BSMI、CE DoC、UKCA DoC
* 標準 EMC/EMI：BS-EN-55024、BS-EN55035、CISPR 32、EN55022、EN55024、EN55032、EN55035、EN61000-3-2、EN61000-3-3、KS 第 15 部分 A 3830 33 類
* 標準安全：ANSI/UL60950-1、ANSI/UL62368-1、BS-EN62368-1、CAN/CSA C22.2 No. 60950-1、CAN/CSA C22.2 No. 62368-1、CNS 14336、EN60825-12368-1、CNS 14336、EN60825-6 62368-1、IEC60950-1、IS 13252（第 1 部分）




=== 高可用性

以乙太網路為基礎的基板管理控制器 (BMC) 和ONTAP管理介面；冗餘熱插拔控制器；冗餘熱插拔電源；透過 SAS 連接對外部機架進行 SAS 帶內管理；
