---
permalink: a200/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: aff a200, how to recable the system, how to reassign disks 
summary: 您必須重新儲存並確認磁碟重新指派。 
---
= 重新安裝系統並重新分配磁碟- AFF VA200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
重新佈線儲存設備並確認磁碟重新指派、以繼續執行更換程序。



== 步驟1：重新連接系統纜線

執行診斷之後、您必須重新連接控制器模組的儲存設備和網路連線。

.步驟
. 重新安裝系統。
. 使用確認纜線正確無誤 https://["Active IQ Config Advisor"]。
+
.. 下載並安裝Config Advisor 此功能。
.. 輸入目標系統的資訊、然後按一下「Collect Data（收集資料）」。
.. 按一下「纜線」索引標籤、然後檢查輸出。請確定所有磁碟櫃均已顯示、且所有磁碟均顯示在輸出中、以修正您發現的任何纜線問題。
.. 按一下適當的索引標籤、然後檢查Config Advisor 來自NetApp的輸出、檢查其他纜線。






== 步驟2：重新指派磁碟

如果儲存系統位於HA配對中、則在程序結束時進行恢復時、新控制器模組的系統ID會自動指派給磁碟。在獨立式系統中、您必須手動將ID重新指派給磁碟。您必須使用正確的組態程序。



=== 選項1：驗證HA系統上的系統ID變更

您必須在開機_replaced_控制器時確認系統ID變更、然後確認變更是否已實作。

.關於這項工作
此程序僅適用於ONTAP HA配對中執行的系統。

.步驟
. 如果_replaced_控制器處於維護模式（顯示"*>"提示符）、請退出維護模式並進入載入器提示："half"（停止）
. 在_replace_控制器的載入器提示中、啟動控制器、如果系統ID不相符、系統提示您覆寫系統ID、請輸入「y」
. 請等到_replace_控制器主控台顯示「waiting for恢復...（正在等待恢復...）」訊息、然後從健全的控制器驗證是否已自動指派新的合作夥伴系統ID：「儲存容錯移轉顯示」
+
在命令輸出中、您應該會看到一則訊息、指出受損控制器上的系統ID已變更、顯示正確的舊ID和新ID。在下列範例中、node2已完成更換、新的系統ID為151759706。

+
[listing]
----
node1> `storage failover show`
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. 從健全的控制器、確認已儲存任何核心傾印：
+
.. 變更為進階權限等級：「et -priv榮幸 進階」
+
當系統提示您繼續進入進階模式時、您可以回應「Y」。出現進階模式提示（*>）。

.. 儲存任何核心傾印：「系統節點執行節點_nocal-node-name_合作夥伴儲存資源」
.. 在發出恢復之前、請等待「命令」完成。
+
您可以輸入下列命令來監控savecore命令的進度：「ystem節點run -node-node-name_合作夥伴savecore -ss」

.. 返回管理員權限等級：「et -priv. admin」


. 如果您的儲存系統已設定儲存或磁碟區加密、則必須使用下列其中一個程序來還原儲存或磁碟區加密功能、視您使用的是內建或外部金鑰管理而定：
+
** https://["還原內建金鑰管理加密金鑰"^]
** https://["還原外部金鑰管理加密金鑰"^]


. 退回控制器：
+
.. 從健全的控制器中、歸還更換的控制器儲存設備：「torage容錯移轉恢復-ofnode_replace_node_name_」
+
_replacement控制器會恢復其儲存設備並完成開機。

+
如果系統ID不相符、系統提示您覆寫系統ID、請輸入「y」。

+

NOTE: 如果被否決、您可以考慮覆寫否決。

+
http://["尋找ONTAP 適用於您版本的更新版本的高可用度組態內容"]

.. 完成恢復後、請確認HA配對正常、而且可以接管：「顯示容錯移轉」
+
「儲存容錯移轉show」命令的輸出不應包含在合作夥伴訊息中變更的系統ID。



. 驗證是否已正確分配磁碟：「torage disk show -所有權」
+
屬於_replaced_控制器的磁碟應顯示新的系統ID。在下列範例中、node1擁有的磁碟現在顯示新的系統ID：1873775277：

+
[listing]
----
node1> `storage disk show -ownership`

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----
. 驗證每個控制器是否存在預期的磁碟區：「vol. show -node-name」
. 如果您在重新開機時停用自動接管、請從健全的控制器啟用：「torage容錯移轉修改-node-node-name_-onreboottrue」




=== 選項2：手動重新指派ONTAP 系統ID給位於支援中的獨立系統

在獨立式系統中、您必須手動將磁碟重新指派給新控制器的系統ID、才能將系統恢復正常運作。

.關於這項工作

NOTE: 此程序僅適用於獨立組態的系統。

.步驟
. 如果您尚未重新啟動_replaced_節點、請按Ctrl-C中斷開機程序、然後從顯示的功能表中選取開機至維護模式的選項。
. 由於系統ID不相符、當系統提示您置換系統ID時、您必須輸入「Y」。
. 查看系統ID："Disk show -A"
. 您應該記下舊的系統ID、該ID會顯示為磁碟擁有者欄的一部分。
+
以下範例顯示舊系統ID 118673209：

+
[listing]
----
*> disk show -a
Local System ID: 118065481

  DISK      OWNER                  POOL   SERIAL NUMBER  HOME
--------    -------------          -----  -------------  -------------
disk_name    system-1  (118073209)  Pool0  J8XJE9LC       system-1  (118073209)
disk_name    system-1  (118073209)  Pool0  J8Y478RC       system-1  (118073209)
.
.
.

----
. 使用從disk show命令中獲得的系統ID資訊重新指派磁碟擁有權：「磁碟重新指派- s舊系統ID磁碟重新指派- s 118673209」
. 驗證是否正確分配了這些磁碟：「磁碟show -A」
+
屬於替換節點的磁碟應顯示新的系統ID。以下範例現在顯示系統1擁有的磁碟、新的系統ID 118065481：

+
[listing]
----
*> disk show -a
Local System ID: 118065481

  DISK      OWNER                  POOL   SERIAL NUMBER  HOME
--------    -------------          -----  -------------  -------------
disk_name    system-1  (118065481)  Pool0  J8Y0TDZC       system-1  (118065481)
disk_name    system-1  (118065481)  Pool0  J8Y0TDZC       system-1  (118065481)
.
.
.

----
. 如果您的儲存系統已設定儲存或磁碟區加密、則必須使用下列其中一個程序來還原儲存或磁碟區加密功能、視您使用的是內建或外部金鑰管理而定：
+
** https://["還原內建金鑰管理加密金鑰"^]
** https://["還原外部金鑰管理加密金鑰"^]


. 開機節點：「boot_ONTAP」

