---
permalink: a220/bootmedia-shutdown.html 
sidebar: sidebar 
keywords: fas2700, aff a220, shut, down, impaired, controller, take, over 
summary: 根據儲存系統硬體組態的不同、您可以使用不同的程序來關閉或接管受損的控制器。 
---
= 關閉受損控制器 - AFF A220
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用適合您組態的適當程序來關閉或接管受損的控制器。



== 選項1：大多數組態

完成NVE或NSE工作之後、您必須完成受損控制器的關機。

.步驟
. 將受損的控制器移至載入器提示：
+
[cols="1,2"]
|===
| 如果受損的控制器顯示... | 然後... 


 a| 
載入程式提示
 a| 
移至「移除控制器模組」。



 a| 
《等待贈品……》
 a| 
按Ctrl-C、然後在出現提示時回應「y」。



 a| 
系統提示或密碼提示（輸入系統密碼）
 a| 
從健全的控制器接管或停止受損的控制器：「torage容錯移轉接管-節點受損節點名稱」

當受損的控制器顯示正在等待恢復...時、請按Ctrl-C、然後回應「y」。

|===
. 在載入器提示字元中、輸入：「prontenv」以擷取所有開機環境變數。將輸出儲存至記錄檔。
+

NOTE: 如果開機裝置毀損或無法運作、此命令可能無法運作。





== 選項2：控制器位於MetroCluster 一個不二之處

完成NVE或NSE工作之後、您必須完成受損控制器的關機。


NOTE: 如果您的系統採用雙節點MetroCluster 的功能、請勿使用此程序。

若要關閉受損的控制器、您必須判斷控制器的狀態、並在必要時接管控制器、以便健全的控制器繼續從受損的控制器儲存設備提供資料。

* 如果叢集有兩個以上的節點、則叢集必須處於仲裁狀態。如果叢集未達到法定人數、或健全的控制器顯示為「假」、表示符合資格和健全狀況、則您必須在關閉受損的控制器之前修正問題；請參閱 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["將節點與叢集同步"^]。
* 如果您使用MetroCluster 的是功能不全的組態、則必須確認MetroCluster 已設定「功能不全」狀態、且節點處於啟用且正常的狀態（「MetroCluster 功能不全」）。


.步驟
. 如果啟用了此功能、請叫用下列訊息來抑制自動建立案例：「System Node現象叫用節點*-type all -Message MAn=number_of_hs_Downh」AutoSupport AutoSupport AutoSupport
+
下列AutoSupport 資訊不顯示自動建立案例兩小時的訊息：「cluster1：*>系統節點AutoSupport 、叫用節點*-輸入ALL -Message MAn=2h」

. 停用健全控制器主控台的自動恢復功能：「torage容錯移轉修改–節點本機-自動恢復錯誤」
. 將受損的控制器移至載入器提示：
+
[cols="1,2"]
|===
| 如果受損的控制器正在顯示... | 然後... 


 a| 
載入程式提示
 a| 
前往下一步。



 a| 
正在等待恢復...
 a| 
按Ctrl-C、然後在出現提示時回應「y」。



 a| 
系統提示或密碼提示（輸入系統密碼）
 a| 
從正常控制器接管或停止受損的控制器：「torage容錯移轉接管-節點_受損節點_節點名稱_」

當受損的控制器顯示正在等待恢復...時、請按Ctrl-C、然後回應「y」。

|===

