---
settings:
  search: ontap-systems
  name: ONTAP Systems
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,ja-jp,zh-cn,ko-kr
sidebar:
  entries:
  - title: 系統文件AFF FAS
    url: "/index.html"
  - title: 開始使用
    entries:
    - title: 新增功能
      url: "/whats-new.html"
    - title: 版本資訊
      url: "/rel-notes.html"
  - title: 系統AFF
    entries:
    - section: c190
    - section: a200
    - section: a220
    - section: a250
    - section: a300
    - section: a320
    - section: a400
    - section: a700
    - section: a700s
    - section: a800
    - section: a900
  - title: 系統FAS
    entries:
    - section: fas500f
    - section: fas2600
    - section: fas2700
    - section: fas8200
    - section: fas8300
    - section: fas9000
    - section: fas9500
  - section: allsan
  - section: upgrade
  - title: 系統層級診斷
    entries:
    - title: 簡介
      url: "/platform-supplemental/sldiag-introduction.html"
    - title: 需求
      url: "/platform-supplemental/sldiag-requirements.html"
    - title: 如何使用命令列說明
      url: "/platform-supplemental/sldiag-use-cli-help.html"
    - title: 執行系統安裝診斷
      url: "/platform-supplemental/sldiag-system-installation-diagnostics.html"
    - title: 執行系統嚴重問題診斷
      url: "/platform-supplemental/sldiag-system-panic-diagnostics.html"
    - title: 執行慢速系統回應診斷
      url: "/platform-supplemental/sldiag-slow-system-diagnostics.html"
    - title: 執行硬體安裝診斷
      url: "/platform-supplemental/sldiag-hardware-installation-diagnostics.html"
    - title: 執行裝置故障診斷
      url: "/platform-supplemental/sldiag-device-failure-diagnostics.html"
  - title: 磁碟機櫃
    entries:
    - section: ns224
    - section: sas3
  - section: switch
  - title: 機櫃與軌道套件
    entries:
    - title: 超級軌道套件
      url: "/platform-supplemental/superrail-install.html"
    - title: FASA700/FAS9000雙柱軌道套件AFF
      url: "/platform-supplemental/telco-installation-instructions.html"
    - title: 42U 1、280公釐系統機櫃
      entries:
      - title: 準備安裝機櫃
        entries:
        - title: 機櫃功能
          url: "/platform-supplemental/42u-1280mm-features.html"
        - title: 必要工具/設備
          url: "/platform-supplemental/42u-1280mm-required-tools.html"
        - title: 空間需求與機櫃尺寸
          url: "/platform-supplemental/42u-1280mm-space-and-dimensions.html"
        - title: 支援的PDU類型與規格
          url: "/platform-supplemental/42u-1280mm-supported-pdu-types-and-specifications.html"
      - title: 打開系統機櫃
        url: "/platform-supplemental/42u-1280mm-unpack.html"
      - title: 安裝機櫃
        entries:
        - title: 總覽
          url: "/platform-supplemental/42u-1280mm-install.html"
        - title: 安裝機櫃互連套件
          url: "/platform-supplemental/42u-1280mm-install-cabinet-interconnect-kit.html"
        - title: 安裝栓接套件
          url: "/platform-supplemental/42u-1280mm-install-bolt-down-kit.html"
        - title: 安裝支撐軌道
          url: "/platform-supplemental/42u-1280mm-install-additional-rails.html"
        - title: 安裝設備
          url: "/platform-supplemental/42u-1280mm-install-equipment.html"
        - title: 開啟機櫃電源
          url: "/platform-supplemental/42u-1280mm-power-on.html"
      - title: 更換PDU
        url: "/platform-supplemental/42u-1280mm-replace-pdus.html"
      - title: 翻轉機櫃前側擋門
        entries:
        - title: 您需要的一切
          url: "/platform-supplemental/42u-1280mm-reverse-front-door.html"
        - title: 移除發光的徽章
          url: "/platform-supplemental/42u-1280mm-remove-illuminated-badge.html"
        - title: 拆下機櫃門
          url: "/platform-supplemental/42u-1280mm-remove-door.html"
        - title: 移動標牌電源供應器和纜線
          url: "/platform-supplemental/42u-1280mm-move-badge-ps-and-cabling.html"
        - title: 反轉門的轉軸和鎖扣
          url: "/platform-supplemental/42u-1280mm-reverse-hinge-and-lock.html"
        - title: 重新安裝門並點亮徽章
          url: "/platform-supplemental/42u-1280mm-reinstall-door-and-badge.html"
  - section: other
  - title: 法律聲明
    url: "/legal-notices.html"
