---
sidebar: sidebar 
permalink: supported-platforms.html 
keywords: new, features, asa r2, aff, asa, fas 
summary: 瞭解適用於您平台或機櫃的 ONTAP 支援版本。 
---
= ONTAP 硬體與軟體相容性
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ONTAP 儲存系統與多個版本的 ONTAP 軟體相容。瞭解儲存系統和磁碟櫃支援的 ONTAP 版本。

ONTAP 硬體系統的完整組態支援與限制 https://hwu.netapp.com["NetApp Hardware Universe"]請參閱。有關 ONTAP 9 軟體中已知問題，限制及升級注意事項的詳細資料，請參閱 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["發行說明ONTAP"]。

[role="tabbed-block"]
====
.系統AFF
--
AFF A 系列和 AFF C 系列系統提供專為虛擬化環境量身打造的強大橫向擴充平台。它們可以部署為獨立式系統，或部署為 NetApp ONTAP 組態中的高效能階層。link:https://www.netapp.com/data-storage/all-flash-san-storage-array["深入瞭解 AFF 系統"]。

從下列 ONTAP 版本開始，就支援 AFF A 系列和 AFF C 系列系統。

ONTAP 9.16.1.::
+
--
* AFF A20
* AFF A30
* AFF A50
* AFF C30
* AFF C60
* AFF C80


--
ONTAP 9.15.1.1::
+
--
* AFF A1K
* AFF A70
* AFF A90


--
ONTAP 9.12.1P1::
+
--
* 解答150 AFF
* C250 AFF
* C400 AFF
* C800 AFF


--
零點9.10.1 ONTAP::
+
--
* 解答900 AFF


--
部分9.8 ONTAP::
+
--
* VA250 AFF


--
更新ONTAP::
+
--
* 解答400 AFF
* 解答800 AFF


--


--
.ASA r2 系統
--
ASA R2 系統提供統一化的硬體與軟體解決方案，可針對僅限 SAN 的客戶需求，提供簡化的體驗。link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["深入瞭解 ASA R2 系統"]。

從下列 ONTAP 版本開始，就支援 ASA R2 系統。

ONTAP 9.16.1.::
+
--
* ASA A20
* ASA A30
* ASA A50


--
ONTAP 9.16.0.::
+
--
* ASA A1K
* ASA A70
* ASA A90


--


--
.系統ASA
--
ASA A 系列和 ASA C 系列系統提供簡化且專屬的 SAN 體驗，可為企業關鍵任務資料庫及其他使用 FCP 或 iSCSI 傳輸協定的 SAN 工作負載提供持續的資料可用度。link:https://www.netapp.com/data-storage/all-flash-san-storage-array["深入瞭解 ASA 系統"]。

從下列 ONTAP 版本開始，就支援 ASA 系統。

ONTAP 9.13.1P1::
+
--
* ASA C250
* ASA C400
* ASA C800


--
ONTAP 9.13.1.12.9.11.9.11.::
+
--
* ASA A150
* ASA A250
* ASA A400
* ASA A900


--
部分9.8 ONTAP::
+
--
* ASA AFF A250
* ASA AFF A800


--
更新ONTAP::
+
--
* ASA AFF A400


--


--
.系統FAS
--
FAS 系統提供高效率且安全的次要儲存設備，這是分層，備份和災難恢復的終極解決方案。link:https://www.netapp.com/data-storage/fas/["深入瞭解 FAS 系統"]。

從下列 ONTAP 版本開始，就支援 FAS 系統。

ONTAP 9.15.1.1::
+
--
* FAS70
* FAS90


--
ONTAP 9.13.1.12.9.11.9.11.::
+
--
* FAS2820


--
零點9.11.1. ONTAP::
+
--
* FAS9500


--
ONTAP 9.10.1P3::
+
--
* FAS9500


--
更新ONTAP::
+
--
* FAS2750
* FAS8300
* FAS8700


--


--
.磁碟機櫃
--
磁碟機櫃專為 NetApp AFF ， ASA 和 FAS 系統所設計，可協助提供數位轉型所需的效能，恢復能力和靈活度。

磁碟機櫃從下列 ONTAP 版本開始供應。

ONTAP 9.16.1.:: NS224 搭配 NSM100B 模組
部分9.6 ONTAP:: NS224 機櫃，含 NSM100 模組


--
====