---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, afx, asa r2, aff, asa, fas 
summary: 瞭解 ONTAP 硬體系統的新平台。 
---
= ONTAP 硬體系統的新功能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
瞭解 ONTAP 硬體系統的新功能。有關其他支持信息，請參閱link:supported-platforms.html["ONTAP 硬體與軟體相容性"]和link:eoa-hardware.html["不再支援硬體"] 。



== 2026 年 1 月



=== I/O 模組熱插拔程序

現在，多個 ONTAP 硬體平台和 ONTAP 版本中的特定 I/O 模組均可支援熱插拔程序。

*ONTAP 9.18.1 GA 或更新版本支援：*

只要乙太網路 I/O 模組的連接埠用於叢集、HA 或用戶端連線，您就可以在任何插槽中熱插拔故障的乙太網路 I/O 模組。此程序適用於任何節點數量的系統。


NOTE: 如果乙太網路 I/O 模組的連接埠已指派給儲存或 MetroCluster 連接，則無法熱插拔該模組。

支援以下平台：

* AFF A 系列：A1K、A20、A30、A50、A70 和 A90
* ASA r2：A1K、A20、A30、A50、A70、A90 和 C30
* AFF C 系列：C30、C60 和 C80
* FAS：FAS50、FAS70 和 FAS90
* AFX：AFX 1K


*ONTAP 9.17.1 或 9.18.1RC 支援：*

為避免雙節點叢集中斷，僅當受損控制器（即具有故障模組的控制器）已接管正常合作夥伴時，才能在插槽 4 中熱插拔故障叢集和 HA I/O 模組。這是唯一無需停機即可恢復的支援方法。

支援以下平台：

* AFF A 系列：A20、A30 和 A50
* ASA r2：A20、A30、A50 和 C30
* AFF C 系列：C30 和 C60
* FAS：FS50




=== AFF C800 停產

AFF C800 系統已移至停產清單，不再接受新訂單。

link:endofavail/index.html["檢視停產硬體"]。



== 2025 年發布

.2025年10月
[%collapsible]
====
.AFX儲存系統
全新NetApp AFX 儲存系統提供分解式解決方案，旨在滿足高效能 NAS 和 S3 工作負載（包括 AI/ML 應用程式）的嚴格要求。AFX 系統為需要可擴充、高吞吐量檔案和物件儲存的客戶提供專門的功能。

link:https://docs.netapp.com/us-en/ontap-afx/get-started/ontap-afx-storage.html["了解有關 AFX 系統的更多信息"] 。

.AFX 的新驅動器架
AFX 的新型 NXS224 儲存架使用非揮發性記憶體快速架構 (NVMe-oF) 連接高密度 SSD。磁碟使用融合乙太網路上的 RDMA (RoCE) 透過超低延遲結構進行通訊。儲存架（包括 I/O 模組、NIC、風扇和電源供應器）完全冗餘，沒有單點故障。自管理技術用於管理和控制 RAID 配置和磁碟佈局的各個方面。

.AFX 的新開關
Cisco 9364D-GX2A 交換器和Cisco 9332D-GX2B 交換器將 AFX 控制器節點與儲存架連接。這些新交換器可讓您建立具有兩個以上節點的ONTAP叢集。使用先進的協定來優化效能。此設計基於具有多個網路路徑的 VLAN 標記以及技術更新配置，以確保持續運行和輕鬆升級。

====
.2025年9月
[%collapsible]
====
.平台規格
ONTAP硬體系統文件現在包括以下規格：link:https://hwu.netapp.com["Hardware Universe"] 。例如，link:https://docs.netapp.com/us-en/ontap-systems/a1k/overview.html["AFF A1K的主要規格"] 。

.按平台系列劃分的替換參考
ONTAP硬體系統文件現在提供按平台系列組織的NetApp儲存系統的更換程序。

link:fru-reference/index.html["尋找取代程序"]用於儲存系統的現場可更換單元 (FRU)。

====
.2025 年 5 月
[%collapsible]
====
.ASA C30
全新ASA C30系統將高效能、智慧、全面的資料管理功能擴展到更多客戶和工作負載。

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["深入瞭解 ASA R2 系統"^] 。

====
.2025 年 4 月
[%collapsible]
====
.FAS50
FAS50 系統為二級儲存和安全網路保險庫提供了最低的每 GB 成本，同時透過更快的備份、更高的 IOPS 和 5-10 毫秒的低延遲提高了二級工作負載的效能。

link:https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["深入瞭解 FAS 系統"^] 。

====
.2025 年 2 月
[%collapsible]
====
.ASA A20 ， ASA A30 和 ASA A50
入門級 ASA A20 和中階 ASA A30 和 A50 系統可為各種規模的公司提供區塊儲存，適用於資料庫和虛擬機器等關鍵任務應用程式。

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["深入瞭解 ASA R2 系統"^] 。

====


== 2024 年發行

.2024 年 12 月
[%collapsible]
====
.AFF A20 、 AFF A30 和 AFF A50
全新的 AFF A20 ， A30 和 A50 硬體系統可將高效能，智慧型和全方位的資料管理功能延伸至更多客戶和工作負載。

這些系統提供即時的 ML 型勒索軟體偵測，無縫的雲端整合，以及無與倫比的效能，可支援區塊，檔案和物件儲存，適用於 AI ， VMware ，資料庫和分析等關鍵任務工作負載。

link:https://www.netapp.com/aff-a-series/["深入瞭解 AFF A 系列系統"^]。

.AFF C30 、 AFF C60 和 AFF C80
全新的 AFF C30 ， AFF C60 和 AFF C80 硬體系統可在雙機架部署中提供領先業界的 1.5PB 儲存容量，讓企業更容易存取 Flash 的效能與效率提升。

此解決方案具備 60 TB 磁碟機的優異密度，更高的效能，以及更高的 I/O 靈活度。

link:https://www.netapp.com/data-storage/aff-c-series/["深入瞭解 AFF C 系列系統"^] 。

.NS224 磁碟機櫃，含 NSM100B 機櫃模組
使用 NS224 和全新的 NSM100B NVMe 儲存擴充模組，增強資料中心的功能。全新的 NSM100B 機櫃模組是專為直接取代 NSM100 模組而設計，可無縫整合至您現有的設定中。它同時支援 NS224 機櫃的直接附加組態和交換器附加組態，提供優異的靈活度，可最佳化儲存系統的效率和擴充性。

====
.2024 年 9 月
[%collapsible]
====
.ASA r2 系統
全新的 ASA R2 硬體系統（ ASA A1K ， ASA A70 和 ASA A90 ）提供統一化的硬體與軟體解決方案，可針對僅限 SAN 的客戶需求，提供簡化的體驗。

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["深入瞭解 ASA R2 系統"^] 。

.FAS70 和 FAS90
全新 FAS70 和 FAS90 硬體系統提供經濟實惠且效能優異的備份儲存設備，讓安全的網路資料保險箱能夠從勒索軟體攻擊中恢復。

link:https://www.netapp.com/data-storage/fas/["深入瞭解 FAS 系統"^] 。

====