---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, asa r2, aff, asa, fas 
summary: 瞭解 ONTAP 硬體系統的新平台。 
---
= ONTAP 硬體系統的新功能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
瞭解 ONTAP 硬體系統的新功能。有關其他支持信息，請參閱link:supported-platforms.html["ONTAP 硬體與軟體相容性"]和link:eoa-hardware.html["不再支援硬體"] 。



== 2025年9月



=== 平台規格

ONTAP硬體系統文件現在包括以下規格：link:https://hwu.netapp.com["Hardware Universe"] 。例如，link:https://docs.netapp.com/us-en/ontap-systems_hotfix-main/a1k/overview.html["AFF A1K的主要規格"] 。



=== 平台 FRU 程式參考

ONTAP硬體系統文件現在包含按 FRU 類型組織的 FRU 程式連結。

link:fru-reference/fru-overview.html["平台 FRU 參考"]



== 2025 年 5 月



=== ASA C30

全新ASA C30系統將高效能、智慧、全面的資料管理功能擴展到更多客戶和工作負載。

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["深入瞭解 ASA R2 系統"]。



== 2025 年 4 月



=== FAS50

FAS50 系統可為次要儲存設備和提供最低的每 GB 成本link:https://docs.netapp.com/us-en/netapp-solutions/cyber-vault/ontap-cyber-vault-overview.html["安全的網路儲存庫"]，並以更快的備份速度，更高的 IOPS ，以及 5 – 10 毫秒的低延遲，為次要工作負載提供更高的效能。

link:https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["深入瞭解 FAS 系統"]。



== 2025 年 2 月



=== ASA A20 ， ASA A30 和 ASA A50

入門級 ASA A20 和中階 ASA A30 和 A50 系統可為各種規模的公司提供區塊儲存，適用於資料庫和虛擬機器等關鍵任務應用程式。

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["深入瞭解 ASA R2 系統"]。



== 2024 年 12 月



=== AFF A20 、 AFF A30 和 AFF A50

全新的 AFF A20 ， A30 和 A50 硬體系統可將高效能，智慧型和全方位的資料管理功能延伸至更多客戶和工作負載。

這些系統提供即時的 ML 型勒索軟體偵測，無縫的雲端整合，以及無與倫比的效能，可支援區塊，檔案和物件儲存，適用於 AI ， VMware ，資料庫和分析等關鍵任務工作負載。

link:https://www.netapp.com/data-storage/aff-a-series/["深入瞭解 AFF A 系列系統"]。



=== AFF C30 、 AFF C60 和 AFF C80

全新的 AFF C30 ， AFF C60 和 AFF C80 硬體系統可在雙機架部署中提供領先業界的 1.5PB 儲存容量，讓企業更容易存取 Flash 的效能與效率提升。

此解決方案具備 60 TB 磁碟機的優異密度，更高的效能，以及更高的 I/O 靈活度。

link:https://www.netapp.com/data-storage/aff-c-series/["深入瞭解 AFF C 系列系統"]。



=== NS224 磁碟機櫃，含 NSM100B 機櫃模組

使用 NS224 和全新的 NSM100B NVMe 儲存擴充模組，增強資料中心的功能。全新的 NSM100B 機櫃模組是專為直接取代 NSM100 模組而設計，可無縫整合至您現有的設定中。它同時支援 NS224 機櫃的直接附加組態和交換器附加組態，提供優異的靈活度，可最佳化儲存系統的效率和擴充性。



== 2024 年 9 月



=== ASA r2 系統

全新的 ASA R2 硬體系統（ ASA A1K ， ASA A70 和 ASA A90 ）提供統一化的硬體與軟體解決方案，可針對僅限 SAN 的客戶需求，提供簡化的體驗。

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["深入瞭解 ASA R2 系統"]。



=== FAS70 和 FAS90

全新 FAS70 和 FAS90 硬體系統提供經濟實惠且效能優異的備份儲存設備，讓安全的網路資料保險箱能夠從勒索軟體攻擊中恢復。

link:https://www.netapp.com/data-storage/fas/["深入瞭解 FAS 系統"]。
