---
permalink: c80/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: c80, how to recable the system, teboot the system 
summary: 將儲存資源的控制權交給更換控制器，讓 AFF C80 系統恢復正常運作。 
---
= 可回收並退回控制器 - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
將儲存資源的控制權交給更換控制器，讓 AFF C80 系統恢復正常運作。回饋程序會因系統使用的加密類型而異：無加密，內建金鑰管理程式（ OKM ）加密或外部金鑰管理程式（ EKM ）加密。

[role="tabbed-block"]
====
.無加密
--
將受損的控制器歸還其儲存設備，使其恢復正常運作。

.步驟
. 在 Loader 提示符下，輸入 `boot_ontap`。
. 主控台訊息停止時、按 <enter> 。
+
** 如果您看到 _login_ 提示、請前往本節結尾的下一個步驟。
** 如果您看到 _waiting for 贈品、請按下 <enter> 鍵、登入合作夥伴節點、然後前往本節結尾的下一步。


. 將受損的控制器歸還其儲存設備、使其恢復正常運作：
+
`storage failover giveback -ofnode _impaired_node_name_`。

. 如果自動恢復已停用、請重新啟用：
+
`storage failover modify -node local -auto-giveback true`。

. 如果啟用 AutoSupport ，則還原 / 恢復自動建立個案：
+
`system node autosupport invoke -node * -type all -message MAINT=END`。



--
.OKM加密
--
重設內建加密，並將控制器恢復正常運作。

.步驟
. 在 Loader 提示字元中，輸入：
+
`boot_ontap maint`

. 從 Loader 提示字元開機至 ONTAP 功能表 `boot_ontap menu`、然後選取選項 10 。
. 輸入 OKM 複雜密碼。您可以向客戶索取此通關密碼、或聯絡 https://support.netapp.com["NetApp支援"]。
+

NOTE: 系統會提示您輸入兩次密碼。

. 出現提示時輸入備份金鑰資料。
. 在開機功能表中、輸入正常開機的選項 `1`。
. 顯示 _ 正在等待恢復 _ 時、請按 <enter> 。
. 將主控台纜線移至合作夥伴節點、然後以登入 `admin`。
. 僅回饋 CFO 集合體（根集合體）：
+
`storage failover giveback -fromnode local -only-cfo-aggregates true`

+
如果您遇到錯誤、請聯絡 https://support.netapp.com["NetApp支援"]。

. 在恢復報告完成後等待 5 分鐘，並檢查容錯移轉狀態和恢復狀態：
+
`storage failover show`和 `storage failover show-giveback`。

. 將主控台纜線移至更換節點，然後輸入：
+
`security key-manager onboard sync`

+

NOTE: 系統會提示您輸入叢集範圍的 OKM 複雜密碼。

. 使用下列命令檢查金鑰的狀態：
+
`security key-manager key query -key-type svm-KEK`。

+
如果 _RESTOREURE_ 欄顯示 _true_ 以外的任何內容、請聯絡 https://support.netapp.com["NetApp支援"]。

. 將受損的控制器歸還其儲存設備、使其恢復正常運作：
+
`storage failover giveback -ofnode _impaired_node_name_`。

. 如果自動恢復已停用、請重新啟用：
+
`storage failover modify -node local -auto-giveback true`。

. 如果啟用 AutoSupport ，則還原 / 恢復自動建立個案：
+
`system node autosupport invoke -node * -type all -message MAINT=END`。



--
.EKM加密
--
重設加密，並將控制器恢復正常運作。

.步驟
. 如果根磁碟區是使用外部金鑰管理程式加密、且主控台纜線已連接至替換節點、請輸入 `boot_ontap menu`並選擇選項 `11`。
. 回答或 `n`回答 `y`下列問題：
+
您是否有 /ccfcard/kmip/certs/client.crt 檔案的複本？｛ y/n ｝

+
您是否擁有 /ccfcard/kmip/certs/client.key 檔案的複本？｛ y/n ｝

+
您是否擁有 /ccfcard/kmip/certs/ca.pem 檔案的複本？｛ y/n ｝

+
或

+
您是否有 /ccfcard/kmip/servers.cfg 檔案的複本？｛ y/n ｝

+
您知道 KMIP 伺服器位址嗎？｛ y/n ｝

+
您知道 KMIP 連接埠嗎？｛ y/n ｝

+

NOTE: 如有任何問題、請聯絡 https://support.netapp.com["NetApp支援"]。

. 提供以下資訊：
+
** 用戶端憑證（ client.crt ）檔案內容。
** 用戶端金鑰（ client.key ）檔案內容。
** KMIP 伺服器 CA （ CA.pem ）檔案內容。
** KMIP 伺服器的 IP 位址。
** KMIP 伺服器的連接埠。


. 系統處理完畢後、您將會看到 Boot Menu （開機功能表）。選擇「 1 」以進行正常開機。
. 檢查接管狀態：
+
`storage failover show`。

. 將功能受損的控制器恢復正常運作，只需歸還其儲存設備 `storage failover giveback -ofnode _impaired_node_name_`：。
. 如果自動恢復已停用、請重新啟用：
+
`storage failover modify -node local -auto-giveback true`。

. 如果啟用 AutoSupport ，則還原 / 恢復自動建立個案：
+
`system node autosupport invoke -node * -type all -message MAINT=END`。



--
====
.接下來呢？
將儲存資源的擁有權移回更換控制器後，您需要link:controller-replace-restore-system-rma.html["完成控制器更換"]進行程序。
