---
permalink: c80/drive-replace.html 
sidebar: sidebar 
keywords: c80, replace the drives 
summary: 當磁碟機故障或需要升級時，請更換 AFF C80 系統中的磁碟機。此程序包括識別故障磁碟機，安全地移除磁碟機，以及安裝新磁碟機，以確保資料存取和系統效能不中斷。 
---
= 更換 SSD 磁碟機 - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當磁碟機故障或需要升級時，請更換 AFF C80 系統中的磁碟機。此程序包括識別故障磁碟機，安全地移除磁碟機，以及安裝新磁碟機，以確保資料存取和系統效能不中斷。

您可以在I/O進行期間、不中斷營運地更換故障的SSD磁碟機。

當磁碟機故障時、平台會將警告訊息記錄到系統主控台、指出哪個磁碟機故障。此外、操作員顯示面板上的故障LED和故障磁碟機上的故障LED都會亮起。

.開始之前
* 在更換磁碟機之前、請遵循最佳實務做法並安裝目前版本的磁碟認證套件（DQP）。
* 從系統主控台執行「shorage disk show -disf肯」命令、以識別故障的磁碟機。
+
故障磁碟機出現在故障磁碟機清單中。如果沒有、您應該稍候、然後再次執行命令。

+
磁碟機可能需要數小時才能出現在故障磁碟機清單中。

* 確定是否已啟用SED驗證。
+
如何更換磁碟取決於磁碟機的使用方式。如果啟用了 SED 身份驗證，則必須使用 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/home.html["《NetApp加密電源指南》（英文）ONTAP"]。這些說明描述了更換 SED 之前和之後必須執行的附加步驟。

* 確保您的平台支援替換的驅動器。看 https://hwu.netapp.com["NetApp Hardware Universe"]。
* 請確定系統中的所有其他元件都正常運作；如果沒有、您必須聯絡技術支援部門。


.關於這項工作
磁碟機韌體會自動更新（不中斷營運）、以安裝非最新韌體版本的新磁碟機。

更換數個磁碟機時、每個故障磁碟機的移除與插入替換磁碟機之間、您必須等待 70 秒、讓儲存系統能夠識別每個新磁碟的存在。

您可以手動指派磁碟機擁有權、然後在本程序稍後重新啟用自動磁碟機指派。

.步驟
. 如果您想要手動指派替換磁碟機的磁碟機所有權，則需要停用自動磁碟機指派（如果已啟用）。
+
.. 驗證是否已啟用自動磁碟指派：「torage disk option show」
+
您可以在任一控制器模組上輸入命令。

+
如果啟用自動磁碟指派、輸出會在「Auto assign」（自動指派）欄中顯示「On」（開啟）（針對每個控制器模組）。

.. 如果已啟用自動磁碟指派、請停用此功能：「torage disk option modify -node_name -autodassign Off」（磁碟選項修改-node_name -autodassign Off）
+
您必須停用兩個控制器模組上的自動磁碟機指派。



. 請妥善接地。
. 實體識別故障磁碟機。
+
當磁碟機故障時、系統會將警告訊息記錄到系統主控台、指出哪個磁碟機故障。此外、磁碟機櫃操作員顯示面板上的警示（黃色）LED和故障磁碟機也會亮起。

+

NOTE: 故障磁碟機上的活動（綠色）LED可亮起（持續亮起）、表示磁碟機已開機、但不應閃爍、這表示I/O活動。故障磁碟機沒有I/O活動。

. 移除故障磁碟機：
+
.. 按下磁碟機面上的釋放按鈕、以開啟CAM握把。
.. 使用CAM握把將磁碟機滑出磁碟櫃、並用另一隻手支撐磁碟機。


. 請等待至少70秒、再插入替換磁碟機。
+
這可讓系統辨識磁碟機已移除。

. 插入替換磁碟機：
+
.. 在CAM握把處於開啟位置時、請用兩隻手插入更換的磁碟機。
.. 推動直到磁碟機停止。
.. 關閉 CAM 把手、使磁碟機完全插入中間背板、把手卡入定位。
+
請務必緩慢關閉CAM握把、使其與磁碟機正面正確對齊。



. 確認磁碟機的活動（綠色）LED亮起。
+
當磁碟機的活動LED持續亮起時、表示磁碟機已有電力。當磁碟機的活動LED燈在閃爍時、表示磁碟機已開機且I/O正在進行中。如果磁碟機韌體正在自動更新、LED會開始閃爍。

. 如果要更換另一個驅動器，請重複步驟 3 至 7。
. 如果您在步驟 1 中停用自動磁碟機指派，請手動指派磁碟機擁有權，然後視需要重新啟用自動磁碟機指派。
+
.. 顯示所有未擁有的磁碟機：
+
`storage disk show -container-type unassigned`

+
您可以在任一控制器模組上輸入命令。

.. 指派每個磁碟機：
+
`storage disk assign -disk disk_name -owner node_name`

+
您可以在任一控制器模組上輸入命令。

+
您可以使用萬用字元一次指派多個磁碟機。

.. 如有需要，請重新啟用自動磁碟機指派：
+
`storage disk option modify -node node_name -autoassign on`

+
您必須在兩個控制器模組上重新啟用自動磁碟機指派。



. 如套件隨附的RMA指示所述、將故障零件退回NetApp。
+
接觸 https://mysupport.netapp.com/site/global/dashboard["NetApp支援"]如果您需要 RMA 號碼或更換程式的額外協助。


