---
permalink: c80/overview.html 
sidebar: sidebar 
keywords: AFF C80 specifications, AFF C80 specs, NetApp AFF C80, AFF C80 hardware 
summary: AFF C80 儲存系統的主要規格 
---
= AFF C80 的主要規格
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下是AFF C80 的部分規格。訪問 https://hwu.netapp.com["NetApp Hardware Universe"^]（HWU）取得AFF C80 規格的完整清單。此頁面反映的是單一高可用性對。



=== AFF C80 的主要規格

平台配置： AFF C80 單機箱 HA 對

最大原容量：14.7360 PB

記憶體：512.0000 GB

外形尺寸：4U 機箱，配備 2 個 HA 控制器和 48 個驅動器插槽

ONTAP版本：b_startONTAP：9.16.1P2b_end

PCIe 擴充槽：18

最低ONTAP版本： ONTAP 9.16.1RC1



=== 橫向擴展最大值

|===


| 類型 | HA 對 | 原始容量 | 最大記憶體 


| 網路儲存 | 12 | 176.8 PB / 157.0 PiB | 6144GB 


| 儲存區域網絡 | 6 | 88.4 PB / 78.5 PiB | 3072GB 


| HA 對 |  | 14.7 PB / 13.1 PiB | 512.0000 
|===


=== 輸入輸出



==== 板載 IO

無板載 IO 資料。



==== 總 IO

|===


| 協定 | 連接埠 


| 乙太網路 200 Gbps | 24 


| 乙太網路 100 Gbps | 36 


| 乙太網路 25 Gbps | 56 


| 乙太網路 10 Gbps | 56 


| 光纖通道 64 Gbps | 56 


| NVMe/FC 64 Gbps | 56 


|  | 0 
|===


==== 管理埠

|===


| 協定 | 連接埠 


| 乙太網路 1 Gbps | 2. 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2. 
|===


=== 支援的儲存網絡

CIFS；FC；iSCSI；NFS v3；NFS v4.0；NFS v4.1；NFS v4.2；NFSv3/RDMA；NFSv4/RDMA；NVMe/FC；NVMe/TCP；S3；附 NAS 的 S3；SMB 2.0；SMB 2.1；



=== 系統環境規格

沒有可用的環境數據。



=== 遵守

* EMC/EMI 認證：AMCA、FCC、ICES、KC、摩洛哥、VCCI
* 安全認證：BIS、CB、CSA、G_K_U-SoR、IRAM、NOM、NRCS、SONCAP、TBS
* 安全/EMC/EMI認證：EAC、UKRSEPRO
* 認證安全/EMC/EMI/RoHS：BSMI、CE DoC、UKCA DoC
* 標準 EMC/EMI：BS-EN-55032、BS-EN55035、CISPR 32、EN55022、EN55024、EN55032、EN55035、EN61000-3-2、EN61000-3-3、KS 第 15 部分 A 3830 33、230 3、KS 930 類
* 標準安全：ANSI/UL60950-1、ANSI/UL62368-1、BS-EN62368-1、CAN/CSA C22.2 No. 60950-1、CAN/CSA C22.2 No. 62368-1、CNS 15598-1,6086825-168-1、CNS 15598-1、1086823623623639 62368-1、IEC60950-1、IS 13252（第 1 部分）




=== 高可用性

以乙太網路為基礎的基板管理控制器（BMC）和ONTAP管理介面；冗餘熱插拔控制器；冗餘熱插拔電源；
