---
permalink: fas2700/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: fas2700, aff a220, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: 若要更換機箱、您必須關閉控制器。 
---
= 關閉控制器- AFF EFASA220和FAS2700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用適合您組態的適當程序來關閉或接管受損的控制器。



== 選項1：大多數組態

[role="lead"]
您必須先關閉機箱中的控制器或控制器、才能將其移至新機箱。

.關於這項工作
* 如果叢集有兩個以上的控制器、則叢集必須處於仲裁狀態。如果叢集不在仲裁中、或顯示正常的控制器 `false` 如需資格和健全狀況、您必須先修正問題、再關閉受損的控制器；請參閱 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["將節點與叢集同步"^]。
* 如果啟用了此功能、請叫用下列訊息來抑制自動建立案例：「System Node現象叫用節點*-type all -Message MAn=number_of_hs_Downh」AutoSupport AutoSupport AutoSupport
+
下列AutoSupport 資訊不顯示自動建立案例兩小時的訊息：「cluster1：*>系統節點AutoSupport 、叫用節點*-輸入ALL -Message MAn=2h」



.步驟
. 如果您的系統有兩個控制器模組、請停用HA配對。
+
[cols="1,2"]
|===
| 如果您的系統執行叢集ONTAP 式的 | 然後... 


 a| 
叢集中的兩個控制器
 a| 
「叢集ha modify -configured假」、「儲存容錯移轉修改節點node0 -enabled假」



 a| 
叢集中有兩個以上的控制器
 a| 
「torage容錯移轉修改節點node0 -enabled假」

|===
. 當系統提示您確認停止時、請按「y」停止控制器：「System Node halt -node_node_name_」
+
確認訊息如下所示：

+
[listing]
----
Warning: This operation will cause controller "node-name" to be marked as unhealthy. Unhealthy nodes do not participate in quorum voting. If the controller goes out of service and one more controller goes out of service there will be a data serving failure for the entire cluster. This will cause a client disruption. Use "cluster show" to verify cluster state. If possible bring other nodes online to improve the resiliency of this cluster.

Do you want to continue? {y|n}:
----
+

NOTE: 在更換機箱之前、您必須執行乾淨的系統關機、以避免在非揮發性記憶體（NVMEM/NVRAM）中遺失未寫入的資料。根據您的系統、如果NVMEM/NVRAM LED正在快閃、則在NVMEM/NVRAM中有尚未儲存至磁碟的內容。您需要重新啟動控制器、並從本程序開始。如果重複嘗試完全關閉控制器失敗、請注意、您可能會遺失任何未儲存至磁碟的資料。

. 如果適用、請停止第二個控制器、以避免HA配對組態中出現可能的仲裁錯誤訊息：「System Node halt -node_dee_node_name_-ignore -quorum - warnings true -skip-lif-imcalemation-tape-shute-shuted true」
+
出現提示時回答「y」。





== 選項2：控制器採用MetroCluster 不含資訊的組態


NOTE: 如果您的系統採用雙節點MetroCluster 的功能、請勿使用此程序。

若要關閉受損的控制器、您必須判斷控制器的狀態、並在必要時接管控制器、以便健全的控制器繼續從受損的控制器儲存設備提供資料。

* 如果叢集有兩個以上的節點、則叢集必須處於仲裁狀態。如果叢集未達到法定人數、或健全的控制器顯示為「假」、表示符合資格和健全狀況、則您必須在關閉受損的控制器之前修正問題；請參閱 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["將節點與叢集同步"^]。
* 如果您使用MetroCluster 的是功能不全的組態、則必須確認MetroCluster 已設定「功能不全」狀態、且節點處於啟用且正常的狀態（「MetroCluster 功能不全」）。


.步驟
. 如果啟用了此功能、請叫用下列訊息來抑制自動建立案例：「System Node現象叫用節點*-type all -Message MAn=number_of_hs_Downh」AutoSupport AutoSupport AutoSupport
+
下列AutoSupport 資訊不顯示自動建立案例兩小時的訊息：「cluster1：*>系統節點AutoSupport 、叫用節點*-輸入ALL -Message MAn=2h」

. 停用健全控制器主控台的自動恢復功能：「torage容錯移轉修改–節點本機-自動恢復錯誤」
. 將受損的控制器移至載入器提示：
+
[cols="1,2"]
|===
| 如果受損的控制器正在顯示... | 然後... 


 a| 
載入程式提示
 a| 
移至「移除控制器模組」。



 a| 
正在等待恢復...
 a| 
按Ctrl-C、然後在出現提示時回應「y」。



 a| 
系統提示或密碼提示（輸入系統密碼）
 a| 
從正常控制器接管或停止受損的控制器：「torage容錯移轉接管-節點_受損節點_節點名稱_」

當受損的控制器顯示正在等待恢復...時、請按Ctrl-C、然後回應「y」。

|===

