---
permalink: platform-supplemental/42u-1280mm-features.html 
sidebar: sidebar 
keywords: system, cabinet, side, panel, front, rear, door, bolt-down, kit, optional, interconnect, pdu, equipment, integrate, cable, management, system, feature, system cabinet feature 
summary: 系統機櫃包含側邊面板、前後門、選購的栓扣套件、選用的互連套件、設備的PDU、以及整合式纜線管理系統。 
---
= 系統機櫃功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
系統機櫃包含側邊面板、前後門、選購的栓扣套件、選用的互連套件、設備的PDU、以及整合式纜線管理系統。

[cols="1,2"]
|===
| 功能 | 說明 


 a| 
側邊面板
 a| 
系統機櫃具有可鎖定、可拆式及可互換的側邊面板。



 a| 
前後門均有孔
 a| 
系統機櫃具有可拆式前後門、並具備快速釋放機制。前側擋門可反轉、後側擋門則會分開。兩個門都有孔以供冷卻。



 a| 
通用金鑰
 a| 
此按鍵可為前側擋門、後側擋門和側邊面板開鎖。



 a| 
備用套件
 a| 
此套件位於系統機櫃內、連接至機櫃門。其中包含下列元件：

* 四顆10-32 x 0.75英吋十字頭螺絲
* 四個10-32鎖緊螺帽
* 一個鎖緊螺帽插入工具
* 兩個主要金鑰複本




 a| 
纜線存取
 a| 
纜線通道內建於機櫃的頂端和底部、以及後側擋門底部和機架之間。



 a| 
纜線管理
 a| 
纜線管理掛勾和迴圈綁定會以相同的時間間隔連接至系統機櫃的框架。



 a| 
支援軌道
 a| 
您收到的支援軌道數量取決於您的組態。空的系統機櫃在出廠時未安裝支援軌道。

* 對於已設定的系統機櫃、系統機櫃隨附一個固定軌道套件、可支援80xx、FAS8200和DS4486後固定支架。
* 快速出貨系統機櫃不含額外的固定軌道套件。




 a| 
空白面板
 a| 
您所收到的空白面板數量和大小取決於您的組態。空的系統機櫃在出廠時未安裝擋板。



 a| 
栓接套件
 a| 
此選購套件可讓您將系統機櫃固定在資料中心樓層。此套件不適用於震測穩定性。

* 四個栓接式托架
* 四個分隔墊
* 六個M8x20公釐六角頭螺絲和墊圈




 a| 
互連套件
 a| 
此選購套件可讓您將多個系統機櫃彼此連接。

* 互連支架
+
** 一組四個互連支架、用於將系統機櫃與側邊面板連接在一起
** 一組四個互連支架、用於連接系統機櫃與側邊面板


* 系統機櫃中使用四顆M12x20 tor-30螺絲、側邊面板位於。
* 系統機櫃中使用八顆M6x10沉頭的tore-30螺絲、側邊面板為關閉狀態。




 a| 
支援軌道套件
 a| 
如果您隨系統機櫃一起訂購額外的支撐軌道、則每個套件都包含一個左右支撐軌道。


NOTE: 支援軌道與套件的設計僅適用於NetApp 42U 1280公釐系統機櫃。請勿使用其他系統機櫃的滑軌或軌道套件、因為這些滑軌或軌道套件並非設計用於42U 1280公釐系統機櫃。

* A左右支撐軌道
* 每個滑軌兩顆螺絲、用於將滑軌固定至系統機箱框架




 a| 
Crescent扳手
 a| 
重新傳送扳手可用來移除包裝托板上的固定托架、調整系統機櫃的水平墊腳、以及安裝栓接式套件托架（如有訂購）。

|===