---
permalink: platform-supplemental/drive-hotswap-drive.html 
sidebar: sidebar 
keywords: drive, fail, platform, log, warning, message, system, console, drive, addition, fault, led, operator, display, panel, fault, led, illuminate, nondisruptive, i/o, hot-swap, hot-swap a drive 
summary: 當磁碟機故障時、平台會將警告訊息記錄到系統主控台、指出哪個磁碟機故障。此外、操作員顯示面板上的故障LED和故障磁碟機上的故障LED都會亮起。在I/O進行期間、您可以不中斷地更換故障磁碟機。 
---
= 熱交換磁碟機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當磁碟機故障時、平台會將警告訊息記錄到系統主控台、指出哪個磁碟機故障。此外、操作員顯示面板上的故障LED和故障磁碟機上的故障LED都會亮起。在I/O進行期間、您可以不中斷地更換故障磁碟機。

* 替換磁碟機必須由您的平台支援。
+
https://hwu.netapp.com["NetApp Hardware Universe"]

* 如果已啟用SED驗證、您必須使用ONTAP 本文檔中的SED替換說明。
+
本白皮書中的說明ONTAP 說明說明更換SED之前和之後、您必須執行的其他步驟。

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/home.html["《NetApp加密電源指南》（英文）ONTAP"]

* 系統中的所有其他元件都必須正常運作；如果無法正常運作、請聯絡技術支援部門。
* 執行「shorage disk show -disf肯」命令、確認您要移除的磁碟機故障。故障磁碟機出現在故障磁碟機清單中。如果沒有、您應該稍候、然後再次執行命令。
+

NOTE: 視磁碟機類型和容量而定、磁碟機可能需要數小時才會出現在故障磁碟機清單中。

* *最佳實務做法：*最佳實務做法是先安裝目前版本的磁碟認證套件（DQP）、再進行磁碟機熱交換。
* 磁碟機韌體會自動更新（不中斷營運）、以安裝非最新韌體版本的新磁碟機。
* 打開更換磁碟機的包裝時、請保留所有包裝材料、以便在退回故障磁碟機時使用。
+
.. 如果您想要手動指派更換磁碟機的磁碟機所有權、則必須停用自動磁碟機指派更換磁碟機（如果已啟用）
+

NOTE: 您可以手動指派磁碟機擁有權、然後在本程序稍後重新啟用自動磁碟機指派。

+
... 驗證是否已啟用自動磁碟指派：「torage disk option show」
+
您可以在任一控制器模組上輸入命令。

+
如果啟用自動磁碟指派、輸出會在「Auto assign」（自動指派）欄中顯示「On」（開啟）（針對每個控制器模組）。

... 如果已啟用自動磁碟指派、請停用此功能：「torage disk option modify -node_name -autodassign Off」（磁碟選項修改-node_name -autodassign Off）
+
您必須停用兩個控制器模組上的自動磁碟機指派。



.. 請妥善接地。
.. 實體識別故障磁碟機。
+
當磁碟機故障時、系統會將警告訊息記錄到系統主控台、指出哪個磁碟機故障。此外、磁碟機櫃操作員顯示面板上的警示（黃色）LED和故障磁碟機也會亮起。

+

NOTE: 故障磁碟機上的活動（綠色）LED可亮起（持續亮起）、表示磁碟機已開機、但不應閃爍、這表示I/O活動。故障磁碟機沒有I/O活動。

.. 移除故障磁碟機：
+
... 按下磁碟機面上的釋放按鈕、以開啟CAM握把。
... 使用CAM握把將磁碟機滑出磁碟櫃、並用另一隻手支撐磁碟機。


.. 請等待至少70秒、再插入替換磁碟機。
+
這可讓系統辨識磁碟機已移除。

.. 插入替換磁碟機：
+
... 在CAM握把處於開啟位置時、請用兩隻手插入更換的磁碟機。
... 推動直到磁碟機停止。
... 合上CAM握把、讓磁碟機完全插入中間平面、並將握把卡入定位。
+
請務必緩慢關閉CAM握把、使其與磁碟機正面正確對齊。



.. 確認磁碟機的活動（綠色）LED亮起。
+
當磁碟機的活動LED持續亮起時、表示磁碟機已有電力。當磁碟機的活動LED燈在閃爍時、表示磁碟機已開機且I/O正在進行中。如果磁碟機韌體正在自動更新、LED會開始閃爍。

.. 如果您要更換另一個磁碟機、請重複步驟3到7。
.. 如果您在步驟1中停用自動指派磁碟機、請手動指派磁碟機擁有權、然後視需要重新啟用自動指派磁碟機。
+
... 顯示所有未擁有的磁碟機：「torage disk show -conter-type unallected」
+
您可以在任一控制器模組上輸入命令。

... 指派每個磁碟機：「torage disk assign -disk disk_name -Owner_name」
+
您可以在任一控制器模組上輸入命令。

+
您可以使用萬用字元一次指派多個磁碟機。

... 如有需要、請重新啟用自動磁碟指派：「儲存磁碟選項modify -node_name -autodassign on」
+
您必須在兩個控制器模組上重新啟用自動磁碟機指派。



.. 如套件隨附的RMA指示所述、將故障零件退回NetApp。
+
請聯絡技術支援人員： https://mysupport.netapp.com/site/global/dashboard["NetApp支援"]如果您需要RMA編號或更換程序的其他協助、請撥打888-463-8277（北美）、00-800-44-638277（歐洲）或+800-800-80-800（亞太地區）。




