---
permalink: platform-supplemental/sldiag-hardware-installation-diagnostics.html 
sidebar: sidebar 
keywords: run, diagnostic, add, replacing, replace, hardware, component, storage, systen, verify, installation, successful, run hardware installation diagnostic 
summary: 您在新增或更換儲存系統中的硬體元件之後、執行診斷、以驗證元件是否沒有問題、以及安裝是否成功。 
---
= 執行硬體安裝診斷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您在新增或更換儲存系統中的硬體元件之後、執行診斷、以驗證元件是否沒有問題、以及安裝是否成功。

. 在儲存系統提示下、切換至載入程式提示：「halt（停止）」
. 在載入程式提示字元中輸入下列命令：「boot_diags'」
+

NOTE: 您必須從載入程式提示字元執行此命令、系統層級診斷才能正常運作。boot_diags命令會啟動專為系統層級診斷所設計的特殊驅動程式。

. 在您新增或取代的特定裝置上執行預設測試、方法是輸入下列命令：「ldiag設備執行[-devtype | MB| slotslotnum][-name _device_]
+
** -devtype指定要測試的裝置類型。
+
*** 「ATA」是先進的技術附加設備。
*** 「bootmedia」是系統開機裝置。
*** 「cna」是未連線至網路或儲存設備的整合式網路卡。
*** 「env」是主機板環境。
*** 「fcache」是Flash Cache介面卡、也稱為效能加速模組2。
*** 「FCAL」是光纖通道仲裁迴圈設備、未連接至儲存設備或光纖通道網路。
*** 「fcvi」是未連線至光纖通道網路的光纖通道虛擬介面。
*** 「互連」或「NVRA-IB」是高可用度介面。
*** 「我」是系統記憶體。
*** 「NIC」是未連線至網路的網路介面卡。
*** NVRAM是非易失性RAM。
*** 「nvmem」是NVRAM與系統記憶體的混合體。
*** 「AS」是未連接至磁碟櫃的序列連接SCSI裝置。
*** 「服務處理器」是指服務處理器。
*** 「儲存」是ATA、FC-AL或SAS介面、具有附加的磁碟櫃。
*** 「Toe」是一種TCP卸載引擎、一種NIC。


** 「-b」指定所有的主機板裝置都要進行測試。
** 「lot _slotnum_」指定要測試特定插槽編號中的裝置。
** 名稱_device-'指定給定的設備類和類型。


. 輸入下列命令以檢視測試狀態：「ldiag」裝置狀態
+
您的儲存系統會在測試仍在執行時提供下列輸出：

+
[listing]
----
There are still test(s) being processed.
----
+
完成所有測試後、預設會出現下列回應：

+
[listing]
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----
. 輸入下列命令、確認儲存系統上新增或更換硬體元件時沒有發生硬體問題：「ldiag設備狀態[-devtype | MB| slotslotnum][-name設備]-long -stStatus falled]
+
下列範例會擷取測試新安裝的FC-AL介面卡所導致的故障完整狀態：

+
[listing]
----

*> **sldiag device status -dev fcal -long -state failed**

TEST START ------------------------------------------
DEVTYPE: fcal
NAME: Fcal Loopback Test
START DATE: Sat Jan  3 23:10:56 GMT 2009

STATUS: Completed
Starting test on Fcal Adapter: 0b
Started gathering adapter info.
Adapter get adapter info OK
Adapter fc_data_link_rate: 1Gib
Adapter name: QLogic 2532
Adapter firmware rev: 4.5.2
Adapter hardware rev: 2

Started adapter get WWN string test.
Adapter get WWN string OK wwn_str: 5:00a:098300:035309

Started adapter interrupt test
Adapter interrupt test OK

Started adapter reset test.
Adapter reset OK

Started Adapter Get Connection State Test.
Connection State: 5
Loop on FC Adapter 0b is OPEN

Started adapter Retry LIP test
Adapter Retry LIP OK

ERROR: failed to init adaptor port for IOCTL call

ioctl_status.class_type = 0x1

ioctl_status.subclass = 0x3

ioctl_status.info = 0x0
 Started INTERNAL LOOPBACK:
INTERNAL LOOPBACK   OK
Error Count: 2  Run Time: 70 secs
>>>>> ERROR, please ensure the port has a shelf or plug.
END DATE: Sat Jan  3 23:12:07 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------
----
+
[cols="1,2"]
|===
| 如果系統層級的診斷測試... | 然後... 


 a| 
已完成、沒有任何故障
 a| 
沒有硬體問題、您的儲存系統會回到提示狀態。

.. 輸入下列命令清除狀態記錄：「ldiag」裝置的清除狀態[-dev_devtype_|MB| slotslotnum]
.. 輸入下列命令、確認記錄已清除：「ldiag」裝置狀態（-dev_devtype_|MB| slotslotnum]）
+
畫面會顯示下列預設回應：

+
[listing]
----
SLDIAG: No log messages are present.
----
.. 輸入以下命令退出維護模式：「halt（停止）」
.. 在加載器提示符下輸入以下命令以引導儲存系統："boot_ontap（boot_ONTAP）您已完成系統級診斷。




 a| 
導致某些測試失敗
 a| 
確定問題的原因。

.. 輸入以下命令退出維護模式：「halt（停止）」
.. 執行乾淨關機並拔下電源供應器。
.. 確認您已注意到執行系統層級診斷所需的所有考量事項、纜線是否穩固連接、以及硬體元件是否已正確安裝在儲存系統中。
.. 重新連接電源供應器、並開啟儲存系統的電源。


|===


如果重複上述步驟後仍有故障、您需要更換硬體。
