---
permalink: platform-supplemental/sldiag-requirements.html 
sidebar: sidebar 
keywords: system-level, diagnostic, test, run, time, system, requirement, system, memory, general, nic, sas, fc-al, cna, interconnect, requirement for running system-level diagnostic 
summary: 視您執行的系統層級診斷測試而定、您必須瞭解時間和系統硬體需求。 
---
= 執行系統層級診斷的需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
視您執行的系統層級診斷測試而定、您必須瞭解時間和系統硬體需求。

每項記錄的工作都有少許差異；請使用建議的工作程序。

執行系統層級診斷時、必須符合下列需求；否則、部分測試會失敗、狀態報告中會顯示錯誤訊息：



== 一般要求

* 每個要測試的系統都必須位於不同的網路上。
+
網路介面測試會將唯一的靜態IP位址指派給儲存系統上所有可用的網路介面、從172.25.150.23開始。這會導致不同儲存控制器上的網路介面連接埠被指派相同的IP位址。如果測試的所有系統都在同一個網路上、則連接的主控台上會出現重複的IP位址警告訊息。這些警告訊息不會影響測試結果。





== 系統記憶體需求

* 執行記憶體測試時、您需要預留時間；儲存系統的記憶體容量越大、所需時間就越長。




== NIC需求

* 必須使用標準乙太網路纜線連接系統上所有鄰近的網路介面連接埠、以獲得最佳效能。
+
鄰近連接埠的範例包括e0a和e0b或e2c和e2d。

+

NOTE: 由於內部交換器連線、e0M和e0P連接埠無法連接在一起。在具有e0M和e0P連接埠的系統中、最有效率的配對是e0M搭配e0a和e0P搭配e0b。

* 如果系統上有許多網路介面連接埠、您可能需要執行NIC系統層級診斷測試數次、每次執行的次數限制為兩對以上。




== SAS需求

* 執行SAS系統層級診斷測試時、必須連接鄰近的SAS連接埠以獲得最佳效能；儲存櫃必須從連接埠中斷連線。
+

NOTE: 執行Data ONTAP NetApp 8.2的系統不再需要連接鄰近SAS連接埠；不過、只有未連接SAS連接埠的系統才會執行內部迴路測試。





== FC-AL要求

* 執行FC-AL系統層級診斷測試時、您必須在主機板或擴充介面卡的FC-AL介面上使用回送護罩、才能獲得最佳效能；儲存或光纖通道網路的所有其他纜線都必須從連接埠拔下。
+

NOTE: 雖然在FC-AL介面上使用回送護罩已不再需要執行Data ONTAP 版本號8.2的系統、但介面上的測試涵蓋範圍也會縮小。





== CNA要求

* 使用回送護罩並不需要執行CNA系統層級的診斷測試。




== 互連需求

* 雙控制器系統中的兩個平台控制器模組都必須處於維護模式、才能執行互連系統層級的診斷測試。
+

NOTE: 如果您嘗試以其他系統層級的診斷測試來執行互連系統層級的診斷測試、您將會收到一則警告訊息。


