---
permalink: platform-supplemental/sldiag-device-failure-diagnostics.html 
sidebar: sidebar 
keywords: run, diagnostic, help, access, device, intermittent, device, unavailable, storage, system, failure, run device failure diagnostic 
summary: 執行診斷可協助您判斷存取特定裝置的原因為何會變成間歇性、或是儲存系統中的裝置無法使用的原因。 
---
= 執行裝置故障診斷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
執行診斷可協助您判斷存取特定裝置的原因為何會變成間歇性、或是儲存系統中的裝置無法使用的原因。

. 在儲存系統提示下、切換至載入程式提示：「halt（停止）」
. 在載入程式提示字元中輸入下列命令：「boot_diags'」
+

NOTE: 您必須從載入程式提示字元執行此命令、系統層級診斷才能正常運作。boot_diags命令會啟動專為系統層級診斷所設計的特殊驅動程式。

. 輸入下列命令、對造成問題的裝置執行診斷：「lag裝置執行[-dev-type|MB| slotslotnum][-name devica]」
+
** -dev_devtyp__指定要測試的裝置類型。
+
*** 「ATA」是先進的技術附加設備。
*** 「bootmedia」是系統開機裝置。
*** 「cna」是未連線至網路或儲存設備的整合式網路卡。
*** 「env」是主機板環境。
*** 「fcache」是Flash Cache介面卡、也稱為效能加速模組2。
*** 「FCAL」是光纖通道仲裁迴圈設備、未連接至儲存設備或光纖通道網路。
*** 「fcvi」是未連線至光纖通道網路的光纖通道虛擬介面。
*** 「互連」或「NVRA-IB」是高可用度介面。
*** 「我」是系統記憶體。
*** 「NIC」是未連線至網路的網路介面卡。
*** NVRAM是非易失性RAM。
*** 「nvmem」是NVRAM與系統記憶體的混合體。
*** 「AS」是未連接至磁碟櫃的序列連接SCSI裝置。
*** 「服務處理器」是指服務處理器。
*** 「儲存」是ATA、FC-AL或SAS介面、具有附加的磁碟櫃。
*** 「Toe」是一種TCP卸載引擎、一種NIC。


** 「-b」指定所有的主機板裝置都要進行測試。
** 「lot_slotnum_」指定要測試特定插槽編號中的裝置。
** 名稱_device-'指定給定的設備類和類型。


. 輸入下列命令以檢視測試狀態：「ldiag」裝置狀態
+
您的儲存系統會在測試仍在執行時提供下列輸出：

+
[listing]
----
There are still test(s) being processed.
----
+
完成所有測試後、預設會出現下列回應：

+
[listing]
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----
. 輸入下列命令來識別任何硬體問題：「ldiag設備狀態（-dev-type|MB| slotslotnum][-name _device_]-long -stStatus fAILED）」
+
下列範例顯示測試FC-AL介面卡所導致的故障完整狀態：

+
[listing]
----

*> **sldiag device status fcal -long -state failed**

TEST START ------------------------------------------
DEVTYPE: fcal
NAME: Fcal Loopback Test
START DATE: Sat Jan  3 23:10:56 GMT 2009

STATUS: Completed
Starting test on Fcal Adapter: 0b
Started gathering adapter info.
Adapter get adapter info OK
Adapter fc_data_link_rate: 1Gib
Adapter name: QLogic 2532
Adapter firmware rev: 4.5.2
Adapter hardware rev: 2

Started adapter get WWN string test.
Adapter get WWN string OK wwn_str: 5:00a:098300:035309

Started adapter interrupt test
Adapter interrupt test OK

Started adapter reset test.
Adapter reset OK

Started Adapter Get Connection State Test.
Connection State: 5
Loop on FC Adapter 0b is OPEN

Started adapter Retry LIP test
Adapter Retry LIP OK

ERROR: failed to init adaptor port for IOCTL call

ioctl_status.class_type = 0x1

ioctl_status.subclass = 0x3

ioctl_status.info = 0x0
 Started INTERNAL LOOPBACK:
INTERNAL LOOPBACK   OK
Error Count: 2  Run Time: 70 secs
>>>>> ERROR, please ensure the port has a shelf or plug.
END DATE: Sat Jan  3 23:12:07 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------
----
+
[cols="1,2"]
|===
| 如果系統層級的診斷測試... | 然後... 


 a| 
導致某些測試失敗
 a| 
確定問題的原因。

.. 輸入以下命令退出維護模式：「halt（停止）」
.. 執行乾淨關機並拔下電源供應器。
.. 確認您已注意到執行系統層級診斷所需的所有考量事項、纜線是否穩固連接、以及硬體元件是否已正確安裝在儲存系統中。
.. 重新連接電源供應器、並開啟儲存系統的電源。
.. 重複執行裝置故障診斷_的步驟1到5。




 a| 
導致相同的測試失敗
 a| 
技術支援人員可能會建議修改部分測試的預設設定、以協助識別問題。

.. 輸入下列命令、修改儲存系統上特定裝置或裝置類型的選擇狀態： 「ldiag」裝置可修改[-dev_devtype_|MB| slot_slotnum_][-name設備][-selection _enable | disable| default|only _]+-"sh【_enable | disable|預設| only __」允許您啟用、停用、接受指定裝置類型或命名裝置的預設選擇、或僅啟用指定裝置或先停用所有其他裝置。
.. 輸入下列命令、確認測試是否已修改：「ldiag option show」
.. 重複執行裝置故障診斷_的步驟3到5。
.. 識別並解決問題後、重複執行子步驟1和2、將測試重設為「預設」狀態。
.. 重複執行裝置故障診斷_的步驟1到5。




 a| 
已完成、沒有任何故障
 a| 
沒有硬體問題、您的儲存系統會回到提示狀態。

.. 輸入下列命令清除狀態記錄：「ldiag」裝置的清除狀態[-dev_devtype_|MB|slot_slotnum_]
.. 輸入下列命令、確認記錄已清除：「ldiag」裝置狀態（-dev_devtype_|MB|slot_slotnum_]）
+
畫面會顯示下列預設回應：

+
[listing]
----
SLDIAG: No log messages are present.
----
.. 輸入以下命令退出維護模式：「halt（停止）」
.. 在加載器提示符下輸入以下命令以引導儲存系統："boot_ontap（boot_ONTAP）您已完成系統級診斷。


|===


如果重複上述步驟後仍有故障、您需要更換硬體。
