---
permalink: sas3/install-change-shelf-id.html 
sidebar: sidebar 
keywords: change, shelf, id, system, ontap, run, hot-add, ontap, controller, module, available, serve, data, unown, spare, offline, aggregate 
summary: 當系統尚未執行任何功能時、或是在將機櫃連接至系統之前熱新增機櫃時、您可以變更系統中的機櫃ID ONTAP 。您也可以在ONTAP 啟用且執行更新時變更機櫃ID（控制器模組可用於提供資料）、機櫃中的所有磁碟機均為無擁有、備援或是外聯Aggregate的一部分。 
---
= 變更機櫃ID：機櫃採用IOM12/IOM12B模組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當系統尚未執行任何功能時、或是在將機櫃連接至系統之前熱新增機櫃時、您可以變更系統中的機櫃ID ONTAP 。您也可以在ONTAP 啟用並執行更新時變更機櫃ID（控制器模組可用於處理資料）、機櫃中的所有磁碟機均為無擁有、備援磁碟機、或是外聯Aggregate的一部分。

.開始之前
* 如果已啟動且正在執行（控制器模組可用於提供資料）、您必須已確認機櫃中的所有磁碟機均為無擁有、備援或是外聯Aggregate的一部分。ONTAP
+
您可以使用「儲存磁碟show -sh現 況_機櫃_機櫃_編號_」命令來驗證磁碟機的狀態。Container Type（容器類型）欄中的輸出應顯示為備用磁碟機或故障磁碟機。此外、「Container Name（容器名稱）」和「Owner"（擁有者）欄應該會有破折號。

* 您可以執行Active IQ Config Advisor 下列命令、驗證系統中已使用的機櫃ID：執行下列命令、或使用「shorage shield show -Fields shid]命令。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp下載Config Advisor"]



.關於這項工作
* 有效的機櫃ID為00至99。
* 機櫃ID在HA配對或單一控制器組態中必須是唯一的。
+
如果您的平台具有內部儲存設備、則內部磁碟櫃和任何外部附加磁碟櫃的機櫃ID都必須是唯一的。

* 您必須關閉磁碟櫃電源再開啟、磁碟櫃ID才會生效。
+
重新開啟電源之前所等待的時間取決於ONTAP 本程序稍後所述的狀況。



.步驟
. 如果磁碟櫃尚未開啟、請開啟電源。
. 取下左端蓋、找到靠近機櫃LED的按鈕。
. 按住橘色按鈕、直到數位顯示器上的第一個數字開始閃爍、最多需要三秒鐘、即可變更機櫃ID的第一個數字。
+
[NOTE]
====
如果ID需要超過三秒時間才能開始閃爍、請再次按下按鈕、確定一定要完全按下。

這會啟動磁碟櫃ID程式設定模式。

====
. 按下按鈕以前進該號碼、直到您達到所需的0到9之間的數字為止。
+
第一個數字會持續閃爍。

. 按住按鈕、直到數位顯示器上的第二個數字開始閃爍（最多需要三秒鐘）、即可變更機櫃ID的第二個數字。
+
數位顯示器上的第一個數字會停止閃爍。

. 按下按鈕以前進號碼、直到達到所需的號碼1到9為止。
+
第二個數字會持續閃爍。

. 鎖定所需的號碼、然後按住按鈕、直到第二個號碼停止閃爍為止、這可能需要三秒鐘的時間。
+
數位顯示器上的兩個數字都會開始閃爍、而操作員顯示面板上的黃色LED會在約五秒鐘後亮起、提醒您、擱置中的磁碟櫃ID尚未生效。

. 重新啟動磁碟櫃、使機櫃ID生效。
+
您必須關閉兩個電源開關、等待適當的時間、然後重新開啟電源、才能完成電源循環。

+
** 如果ONTAP 尚未執行緒、或您正在熱新增機櫃（尚未連接至系統）、請等待至少10秒鐘。
** 如果執行的是（控制器可用於處理資料）、且機櫃中的所有磁碟機均為無擁有、備援或是外聯Aggregate的一部分、請等待至少70秒。ONTAP
+
這次ONTAP 、支援使用者正確刪除舊的機櫃位址、並更新新機櫃位址的複本。



. 更換左端蓋。
. 針對每個額外的磁碟櫃重複步驟1到9。
. 確認您的系統沒有重複的機櫃ID。
+
當兩個或多個磁碟櫃具有相同的ID時、系統會指派一個等於或大於100的軟體ID號碼給重複的磁碟櫃。您必須變更軟體ID（重複）號碼。

+
.. 執行Active IQ Config Advisor 此功能可檢查是否有重複的機櫃ID警示、或執行「shorage sh家 中的show -Fields sh家 中的id」命令、查看已在使用中的機櫃ID清單、包括任何重複的ID。
.. 如果您的系統有任何重複的機櫃ID、請重複此程序來變更重複的機櫃ID。



