---
permalink: sas3/install-change-shelf-id.html 
sidebar: sidebar 
keywords: change, shelf, id, system, ontap, controller, module, ds212c, ds224c, ds460c 
summary: 在 ONTAP 尚未執行時、在將磁碟櫃連接至系統之前熱新增磁碟櫃、或是當 ONTAP 已啟動並執行且磁碟櫃中的所有磁碟機均為未擁有、備用或屬於離線 Aggregate 的情況下，變更系統中的磁碟櫃 ID。 
---
= 更改 DS212C、DS224C 或 DS460C 機架 ID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當 ONTAP 尚未運作或在將機架連接到系統之前熱新增機架時，您可以變更 DS212C、DS224C 或 DS460C 機架中的機架 ID。此外，當 ONTAP 已啟動並運作（控制器模組可用於資料服務）且機架中的所有磁碟機均為無人認領、備用或屬於已離線的集合體時，您也可以變更機架 ID。

此程序適用於具有 IOM12、IOM12B 或 IOM12C 模組的磁碟櫃。

.關於這項工作
* 有效的機櫃ID為00至99。
* 機櫃ID在HA配對或單一控制器組態中必須是唯一的。
+
如果您的平台具有內部儲存設備、則內部磁碟櫃和任何外部附加磁碟櫃的機櫃ID都必須是唯一的。

* 您必須關閉磁碟櫃電源再開啟、磁碟櫃ID才會生效。
+
重新開啟電源之前所等待的時間取決於ONTAP 本程序稍後所述的狀況。



.開始之前
* 如果已啟動且正在執行（控制器模組可用於提供資料）、您必須已確認機櫃中的所有磁碟機均為無擁有、備援或是外聯Aggregate的一部分。ONTAP
+
您可以使用「儲存磁碟show -sh現 況_機櫃_機櫃_編號_」命令來驗證磁碟機的狀態。Container Type（容器類型）欄中的輸出應顯示為備用磁碟機或故障磁碟機。此外、「Container Name（容器名稱）」和「Owner"（擁有者）欄應該會有破折號。

* 您可以透過執行Active IQ Config Advisor或使用 `storage shelf show -fields shelf-id`命令。您可以 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["下載並造訪Active IQ Config Advisor"]在NetApp支援站點上。


.步驟
. 如果磁碟櫃尚未開啟、請開啟電源。
. 取下左端蓋、找到靠近機櫃LED的按鈕。
. 按住橘色按鈕、直到數位顯示器上的第一個數字開始閃爍、最多需要三秒鐘、即可變更機櫃ID的第一個數字。
+
[NOTE]
====
如果ID需要超過三秒時間才能開始閃爍、請再次按下按鈕、確定一定要完全按下。

這會啟動磁碟櫃ID程式設定模式。

====
. 按下按鈕以前進該號碼、直到您達到所需的0到9之間的數字為止。
+
第一個數字會持續閃爍。

. 按住按鈕、直到數位顯示器上的第二個數字開始閃爍（最多需要三秒鐘）、即可變更機櫃ID的第二個數字。
+
數位顯示器上的第一個數字會停止閃爍。

. 按下按鈕以前進號碼、直到達到所需的號碼1到9為止。
+
第二個數字會持續閃爍。

. 鎖定所需的號碼、然後按住按鈕、直到第二個號碼停止閃爍為止、這可能需要三秒鐘的時間。
+
數位顯示器上的兩個數字都會開始閃爍、而操作員顯示面板上的黃色LED會在約五秒鐘後亮起、提醒您、擱置中的磁碟櫃ID尚未生效。

. 重新啟動磁碟櫃、使機櫃ID生效。
+
您必須關閉兩個電源開關、等待適當的時間、然後重新開啟電源、才能完成電源循環。

+
** 如果ONTAP 尚未執行緒、或您正在熱新增機櫃（尚未連接至系統）、請等待至少10秒鐘。
** 如果ONTAP正在運作（控制器可用於提供資料），且機架中的所有磁碟機均為無人擁有、備用或離線聚合的一部分，則等待至少 120 秒。
+
這次ONTAP 、支援使用者正確刪除舊的機櫃位址、並更新新機櫃位址的複本。



. 更換左端蓋。
. 對每個額外的磁碟架重複上述步驟。
. 確認您的系統沒有重複的機櫃ID。
+
當兩個或多個磁碟櫃具有相同的ID時、系統會指派一個等於或大於100的軟體ID號碼給重複的磁碟櫃。您必須變更軟體ID（重複）號碼。

+
.. 執行Active IQ Config Advisor 此功能可檢查是否有重複的機櫃ID警示、或執行「shorage sh家 中的show -Fields sh家 中的id」命令、查看已在使用中的機櫃ID清單、包括任何重複的ID。
.. 如果您的系統有任何重複的機櫃ID、請重複此程序來變更重複的機櫃ID。



