---
permalink: a320/chassis-replace-move-hardware.html 
sidebar: sidebar 
keywords: aff, a320, aff a320, replace, chassis, fan, controller, module, impair, model, shut, down, replacing, remove, move, equipment, rack, complete, replacement, process, replace the chassis, shut down the controllers when replacing a chassis, remove the controller modules, move the fans, replace a chassis from within the equipment rack or system cabinet, install the controller modules, complete the replacement process 
summary: 將風扇、硬碟機和控制器模組或模組從受損的機箱移至新機箱、然後將受損的機箱從設備機架或系統機櫃換成與受損機箱相同機型的新機箱。 
---
= 更換硬體- AFF REVA320
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
將風扇、硬碟機和控制器模組或模組從受損的機箱移至新機箱、然後將受損的機箱從設備機架或系統機櫃換成與受損機箱相同機型的新機箱。



== 步驟1：移除控制器模組

若要更換機箱、您必須從舊機箱中移除控制器模組。

. 如果您尚未接地、請正確接地。
. 釋放電源線固定器、然後從電源供應器拔下纜線。
. 解開將纜線綁定至纜線管理裝置的掛勾和迴圈帶、然後從控制器模組拔下系統纜線和SFP（如有需要）、並追蹤纜線的連接位置。
+
將纜線留在纜線管理裝置中、以便在重新安裝纜線管理裝置時、整理好纜線。

. 從控制器模組的左側和右側移除纜線管理裝置、並將其放在一邊。
. 從機箱中取出控制器模組：
+
.. 將您的指夾插入控制器模組兩側的鎖定機制。
.. 按下鎖定機制頂端的橘色彈片、直到它清除機箱上的鎖定銷為止。
+
鎖定機制掛勾應幾乎垂直、且應遠離機箱插銷。

.. 將控制器模組往您的方向輕拉幾英吋、以便抓住控制器模組的兩側。
.. 用兩隻手將控制器模組從機箱中輕拉出、然後放在平穩的表面上。


. 對機箱中的其他控制器模組重複這些步驟。




== 步驟2：移動風扇

若要在更換機箱時將風扇模組移至更換機箱、您必須執行特定的工作順序。

. 如果您尚未接地、請正確接地。
. 用兩隻手抓住擋板兩側的開孔、然後朝自己的方向拉動擋板、直到擋板從機箱框架上的球形接線柱中釋放為止、以卸下擋板（如有必要）。
. 向下按風扇模組CAM握把上的釋放栓鎖、然後向下旋轉CAM握把。
+
風扇模組會稍微移離機箱。

. 將風扇模組從機箱中直接拉出、並確保您可以用手支撐、以免其從機箱中滑出。
+

CAUTION: 風扇模組很短。請務必用手支撐風扇模組的底部、以免突然從機箱中掉落而造成傷害。

. 將風扇模組放在一邊。
. 對其餘的任何風扇模組重複上述步驟。
. 將風扇模組與開孔對齊、然後滑入機箱、將其插入更換機箱。
. 將風扇模組CAM握把穩固推入、使其完全插入機箱。
+
當風扇模組完全就位時、CAM握把會稍微提高。

. 將CAM握把向上旋轉至閉模位置、確保CAM握把釋放栓鎖卡入鎖定位置。
+
風扇安裝後、風扇LED應為綠色、並可加速運作速度。

. 對其餘的風扇模組重複這些步驟。




== 步驟3：從設備機架或系統機櫃內更換機箱

您必須先從設備機架或系統機櫃中移除現有機箱、才能安裝替換機箱。

. 從機箱安裝點卸下螺絲。
. 兩人一起將舊機箱從系統機櫃或設備機架的機架軌道滑出、然後放在一旁。
. 如果您尚未接地、請正確接地。
. 請由兩個人將替換機箱裝入設備機架或系統機櫃、方法是將機箱引導至系統機櫃或設備機架的機架軌道。
. 將機箱完全滑入設備機架或系統機櫃。
. 使用您從舊機箱中取出的螺絲、將機箱正面固定在設備機架或系統機櫃上。
. 如果您尚未安裝擋板、請安裝擋板。




== 步驟4：安裝控制器模組

將控制器模組安裝至新機箱後、您必須啟動系統。

對於同一機箱中有兩個控制器模組的HA配對、安裝控制器模組的順序特別重要、因為當您將控制器模組完全裝入機箱時、它會嘗試重新開機。

. 將控制器模組的一端與機箱的開口對齊、然後將控制器模組輕推至系統的一半。
+

NOTE: 在指示之前、請勿將控制器模組完全插入機箱。

. 將主控台重新連接至控制器模組、然後重新連接管理連接埠。
. 將電源線插入電源供應器、然後重新安裝電源線固定器。
. 完成控制器模組的重新安裝：
+
.. 確定鎖銷臂鎖定在延伸位置。
.. 使用栓鎖臂、將控制器模組推入機箱支架、直到停止為止。
.. 按住鎖定機制頂端的橘色彈片。
.. 將控制器模組輕推入機箱支架、直到與機箱邊緣齊平為止。
+

NOTE: 鎖定機制臂滑入機箱。

+
控制器模組一旦完全插入機箱、就會開始開機。

.. 釋放栓鎖、將控制器模組鎖定到位。
.. 重新接上電源供應器。
.. 如果您尚未重新安裝纜線管理裝置、請重新安裝。
.. 按下「Ctrl-C」來中斷正常開機程序。


. 重複上述步驟、將第二個控制器安裝到新機箱中。

