---
permalink: c400/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff c400, verify and set HA state, run diagnostics, complete the replacement process 
summary: 您必須驗證機箱的HA狀態、執行診斷、並將故障零件歸還給NetApp、如套件隨附的RMA指示所述。 
---
= 完成還原與更換程序AFF -還原C400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須驗證機箱的HA狀態、執行診斷、並將故障零件歸還給NetApp、如套件隨附的RMA指示所述。



== 步驟1：驗證並設定機箱的HA狀態

您必須驗證機箱的HA狀態、並視需要更新狀態以符合您的系統組態。

. 在維護模式中、從任一控制器模組顯示本機控制器模組和機箱的HA狀態：「ha-config show」
+
所有元件的HA狀態都應該相同。

. 如果所顯示的機箱系統狀態與您的系統組態不符：
+
.. 設定機箱的HA狀態：「ha-config modify chassis _ha-stu__」
+
_HA-stu__的值可以是下列其中一項：

+
*** 《哈》
*** "Malc"
*** 「抄送給我們」
*** 《MCCIP》
*** 「非哈」


.. 確認設定已變更：「ha-config show」


. 如果您尚未重新設定、請重新設定系統的其他部分。
. 重新安裝系統正面的擋板。




== 步驟2：執行診斷

更換系統中的元件之後、您應該對該元件執行診斷測試。

您的系統必須處於載入器提示狀態、才能開始診斷。

診斷程序中的所有命令都會從要更換元件的節點發出。

. 如果要服務的節點不在載入程式提示下、請重新開機節點：「ystem Node halt -node_name」（系統節點停止節點節點節點名稱）
+
發出命令之後、您應該等到系統在載入程式提示字元停止。

. 在載入程式提示字元下、存取專為系統層級診斷所設計的特殊驅動程式、以正常運作：「boot_diags'（boot_diags'）
. 從顯示的功能表中選取*掃描系統*、即可執行診斷測試。
. 從顯示的功能表中選取*測試系統*以執行診斷測試。
. 從各種子功能表中選取測試或一系列測試。
. 根據上述步驟的結果繼續進行：
+
** 如果測試失敗、請修正故障、然後重新執行測試。
** 如果測試報告無故障、請從功能表中選取重新開機、以重新啟動系統。






== 步驟3：在雙節點MetroCluster 的不二組態中切換回集合體

完成雙節點MetroCluster 的故障恢復組態中的FRU更換之後、您就可以執行MetroCluster 還原還原作業。這會將組態恢復至正常運作狀態、使先前受損站台上的同步來源儲存虛擬機器（SVM）現在處於作用中狀態、並從本機磁碟集區提供資料。

此工作僅適用於雙節點MetroCluster 的不完整組態。

.步驟
. 驗證所有節點是否都處於「啟用」狀態：MetroCluster 「顯示節點」
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. 確認所有SVM上的重新同步已完成：MetroCluster 「Svserver show」
. 驗證修復作業所執行的任何自動LIF移轉是否已成功完成：「MetroCluster 還原檢查LIF show」
. 從存續叢集中的任何節點使用「MetroCluster 還原」命令執行切換。
. 確認切換作業已完成：MetroCluster 「不顯示」
+
當叢集處於「等待切換」狀態時、切換回復作業仍在執行中：

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
當叢集處於「正常」狀態時、即可完成切換作業：

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
如果切換需要很長時間才能完成、您可以使用「MetroCluster show config-repl複 寫res同步 狀態show」命令來檢查進行中的基準狀態。

. 重新建立任何SnapMirror或SnapVault 不完整的組態。




== 步驟4：將故障零件歸還給NetApp

如套件隨附的RMA指示所述、將故障零件退回NetApp。請參閱 https://mysupport.netapp.com/site/info/rma["產品退貨安培；更換"] 頁面以取得更多資訊。
