---
permalink: c400/chassis-replace-move-hardware.html 
sidebar: sidebar 
keywords: aff c400, aff, c400, component, system, function, properly, contact, technical, support, replace, chassis, shut, down, controller, replacing, remove, module, fan, equipment, rack, cabinet, ha, state, diagnostic, switch, back, aggregate, two-node, metrocluster, configuration, complete, replacement, process, replace the chassis, shut down the controllers when replacing a chassis, remove the controller modules, move the fans, replace a chassis from within the equipment rack or system cabinet, install the controller modules, verify and set the ha state of the chassis, run diagnostics, switch back aggregates in a two-node metrocluster configuration, complete the replacement process 
summary: 將風扇、硬碟機和控制器模組或模組從受損的機箱移至新機箱、然後將受損的機箱從設備機架或系統機櫃換成與受損機箱相同機型的新機箱。 
---
= 更換硬體- AFF REC400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
將風扇、硬碟機和控制器模組或模組從受損的機箱移至新機箱、然後將受損的機箱從設備機架或系統機櫃換成與受損機箱相同機型的新機箱。



== 步驟1：移除控制器模組

若要更換機箱、您必須從舊機箱中移除控制器模組。

. 如果您尚未接地、請正確接地。
. 釋放電源線固定器、然後從電源供應器拔下纜線。
. 解開將纜線綁定至纜線管理裝置的掛勾和迴圈帶、然後從控制器模組拔下系統纜線和SFP（如有需要）、並追蹤纜線的連接位置。
+
將纜線留在纜線管理裝置中、以便在重新安裝纜線管理裝置時、整理好纜線。

. 從控制器模組的左側和右側移除纜線管理裝置、並將其放在一邊。
. 向下按兩個鎖定栓、然後同時向下轉動兩個鎖條。
+
控制器模組會稍微移出機箱。

. 將控制器模組滑出機箱。
+
將控制器模組滑出機箱時、請確定您支援控制器模組的底部。

. 將控制器模組放在安全的地方、然後針對機箱中的其他控制器模組重複這些步驟。




== 步驟2：移動風扇

若要在更換機箱時將風扇模組移至更換機箱、您必須執行特定的工作順序。

. 如果您尚未接地、請正確接地。
. 用兩隻手抓住擋板兩側的開孔、然後朝自己的方向拉動擋板、直到擋板從機箱框架上的球形接線柱中釋放為止、以卸下擋板（如有必要）。
. 向下按風扇模組CAM握把上的釋放栓鎖、然後向下旋轉CAM握把。
+
風扇模組會稍微移離機箱。

. 將風扇模組從機箱中直接拉出、並確保您可以用手支撐、以免其從機箱中滑出。
+

CAUTION: 風扇模組很短。請務必用手支撐風扇模組的底部、以免突然從機箱中掉落而造成傷害。

. 將風扇模組放在一邊。
. 對其餘的任何風扇模組重複上述步驟。
. 將風扇模組與開孔對齊、然後滑入機箱、將其插入更換機箱。
. 將風扇模組CAM握把穩固推入、使其完全插入機箱。
+
當風扇模組完全就位時、CAM握把會稍微提高。

. 將CAM握把向上旋轉至閉模位置、確保CAM握把釋放栓鎖卡入鎖定位置。
. 對其餘的風扇模組重複這些步驟。




== 步驟3：從設備機架或系統機櫃內更換機箱

您必須先從設備機架或系統機櫃中移除現有機箱、才能安裝替換機箱。

. 從機箱安裝點卸下螺絲。
. 兩人一起將舊機箱從系統機櫃或設備機架的機架軌道滑出、然後放在一旁。
. 如果您尚未接地、請正確接地。
. 請由兩個人將替換機箱裝入設備機架或系統機櫃、方法是將機箱引導至系統機櫃或設備機架的機架軌道。
. 將機箱完全滑入設備機架或系統機櫃。
. 使用您從舊機箱中取出的螺絲、將機箱正面固定在設備機架或系統機櫃上。
. 如果您尚未安裝擋板、請安裝擋板。




== 步驟4：安裝控制器模組

將控制器模組安裝到新機箱之後、您需要將其開機至可執行診斷測試的狀態。

對於同一機箱中有兩個控制器模組的HA配對、安裝控制器模組的順序特別重要、因為當您將控制器模組完全裝入機箱時、它會嘗試重新開機。

. 將控制器模組的一端與機箱的開口對齊、然後將控制器模組輕推至系統的一半。
+

NOTE: 在指示之前、請勿將控制器模組完全插入機箱。

. 將主控台重新連接至控制器模組、然後重新連接管理連接埠。
. 完成控制器模組的安裝：
+
.. 將電源線插入電源供應器、重新安裝電源線鎖環、然後將電源供應器連接至電源。
.. 使用鎖定鎖條、將控制器模組穩固地推入機箱、直到鎖定鎖條開始上升。
+

NOTE: 將控制器模組滑入機箱時、請勿過度施力、以免損壞連接器。

.. 將鎖定鎖條向上轉動、將鎖定鎖條向內傾、使其脫離鎖定插銷、將控制器推入到底、然後將鎖定鎖條向下推入鎖定位置、以將控制器模組完全裝入機箱。
+
控制器模組一旦完全插入機箱、就會開始開機。準備好中斷開機程序。

.. 如果您尚未重新安裝纜線管理裝置、請重新安裝。
.. 中斷正常開機程序、然後按「Ctrl-C」開機至載入器。
+

NOTE: 如果系統在開機功能表停止、請選取開機至載入器選項。

.. 在載入程式提示下、輸入「bye」重新初始化PCIe卡和其他元件。
.. 中斷開機程序、然後按「Ctrl-C」開機至載入器提示字元。
+
如果系統在開機功能表停止、請選取開機至載入器選項。



. 重複上述步驟、將第二個控制器安裝到新機箱中。

