---
permalink: a800/bootmedia-shutdown.html 
sidebar: sidebar 
keywords: aff a800, shut down the controller 
summary: 完成NVE或NSE工作之後、您必須完成受損控制器的關機。 
---
= 關閉控制器以進行手動啟動媒體恢復 - AFF A800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
關閉AFF A800 儲存系統中受損的控制器，以防止資料遺失並在自動啟動媒體復原過程中保持系統穩定性。

如果您的儲存系統運作的是ONTAP 9.17.1 或更高版本，請使用link:bootmedia-replace-workflow-bmr.html["自動啟動恢復程序"]。如果您的系統運行的是早期版本的ONTAP，則必須使用手動啟動復原程序。



== 選項1：大多數系統

完成NVE或NSE工作之後、您必須完成受損控制器的關機。

.步驟
. 將受損的控制器移至載入器提示：
+
[cols="1,2"]
|===
| 如果受損的控制器顯示... | 然後... 


 a| 
載入程式提示
 a| 
移至「移除控制器模組」。



 a| 
《等待贈品……》
 a| 
按Ctrl-C、然後在出現提示時回應「y」。



 a| 
系統提示或密碼提示（輸入系統密碼）
 a| 
從健全的控制器接管或停止受損的控制器：「torage容錯移轉接管-節點受損節點名稱」

當受損的控制器顯示正在等待恢復...時、請按Ctrl-C、然後回應「y」。

|===
. 在載入器提示字元中、輸入：「prontenv」以擷取所有開機環境變數。將輸出儲存至記錄檔。
+

NOTE: 如果開機裝置毀損或無法運作、此命令可能無法運作。





== 選項2：系統MetroCluster 位於一個不二之處


NOTE: 如果您的系統採用雙節點MetroCluster 的功能、請勿使用此程序。

若要關閉受損的控制器、您必須判斷控制器的狀態、並在必要時接管控制器、以便健全的控制器繼續從受損的控制器儲存設備提供資料。

* 如果叢集有兩個以上的節點、則叢集必須處於仲裁狀態。如果叢集未達到法定人數、或健全的控制器顯示為「假」、表示符合資格和健全狀況、則您必須在關閉受損的控制器之前修正問題；請參閱 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["將節點與叢集同步"^]。
* 如果您使用MetroCluster 的是功能不全的組態、則必須確認MetroCluster 已設定「功能不全」狀態、且節點處於啟用且正常的狀態（「MetroCluster 功能不全」）。


.步驟
. 如果啟用了此功能、請叫用下列訊息來抑制自動建立案例：「System Node現象叫用節點*-type all -Message MAn=number_of_hs_Downh」AutoSupport AutoSupport AutoSupport
+
下列AutoSupport 資訊不顯示自動建立案例兩小時的訊息：「cluster1：*>系統節點AutoSupport 、叫用節點*-輸入ALL -Message MAn=2h」

. 停用健全控制器主控台的自動恢復功能：「torage容錯移轉修改–節點本機-自動恢復錯誤」
. 將受損的控制器移至載入器提示：
+
[cols="1,2"]
|===
| 如果受損的控制器正在顯示... | 然後... 


 a| 
載入程式提示
 a| 
前往下一步。



 a| 
正在等待恢復...
 a| 
按Ctrl-C、然後在出現提示時回應「y」。



 a| 
系統提示或密碼提示（輸入系統密碼）
 a| 
從正常控制器接管或停止受損的控制器：「torage容錯移轉接管-節點_受損節點_節點名稱_」

當受損的控制器顯示正在等待恢復...時、請按Ctrl-C、然後回應「y」。

|===


.接下來呢？
關閉控制器之後，您需要link:bootmedia-replace.html["更換開機媒體"]執行。
