---
permalink: asa-r2-c30/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa c30, replace the boot media 
summary: 在更換 ASA C30 儲存系統中的開機媒體之前、請確保符合成功更換所需的必要需求和考量事項。這包括驗證您擁有正確的替換開機媒體、確認受損控制器上的 e0M 管理連接埠運作正常、以及判斷是否已啟用 Onboard Key Manager 或 External Key Manager。 
---
= 更換開機媒體的需求 - ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在更換ASA C30 儲存系統中的啟動媒體之前，請確保滿足成功更換所需的必要要求和注意事項。這包括驗證您是否擁有正確的替換啟動媒體、確認受損控制器上的 e0M（扳手）連接埠是否正常運作，以及確定是否啟用了板載密鑰管理器 (OKM) 或外部密鑰管理器 (EKM)。

[NOTE]
====
NetApp 強烈建議您在使用的裝置上啟用主控台記錄功能，並在執行此程序時採取下列行動：

* 在維護期間保持 AutoSupport 啟用狀態。這樣一來，如果發生問題，NetApp 支援人員就能收到診斷資訊。
* 啟用所有 CLI 工作階段的工作階段記錄。這會建立維護活動期間所有命令和系統輸出的完整記錄。如需如何啟用工作階段記錄的指引，請參閱 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["如何設定 PuTTY 以獲得與 ONTAP 系統的最佳連線"^]。


====
* 您必須使用與從 NetApp 收到的容量相同的替換 FRU 元件來更換故障元件。
* 確認故障控制器上的 e0S 介面 (e0M 扳手連接埠) 沒有故障。
+
e0M 連接埠用於在自動啟動復原過程中在兩個控制器之間進行通訊。

* 對於 OKM，您需要叢集範圍的密碼以及備份資料。
* 對於 EKM ，您需要從合作夥伴節點複本下列檔案：
+
** /ccfcard/kmip/servers.cfg 檔案。
** /ccfcard/kmip/certs/client.crt 檔案。
** /ccfcard/kmip/certs/client.key 檔案。
** /ccfcard/kmip/certs/ca.pem 檔案。


* 更換受損的啟動介質時，將命令應用到正確的控制器至關重要：
+
** _受損控制器_是您正在執行維護的控制器。
** _健康控制器_是受損控制器的 HA 夥伴。




.下一步
檢閱開機媒體需求之後link:bootmedia-shutdown-bmr.html["關閉控制器"]，您就可以了。
