---
permalink: asa-r2-c30/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa c30, replace the boot media 
summary: '在更換 ASA C30 儲存系統中的啟動媒體之前，請確保滿足成功更換所需的必要要求和注意事項。這包括驗證您是否擁有正確的替換啟動媒體、確認受損控制器上的 e0S（e0M 扳手）連接埠是否正常運作，以及確定是否啟用了板載密鑰管理器 (OKM) 或外部密鑰管理器 (EKM)。' 
---
= 更換開機媒體的需求 - ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在更換 ASA C30 儲存系統中的啟動媒體之前，請確保滿足成功更換所需的必要要求和注意事項。這包括驗證您是否擁有正確的替換啟動媒體、確認受損控制器上的 e0S（e0M 扳手）連接埠是否正常運作，以及確定是否啟用了板載密鑰管理器 (OKM) 或外部密鑰管理器 (EKM)。



== 需求

* 您必須使用與從 NetApp 收到的容量相同的替換 FRU 元件來更換故障元件。
* 受損控制器上的 e0S （ e0M 扳手）連接埠無法故障。
+
e0S 連接埠用於自動開機恢復。

* 若為 OKM ，您需要 OKM 複雜密碼檔案內容。
* 對於 EKM ，您需要從合作夥伴節點複本下列檔案：
+
** /ccfcard/kmip/servers.cfg 檔案。
** /ccfcard/kmip/certs/client.crt 檔案。
** /ccfcard/kmip/certs/client.key 檔案。
** /ccfcard/kmip/certs/ca.pem 檔案。






== 考量

* 請務必在正確的控制器上套用下列步驟中的命令：
+
** _減損_控制器是您要執行維護的控制器。
** _Healthy控制器是受損控制器的HA合作夥伴。


* 如有需要，您可以開啟平台機箱位置（藍色） LED ，以協助實際定位受影響的平台。使用 SSH 登入 BMC ，然後輸入 `system location-led _on_`命令。
+
平台機箱有三個位置 LED ：一個在操作員顯示面板上，一個在每個控制器上。位置LED會持續亮起30分鐘。

+
您可以輸入命令將其關閉 `system location-led _off_`。如果您不確定 LED 是否亮起或熄滅，可以輸入命令來檢查其狀態 `system location-led show`。



.下一步
檢閱開機媒體需求之後link:bootmedia-shutdown-bmr.html["關閉控制器"]，您就可以了。
