---
permalink: a250/maintain-overview.html 
sidebar: sidebar 
keywords: aff A250 maintenance, maintenance, repairing A250, repairing aff A250, replace aff A250 components, replace aff A250 components 
summary: 維護 AFF A250 硬體 
---
= 維護 AFF A250 硬體
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
維護您的 AFF A250 儲存系統的硬體，以確保長期可靠性和最佳效能。定期執行維護任務，例如更換故障元件，這有助於防止停機和資料遺失。

維護程序假定 AFF A250 儲存系統已作為儲存節點部署在 ONTAP 環境中。



== 系統元件

對於 AFF A250 儲存系統、您可以對下列元件執行維護程序。

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["啟動媒體 - 自動恢復"]
 a| 
啟動媒體儲存儲存系統用於啟動的主要和次要 ONTAP 映像檔集。在自動復原期間，系統會從合作夥伴節點擷取啟動映像，並自動執行適當的啟動功能表選項，將映像安裝到替換的啟動媒體上。自動啟動媒體復原程序僅在 ONTAP 9.18.1 及更新版本中受支援。如果您的儲存系統執行的是較早版本的 ONTAP，請使用 link:bootmedia-replace-workflow.html["手動啟動恢復程序"]。



 a| 
link:bootmedia-replace-workflow.html["啟動媒體 - 手動恢復"]
 a| 
啟動媒體儲存儲存系統用於啟動的主要和次要 ONTAP 映像檔集。在手動還原期間，您可以從 USB 磁碟機啟動儲存系統，並手動還原檔案系統映像和組態。如果您的儲存系統執行 ONTAP 9.18.1 或更新版本，請使用 link:bootmedia-replace-workflow-bmr.html["自動啟動恢復程序"]。



 a| 
link:chassis-replace-workflow.html["機箱"]
 a| 
機箱是實體機箱、可容納所有控制器元件、例如控制器 /CPU 單元、電源供應器和 I/O



 a| 
link:controller-replace-workflow.html["控制器"]
 a| 
控制器由主機板、韌體和軟體組成。它控制磁碟機並執行 ONTAP 功能。



 a| 
link:dimm-replace.html["DIMM"]
 a| 
如果存在記憶體不相符的情況、或是有故障的DIMM、則必須更換DIMM（雙列直插式記憶體模組）。



 a| 
link:drive-replace.html["磁碟機"]
 a| 
磁碟機是提供資料實體儲存媒體的裝置。



 a| 
link:fan-replace.html["風扇"]
 a| 
風扇會冷卻控制器。



 a| 
link:mezzanine-replace.html["夾層卡"]
 a| 
Mezzanine 卡是一種印刷電路板，可直接插入另一張插件卡。



 a| 
link:nvmem-nvram-battery-replace.html["NVMEM電池"]
 a| 
NVMEM 電池負責在交流電源故障時保存快取資料。



 a| 
link:power-supply-replace.html["電源供應器"]
 a| 
電源供應器可在控制器機櫃中提供備援電源。



 a| 
link:rtc-battery-replace.html["即時時鐘電池"]
 a| 
即時時鐘電池會在電源關閉時保留系統日期和時間資訊。

|===