---
permalink: afx-1k/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: afx 1k,  verify and set HA state, complete the replacement process 
summary: 重新啟動控制器，驗證系統健康狀況，並將故障零件傳回給NetApp ，以完成AFF A1K機箱更換程序的最後一步。 
---
= 完成底盤更換 - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
重新啟動控制器，驗證系統健康狀況，並將故障部件傳回給NetApp ，以完成 AFX 1K 機箱更換程序的最後一步。



== 步驟 1 ：啟動控制器，然後將控制器交回

控制器重新開機後，請啟動 ONTAP ，然後將控制器交回。

.步驟
. 檢查主控台輸出：
+
.. 如果控制器在 LOADER 提示字元處停止，則使用 `boot_ontap`命令。
.. 節點啟動並提供登入提示後，登入合作夥伴控制器並檢查更換的控制器是否已準備好進行交還 `storage failover show`命令。


. 執行贈品：
+
.. 將主控台纜線連接至合作夥伴控制器。
.. 主控台訊息停止時、按 <enter> 。
+
*** 如果您看到_login_提示，請前往下一個步驟。
*** 如果您沒有看到登入提示，請登入合作夥伴節點。


.. 僅傳回具有 override-destination-checks 選項的根：
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`

+

NOTE: 以下命令僅在診斷模式權限等級下可用。有關權限級別的更多信息，請參閱link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["了解ONTAP CLI 指令的權限級別"^]。

+
如果您遇到錯誤、請聯絡 https://support.netapp.com["NetApp支援"]。

.. 在恢復報告完成後等待 5 分鐘，並檢查容錯移轉狀態和恢復狀態：
+
`storage failover show`和 `storage failover show-giveback`

+

NOTE: 以下命令僅在診斷模式權限等級下可用。

.. 如果 HA 互連鏈路已斷開，請將其恢復：
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`

.. 將受損的控制器歸還其儲存設備、使其恢復正常運作：
+
'容錯移轉還原-ofnode_disapped_node_name_'

.. 如果自動交還功能已停用，請重新啟用它： `storage failover modify -node _impaired_node_name_ -auto-giveback-of _true_`
.. 如果啟用 AutoSupport ，則還原 / 恢復自動建立個案： `system node autosupport invoke -node * -type all -message MAINT=END`






== 步驟 2 ：驗證儲存系統健全狀況

控制器歸還儲存後，使用 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"]。

.步驟
. 恢復完成後，請執行 Active IQ Config Advisor 以驗證儲存系統的健全狀況。
. 修正您遇到的任何問題。




== 步驟3：將故障零件歸還給NetApp

如套件隨附的RMA指示所述、將故障零件退回NetApp。如 https://mysupport.netapp.com/site/info/rma["零件退貨與更換"]需詳細資訊、請參閱頁面。
