---
permalink: afx-1k/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: afx 1k, shutdown the controller 
summary: 關閉 AFX 1K 儲存系統中的控制器，以防止資料遺失並確保更換機殼時系統穩定性。 
---
= 關閉控制器更換底盤 - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
關閉 AFX 1K 儲存系統中的控制器，以防止資料遺失並確保更換機殼時系統穩定性。

要關閉受損控制器，您必須確定控制器的狀態，並在必要時執行控制器的儲存故障轉移接管，以便健康的控制器繼續從受損控制器儲存提供資料。

.關於這項工作
* 如果您的叢集具有四個以上的節點，則它必須達到法定人數。要查看有關節點的叢集信息，請使用 `cluster show`命令。有關 `cluster show`命令，請參閱link:https://docs.netapp.com/us-en/ontap/system-admin/display-nodes-cluster-task.html["查看ONTAP叢集中的節點級詳細信息"^]。
* 如果叢集不處於法定人數，或任何控制器（受損控制器除外）的健康狀況或資格顯示為錯誤，則必須在關閉受損控制器之前修正該問題。看link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["將節點與叢集同步"^] 。


.步驟
. 如果啟用了「支援」功能、請叫用下列消息來禁止自動建立個案AutoSupport AutoSupport ：
+
`system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`

+
下列AutoSupport 資訊不顯示自動建立案例兩小時：

+
`cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. 從受損控制器的控制台停用自動交還：
+
`storage failover modify -node impaired-node -auto-giveback-of false`

+

NOTE: 當您看到「您想要停用自動回饋嗎？」時，請輸入 `y`。

+
.. 如果您執行的是ONTAP版本 9.17.1，且受損控制器無法啟動或已被接管，則必須在啟動受損控制器之前從正常控制器上斷開 HA 互連鏈路。這可以防止受損控制器執行自動交還。
+
`system ha interconnect link off -node healthy-node -link 0`

+
`system ha interconnect link off -node healthy-node -link 1`



. 將受損的控制器移至載入器提示：
+
[cols="1,2"]
|===
| 如果受損的控制器正在顯示... | 然後... 


 a| 
載入程式提示
 a| 
前往下一步。



 a| 
系統提示或密碼提示
 a| 
從健康控制器接管或停止受損控制器：
`storage failover takeover -ofnode _impaired_node_name_ -halt _true_`

_-halt true_ 參數將受損節點帶入 LOADER 提示符。

|===


.接下來呢？
關閉控制器之後，您需要執行link:chassis-replace-move-hardware.html["更換機箱"]。
