---
permalink: afx-1k/io-module-add.html 
sidebar: sidebar 
keywords: afx 1k, add I/O module 
summary: 在您的 AFX 1K 儲存系統中新增 I/O 模組，以增強網路連接並擴展系統處理資料流量的能力。 
---
= 新增 I/O 模組 - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在您的 AFX 1K 儲存系統中新增 I/O 模組，以增強網路連接並擴展系統處理資料流量的能力。

當有空插槽或所有插槽都已滿時，您可以為 AFX 1K 儲存系統新增 I/O 模組。



== 步驟 1 ：關閉受損的控制器模組

若要關閉受損的控制器、您必須判斷控制器的狀態、並在必要時接管控制器、以便健全的控制器繼續從受損的控制器儲存設備提供資料。

.開始之前
如果叢集有兩個以上的節點、則叢集必須處於仲裁狀態。如果叢集未達到法定人數、或健全的控制器顯示為「假」、表示符合資格和健全狀況、則您必須在關閉受損的控制器之前修正問題；請參閱 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["將節點與叢集同步"^]。

.步驟
. 如果啟用了AutoSupport ，則透過呼叫AutoSupport訊息指令來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`

+
以下AutoSupport指令可抑制自動案例建立兩小時：

+
`cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. 從健康控制器的控制台停用自動交還：
+
`storage failover modify –node local -auto-giveback false`

. 將受損的控制器移至載入器提示：
+
[cols="1,2"]
|===
| 如果受損的控制器正在顯示... | 然後... 


 a| 
載入程式提示
 a| 
前往下一步。



 a| 
《等待贈品……》
 a| 
按Ctrl-C、然後在出現提示時回應「y」。



 a| 
系統提示或密碼提示（輸入系統密碼）
 a| 
從健全的控制器接管或停止受損的控制器：

`storage failover takeover -ofnode impaired_node_name -halt true`

這 `-halt true`參數將帶您進入 LOADER 提示符號。

|===




== 步驟 2 ：新增 I/O 模組

如果儲存系統有可用的插槽，請將新的 I/O 模組安裝到其中一個可用的插槽中。如果所有插槽都已佔用，請移除現有的 I/O 模組以騰出空間，然後安裝新的 I/O 模組。

.開始之前
* 檢查 https://hwu.netapp.com/["NetApp Hardware Universe"^]確保新的 I/O 模組與您的儲存系統和ONTAP版本相容。
* 如果有多個插槽可用、請檢查中的插槽優先順序 https://hwu.netapp.com/["NetApp Hardware Universe"^] 並使用適用於您I/O模組的最佳工具。
* 確定所有其他元件都正常運作。
* 確保您擁有從NetApp收到的替換元件。


[role="tabbed-block"]
====
.將 I/O 模組新增至可用的插槽
--
您可以在具有可用插槽的儲存系統中新增 I/O 模組。

.步驟
. 如果您尚未接地、請正確接地。
. 向下轉動纜線管理托盤、方法是拉動纜線管理托盤內部的按鈕、然後向下旋轉。
. 從載體中卸下目標插槽空白模組：
+
.. 按下目標插槽中遮光模組上的凸輪鎖扣。
.. 將 CAM 栓鎖儘量遠離模組。
.. 將手指連入凸輪桿開口處、然後將模組從機箱中拉出、即可將模組從機箱中取出。


. 安裝I/O模組：
+
.. 將 I/O 模組與機箱插槽開口的邊緣對齊。
.. 將模組一路滑入機箱中的插槽、然後將 CAM 栓鎖完全向上旋轉、將模組鎖定到位。


. 將 I/O 模組連接至指定的裝置。
+

NOTE: 請確定所有未使用的I/O插槽均已安裝空白、以避免可能的散熱問題。

. 將纜線管理承載器向上旋轉至關閉位置。
. 在 Loader 提示字元中，重新啟動節點：
+
`bye`

+

NOTE: 這會重新初始化 I/O 模組和其他元件，然後重新啟動節點。

. 主控台訊息停止時、按 <enter> 。
+
** 如果您看到_login_提示，請前往下一個步驟。
** 如果您沒有看到登入提示，請登入合作夥伴節點。


. 僅傳回具有 override-destination-checks 選項的根：
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`

+

NOTE: 以下命令僅在診斷模式權限等級下可用。有關權限級別的更多信息，請參閱link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["了解ONTAP CLI 指令的權限級別"^]。

+
如果您遇到錯誤、請聯絡 https://support.netapp.com["NetApp支援"]。

. 在恢復報告完成後等待 5 分鐘，並檢查容錯移轉狀態和恢復狀態：
+
`storage failover show`和 `storage failover show-giveback`

+

NOTE: 以下命令僅在診斷模式權限等級下可用。

. 如果 HA 互連鏈路已斷開，請將其恢復：
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`

. 將受損的控制器歸還其儲存設備、使其恢復正常運作：
+
'容錯移轉還原-ofnode_disapped_node_name_'

. 對控制器B重複這些步驟
. 如果您停用自動恢復功能，請從健全的節點還原：
+
`storage failover modify -node local -auto-giveback-of _true_`

. 如果啟用 AutoSupport 、請還原自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
.將 I/O 模組新增至完全填入的系統
--
您可以移除現有的 I/O 模組，並在其所在位置安裝新的 I/O 模組，將 I/O 模組新增至完全安裝的系統。

.關於這項工作
請確定您瞭解下列案例，以便將新的 I/O 模組新增至完全填入的系統：

[cols="1,2"]
|===
| 案例 | 需要採取行動 


 a| 
NIC 對 NIC （相同數量的連接埠）
 a| 
當控制器模組關閉時、LIF會自動移轉。



 a| 
NIC 對 NIC （不同的連接埠數量）
 a| 
將選取的生命由永久重新指派至不同的主連接埠。如需詳細資訊、請參閱 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["移轉LIF"^] 。



 a| 
NIC 至儲存 I/O 模組
 a| 
使用System Manager將lifs永久移轉至不同的主連接埠、如所述 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["移轉LIF"^]。

|===
.步驟
. 如果您尚未接地、請正確接地。
. 拔下目標I/O模組上的任何纜線。
. 向下轉動纜線管理托盤、方法是拉動纜線管理托盤內部的按鈕、然後向下旋轉。
. 從機箱中移除目標I/O模組：
+
.. 按下 CAM LATCH 按鈕。
.. 將 CAM 栓鎖儘量遠離模組。
.. 將手指連入凸輪桿開口處、然後將模組從機箱中拉出、即可將模組從機箱中取出。
+
請務必追蹤I/O模組所在的插槽。



. 將 I/O 模組安裝至機箱中的目標插槽：
+
.. 將模組與機箱插槽開口的邊緣對齊。
.. 將模組一路滑入機箱中的插槽、然後將 CAM 栓鎖完全向上旋轉、將模組鎖定到位。


. 將 I/O 模組連接至指定的裝置。
. 重複執行移除和安裝步驟、以更換控制器的其他模組。
. 將纜線管理承載器向上旋轉至關閉位置。
. 從載入程式提示字元： _by_ 重新啟動控制器
+
這會重新初始化PCIe卡和其他元件、然後重新啟動節點。

. 主控台訊息停止時、按 <enter> 。
+
** 如果您看到_login_提示，請前往下一個步驟。
** 如果您沒有看到登入提示，請登入合作夥伴節點。


. 僅傳回具有 override-destination-checks 選項的根：
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`

+

NOTE: 以下命令僅在診斷模式權限等級下可用。有關權限級別的更多信息，請參閱link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["了解ONTAP CLI 指令的權限級別"^]。

+
如果您遇到錯誤、請聯絡 https://support.netapp.com["NetApp支援"]。

. 在恢復報告完成後等待 5 分鐘，並檢查容錯移轉狀態和恢復狀態：
+
`storage failover show`和 `storage failover show-giveback`

+

NOTE: 以下命令僅在診斷模式權限等級下可用。

. 如果 HA 互連鏈路已斷開，請將其恢復：
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`

. 將受損的控制器歸還其儲存設備、使其恢復正常運作：
+
`storage failover giveback -ofnode impaired_node_name`

. 如果停用自動恢復功能，請啟用：
+
`storage failover modify -node local -auto-giveback-of true`

. 執行下列其中一項：
+
** 如果您移除了儲存 I/O 模組並安裝了新的 NIC I/O 模組，請對每個連接埠使用下列網路指令：
+
`storage port modify -node <node name>__ -port <port name>__ -mode network`

** 如果您移除了 NIC I/O 模組並安裝了儲存 I/O 模組，請安裝 NX224 磁碟架並佈線，如link:../nx224/hot-add-shelf.html["熱添加 NX224 機架"]。


. 對控制器B重複這些步驟


--
====