---
permalink: fas50/maintain-overview.html 
sidebar: sidebar 
keywords: fas50 maintenance, maintenance, repairing fas50, replace fas50 components 
summary: 維護 FAS50 儲存系統的硬件，以確保長期可靠性和最佳效能。定期執行維護任務（例如更換故障組件），有助於防止停機和資料遺失。 
---
= 硬體維護總覽： FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
維護 FAS50 儲存系統的硬件，以確保長期可靠性和最佳效能。定期執行維護任務（例如更換故障組件），有助於防止停機和資料遺失。

維護過程假定 FAS50 儲存系統已部署為ONTAP環境中的儲存節點。



== 系統元件

對於 FAS50 儲存系統，您可以在下列元件上執行維護程序。

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["啟動媒體 - 自動恢復"]
 a| 
啟動媒體儲存一組主ONTAP映像檔和一組輔助 ONTAP 映像文件，儲存系統使用這些文件從配對節點啟動映像，並自動執行相應的啟動選單選項，以將啟動映像安裝到已取代的啟動媒體上。自動啟動媒體復原過程僅在ONTAP 9.17.1 及更高版本中支援。如果您的儲存系統運行的是早期版本的ONTAP，請使用link:bootmedia-replace-workflow.html["手動啟動恢復程序"] 。



 a| 
link:bootmedia-replace-workflow.html["啟動媒體 - 手動恢復"]
 a| 
啟動媒體儲存一組主ONTAP映像檔和一組輔助 ONTAP 映像文件，儲存系統使用這些檔案從 USB 磁碟機啟動映像並從合作夥伴節點恢復配置。



 a| 
link:caching-module-hot-swap.html["快取模組"]
 a| 
快取模組（ Flash Cache 模組）使用高速 SSD 來儲存經常存取的資料，以便更快擷取。



 a| 
link:chassis-replace-workflow.html["機箱"]
 a| 
機箱是實體機箱、可容納所有控制器元件、例如控制器 /CPU 單元、電源供應器和 I/O



 a| 
link:controller-replace-workflow.html["控制器"]
 a| 
控制器由主機板、韌體和軟體組成。它控制磁碟機並執行 ONTAP 作業系統軟體。



 a| 
link:dimm-replace.html["DIMM"]
 a| 
雙列直插式記憶體模組（ DIMM ）是一種電腦記憶體類型。它們是為了將系統記憶體新增至控制器主機板而安裝。



 a| 
link:drive-replace.html["磁碟機"]
 a| 
磁碟機是提供資料所需實體儲存設備的裝置。



 a| 
link:fan-replace.html["風扇"]
 a| 
風扇可冷卻控制器和磁碟機。



 a| 
link:io-module-overview.html["I/O模組"]
 a| 
I/O 模組（輸入 / 輸出模組）是一種硬體元件、可作為控制器與需要與控制器交換資料的各種裝置或系統之間的中介。



 a| 
link:nvdimm-battery-replace.html["非易失電池"]
 a| 
非揮發性記憶體（ NV ）電池負責為 NVMEM 元件提供電力，而在電力中斷後，資料傳輸中的資料會轉到快閃記憶體。



 a| 
link:power-supply-replace.html["電源供應器"]
 a| 
電源供應器在控制器中提供備援電源。



 a| 
link:rtc-battery-replace.html["即時時鐘電池"]
 a| 
即時時鐘電池會在電源關閉時保留系統日期和時間資訊。

|===