---
permalink: fas50/maintain-overview.html 
sidebar: sidebar 
keywords: aff a20 aff a30 aff a50 maintenance, maintenance, repairing a20 aff a30 aff a50, replace a20 aff a30 aff a50 components 
summary: 維護 FAS50 儲存系統的硬體，以確保長期的可靠性和最佳效能。定期執行維護工作，例如更換故障元件，如此有助於避免停機和資料遺失。 
---
= 硬體維護總覽： FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
維護 FAS50 儲存系統的硬體，以確保長期的可靠性和最佳效能。定期執行維護工作，例如更換故障元件，如此有助於避免停機和資料遺失。

維護程序假設 FAS50 系統已部署為 ONTAP 環境中的儲存節點。



== 系統元件

對於 FAS50 儲存系統，您可以在下列元件上執行維護程序。

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow.html["開機媒體"]
 a| 
開機媒體會儲存一組主要和次要的 ONTAP 映像檔案，以及系統開機時所使用的系統組態資訊。



 a| 
link:caching-module-hot-swap.html["快取模組"]
 a| 
快取模組（ Flash Cache 模組）使用高速 SSD 來儲存經常存取的資料，以便更快擷取。



 a| 
link:chassis-replace-workflow.html["機箱"]
 a| 
機箱是實體機箱、可容納所有控制器元件、例如控制器 /CPU 單元、電源供應器和 I/O



 a| 
link:controller-replace-workflow.html["控制器"]
 a| 
控制器由主機板、韌體和軟體組成。它控制磁碟機並執行 ONTAP 作業系統軟體。



 a| 
link:dimm-replace.html["DIMM"]
 a| 
雙列直插式記憶體模組（ DIMM ）是一種電腦記憶體類型。它們是為了將系統記憶體新增至控制器主機板而安裝。



 a| 
link:fan-replace.html["風扇"]
 a| 
風扇可冷卻控制器和磁碟機。



 a| 
link:io-module-overview.html["I/O模組"]
 a| 
I/O 模組（輸入 / 輸出模組）是一種硬體元件、可作為控制器與需要與控制器交換資料的各種裝置或系統之間的中介。



 a| 
link:nvdimm-battery-replace.html["非易失電池"]
 a| 
非揮發性記憶體（ NV ）電池負責為 NVMEM 元件提供電力，而在電力中斷後，資料傳輸中的資料會轉到快閃記憶體。



 a| 
link:power-supply-replace.html["電源供應器"]
 a| 
電源供應器在控制器中提供備援電源。



 a| 
link:rtc-battery-replace.html["即時時鐘電池"]
 a| 
即時時鐘電池會在電源關閉時保留系統日期和時間資訊。

|===