---
permalink: fas9500/chassis_replace_shutdown.html 
sidebar: sidebar 
keywords: aff fas9500, shutdown the controllers 
summary: 若要更換機箱、您必須關閉控制器。 
---
= 關閉受損的控制器- FAS9500
:allow-uri-read: 




== 關閉受損的控制器- FAS9500

[role="lead"]
關閉控制器、以便在機箱上執行維護。

此程序適用於具有兩個節點組態的系統。如果您的系統具有兩個以上的節點、請參閱 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_perform_a_graceful_shutdown_and_power_up_of_one_HA_pair_in_a_4__node_cluster["如何在四節點叢集中執行一個 HA 配對的正常關機和開機"^]。

.開始之前
* 停止所有用戶端 / 主機存取 NetApp 系統上的資料。
* 暫停外部備份工作。
* 請確定您擁有必要的權限和認證：
+
** ONTAP 的本機系統管理員認證。
** NetApp 板載金鑰管理（ OKM ）叢集範圍的複雜密碼（如果使用儲存加密或 NVE/NAE ）。
** 每個控制器的 BMC 存取能力。


* 請確定您擁有必要的工具和設備以進行更換。
* 關機前的最佳做法是：
+
** 執行其他 https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["系統健全狀況檢查"]。
** 將 ONTAP 升級至建議的系統版本。
** 解決任何問題 https://activeiq.netapp.com/["Active IQ 健康警示與風險"]。記下系統上目前存在的任何故障、例如系統元件上的 LED 。




.步驟
. 透過 SSH 登入叢集、或使用本機主控台纜線和筆記型電腦 / 主控台、從叢集中的任何節點登入。
. 關閉 AutoSupport 並指出您預期系統離線的時間：
+
`system node autosupport invoke -node * -type all -message "MAINT=8h Power Maintenance"`

. 識別所有節點的 SP/BMC 位址：
+
`system service-processor show -node * -fields address`

. 結束叢集 Shell ： `exit`
. 使用上一步輸出中列出的任何節點的 IP 位址、透過 SSH 登入 SP/BMC 。
+
如果您使用的是主控台 / 筆記型電腦、請使用相同的叢集管理員認證登入控制器。

+

NOTE: 開啟每個 SP/BMC 連線的 SSH 工作階段、以便監控進度。

. 停止位於受損機箱中的兩個節點：
+
`system node halt -node <node1>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: 對於在 StrictSync 模式下使用 SnapMirror 同步操作的叢集： `system node halt -node <node1>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. 當您看到時、請為叢集中的每個控制器輸入 * y* `_Warning: Are you sure you want to halt node "cluster <node-name> number"?
{y|n}:_`
. 等待每個控制器停止並顯示載入器提示。

