---
permalink: fas9500/nvram_module_or_nvram_dimm_replacement.html 
sidebar: sidebar 
keywords:  
summary: NVRAM模組包含NVRAM11和DIMM、以及每個NVRAM模組最多兩個NVMe SSD Flash Cache模組（FlashCache或快取模組）。 
---
= 更換NVRAM模組和/或NVRAM DIMM - FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVRAM模組由NVRAM11和DIMM組成。您可以更換故障的NVRAM模組或NVRAM模組內的DIMM。若要更換故障的NVRAM模組、您必須將其從機箱中取出、將DIMM移至更換模組、然後將替換的NVRAM模組安裝到機箱中。

若要更換和NVRAM DIMM、您必須從機箱中移除NVRAM模組、更換模組中故障的DIMM、然後重新安裝NVRAM模組。

由於系統ID是從NVRAM模組衍生而來、因此如果更換模組、則屬於系統的磁碟會重新指派至新的系統ID。

.開始之前
* 所有磁碟櫃都必須正常運作。
* 如果您的系統是HA配對、則合作夥伴節點必須能夠接管與要更換的NVRAM模組相關的節點。
* 本程序使用下列術語：
+
** 「受損」節點是您要執行維護的節點。
** 健全節點是受損節點的HA合作夥伴。


* 此程序包括自動或手動將磁碟重新指派給與新NVRAM模組相關聯的控制器模組的步驟。您必須依照程序中的指示重新指派磁碟。在恢復之前完成磁碟重新指派可能會造成問題。
* 您必須使用從供應商處收到的替換FRU元件來更換故障元件。
* 在此程序中、您無法變更任何磁碟或磁碟櫃。




== 步驟1：關閉受損節點

若要關閉受損的控制器、您必須判斷控制器的狀態、並在必要時接管控制器、以便健全的控制器繼續從受損的控制器儲存設備提供資料。

如果叢集有兩個以上的節點、則叢集必須處於仲裁狀態。如果叢集未達到法定人數、或健全的控制器顯示為「假」、表示符合資格和健全狀況、則您必須在關閉受損的控制器之前修正問題；請參閱 link:https://docs.netapp.com/us-en/ontap/system-admin/index.html["使用CLI進行系統管理總覽"^]。

.步驟
. 如果啟用了此功能、請叫用下列訊息來抑制自動建立案例：「System Node現象叫用節點*-type all -Message MAn=number_of_hs_Downh」AutoSupport AutoSupport AutoSupport
+
下列AutoSupport 資訊不顯示自動建立案例兩小時的訊息：「cluster1：*>系統節點AutoSupport 、叫用節點*-輸入ALL -Message MAn=2h」

. 停用健全控制器主控台的自動恢復功能：「torage容錯移轉修改–節點本機-自動恢復錯誤」
. 將受損的控制器移至載入器提示：
+
[cols="1,2"]
|===
| 如果受損的控制器正在顯示... | 然後... 


 a| 
載入程式提示
 a| 
前往下一步。



 a| 
《等待贈品……》
 a| 
按Ctrl-C、然後在出現提示時回應「y」。



 a| 
系統提示或密碼提示（輸入系統密碼）
 a| 
從正常控制器接管或停止受損的控制器：「torage容錯移轉接管-節點_受損節點_節點名稱_」

當受損的控制器顯示正在等待恢復...時、請按Ctrl-C、然後回應「y」。

|===




== 步驟2：更換NVRAM模組

若要裝回NVRAM模組、請將其置於機箱的插槽6中、然後依照特定的步驟順序進行。

. 如果您尚未接地、請正確接地。
. 從機箱中移除目標NVRAM模組：
+
.. 按下帶有字母和編號的CAM按鈕。
+
CAM按鈕會從機箱移出。

.. 向下轉動CAM栓鎖、直到其處於水平位置。
+
NVRAM模組會從機箱中鬆脫、然後移出幾英吋。

.. 拉動模組面兩側的拉片、將NVRAM模組從機箱中取出。
+





endif::[]

endif::[]
