---
permalink: fas9500/pci_cards_and_risers_replace.html 
sidebar: sidebar 
keywords:  
summary: 若要更換I/O模組、您必須執行特定的工作順序。 
---
= 更換I/O模組- FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要更換I/O模組、您必須執行特定的工作順序。

* 您可以將此程序用於ONTAP 系統支援的所有版本的功能。
* 系統中的所有其他元件都必須正常運作；否則、您必須聯絡技術支援部門。




== 步驟1：關閉受損節點

若要關閉受損的控制器、您必須判斷控制器的狀態、並在必要時接管控制器、以便健全的控制器繼續從受損的控制器儲存設備提供資料。

如果叢集有兩個以上的節點、則叢集必須處於仲裁狀態。如果叢集未達到法定人數、或健全的控制器顯示為「假」、表示符合資格和健全狀況、則您必須在關閉受損的控制器之前修正問題；請參閱 link:https://docs.netapp.com/us-en/ontap/system-admin/index.html["使用CLI進行系統管理總覽"^]。

.步驟
. 如果啟用了此功能、請叫用下列訊息來抑制自動建立案例：「System Node現象叫用節點*-type all -Message MAn=number_of_hs_Downh」AutoSupport AutoSupport AutoSupport
+
下列AutoSupport 資訊不顯示自動建立案例兩小時的訊息：「cluster1：*>系統節點AutoSupport 、叫用節點*-輸入ALL -Message MAn=2h」

. 停用健全控制器主控台的自動恢復功能：「torage容錯移轉修改–節點本機-自動恢復錯誤」
. 將受損的控制器移至載入器提示：
+
[cols="1,2"]
|===
| 如果受損的控制器正在顯示... | 然後... 


 a| 
載入程式提示
 a| 
前往下一步。



 a| 
《等待贈品……》
 a| 
按Ctrl-C、然後在出現提示時回應「y」。



 a| 
系統提示或密碼提示（輸入系統密碼）
 a| 
從正常控制器接管或停止受損的控制器：「torage容錯移轉接管-節點_受損節點_節點名稱_」

當受損的控制器顯示正在等待恢復...時、請按Ctrl-C、然後回應「y」。

|===




== 步驟2：更換I/O模組

若要更換I/O模組、請在機箱內找到該模組、然後依照特定的步驟順序進行。

. 如果您尚未接地、請正確接地。
. 拔下與目標I/O模組相關的任何纜線。
+
請務必貼上纜線的標籤、以便知道纜線的來源。

. 從機箱中移除目標I/O模組：
+
.. 按下帶有字母和編號的CAM按鈕。
+
CAM按鈕會從機箱移出。

.. 向下轉動CAM栓鎖、直到其處於水平位置。
+
I/O模組從機箱鬆脫、並從I/O插槽移出約1/2英吋。

.. 拉動模組面兩側的拉片、將I/O模組從機箱中移除。
+
請務必追蹤I/O模組所在的插槽。

+





endif::[]
