---
permalink: fas2800/chassis-replace-move-hardware.html 
sidebar: sidebar 
keywords: fas2800, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: 將電源供應器、硬碟機和控制器模組或模組從損壞的機箱移至替換機箱、然後將損壞的機箱從設備機架或系統機櫃中換出與損壞機箱相同型號的替換機箱。 
---
= 移動和更換硬體： FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
將電源供應器、硬碟機和控制器模組或模組從損壞的機箱移至替換機箱、然後將損壞的機箱從設備機架或系統機櫃中換出與損壞機箱相同型號的替換機箱。



== 步驟1：搬移電源供應器

在更換機箱時、移出電源供應器需要關閉、中斷連接、並從損壞的機箱中移除電源供應器、然後在替換機箱上安裝並連接電源供應器。

. 如果您尚未接地、請正確接地。
. 關閉電源供應器並拔下電源線：
+
.. 關閉電源供應器上的電源開關。
.. 打開電源線固定器、然後從電源供應器拔下電源線。
.. 從電源拔下電源線。


. 擠壓電源供應器CAM握把上的栓鎖、然後打開CAM握把、從中間面完全釋放電源供應器。
. 使用CAM握把將電源供應器滑出系統。
+

CAUTION: 移除電源供應器時、請務必用兩隻手支撐其重量。

. 針對任何剩餘的電源供應器、重複上述步驟。
. 用兩隻手支撐電源供應器邊緣、並將其與系統機箱的開孔對齊、然後使用CAM握把將電源供應器輕推入機箱。
+
電源供應器採用鎖定式設計、只能以單一方式安裝。

+

NOTE: 將電源供應器滑入系統時、請勿過度施力。您可能會損壞連接器。

. 關閉CAM握把、使栓鎖卡入鎖定位置、且電源供應器已完全就位。
. 重新連接電源線、並使用電源線鎖定機制將其固定至電源供應器。
+

NOTE: 只能將電源線連接至電源供應器。此時請勿將電源線連接至電源。





== 步驟2：移除控制器模組

從受損機箱中卸下控制器模組。

. 解開將纜線綁定至纜線管理裝置的掛勾和迴圈帶、然後從控制器模組拔下系統纜線和SFP（如有需要）、並追蹤纜線的連接位置。
+
將纜線留在纜線管理裝置中、以便在重新安裝纜線管理裝置時、整理好纜線。

. 從控制器模組的左側和右側移除纜線管理裝置、並將其放在一邊。
. 壓下CAM把手上的栓鎖直到釋放為止、完全打開CAM把把、以從中間板釋放控制器模組、然後用兩隻手將控制器模組從機箱中拉出。
+
image::../media/drw_2850_pcm_remove_install_IEOPS-694.svg[DRW 2850 PCM 移除安裝 IEOPS 694]

. 將控制器模組放在安全的地方。
. 對機箱中的第二個控制器模組重複這些步驟。




== 步驟 3 ：將磁碟機移至更換的機箱

將磁碟機從受損機箱中的每個磁碟機支架開口移到更換機箱中的同一個托架開口處。

. 從系統正面輕移擋板。
. 移除磁碟機：
+
.. 按下 LED 另一側的釋放按鈕。
.. 將CAM握把拉到完全開啟的位置、以從中間板中取出磁碟機、然後將磁碟機從機箱中輕推。
+
磁碟機應從機箱中鬆脫、使其可從機箱中滑出。

+

NOTE: 移除磁碟機時、請務必用兩隻手支撐其重量。

+

NOTE: 磁碟機很脆弱。請儘量少處理這些問題、以避免對其造成損害。



. 將受損機箱中的磁碟機與替換機箱中的同一個插槽開口對齊。
. 將磁碟機輕推入機箱、使其儘可能遠。
+
凸輪把手會接合、並開始旋轉至關閉位置。

. 將磁碟機的其餘部分穩固地推入機箱、然後將 CAM 把手推向磁碟機支架、以鎖定其。
+
請務必緩慢關閉CAM握把、使其與磁碟機承載器正面正確對齊。當安全時、它會發出「一鍵」的提示。

. 對系統中的其餘磁碟機重複此程序。




== 步驟4：從設備機架或系統機櫃內更換機箱

從設備機架或系統機櫃中移除現有機箱、然後將替換機箱安裝在設備機架或系統機櫃中。

. 從機箱安裝點卸下螺絲。
. 在兩到三個人的協助下、將受損的機箱滑出系統機櫃或設備機架中的 _L_ 支架中的機架軌道、然後將其放在一邊。
. 如果您尚未接地、請正確接地。
. 使用兩三個人、將替換機箱裝入設備機架或系統機櫃、方法是將機箱引導至系統機櫃的機架軌道或設備機架的_L_支架。
. 將機箱完全滑入設備機架或系統機櫃。
. 使用您從受損機箱中卸下的螺絲、將機箱正面固定至設備機架或系統機櫃。
. 如果您尚未安裝擋板、請安裝擋板。




== 步驟5：安裝控制器

將控制器模組和任何其他元件安裝到更換的機箱中、將其開機至維護模式。

對於同一機箱中有兩個控制器模組的HA配對、安裝控制器模組的順序特別重要、因為當您將控制器模組完全裝入機箱時、它會嘗試重新開機。

. 將控制器模組的一端與機箱的開口對齊、然後將控制器模組輕推至系統的一半。
+

NOTE: 在指示之前、請勿將控制器模組完全插入機箱。

. 將主控台重新連接至控制器模組、然後重新連接管理連接埠。
. 對更換機箱中的第二個控制器重複上述步驟。
. 完成控制器模組的安裝：
+
.. 將CAM握把置於開啟位置時、將控制器模組穩固推入、直到它與中間背板接觸並完全就位、然後將CAM握把關閉至鎖定位置。
+

NOTE: 將控制器模組滑入機箱時、請勿過度施力、以免損壞連接器。

.. 如果您尚未重新安裝纜線管理裝置、請重新安裝。
.. 使用掛勾和迴圈固定帶將纜線綁定至纜線管理裝置。
.. 對更換機箱中的第二個控制器模組重複上述步驟。


. 將電源供應器連接至不同的電源、然後開啟電源。
. 將每個控制器開機至維護模式：
+
.. 當每個控制器開始開機時、當您看到「Press Ctrl-C for Boot Menu（按Ctrl-C進入開機功能表）」訊息時、請按「Ctrl-C」來中斷開機程序。
+

NOTE: 如果您錯過提示、且控制器模組開機至ONTAP 指令碼、請輸入「halt」、然後在載入程式提示字元輸入「boot_ONTAP」、並在出現提示時按「Ctrl-C」、然後重複此步驟。

.. 從開機功能表中、選取維護模式選項。



