---
permalink: fas2800/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: fas2800, how to recable the system, how to reassign disks 
summary: 您必須重新儲存並確認磁碟重新指派。 
---
= 可重新分配系統並重新分配磁碟： FAS2800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要完成更換程序並將系統還原為完整作業、您必須重新儲存、確認磁碟重新指派、還原NetApp儲存加密組態（如有必要）、以及安裝新控制器的授權。您必須先完成一系列工作、才能將系統還原至完整運作狀態。



== 步驟1：重新安裝系統

可重新連接控制器模組的儲存設備和網路連線。

.步驟
. 將控制器模組重新連接至儲存設備和網路連線。
. 使用確認纜線正確無誤 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"]。
+
.. 下載並安裝Config Advisor 此功能。
.. 輸入目標系統的資訊、然後按一下「Collect Data（收集資料）」。
.. 按一下「纜線」索引標籤、然後檢查輸出。請確定所有磁碟櫃均已顯示、且所有磁碟均顯示在輸出中、以修正您發現的任何纜線問題。
.. 按一下適當的索引標籤、然後檢查Config Advisor 來自NetApp的輸出、檢查其他纜線。






== 步驟2：重新指派磁碟

您必須在開機_replaced_控制器時確認系統ID變更、然後確認變更是否已實作。

. 如果_replaced_控制器處於維護模式（顯示"*>"提示符）、請退出維護模式並進入載入器提示："half"（停止）
. 在_replace_控制器的載入器提示中、啟動控制器、如果系統ID不相符、系統提示您覆寫系統ID、請輸入「y」
. 請等到_replace_控制器主控台顯示「waiting for恢復...（正在等待恢復...）」訊息、然後從健全的控制器驗證是否已自動指派新的合作夥伴系統ID：「儲存容錯移轉顯示」
+
在命令輸出中、您應該會看到一則訊息、指出受損控制器上的系統ID已變更、顯示正確的舊ID和新ID。在下列範例中、node2已完成更換、新的系統ID為151759706。

+
[listing]
----
node1> `storage failover show`
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. 從健全的控制器、確認已儲存任何核心傾印：
+
.. 變更為進階權限等級：「et -priv榮幸 進階」
+
當系統提示您繼續進入進階模式時、您可以回應「Y」。出現進階模式提示（*>）。

.. 儲存任何核心傾印：「系統節點執行節點_nocal-node-name_合作夥伴儲存資源」
.. 等待 `savecore` 發出贈品前先完成的命令。
+
您可以輸入下列命令來監控savecore命令的進度：「ystem節點run -node-node-name_合作夥伴savecore -ss」

.. 返回管理員權限等級：「et -priv. admin」


. 退回控制器：
+
.. 從健全的控制器中、歸還更換的控制器儲存設備：「torage容錯移轉恢復-ofnode_replace_node_name_」
+
_replacement控制器會恢復其儲存設備並完成開機。

+
如果系統ID不相符、系統提示您覆寫系統ID、請輸入「y」。

+

IMPORTANT: 如果恢復被否決、請解決否決權問題。如果否決不至關重要、您可以覆寫否決。

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["尋找ONTAP 適用於您版本的更新版本的高可用度組態內容"]

.. 完成恢復後、請確認HA配對正常、而且可以接管：「顯示容錯移轉」
+
「儲存容錯移轉show」命令的輸出不應包含在合作夥伴訊息中變更的系統ID。



. 驗證是否已正確分配磁碟：「torage disk show -所有權」
+
屬於_replaced_控制器的磁碟應顯示新的系統ID。在下列範例中、node1擁有的磁碟現在顯示新的系統ID：1873775277：

+
[listing]
----
node1> `storage disk show -ownership`

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----

