---
permalink: fas2800/power-supply-swap-out.html 
sidebar: sidebar 
keywords: fas2820, swap, power, supply, turn off, disconnect, remove, install, connect, turn on, replacement 
summary: 在 FAS2820 系統中熱交換電源供應，需要關閉、斷開並移除受損的電源供應，然後安裝、連接並開啟替換的電源供應。 
---
= 在 FAS2820 系統中熱交換電源供應
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果 FAS2820 系統中的電源供應發生故障或效能下降，可在不中斷系統運作的情況下熱交換電源供應。此程序包括關閉並移除受損的電源供應，然後安裝並啟動替換電源供應。

如果系統中的任何其他組件無法正常運作，請聯絡技術支援。

* 電源供應器備援且可熱交換。
* 本程序是針對一次更換一個電源供應器而撰寫。
+

NOTE: 請在將電源供應從機箱取出後兩分鐘內更換電源供應。系統仍可繼續運作，但 ONTAP 會向主控台傳送有關電源供應降級的訊息，直到更換電源供應為止。

* 電源供應器為自動調整範圍。


.動畫 - 更換電源供應器
video::0631b48a-ad6f-4433-a2bd-af54014778c2[panopto]
.步驟
. 根據主控台錯誤訊息或電源供應器上的LED、識別您要更換的電源供應器。
. 如果您尚未接地、請正確接地。
. 關閉電源供應器並拔下電源線：
+
.. 關閉電源供應器上的電源開關。
.. 打開電源線固定器、然後從電源供應器拔下電源線。
.. 從電源拔下電源線。


. 擠壓電源供應器CAM握把上的栓鎖、然後打開CAM握把、從中間面完全釋放電源供應器。
+
image::../media/drw_2850_replace_PSU_IEOPS-702.svg[更換 PSU]

. 使用CAM握把將電源供應器滑出系統。
+

CAUTION: 移除電源供應器時、請務必用兩隻手支撐其重量。

. 確定新電源供應器的開關位於「關閉」位置。
. 用雙手支撐電源供應的邊緣並使其與系統機箱開口對齊，然後用凸輪手柄輕輕將電源供應推入機箱。
+
電源供應器採用鎖定式設計、只能以單一方式安裝。

+

NOTE: 將電源供應器滑入系統時、請勿過度施力。您可能會損壞連接器。

. 關閉CAM握把、使栓鎖卡入鎖定位置、且電源供應器已完全就位。
. 重新連接電源供應器纜線：
+
.. 將電源線重新連接至電源供應器和電源。
.. 使用電源線固定器將電源線固定至電源供應器。


+
電源供應恢復後，狀態指示燈應為綠色。

. 開啟新電源供應器的電源、然後確認電源供應器活動LED的運作。
+
電源供應器上線時、電源供應器LED會亮起。

. 如套件隨附的RMA指示所述、將故障零件退回NetApp。如 https://mysupport.netapp.com/site/info/rma["零件退貨與更換"^]需詳細資訊、請參閱頁面。

