---
permalink: asa-c400/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: asa c400, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: 完成硬體更換並開機至維護模式之後、您需要驗證更換控制器的低階系統組態、並視需要重新設定系統設定。 
---
= 還原並驗證系統組態 - ASA C400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
完成硬體更換並開機至維護模式之後、您需要驗證更換控制器的低階系統組態、並視需要重新設定系統設定。



== 步驟1：更換控制器後、請設定並驗證系統時間

您應該對照HA配對中的健全控制器模組、或獨立組態中的可靠時間伺服器、檢查更換控制器模組的時間和日期。如果時間和日期不相符、您必須在更換的控制器模組上重設、以避免客戶端因時間差異而可能發生中斷。

.關於這項工作
請務必在正確的系統上套用步驟中的命令：

* _replaced_節點是新的節點、在本程序中會取代受損節點。
* _Healthy節點是_replace_節點的HA合作夥伴。


.步驟
. 如果_replacem__節點未出現在載入程式提示字元、請停止系統並顯示載入程式提示字元。
. 在 _health_ 節點上、檢查系統時間： `cluster date show`
+
日期和時間是根據設定的時區而定。

. 在載入程式提示下、檢查_replacement節點上的日期和時間：「How date（顯示日期）」
+
日期與時間以GMT.為準。

. 如有必要、請在替換節點上設定以GMT0為單位的日期：「et date _mm/dd/ymm_'（設定日期_月/日/西元年_）」
. 如有必要、請在替換節點上設定以GMT0為單位的時間：「et time _hh：mm:ss_」（設定時間_hh：mm：ss_）
. 在載入程式提示下、確認 _ 置換 _ 節點上的日期和時間： `date`
+
日期與時間以GMT.為準。





== 步驟2：驗證並設定控制器模組的HA狀態

您必須驗證控制器模組的「HA」狀態、並視需要更新狀態以符合您的系統組態。

. 在新控制器模組的維護模式中、確認所有元件都顯示相同的「HA」狀態：「ha-config show」
+
所有元件的HA狀態都應該相同。

. 如果顯示的控制器模組系統狀態與您的系統組態不符、請設定控制器模組的「HA」狀態：「ha-config modify controller ha-state」
+
HA狀態的值可以是下列其中一項：

+
** 《哈》
** "Malc"
** 「抄送給我們」
** 《MCCIP》
** 「非哈」


. 如果顯示的控制器模組系統狀態與您的系統組態不符、請設定控制器模組的「HA」狀態：「ha-config modify controller ha-state」
. 確認設定已變更：「ha-config show」

