---
permalink: c30-60/overview.html 
sidebar: sidebar 
keywords: AFF C30 C60 specifications, AFF C30 C60 specs, AFF C30 C60 capacity, AFF C30 C60 memory, AFF C30 C60 I/O, AFF C30 C60 compliance 
summary: C30-60平台組的主要規格 
---
= C30-60平台組主要規格
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下是 C30-60 平台組的精選規格。訪問 https://hwu.netapp.com["NetApp Hardware Universe"^]（HWU）取得完整規格清單。此頁面反映的是單一高可用性對。



== AFF C60



=== AFF C60 的主要規格

平台配置： AFF C60 單機箱 HA 對

最大原始容量：7.3680 PB

記憶體：128.0000 GB

外型尺寸：2U 機箱，配備 2 個 HA 控制器和 24 個驅動器插槽

ONTAP版本：b_startONTAP：9.16.1P2b_end

PCIe 擴充槽：8

最低ONTAP版本： ONTAP 9.16.1RC1



=== 橫向擴展最大值

|===


| 類型 | HA 對 | 原始容量 | 最大記憶體 


| 網路儲存 | 4 | 29.5 PB / 26.2 PiB | 512GB 


| 儲存區域網絡 | 4 | 29.5 PB / 26.2 PiB | 512GB 


| HA 對 |  | 7.4 PB / 6.5 PiB | 128.0000 
|===


=== 輸入輸出



==== 板載 IO

無板載 IO 資料。



==== 總 IO

|===


| 協定 | 連接埠 


| 乙太網路 100 Gbps | 16 


| 乙太網路 25 Gbps | 24 


| 乙太網路 10 Gbps | 24 


| 光纖通道 64 Gbps | 24 


| NVMe/FC 64 Gbps | 24 


|  | 0 
|===


==== 管理埠

|===


| 協定 | 連接埠 


| 乙太網路 1 Gbps | 2. 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2. 
|===


=== 支援的儲存網絡

CIFS；FC；iSCSI；NFS v3；NFS v4.0；NFS v4.1；NFS v4.2；NVMe/FC；NVMe/TCP；S3；含 NAS 的 S3；SMB 2.0；SMB 2.1；SMB 2.x；SMB 3.SMB 3.1.1；



=== 系統環境規格

* 典型功率：2892 BTU/小時
* 最壞情況下的功率：4445 BTU/小時
* 重量：60.7 磅 27.5 公斤
* 高度：2U
* 寬度：19 英寸，符合 IEC 機架標準（17.6 英寸，44.7 厘米）
* 深度：
* 工作溫度/海拔/濕度：10°C 至 35°C（50°F 至 95°F），海拔最高可達 3048 公尺（10000 英尺）；相對濕度 8% 至 80%，無冷凝
* 非工作溫度/濕度：-40°C 至 70°C（-40°F 至 158°F），海拔最高 12192 公尺（40000 英尺），相對濕度 10% 至 95%，無冷凝，原包裝
* 聲學噪音：標稱聲功率 (LwAd)：8.0；聲壓 (LpAm)（旁觀者位置）：70.5 分貝




=== 遵守

* EMC/EMI 認證：AMCA、FCC、ICES、KC、摩洛哥、VCCI
* 安全認證：BIS、CB、CSA、G_K_U-SoR、IRAM、NOM、NRCS、SONCAP、TBS
* 安全/EMC/EMI認證：EAC、UKRSEPRO
* 認證安全/EMC/EMI/RoHS：BSMI、CE DoC、UKCA DoC
* 標準 EMC/EMI：BS-EN-55032、BS-EN55035、CISPR 32、EN55022、EN55024、EN55032、EN55035、EN61000-3-2、EN61000-3-3、KS 第 15 部分 A 3830 33、230 3、KS 930 類
* 標準安全：ANSI/UL60950-1、ANSI/UL62368-1、BS-EN62368-1、CAN/CSA C22.2 No. 60950-1、CAN/CSA C22.2 No. 62368-1、CNS 15598-1,6086825-168-1、CNS 15598-1、1086823623623639 62368-1、IEC60950-1、IS 13252（第 1 部分）




=== 高可用性

以乙太網路為基礎的基板管理控制器（BMC）和ONTAP管理介面；冗餘熱插拔控制器；冗餘熱插拔電源；



== AFF C30



=== AFF C30 的主要規格

平台配置： AFF C30 單機箱 HA 對

最大原容量：2.2104 PB

記憶體：128.0000 GB

外型尺寸：2U 機箱，配備 2 個 HA 控制器和 24 個驅動器插槽

ONTAP版本：b_startONTAP：9.16.1P2b_end

PCIe 擴充槽：8

最低ONTAP版本： ONTAP 9.16.1RC1



=== 橫向擴展最大值

|===


| 類型 | HA 對 | 原始容量 | 最大記憶體 


| 網路儲存 | 4 | 8.8 PB / 7.9 PiB | 512GB 


| 儲存區域網絡 | 4 | 8.8 PB / 7.9 PiB | 512GB 


| HA 對 |  | 2.2 PB / 2.0 PiB | 128.0000 
|===


=== 輸入輸出



==== 板載 IO

無板載 IO 資料。



==== 總 IO

|===


| 協定 | 連接埠 


| 乙太網路 100 Gbps | 16 


| 乙太網路 25 Gbps | 24 


| 乙太網路 10 Gbps | 24 


| 光纖通道 64 Gbps | 24 


| NVMe/FC 64 Gbps | 24 


|  | 0 
|===


==== 管理埠

|===


| 協定 | 連接埠 


| 乙太網路 1 Gbps | 2. 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2. 
|===


=== 支援的儲存網絡

CIFS；FC；iSCSI；NFS v3；NFS v4.0；NFS v4.1；NFS v4.2；NVMe/FC；NVMe/TCP；S3；含 NAS 的 S3；SMB 2.0；SMB 2.1；SMB 2.x；SMB 3.SMB 3.1.1；



=== 系統環境規格

* 典型功率：2892 BTU/小時
* 最壞情況下的功率：4445 BTU/小時
* 重量：60.7 磅 27.5 公斤
* 高度：2U
* 寬度：19 英寸，符合 IEC 機架標準（17.6 英寸，44.7 厘米）
* 深度：
* 工作溫度/海拔/濕度：10°C 至 35°C（50°F 至 95°F），海拔最高可達 3048 公尺（10000 英尺）；相對濕度 8% 至 80%，無冷凝
* 非工作溫度/濕度：-40°C 至 70°C（-40°F 至 158°F），海拔最高 12192 公尺（40000 英尺），相對濕度 10% 至 95%，無冷凝，原包裝
* 聲學噪音：標稱聲功率 (LwAd)：8.0；聲壓 (LpAm)（旁觀者位置）：70.5 分貝




=== 遵守

* EMC/EMI 認證：AMCA、FCC、ICES、KC、摩洛哥、VCCI
* 安全認證：BIS、CB、CSA、G_K_U-SoR、IRAM、NOM、NRCS、SONCAP、TBS
* 安全/EMC/EMI認證：EAC、UKRSEPRO
* 認證安全/EMC/EMI/RoHS：BSMI、CE DoC、UKCA DoC
* 標準 EMC/EMI：BS-EN-55032、BS-EN55035、CISPR 32、EN55022、EN55024、EN55032、EN55035、EN61000-3-2、EN61000-3-3、KS 第 15 部分 A 3830 33、230 3、KS 930 類
* 標準安全：ANSI/UL60950-1、ANSI/UL62368-1、BS-EN62368-1、CAN/CSA C22.2 No. 60950-1、CAN/CSA C22.2 No. 62368-1、CNS 15598-1,6086825-168-1、CNS 15598-1、1086823623623639 62368-1、IEC60950-1、IS 13252（第 1 部分）




=== 高可用性

以乙太網路為基礎的基板管理控制器（BMC）和ONTAP管理介面；冗餘熱插拔控制器；冗餘熱插拔電源；
