---
permalink: c250/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: aff c250, replace the boot media 
summary: 在更換 AFF C250 系統中的開機媒體之前，請確保符合成功更換的必要需求。這包括確保您擁有具備適當儲存容量的 USB 快閃磁碟機，並確認您擁有正確的替換開機裝置。 
---
= 手動開機媒體還原的需求 - AFF C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在更換 AFF C250 系統中的開機媒體之前，請確保符合成功更換的必要需求。這包括確保您擁有具備適當儲存容量的 USB 快閃磁碟機，並確認您擁有正確的替換開機裝置。

如果您的儲存系統執行的是 ONTAP 9.18.1 或更新版本，請使用 link:bootmedia-replace-workflow-bmr.html["自動啟動恢復程序"]。如果您的系統執行的是較早版本的 ONTAP，則必須使用手動開機還原程序。

[NOTE]
====
NetApp 強烈建議您在使用的裝置上啟用主控台記錄功能，並在執行此程序時採取下列行動：

* 在維護期間保持 AutoSupport 啟用狀態。這樣一來，如果發生問題，NetApp 支援人員就能收到診斷資訊。
* 啟用所有 CLI 工作階段的工作階段記錄。這會建立維護活動期間所有命令和系統輸出的完整記錄。如需如何啟用工作階段記錄的指引，請參閱 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["如何設定 PuTTY 以獲得與 ONTAP 系統的最佳連線"^]。


====
.USB 隨身碟
* 確保您有一個格式化為 FAT32 的 USB 隨身碟。
* USB 必須具有足夠的儲存容量來容納 `image_xxx.tgz`文件。


.文件準備
複製 `image_xxx.tgz`將檔案複製到 USB 隨身碟。使用 USB 隨身碟傳輸ONTAP映像時將使用此檔案。

從提取的 ONTAP 映像中，將  `EFI` 資料夾複製到 USB 隨身碟的根目錄。

.組件更換
使用NetApp提供的替換組件來更換故障組件。

.控制器識別
更換受損的啟動介質時，將命令應用到正確的控制器至關重要：

* _受損控制器_是您正在執行維護的控制器。
* _健康控制器_是受損控制器的 HA 夥伴。


.接下來呢？
在您檢閱了更換開機媒體的需求之後link:bootmedia-encryption-preshutdown-checks.html["檢查開機媒體上的加密金鑰支援和狀態"]，您需要執行。
