---
permalink: c250/bootmedia-recovery-image-boot.html 
sidebar: sidebar 
keywords: aff c250, boot the recovery image 
summary: 您必須從ONTAP USB磁碟機開機支援的影像、還原檔案系統、並驗證環境變數。 
---
= 使用手冊開機恢復程序，在 AFF C250 儲存系統上啟動恢復映像。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在系統中安裝新的開機媒體裝置之後，您可以從 USB 磁碟機開機恢復映像，並從合作夥伴節點還原組態。

如果您的儲存系統執行的是 ONTAP 9.18.1 或更新版本，請使用 link:bootmedia-replace-workflow-bmr.html["自動啟動恢復程序"]。如果您的系統執行的是較早版本的 ONTAP，則必須使用手動開機還原程序。

.開始之前
* 請確保您的遊戲機已連接到故障控制器。
* 確認故障控制器上的 e0S 介面 (e0M 扳手連接埠) 沒有故障。
* 請確認您擁有包含恢復映像的USB。
* 確定您的系統是否使用加密。在步驟 3 中，您需要根據是否啟用加密來選擇對應的選項。


.步驟
. 在故障控制器的 LOADER 提示字元下，從 USB 隨身碟啟動復原映像：
+
`boot_recovery`

+
恢復鏡像檔是從USB下載的。

. 出現提示時，輸入影像名稱或按 *Enter* 鍵接受括號中顯示的預設影像。
. 還原var檔案系統：
+
[cols="1,2"]
|===
| 如果您的系統有... | 然後... 


 a| 
網路連線正常，且運作的是 ONTAP 9.16.0 或更早版本。
 a| 
對受損控制人和合作控制人完成以下步驟：

.. *在故障控制器上：* 按下 `Y`當你看到 `Do you want to restore the backup configuration now?`
.. *在故障控制器上：* 若出現提示，請按 `Y`覆蓋 _/etc/ssh/ssh_host_ecdsa_key_。
.. *在夥伴控制器上：*將故障控制器的權限等級設定為進階：
+
`set -privilege advanced`

.. *在夥伴控制器上：*執行復原備份指令：
+
`system node restore-backup -node local -target-address _impaired_node_IP_address_`

+

NOTE: 如果看到的不是恢復成功的訊息，請聯絡NetApp支援。

.. *在合作夥伴控制器上：* 返回管理員層級：
+
`set -privilege admin`

.. *在故障控制器上：* 按下 `Y`當你看到 `Was the restore backup procedure successful?`
.. *在故障控制器上：* 按下 `Y`當你看到 `...would you like to use this restored copy now?`
.. *在故障控制器上：* 按下 `Y`當提示重啟時，按 `Ctrl-C`當您看到啟動選單時。
.. *對於故障控制器：*執行下列其中一項操作：
+
*** 如果系統不使用加密，請從啟動選單中選擇_選項 1 正常啟動_。
*** 如果系統使用加密，請前往link:bootmedia-encryption-restore.html["還原加密"]。






 a| 
網路連線正常，且執行 ONTAP 9.16.1 或更新版本。
 a| 
對受損控制器完成以下步驟：

.. 當系統提示您還原備份組態時，請按 `Y`。
+
恢復過程成功後，將顯示以下訊息： `syncflash_partner: Restore from partner complete`

.. 按 `Y`當提示確認恢復備份成功。
.. 按 `Y`當系統提示使用恢復的配置。
.. 按 `Y`當系統提示重啟節點時。
.. 按 `Y`當系統提示再次重啟時，請按 `Ctrl-C`當您看到啟動選單時。
.. 執行下列其中一項：
+
*** 如果系統不使用加密，請從啟動選單中選擇_選項 1 正常啟動_。
*** 如果系統使用加密，請前往link:bootmedia-encryption-restore.html["還原加密"]。






 a| 
無網路連線
 a| 
.. 出現提示時，按下  `N` 以還原備份組態。
.. 系統出現提示時、請重新啟動系統。
.. 從顯示的功能表中選取*從備份組態更新Flash *（同步Flash）選項。
+
如果系統提示您繼續更新，請按 `Y`。

.. 看到啟動選單時，請按下 `Ctrl-C`。
.. 執行下列其中一項：
+
*** 如果系統不使用加密，請從啟動選單中選擇_選項 1 正常啟動_。
*** 如果系統使用加密，請前往link:bootmedia-encryption-restore.html["還原加密"]。






 a| 
無網路連線、且為MetroCluster 靜態IP組態
 a| 
.. 出現提示時，按下  `N` 以還原備份組態。
.. 系統出現提示時、請重新啟動系統。
.. 等待iSCSI儲存設備連線連線。
+
您可以在看到下列訊息後繼續：

+
[listing]
----
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
----
.. 從顯示的功能表中選取*從備份組態更新Flash *（同步Flash）選項。
+
如果系統提示您繼續更新，請按 `Y`。

.. 看到啟動選單時，請按下 `Ctrl-C`。
.. 執行下列其中一項：
+
*** 如果系統不使用加密，請從啟動選單中選擇_選項 1 正常啟動_。
*** 如果系統使用加密，請前往link:bootmedia-encryption-restore.html["還原加密"]。




|===
. 將主控台纜線連接至合作夥伴控制器。
. 將控制器的儲存設備歸還，使其恢復正常運作：
+
`storage failover giveback -fromnode local`

. 如果您停用了自動返還功能，請重新啟用它：
+
`storage failover modify -node local -auto-giveback true`

. 如果啟用 AutoSupport 、請還原自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.接下來呢？
引導恢復映像後，您需要link:bootmedia-encryption-restore.html["在開機媒體上還原加密"]。
