---
permalink: c250/overview.html 
sidebar: sidebar 
keywords: AFF C250 specifications, AFF C250 specs, NetApp AFF C250, AFF C250 hardware 
summary: AFF C250儲存系統的主要規格 
---
= AFF C250的主要規格
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下是AFF C250的部分規格。訪問 https://hwu.netapp.com["NetApp Hardware Universe"^]（HWU）取得AFF C250規格的完整清單。此頁面反映的是單一高可用性對。



== AFF C250的主要規格

平台配置： AFF C250單機箱 HA 對

最大原容量：1.4736 PB

記憶體：128.0000 GB

外型尺寸：2U 機箱，配備 2 個 HA 控制器和 24 個驅動器插槽

ONTAP版本：b_startONTAP：9.16.1P2b_end

PCIe 擴充槽：4

最低ONTAP版本： ONTAP 9.10.1P15



== 橫向擴展最大值

|===


| 類型 | HA 對 | 原始容量 | 最大記憶體 


| 網路儲存 | 12 | 17.7 PB / 15.7 PiB | 1536GB 


| 儲存區域網絡 | 6 | 8.8 PB / 7.9 PiB | 768GB 


| HA 對 |  | 1.5 PB / 1.3 PiB | 128.0000 
|===


== 輸入/輸出



=== 板載 IO

|===


| 協定 | 連接埠 


| 乙太網路 25 Gbps | 4 


| 乙太網路 10 Gbps | 4 
|===


=== 總 IO

|===


| 協定 | 連接埠 


| 乙太網路 100 Gbps | 4 


| 乙太網路 25 Gbps | 20 


| 乙太網路 10 Gbps | 4 


| 光纖通道 32 Gbps | 16 


| NVMe/FC 32 Gbps | 16 


|  | 0 
|===


=== 管理埠

|===


| 協定 | 連接埠 


| 乙太網路 1 Gbps | 2. 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 4 
|===


== 支援的儲存網絡

CIFS；FC；iSCSI；NFS v3；NFS v4.0；NFS v4.1；NFS v4.2；NVMe/FC；NVMe/TCP；S3；含 NAS 的 S3；SMB 2.0；SMB 2.1；SMB 2.x；SMB 3.SMB 3.1.1；



== 系統環境規格

* 典型功率：2906 BTU/小時
* 最壞情況下的功率：3750 BTU/小時
* 重量：54.3 磅 24.6 公斤
* 高度：2U
* 寬度：19 吋 IEC 機架相容（17.6 吋 44.7 公分）
* 深度：21.38"（54.3 公分）
* 工作溫度/海拔/濕度：10°C 至 35°C（50°F 至 95°F），海拔最高可達 3048 公尺（10000 英尺）；相對濕度 8% 至 80%，無冷凝
* 非工作溫度/濕度：-40°C 至 70°C（-40°F 至 158°F），海拔最高 12192 公尺（40000 英尺），相對濕度 10% 至 95%，無冷凝，原包裝
* 聲學噪音：標稱聲功率 (LwAd)：7.2；聲壓 (LpAm)（旁觀者位置）：69.1 分貝




== 遵守

* EMC/EMI 認證：AMCA、FCC、ICES、KC、摩洛哥、VCCI
* 安全認證：BIS、CB、CSA、G_K_U-SoR、IRAM、NOM、NRCS、SONCAP、TBS
* 安全/EMC/EMI認證：EAC、UKRSEPRO
* 認證安全/EMC/EMI/RoHS：BSMI、CE DoC、UKCA DoC
* 標準 EMC/EMI：BS-EN-55024、BS-EN55035、CISPR 32、EN55022、EN55024、EN55032、EN55035、EN61000-3-2、EN61000-3-3、KS 第 15 部分 A 3830 33 類
* 標準安全：ANSI/UL60950-1、ANSI/UL62368-1、BS-EN62368-1、CAN/CSA C22.2 No. 60950-1、CAN/CSA C22.2 No. 62368-1、CNS 14336、EN60825-12368-1、CNS 14336、EN60825-6 62368-1、IEC60950-1、IS 13252（第 1 部分）




== 高可用性

以乙太網路為基礎的基板管理控制器（BMC）和ONTAP管理介面；冗餘熱插拔控制器；冗餘熱插拔電源；
