---
permalink: asa-r2-a1k/io-module-add.html 
sidebar: sidebar 
keywords: asa r2 a1k, add I/O module 
summary: 將 I/O 模組新增至 ASA A1K 系統，以增強網路連線能力，並擴充系統處理資料流量的能力。 
---
= 新增 I/O 模組 - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
將 I/O 模組新增至 ASA A1K 系統，以增強網路連線能力，並擴充系統處理資料流量的能力。

當 ASA A1K 儲存系統有可用的空插槽，或是所有插槽都已滿時，您可以將 I/O 模組新增至該儲存系統。關於此工作

如有需要，您可以開啟儲存系統位置（藍色） LED ，以協助實際定位受影響的儲存系統。使用 SSH 登入 BMC ，然後輸入 `system location-led _on_`命令。

儲存系統有兩個位置 LED ，每個控制器各一個。位置LED會持續亮起30分鐘。

您可以輸入命令將其關閉 `system location-led _off_`。如果您不確定 LED 是否亮起或熄滅，可以輸入命令來檢查其狀態 `system location-led show`。



== 步驟 1 ：關閉受損的控制器模組

關閉或接管受損的控制器模組。

若要關閉受損的控制器、您必須判斷控制器的狀態、並在必要時接管控制器、以便健全的控制器繼續從受損的控制器儲存設備提供資料。

.關於這項工作
* 如果您有 SAN 系統，則必須檢查故障控制器 SCSI 刀鋒的事件訊息  `cluster kernel-service show`。 `cluster kernel-service show`命令（從 priv 進階模式）會顯示節點名稱、link:https://docs.netapp.com/us-en/ontap/system-admin/display-nodes-cluster-task.html["仲裁狀態"]該節點的可用度狀態、以及該節點的作業狀態。
+
每個SCSI刀鋒處理序都應與叢集中的其他節點處於仲裁狀態。任何問題都必須先解決、才能繼續進行更換。

* 如果叢集有兩個以上的節點、則叢集必須處於仲裁狀態。如果叢集未達到法定人數、或健全的控制器顯示為「假」、表示符合資格和健全狀況、則您必須在關閉受損的控制器之前修正問題；請參閱 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["將節點與叢集同步"^]。


.步驟
. 如果啟用了「支援」功能、請叫用下列消息來禁止自動建立個案AutoSupport AutoSupport ：
+
`system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`

+
下列AutoSupport 資訊不顯示自動建立案例兩小時：

+
`cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. 停用健康控制器主控台的自動恢復：
+
`storage failover modify -node local -auto-giveback false`

+

NOTE: 當您看到_是否要停用自動恢復？_時、請輸入「y」。

. 將受損的控制器移至載入器提示：
+
[cols="1,2"]
|===
| 如果受損的控制器正在顯示... | 然後... 


 a| 
載入程式提示
 a| 
前往下一步。



 a| 
正在等待恢復...
 a| 
按Ctrl-C、然後在出現提示時回應「y」。



 a| 
系統提示或密碼提示
 a| 
從健全的控制器接管或停止受損的控制器：

`storage failover takeover -ofnode _impaired_node_name_ -halt _true_`

--halt true_ 參數會帶您進入 Loader 提示字元。

|===




== 步驟 2 ：新增 I/O 模組

如果儲存系統有可用的插槽，請將新的 I/O 模組安裝到其中一個可用的插槽中。如果所有插槽都已佔用，請移除現有的 I/O 模組以騰出空間，然後安裝新的 I/O 模組。

.開始之前
* 檢查 https://hwu.netapp.com/["NetApp Hardware Universe"^] 以確定新的 I/O 模組與您執行的儲存系統和 ONTAP 版本相容。
* 如果有多個插槽可用、請檢查中的插槽優先順序 https://hwu.netapp.com/["NetApp Hardware Universe"^] 並使用適用於您I/O模組的最佳工具。
* 確定所有其他元件都正常運作。


[role="tabbed-block"]
====
.將 I/O 模組新增至可用的插槽
--
您可以在具有可用插槽的儲存系統中新增 I/O 模組。

.步驟
. 如果您尚未接地、請正確接地。
. 向下轉動纜線管理托盤、方法是拉動纜線管理托盤內部的按鈕、然後向下旋轉。
. 從載體中卸下目標插槽空白模組：
+
.. 按下目標插槽中遮光模組上的凸輪鎖扣。
.. 將 CAM 栓鎖儘量遠離模組。
.. 將手指連入凸輪桿開口處、然後將模組從機箱中拉出、即可將模組從機箱中取出。


. 安裝I/O模組：
+
.. 將 I/O 模組與機箱插槽開口的邊緣對齊。
.. 將模組一路滑入機箱中的插槽、然後將 CAM 栓鎖完全向上旋轉、將模組鎖定到位。


. 將 I/O 模組連接至指定的裝置。
+

NOTE: 請確定所有未使用的I/O插槽均已安裝空白、以避免可能的散熱問題。

. 將纜線管理承載器向上旋轉至關閉位置。
. 在 Loader 提示字元中，重新啟動節點：
+
`bye`

+

NOTE: 這會重新初始化 I/O 模組和其他元件，然後重新啟動節點。

. 從合作夥伴控制器中退回控制器：
+
`storage failover giveback -ofnode target_node_name`

. 對控制器B重複這些步驟
. 如果您停用自動恢復功能，請從健全的節點還原：
+
`storage failover modify -node local -auto-giveback _true_`

. 如果啟用 AutoSupport 、請還原自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
.將 I/O 模組新增至完全填入的系統
--
您可以移除現有的 I/O 模組，並在其所在位置安裝新的 I/O 模組，將 I/O 模組新增至完全安裝的系統。

.關於這項工作
請確定您瞭解下列案例，以便將新的 I/O 模組新增至完全填入的系統：

[cols="1,2"]
|===
| 案例 | 需要採取行動 


 a| 
NIC 對 NIC （相同數量的連接埠）
 a| 
當控制器模組關閉時、LIF會自動移轉。



 a| 
NIC 對 NIC （不同的連接埠數量）
 a| 
將選取的生命由永久重新指派至不同的主連接埠。如需詳細資訊、請參閱 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["移轉LIF"^] 。



 a| 
NIC 至儲存 I/O 模組
 a| 
使用System Manager將lifs永久移轉至不同的主連接埠、如所述 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["移轉LIF"^]。

|===
.步驟
. 如果您尚未接地、請正確接地。
. 拔下目標I/O模組上的任何纜線。
. 向下轉動纜線管理托盤、方法是拉動纜線管理托盤內部的按鈕、然後向下旋轉。
. 從機箱中移除目標I/O模組：
+
.. 按下 CAM LATCH 按鈕。
.. 將 CAM 栓鎖儘量遠離模組。
.. 將手指連入凸輪桿開口處、然後將模組從機箱中拉出、即可將模組從機箱中取出。
+
請務必追蹤I/O模組所在的插槽。



. 將 I/O 模組安裝至機箱中的目標插槽：
+
.. 將模組與機箱插槽開口的邊緣對齊。
.. 將模組一路滑入機箱中的插槽、然後將 CAM 栓鎖完全向上旋轉、將模組鎖定到位。


. 將 I/O 模組連接至指定的裝置。
. 重複執行移除和安裝步驟、以更換控制器的其他模組。
. 將纜線管理承載器向上旋轉至關閉位置。
. 從載入程式提示字元： _by_ 重新啟動控制器
+
這會重新初始化PCIe卡和其他元件、然後重新啟動節點。

+

NOTE: 如果您在重新開機期間遇到問題、請參閱 https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1494308["Burt 1494308 - 在 I/O 模組更換期間、可能會觸發環境關機"]

. 從合作夥伴控制器中退回控制器：
+
`storage failover giveback -ofnode target_node_name`

. 如果停用自動恢復功能，請啟用：
+
`storage failover modify -node local -auto-giveback true`

. 執行下列其中一項：
+
** 如果您移除 NIC I/O 模組並安裝新的 NIC I/O 模組，請針對每個連接埠使用下列 network 命令：
+
`storage port modify -node *_<node name>__ -port *_<port name>__ -mode network`

** 如果您卸下了 NIC I/O 模組並安裝了儲存 I/O 模組，請依照中所述link:../ns224/hot-add-shelf-overview.html["熱新增工作流程"]，安裝 NS224 機櫃並連接纜線。


. 對控制器B重複這些步驟


--
====