---
permalink: asa-r2-a1k/maintain-overview.html 
sidebar: sidebar 
keywords: asa r2 a1k maintenance, maintenance, repairing a1k, repairing asa a1k, replace asa a1k components, replace asa a1k components 
summary: 維護 ASA R2 A1K 硬體 
---
= 維護 ASA A1K 硬體
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可能需要在硬體上執行維護程序。本節說明維護 ASA A1K 系統元件的特定程序。

本節中的程序假設 A1K 系統已部署為 ONTAP 環境中的儲存節點。



== 系統元件

對於 ASA A1K 儲存系統、您可以對下列元件執行維護程序。

[cols="30,70"]
|===


 a| 
link:bootmedia-overview.html["開機媒體 - 手動還原"]

link:bootmedia-overview-bmr.html["開機媒體 - 自動還原"]
 a| 
您可以使用 USB 模組作為開機映像、手動更換故障的開機媒體。

自動開機媒體更換會使用來自合作夥伴節點的開機映像、並自動執行適當的開機功能表選項、以便在更換的開機媒體上安裝開機映像。



 a| 
link:controller-replace-workflow.html["控制器"]
 a| 
控制器由主機板、韌體和軟體組成。它控制儲存設備、 I/O 卡、並執行 ONTAP 作業系統軟體。



 a| 
link:dimm-replace.html["DIMM"]
 a| 
雙列直插式記憶體模組（ DIMM ）是一種電腦記憶體類型。它們是為了將系統記憶體新增至控制器主機板而安裝。



 a| 
link:fan-replace.html["風扇"]
 a| 
風扇可冷卻控制器。



 a| 
link:nvram-replace.html["NVRAM"]
 a| 
NVRAM （非揮發性隨機存取記憶體）是一個模組、可讓控制器在系統斷電時保護及儲存在線上資料。系統 ID 位於 NVRAM 模組中。更換後、控制器會從更換的 NVRAM 模組中取得新的系統 ID 。



 a| 
link:nvdimm-battery-replace.html["非易失電池"]
 a| 
NV 電池負責為 NVRAM 模組提供電力、而在電力中斷後、正在傳輸的資料會被轉至快閃記憶體。



 a| 
link:io-module-overview.html["I/O模組"]
 a| 
I/O 模組（輸入 / 輸出模組）是一種硬體元件、可作為控制器與需要與控制器交換資料的各種裝置或系統之間的中介。



 a| 
link:power-supply-replace.html["電源供應器"]
 a| 
電源供應器在控制器中提供備援電源。



 a| 
link:rtc-battery-replace.html["即時時鐘電池"]
 a| 
即時時鐘電池會在電源關閉時保留系統日期和時間資訊。



 a| 
link:system-management-replace.html["系統管理模組"]
 a| 
系統管理模組提供控制器與主控台或筆記型電腦之間的介面、以供控制器或系統維護之用。系統管理模組包含開機媒體、並儲存系統序號（ SSN ）。

|===