= 
:allow-uri-read: 


[role="tabbed-block"]
====
.無加密
--
將受損的控制器歸還其儲存設備，使其恢復正常運作。

.步驟
. 在 LOADER 提示符號下輸入
+
`boot_ontap`

. 主控台訊息停止時、按 <enter> 。
+
** 如果您看到 _login_ 提示、請前往本節結尾的下一個步驟。
** 如果沒有看到登入提示，請按<enter>鍵，如果仍然沒有提示，請登入合作夥伴節點。


. 僅傳回具有 override-destination-checks 選項的根：
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`

+

NOTE: 以下命令僅在診斷模式權限等級下可用。有關權限級別的更多信息，請參閱link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["了解ONTAP CLI 指令的權限級別"^]。

+
如果您遇到錯誤、請聯絡 https://support.netapp.com["NetApp支援"]。

. 等待交還報告完成後 5 分鐘，然後檢查故障轉移和交還狀態：
+
`storage failover show`和 `storage failover show-giveback`

+

NOTE: 以下命令僅在診斷模式權限等級下可用。

. 如果 HA 互連鏈路已斷開，請將其恢復：
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`

. 將受損的控制器歸還其儲存設備、使其恢復正常運作：
+
'容錯移轉還原-ofnode_disapped_node_name_'

. 如果自動恢復已停用、請重新啟用：
+
`storage failover modify -node local -auto-giveback-of true`

. 如果啟用 AutoSupport ，則還原 / 恢復自動建立個案：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
.OKM加密
--
重設內建加密，並將控制器恢復正常運作。

.步驟
. 在 Loader 提示字元中，輸入：
+
`boot_ontap maint`

. 從 Loader 提示字元開機至 ONTAP 功能表 `boot_ontap menu`、然後選取選項 10 。
. 輸入 OKM 複雜密碼。您可以向客戶索取此通關密碼、或聯絡 https://support.netapp.com["NetApp支援"]。
+

NOTE: 系統會提示您輸入兩次密碼。

. 出現提示時輸入備份金鑰資料。
. 在開機功能表中、輸入正常開機的選項 `1`。
. 將控制台電纜移至合作夥伴節點並輸入以下登入資訊：
+
`admin`

. 僅傳回具有 override-destination-checks 選項的根：
+
`storage  failover giveback -ofnode impaired-node -only-root true -override-destination-checks true`

+

NOTE: 以下命令僅在診斷模式權限等級下可用。有關權限級別的更多信息，請參閱link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["了解ONTAP CLI 指令的權限級別"^]。

+
如果您遇到錯誤、請聯絡 https://support.netapp.com["NetApp支援"]。

. 等待交還報告完成後 5 分鐘，然後檢查故障轉移和交還狀態：
+
`storage failover show`和 `storage failover show-giveback`

+

NOTE: 以下命令僅在診斷模式權限等級下可用。

. 將控制台電纜移至替換節點並輸入以下內容：
+
`security key-manager onboard sync`

+

NOTE: 系統會提示您輸入叢集範圍的 OKM 複雜密碼。

. 使用下列命令檢查金鑰的狀態：
+
`security key-manager key query -key-type svm-KEK`

+
如果 _RESTOREURE_ 欄顯示 _true_ 以外的任何內容、請聯絡 https://support.netapp.com["NetApp支援"]。

. 將受損的控制器歸還其儲存設備、使其恢復正常運作：
+
'容錯移轉還原-ofnode_disapped_node_name_'

+
.. 如果 HA 互連連結已斷開，請將其恢復以恢復自動交還：
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`



. 如果自動恢復已停用、請重新啟用：
+
`storage failover modify -node local -auto-giveback-of true`

. 如果啟用 AutoSupport ，則還原 / 恢復自動建立個案：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
====