= 
:allow-uri-read: 


當開機媒體毀損時、從合作夥伴節點還原 ONTAP 映像。

.關於這項工作
如果節點的開機媒體毀損、開機程序將在 Loader 提示時停止、並顯示開機錯誤訊息。

當您遇到這些開機錯誤訊息時、需要從合作夥伴節點還原 ONTAP 映像。

.顯示開機錯誤訊息範例
[%collapsible]
====
....
Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014

Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel: Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0, fat)
ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0, fat)

Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>
....
====
.步驟
. 在 Loader 提示字元中、輸入命令：
+
`boot_recovery -partner`

+
畫面會顯示下列訊息：

+
`Starting boot media recovery (BMR) process. Press Ctrl-C to abort…`

. 在 Loader 設定本機叢集連接埠並從合作夥伴節點執行時、監控開機媒體還原程序 `netboot`。
+
當 netboot 正在執行時、 `Starting BMR`會顯示訊息。

. 根據加密方法，選取符合您系統組態的選項：
+
[role="tabbed-block"]
====
.無加密
--
如果未偵測到加密、則開機媒體還原程序會在不需要金鑰管理的情況下繼續進行。

.. 從合作夥伴節點還原備份組態、 env 檔案、 mdb 和 RDB 時、請繼續監控還原程序。
.. 恢復程序完成後、節點將重新開機。下列訊息表示恢復成功：


....

varfs_backup_restore: update checksum for varfs.tgz
varfs_backup_restore: restore using /cfcard/x86_64/freebsd/oldvarfs.tgz
varfs_backup_restore: Rebooting to load the new varfs
.
Terminated
varfs_backup_restore: bootarg.abandon_varfs is set! Skipping /var backup.

....
.. 當節點重新開機時、請確認系統已重新上線且運作正常、以確認開機媒體恢復成功。
.. 將受損的控制器歸還其儲存設備、使其恢復正常運作：
+
`storage failover giveback -ofnode _impaired_node_name_`。



--
.內建金鑰管理程式（OKM）
--
如果偵測到 Onboard Key Manager （ OKM ）、系統會顯示下列提示。

....
key manager is configured.
Entering Bootmenu Option 10...

This option must be used only in disaster recovery procedures. Are you sure? (y or n):
....
.. 在 Bootmenu Option 提示字元中、輸入 `Y`以確認您要使用 bootmedia 恢復選項。
.. 出現提示時、請輸入內建金鑰管理程式的複雜密碼、然後再次輸入複雜密碼以確認。
+
.顯示複雜密碼提示範例
[%collapsible]
=====
....
Enter the passphrase for onboard key management:
Enter the passphrase again to confirm:
Enter the backup data:
TmV0QXBwIEtleSBCbG9iAAECAAAEAAAAcAEAAAAAAAA3yR6UAAAAACEAAAAAAAAA
QAAAAAAAAACJz1u2AAAAAPX84XY5AU0p4Jcb9t8wiwOZoqyJPJ4L6/j5FHJ9yj/w
RVDO1sZB1E4HO79/zYc82nBwtiHaSPWCbkCrMWuQQDsiAAAAAAAAACgAAAAAAAAA
3WTh7gAAAAAAAAAAAAAAAAIAAAAAAAgAZJEIWvdeHr5RCAvHGclo+wAAAAAAAAAA
IgAAAAAAAAAoAAAAAAAAAEOTcR0AAAAAAAAAAAAAAAACAAAAAAAJAGr3tJA/LRzU
QRHwv+1aWvAAAAAAAAAAACQAAAAAAAAAgAAAAAAAAABHVFpxAAAAAHUgdVq0EKNp
.
.
.
.
....
=====
.. 從合作夥伴節點還原備份組態、 env 檔案、 mdb 和 RDB 時、請繼續監控還原程序。
+
恢復程序完成後、節點將重新開機。下列訊息表示恢復成功：

+
....
Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.wkeydb file.

Successfully recovered keymanager secrets.
....
.. 當節點重新開機時、請確認系統已重新上線且運作正常、以確認開機媒體恢復成功。
.. 將受損的控制器歸還其儲存設備、使其恢復正常運作：
+
`storage failover giveback -ofnode _impaired_node_name_`。

.. 只使用 CFO 集合體開機後、請執行下列命令。
+
`security key-manager onboard sync`



--
.外部金鑰管理程式（EKM）
--
如果已設定 EKM 、系統會顯示下列提示。

....
Error when fetching key manager config from partner <IP>:

Has key manager been configured on this system? {y|n}
....
.. 輸入 `Y`是否已設定 EKM 。
+
....
key manager is configured.
Entering Bootmenu Option 11...
....
+
系統會提示您輸入最初在設定期間使用的 EKM 設定。

.. 出現提示時、請輸入每個 EKM 組態設定。
.. 驗證叢集 UUID 和 Keystore UUID 的屬性是否正確。
+
*** 在合作夥伴節點上、使用下列命令擷取叢集 UUID 。
+
`cluster identity show`

*** 在合作夥伴節點上、使用下列命令擷取 Keystore UUID 。
+
`vserver show -type admin -fields uuid`

+
`key-manager keystore show -vserver <nodename>`

*** 如果合作夥伴節點無法使用、請使用 Mroot-AK 鍵擷取 UUID ：
+
**** 對於叢集 UUID 、請輸入下列命令：
+
`x-NETAPP-ClusterName: <cluster name>`

**** 對於 Keystore UUID 、請輸入下列命令：
+
`x-NETAPP-KeyUsage: MROOT-AK`





.. 出現提示時、請輸入 Keystore UUID 和叢集 UUID 的值。
.. 視金鑰是否成功還原而定、請採取下列其中一項動作：
+
*** 如果金鑰已成功還原、則恢復程序會繼續並重新啟動節點。繼續進行步驟 4 。
*** 如果金鑰未成功還原、系統將會停止、並顯示錯誤和警告訊息。重新執行恢復程序。
+
.顯示金鑰還原錯誤和警告訊息的範例
[%collapsible]
=====
....

ERROR: kmip_init: halting this system with encrypted mroot...

WARNING: kmip_init: authentication keys might not be available.

System cannot connect to key managers.

ERROR: kmip_init: halting this system with encrypted mroot...

Terminated

Uptime: 11m32s

System halting...

LOADER-B>
....
=====


.. 當節點重新開機時、請確認系統已重新上線且運作正常、以確認開機媒體恢復成功。
.. 將受損的控制器歸還其儲存設備、使其恢復正常運作：
+
`storage failover giveback -ofnode _impaired_node_name_`。



--
====


. 如果自動恢復已停用、請重新啟用：
+
`storage failover modify -node local -auto-giveback true`。

. 如果啟用 AutoSupport 、請還原自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=END`。


