= 
:allow-uri-read: 


在I/O進行期間、您可以不中斷地更換故障磁碟機。

.開始之前
* 儲存系統必須支援您要安裝的磁碟機。
+
https://hwu.netapp.com["NetApp Hardware Universe"^]

* 如果啟用自我加密磁碟機（ SED ）驗證，您必須使用 ONTAP 文件中的 SED 更換指示。
+
本白皮書中的說明ONTAP 說明說明更換SED之前和之後、您必須執行的其他步驟。

+
https://docs.netapp.com/us-en/ontap/encryption-at-rest/index.html["使用CLI進行NetApp加密概述"^]

* 儲存系統中的所有其他元件都必須正常運作，否則您必須先聯絡 https://mysupport.netapp.com/site/global/dashboard["NetApp支援"]，才能繼續執行此程序。
* 驗證您要移除的磁碟機是否故障。
+
您可以執行「儲存磁碟show -disfed'命令來驗證磁碟機是否故障。故障磁碟機出現在故障磁碟機清單中。如果沒有、您應該稍候、然後再次執行命令。

+

NOTE: 視磁碟機類型和容量而定、磁碟機可能需要數小時才會出現在故障磁碟機清單中。



.關於這項工作
* 更換故障磁碟機時，您必須在移除磁碟機與插入替換磁碟機之間等待 70 秒，以便讓儲存系統辨識磁碟機已移除。
* 最佳做法是在熱插拔磁碟機之前，先安裝最新版本的磁碟資格認證套件（ DQP ）。
+
安裝最新版的DQP可讓您的系統辨識及使用新的合格磁碟機。如此可避免系統事件訊息、因為無法辨識磁碟機、因此無法取得非最新的磁碟機資訊並防止磁碟分割。此外、DQP也會通知您非最新的磁碟機韌體。

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip["NetApp下載：磁碟認證套件"^]

* 最佳做法是在更換 FRU 元件之前，先在系統上安裝最新版本的 NVMe 機架模組（ NSM ）韌體和磁碟機韌體。
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp下載：磁碟櫃韌體"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp下載：磁碟機韌體"^]

+
[NOTE]
====
請勿將韌體還原至不支援機櫃及其元件的版本。

====
* 磁碟機韌體會自動更新（不中斷營運）、以安裝非最新韌體版本的新磁碟機。
+

NOTE: 每兩分鐘檢查一次磁碟機韌體。

* 如有需要，您可以開啟儲存系統位置（藍色） LED ，以協助實際定位受影響的儲存系統。使用 SSH 登入 BMC ，然後輸入 `system location-led _on_`命令。
+
儲存系統有三個位置 LED ：一個在操作員顯示面板上，一個在每個控制器上。位置LED會持續亮起30分鐘。

+
您可以輸入命令將其關閉 `system location-led _off_`。如果您不確定 LED 是否亮起或熄滅，可以輸入命令來檢查其狀態 `system location-led show`。


