= 
:allow-uri-read: 


若要使用此程序，您的儲存系統必須執行 ONTAP 9.17.1 或更新版本，且您的儲存系統必須符合儲存系統所執行 ONTAP 版本的所有要求。


NOTE: 如果您的儲存系統未執行 ONTAP 9.17.1 或更新版本、或不符合儲存系統所執行 ONTAP 版本的所有需求、則無法使用此程序、您必須使用 link:io-module-replace.html["更換 I/O 模組程序"]。

[role="tabbed-block"]
====
.ONTAP 9.17.1 或 9.18.1RC
--
* 您正在熱插拔插槽 4 中發生故障的叢集和 HA I/O 模組，更換為等效的 I/O 模組。您無法變更 I/O 模組類型。
* 具有故障叢集和 HA I/O 模組的控制器（受損控制器）必須已接管正常的合作夥伴控制器。如果 I/O 模組發生故障，接管應該會自動進行。
+
對於雙節點叢集，儲存系統無法區分哪個控制器的 I/O 模組故障，因此任一控制器都可能啟動接管。只有當具有故障 I/O 模組的控制器（受損控制器）接管正常控制器時，才支援熱插拔。熱插拔 I/O 模組是在不中斷的情況下進行還原的唯一方法。

+
您可以輸入以下命令來驗證受損控制器是否成功接管了健康控制器 `storage failover show`命令。

+
如果您不確定哪個控制器的 I/O 模組出現故障，請聯絡 https://mysupport.netapp.com/site/global/dashboard["NetApp支援"] 。

* 您的儲存系統配置必須只有一個位於插槽 4 的叢集和 HA I/O 模組，而不是兩個叢集和 HA I/O 模組。
* 您的儲存系統必須是雙節點（無交換器或有交換器）叢集配置。
* 儲存系統中的所有其他元件都必須正常運作；否則，請先聯絡， https://mysupport.netapp.com/site/global/dashboard["NetApp支援"]再繼續執行此程序。


--
.ONTAP 9.18.1GA 或更新版本
--
* 您正在對任意插槽中的乙太網路 I/O 模組進行熱插拔，該插槽可以包含用於叢集、HA 和用戶端的任意連接埠組合，並且需要使用功能相同的 I/O 模組。您無法變更 I/O 模組類型。
+
乙太網路 I/O 模組，其連接埠用於儲存或 MetroCluster 不支援熱插拔。

* 您的儲存系統（無交換器或有交換器叢集組態）可以有任何數量的節點，以供您的儲存系統支援。
* 叢集中的所有節點都必須執行相同的 ONTAP 版本（ONTAP 9.18.1GA 或更新版本），或執行相同 ONTAP 版本的不同修補程式層級。
+
如果叢集中的節點執行不同的 ONTAP 版本，則該叢集被視為混合版本叢集，不支援熱插拔 I/O 模組。



* 儲存系統中的控制器可能處於下列其中一種狀態：
+
** 兩個控制器都可以啟動並執行 I/O（提供資料）。
** 如果接管是由故障的 I/O 模組引起的，且控制器在其他方面運作正常，則任一控制器都可以處於接管狀態。
+
在某些情況下，ONTAP 可以因為 I/O 模組故障而自動接管任一控制器。例如，如果故障的 I/O 模組包含所有叢集連接埠（該控制器上的所有叢集連結都中斷），ONTAP 會自動執行接管。





* 儲存系統中的所有其他元件都必須正常運作；否則，請先聯絡， https://mysupport.netapp.com/site/global/dashboard["NetApp支援"]再繼續執行此程序。


--
====