= 新的介面卡支援
:allow-uri-read: 




== 新的介面卡支援

[cols="4*"]
|===
| 介面卡零件編號 | 說明 | 類別 | 可用的開始 


 a| 
https://hwu.netapp.com/adapter/index["X91148A."]
 a| 
2埠100GbE ROCE QSFP28
 a| 
* 儲存設備
* 網路
* HA/MetroCluster

 a| 
部分9.8 ONTAP



 a| 
https://hwu.netapp.com/adapter/index["X91122A"]
 a| 
2埠25GbE ROCE QSFP28
 a| 
* 網路
* HA/MetroCluster

 a| 
部分9.8 ONTAP



 a| 
https://hwu.netapp.com/adapter/index["X9170A"]
 a| 
NVMe SSD模組（1 TB）
 a| 
核心傾印裝置
 a| 
部分9.8 ONTAP

|===


== 新交換器支援

[cols="25h,~,~"]
|===
| 交換器 | 說明 | 可用的開始 


 a| 
https://hwu.netapp.com/Switch/Index["36埠100 GbE Cisco交換器（X190200）"]
 a| 
在同一組Cisco Nexus 9336C-FX2交換器上支援共享基礎架構（叢集、HA和交換器附加儲存設備）、包括支援MetroCluster 不支援任何IP組態。
 a| 
部分9.9.1 ONTAP



 a| 
https://hwu.netapp.com/Switch/Index["36埠100 GbE Cisco交換器（X190200和X190210）"]
 a| 
Cisco Nexus 9336C-FX2叢集互連交換器與儲存交換器支援AFF/FAS控制器、以及前端資料連線。
 a| 
部分9.8 ONTAP



 a| 
https://hwu.netapp.com/Switch/Index["Broadcom BCS-53248交換器（X190005和X190005R）"]
 a| 
Broadcom BS-53248叢集互連交換器支援AFF/FAS控制器、具有40/100GbE連接埠。
 a| 
部分9.8 ONTAP



 a| 
https://hwu.netapp.com/Switch/Index["36埠100 GbE Cisco交換器（X190200）"] https://hwu.netapp.com/Switch/Index["32埠100 GbE Cisco交換器（X190100和X190100R）"]
 a| 
Cisco Nexus 100 GbE交換器可作為專用儲存交換器、將NS224 NVMe磁碟機櫃連接至下列平台：

* 介紹A800/AFF的A800 AFF ASA
* 介紹A700/AFF的功能AFF ASA
* 介紹A400/AFF的功能AFF ASA
* 解答320 AFF

 a| 
部分9.8 ONTAP



 a| 
https://hwu.netapp.com/Switch/Index["Broadcom BCS-53248交換器（X190005和X190005R）"]
 a| 
Broadcom BS-53248叢集互連交換器支援AFF/FAS控制器、具備10/25GbE連接埠。
 a| 
零點9.5P8 ONTAP

|===


== 新平台支援

[cols="2*"]
|===
| 平台（含資料表連結） | 可用的開始 


 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["解答900 AFF"]
 a| 
零點9.10.1 ONTAP



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["VA250/AFF F4A250 AFF ASA"]
 a| 
部分9.8 ONTAP



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS500f"]
 a| 
部分9.8 ONTAP



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["解答800 AFF ASA"]
 a| 
部分9.8 ONTAP



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS8300"]
 a| 
更新ONTAP



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS8700"]
 a| 
更新ONTAP



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["解答400 AFF"]
 a| 
更新ONTAP



 a| 
https://www.netapp.com/pdf.html?item=/media/17190-na-382.pdf["VA220 AFF ASA"]
 a| 
更新ONTAP



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["部分A700 AFF ASA"]
 a| 
更新ONTAP



 a| 
https://www.netapp.com/us/media/ds-3989.pdf["C190 AFF"]
 a| 
部分9.6 ONTAP



 a| 
https://www.netapp.com/pdf.html?item=/media/17190-na-382.pdf["解答320 AFF"]
 a| 
部分9.6 ONTAP

|===


== 全新機櫃支援

[cols="2*"]
|===
| 磁碟櫃 | 可用的開始 


 a| 
NS224
 a| 
部分9.6 ONTAP

|===


== 新硬體更新

[cols="25h,~,~"]
|===
| 功能 | 說明及深入瞭解的地方 | 可用的開始 


 a| 
更廣泛的NS224磁碟機櫃平台支援
 a| 
下列平台支援NS224磁碟機櫃：

* 介紹A800/AFF的A800 AFF ASA
* 介紹A700/AFF的功能AFF ASA
* VA250/AFF F4A250 AFF ASA
* FAS500f

 a| 
部分9.8 ONTAP



 a| 
熱新增12Gb SAS磁碟櫃至6Gb SAS儲存堆疊
 a| 
SAS儲存堆疊現在支援從6Gb到12Gb的單一速度轉換。如此一來、現有6Gb堆疊的儲存設備就能以12Gb架架擴充。

https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["將含有IOM12模組的熱新增磁碟櫃放到具有IOM6模組的磁碟櫃堆疊中"]
 a| 
零點9.7P4 ONTAP

部分9.6P9 ONTAP

零點9.5P14 ONTAP

|===


== 新的硬體增強功能

由於推出自動連接埠配置功能、因此在更新過程中、硬體升級程序已在ONTAP 更新過程中簡化。當您升級執行ONTAP 不正常的系統時、必須使用正確的程序來說明連接埠放置功能。

請檢閱下表、查看可用的升級程序。如需其他詳細資料、請參閱每份指南、以判斷程序是否適當。

如需MetroCluster的其他特定程序、請參閱 https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["選擇升級或重新整理方法"]。

[cols="4*"]
|===
| 版本ONTAP | 位置 | 不中斷營運 | 支援MetroCluster 


 a| 
9.8到9.1.x
 a| 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-decide-to-use-this-guide.html["控制器硬體升級快速指南"] （移動現有的實體儲存設備）
 a| 
否
 a| 
否



 a| 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-decide-to-use-this-guide.html["控制器硬體升級快速指南"] （將磁碟區移至新儲存設備）
 a| 
是的
 a| 
否



 a| 
9.8
 a| 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-decide-to-use-this-guide.html["使用「系統控制器更換」命令來升級執行ONTAP VMware 9.8的控制器硬體"]
 a| 
是的
 a| 
有（FC）



 a| 
9.8
 a| 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual-app/index.html["使用Aggregate Relocation來手動升級執行ONTAP VMware 9.8或更新版本的控制器硬體"]
 a| 
是的
 a| 
有（FC）



 a| 
9.7至9.5
 a| 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto/index.html["使用「系統控制器更換」命令、將執行ONTAP VMware 9.5的控制器硬體升級至ONTAP VMware 9.7"]
 a| 
是的
 a| 
有（FC）



 a| 
9.7及更早版本
 a| 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual/index.html["將具有Aggregate Relocation的控制器升級為手動升級執行ONTAP VMware 9.7及更早版本的控制器硬體"]
 a| 
是的
 a| 
有（FC）

|===