= 
:allow-uri-read: 


從 ONATP 開機功能表還原外部金鑰管理程式組態。

.開始之前
您需要下列資訊來還原外部金鑰管理程式（ EKM ）組態：

* 從另一個叢集節點複本 /ccfcard/kmip/servers.cfg 檔案、或以下資訊：
+
** KMIP 伺服器位址。
** KMIP 連接埠。
** 從其他叢集節點或用戶端憑證複本 /ccfcard/kmip/certs/client.crt 檔案。
** 從其他叢集節點或用戶端金鑰複本 /ccfcard/kmip/certs/client.key 檔案。
** 另一個叢集節點或 KMIP 伺服器 CA 的 /ccfcard/kmip/certs/ca.pem 檔案複本。




.步驟
. 將主控台纜線連接至目標控制器。
. 從 ONTAP 開機功能表中選取選項 11 。
+
.顯示開機功能表範例
[%collapsible]
====
....

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 11
....
====
. 出現提示時、請確認您已收集必要資訊。
+
.顯示範例提示
[%collapsible]
====
....
Do you have a copy of the /cfcard/kmip/certs/client.crt file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/client.key file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/CA.pem file? {y/n}
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
....
====
+
.您可能會看到這些提示
[%collapsible]
====
....
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
Do you know the KMIP server address? {y/n}
Do you know the KMIP Port? {y/n}
....
====
. 出現提示時、請輸入用戶端和伺服器資訊。
+
.顯示提示
[%collapsible]
====
....
Enter the client certificate (client.crt) file contents:
Enter the client key (client.key) file contents:
Enter the KMIP server CA(s) (CA.pem) file contents:
Enter the server configuration (servers.cfg) file contents:
....
====
+
.顯示範例
[%collapsible]
====
....
Enter the client certificate (client.crt) file contents:
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

Enter the client key (client.key) file contents:
-----BEGIN RSA PRIVATE KEY-----
<key_value>
-----END RSA PRIVATE KEY-----

Enter the KMIP server CA(s) (CA.pem) file contents:
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

Enter the IP address for the KMIP server: 10.10.10.10
Enter the port for the KMIP server [5696]:

System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
kmip_init: configuring ports
Running command '/sbin/ifconfig e0M'
..
..
kmip_init: cmd: ReleaseExtraBSDPort e0M
....
====
. 恢復程序即告完成。
+
.顯示範例提示
[%collapsible]
====
....


System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
Performing initialization of OpenSSL
Successfully recovered keymanager secrets.

....
.. 從開機功能表中選取選項 1 、以繼續開機至 ONTAP 。
+
....

***********************************************************************************
* Select option "(1) Normal Boot." to complete the recovery process.
*
***********************************************************************************


(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 1

....


====
. 如果停用自動恢復功能，請還原：
+
`storage failover modify -node local -auto-giveback true`

. 如果啟用 AutoSupport 、請輸入下列命令、以還原自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=END`


