= 
:allow-uri-read: 


在將node1替換成node3之前、您需要使用storage Aggregate replace命令、將非根Aggregate從node1移至node2、然後驗證重新配置。

.步驟
. [[step1]]完成下列子步驟、重新部署非根集合體：
+
.. 將權限層級設為進階：
+
"進階權限"

.. 輸入下列命令：
+
「torage Aggregate regate or搬 移開始節點<node1>-destination <node2>-Aggregate-list *-NDA-控制 器升級true」

.. 出現提示時、請輸入「y」。
+
重新配置將會在背景中進行。重新部署集合體可能需要幾秒鐘到幾分鐘的時間。時間包括用戶端中斷和非中斷部分。此命令不會重新部署任何離線或受限的集合體。

.. 輸入下列命令即可返回管理員層級：
+
「et -priv. admin」



. 在節點1上輸入下列命令、檢查重新配置狀態：
+
「torage Aggregate regate reg搬 移顯示-node1>'

+
在重新放置集合體之後、輸出會顯示「Done」。

+

NOTE: 請等到節點1擁有的所有非根集合體都已重新定位至節點2、然後再繼續下一步。

. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果重新配置... | 然後... 


| 所有的集合體都成功 | 前往 <<man_relocate_1_2_step4,步驟4.>>。 


| 任何集合體的故障或被否決  a| 
.. 檢查EMS記錄以瞭解修正行動。
.. 執行修正行動。
.. 重新定位任何故障或被否決的Aggregate：「torage Aggregate relocationstart -node1>- destination <node2>-Aggregate-list *-n控制器升級true」
.. 出現提示時、請輸入「y」。
.. 返回管理員層級：「et -priv. admin」（設定權限管理員）如有必要、您可以使用下列其中一種方法強制重新配置：
+
*** 置換否決檢查：「torage aggregate regate regate or搬 移開始-置換- etoes true -n控制器升級」
*** 置換目的地檢查：「torage Aggregate regate or地址 重新配置start -overre-destination-checkstrue -ND-控制 器升級」




請參閱 link:other_references.html["參考資料"] 如需ONTAP 儲存Aggregate重新定位命令的詳細資訊、請連結至_磁碟與Aggregate Power Guide_和_還原9命令：手冊頁參考_。

|===
. [[man_allocation_1_2_step4]]確認所有非根Aggregate都在線上、且其狀態位於節點2：
+
「torage Aggregate show -node2>-state online -root假」

+
以下範例顯示節點2上的非根Aggregate處於線上狀態：

+
[listing]
----
cluster::> storage aggregate show -node node2 state online -root false
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
aggr_1
           744.9GB 744.8GB      0% online       5 node2            raid_dp,
                                                                   normal
aggr_2     825.0GB 825.0GB      0% online       1 node2            raid_dp,
                                                                   normal
2 entries were displayed.
----
+
如果Aggregate已離線或成為節點2上的外部節點、請在節點2上使用下列命令將其上線、每個Aggregate一次：

+
「torage Aggregate online -gregate <agger_name>」

. 在node2上輸入下列命令並檢查其輸出、以確認節點2上的所有磁碟區均已上線：
+
「Volume show -node2>-state offline」（Volume show -node2>-state offline）

+
如果節點2上有任何磁碟區離線、請在節點2上使用下列命令將其上線、每個磁碟區一次：

+
「Volume online -vserver <vserver-name>-volume <Volume <Volume名稱>'

+
與此命令搭配使用的「vserver名稱」可在先前的「volume show」命令輸出中找到。

. 在節點2上輸入下列命令：
+
「torage容錯移轉show -Node <node2>'」

+
輸出應顯示下列訊息：

+
[listing]
----
Node owns partner's aggregates as part of the nondisruptive controller upgrade procedure.
----
. 驗證node1是否沒有任何線上的非根Aggregate：
+
「torage Aggregate show -Owner-name <node1>-ha-policy SFO -state online」

+
輸出不應顯示任何已重新定位到節點2的線上非根Aggregate。


