= 
:allow-uri-read: 


. [[man_lif_VERIF_3_step6]]輸入下列命令、將每個NAS資料LIF移轉至節點3、每個LIF一次：
+
「網路介面移轉-vserver <vserver_name>-lif<lif_name>-dite-node<node3>-dite-port <netport|ifgrp>'

. [[man_lif_VERIF_3_step7]請確定資料移轉持續進行：
+
「網路介面修改-vserver <vserver_name>-lif <lif_name>-home-port <netport|ifgrp>-home-node3>`

. [[man_lif_VERIF_3_step8]確認SAN LIF位於節點3上的正確連接埠：
+
.. 輸入下列命令並檢查其輸出：
+
「網路介面show -data傳輸協定iscsiSCSI|FCP -home-Node <node3>'

+
系統會傳回類似下列範例的輸出：

+
[listing]
----
cluster::> net int show -data-protocol iscsi|fcp -home-node node3
              Logical     Status      Network             Current        Current  Is
 Vserver      Interface   Admin/Oper  Address/Mask        Node           Port     Home
 -----------  ----------  ----------  ------------------  -------------  -------  ----
 vs0
              a0a         up/down     10.63.0.53/24       node3          a0a      true
              data1       up/up       10.63.0.50/18       node3          e0c      true
              rads1       up/up       10.63.0.51/18       node3          e1a      true
              rads2       up/down     10.63.0.52/24       node3          e1b      true
 vs1
              lif1        up/up       172.17.176.120/24   node3          e0c      true
              lif2        up/up       172.17.176.121/24   node3          e1a      true
----
.. 如果節點3的SAN生命體或SAN生命體群組位於節點1上不存在的連接埠、或需要對應至不同連接埠、請完成下列子步驟、將其移至節點3上的適當連接埠：
+
... 將LIF狀態設為「向下」：
+
「網路介面修改-vserver <vserver_name>-lIF <LIF_name>-STATUS-admin DOWN」

... 從連接埠集移除LIF：
+
「portset移除-vserver <vserver_name>-portset <portSet_name>-port-name <port_name>」

... 輸入下列其中一個命令：
+
**** 移動單一LIF：
+
「網路介面修改-vserver <vserver_name>-lIF <LIF_name>-home-port <new_home_port>`

**** 將單一不存在或不正確連接埠上的所有LIF移至新連接埠：
+
「網路介面修改｛-home-port <port_on_node1>-home-Node <node1>-role data｝-home-port <new_home_port_on_node3>'

**** 將lifs新增回連接埠集：
+
「portset add -vserver <vserver_name>-portset <portset_name>-port-name <port_name>'

+

NOTE: 您需要確保將SAN LIF移至與原始連接埠具有相同連結速度的連接埠。







. 將所有生命期的狀態修改為「up」、以便生命期可以接受及傳送節點上的流量：
+
「網路介面修改-home-port <port_name>-home-node<node3>-lIF DATA -STATUS-admin up」

. 在任一節點上輸入下列命令、檢查其輸出、確認已將l生命 移至正確的連接埠、並在任一節點上輸入下列命令、檢查輸出結果、以確認lIF的狀態為「up」：
+
「網路介面show -home-Node <node3>-role data」

. [[man_lif_VERIF_3_step11]如果有任何lifs當機、請輸入下列命令將lifs的管理狀態設為「up」、每個LIF一次：
+
「網路介面修改-vserver <vserver_name>-lIF <LIF_name>-STATUS-admin up」

. 將升級後AutoSupport 的支援資訊訊息傳送給NetApp for node1：
+
「系統節點AutoSupport 無法叫用節點<node3>-type all -messed "node1 Successfully eved from <platform _old> to <platform _new>""（系統節點無法叫用節點<node3>-type all -messed "node1已


