= 
:allow-uri-read: 


您需要在機架中安裝node3、將node1的連線傳輸至node3、開機node3、以及安裝ONTAP 支援。然後您需要重新指派節點1的任何備用磁碟、屬於根磁碟區的任何磁碟、以及先前未重新定位至節點2的任何非根Aggregate。

如果netboot node3沒有ONTAP 安裝在node1上的相同版本的支援功能、您就需要netboot node3。安裝node3之後、請從ONTAP 儲存在Web伺服器上的Image9映像啟動節點3。然後、您可以將正確的檔案下載到開機媒體裝置、以供後續系統開機。請參閱 link:prepare_for_netboot.html["準備netboot"]。

不過、如果netboot node3的ONTAP 版本與node1上安裝的版本相同或更新、則不需要netboot node3。


NOTE: *重要事項*：如果您要升級連接至儲存陣列的V系列系統、或是使用FlexArray 連接至儲存陣列的「虛擬化」軟體來升級系統、就必須完成 <<man_install3_step1,步驟1.>> 透過 <<man_install3_step5,步驟5.>>請將本節保留在 <<man_install3_step6,步驟6.>> 並遵循中的指示 link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["在節點3上設定FC連接埠"] 和 link:set_fc_uta_uta2_config_node3.html#check-and-configure-UTAUTA2-ports-on-node3["檢查並設定節點3上的UTA/UTA2連接埠"] 視需要在維護模式中輸入命令。接著您必須返回本節並繼續 <<man_install3_step7,步驟7.>>。不過、如果您要升級具有儲存磁碟的系統、則必須完成本節的完整內容、然後前往 link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["在節點3上設定FC連接埠"] 和 link:set_fc_uta_uta2_config_node3.html#check-and-configure-UTAUTA2-ports-on-node3["檢查並設定節點3上的UTA/UTA2連接埠"]，在叢集提示字元中輸入命令。

.步驟
. [[man_install3_step1]]確定您有節點3的機架空間。
+
如果節點1和節點2位於不同的機箱中、您可以將節點3放在與節點1相同的機架位置。但是、如果節點1與節點2位於同一個機箱中、則您需要將節點3放入自己的機架空間、最好是靠近節點1的位置。

. [[step2]]Install node3 in the rack、遵照節點機型的安裝與設定指示_。
+

NOTE: 如果您要升級到同一機箱中同時具有兩個節點的系統、請在機箱中安裝node4以及node3。如果沒有、當您開機節點3時、節點的行為就會如同雙機箱組態、當您開機節點4時、節點之間的互連就不會出現。

. [[step3]]纜 線節點3、將連線從節點1移至節點3。
+
下列參考資料可協助您建立適當的纜線連線。前往 link:other_references.html["參考資料"] 以連結至他們。

+
** _Installation and Setup Instructions（安裝與設定說明）_或_Estratested FlexArray Virtualization Installation Requirements and Reference（_針對節點3平台的虛擬化安裝要求與參考資料）。
** 適當的磁碟櫃指南。
** 《_》《_》9《高可用度組態指南》_ ONTAP


+
纜線連接下列連接：

+
** 主控台（遠端管理連接埠）
** 叢集連接埠
** 資料連接埠
** 叢集與節點管理連接埠
** 儲存設備
** SAN組態：iSCSI乙太網路和FC交換器連接埠
+

NOTE: 您可能不需要將互連卡或叢集互連纜線連線從節點1移至節點3、因為大多數平台機型都有獨特的互連卡模式。若要進行支援、您需要將FC-VI纜線連線從節點1移至節點3。MetroCluster如果新主機沒有FC-VI卡、您可能需要移動FC-VI卡。



. [[man_install3_step4]]開啟節點3的電源、然後在主控台終端按Ctrl-C存取開機環境提示字元、以中斷開機程序。
+
如果您要升級到同一機箱中同時具有兩個節點的系統、節點4也會重新開機。不過、您可以忽略node4開機、直到稍後再執行。

+

NOTE: 當您啟動節點3時、可能會看到下列警告訊息：

+
[listing]
----
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
----
. [[man_install3_step5]如果您在中看到警告訊息 <<man_install3_step4,步驟4.>>、請採取下列行動：
+
.. 檢查可能指出NVRAM電池電量不足以外問題的任何主控台訊息、並視需要採取任何必要的修正行動。
.. 讓電池充電並完成開機程序。
+

NOTE: *注意*：請勿置換延遲；若不允許電池充電、可能導致資料遺失。



. [[man_install3_step6]]採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果您的系統... | 然後... 


| 具有磁碟、無後端儲存設備 | 跳過步驟7至步驟12、前往 <<man_install3_step13,步驟13>>。 


| 是連接FlexArray 至儲存陣列的V系列系統或系統、其中含有與之相關的功能完善的虛擬化軟體  a| 
.. 前往 link:set_fc_uta_uta2_config_node3.html["在節點3上設定FC或UTA/UTA2組態"] 並完成這些小節 link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["在節點3上設定FC連接埠"] 和 link:set_fc_uta_uta2_config_node3.html#check-and-configure-UTAUTA2-ports-on-node3["檢查並設定節點3上的UTA/UTA2連接埠"]（視系統而定）。
.. 返回本節、並完成其餘步驟、從開始 <<man_install3_step7,步驟7.>>。


*重要事項*：您必須先重新設定FC內建連接埠、CNA內建連接埠和CNA卡、才能ONTAP 使用FlexArray 「支援虛擬化」軟體在V系列或系統上啟動。

|===
. [[man_install3_step7]將新節點的FC啟動器連接埠新增至交換器區域。
+
如果您的系統有磁帶SAN、則需要將啟動器分區。請參閱儲存陣列與分區文件以取得相關指示。

. [[man_install3_step8]將FC啟動器連接埠新增至儲存陣列做為新主機、將陣列LUN對應至新主機。
+
請參閱儲存陣列與分區文件以取得相關指示。

. [[man_install3_step9]]修改與儲存陣列上陣列LUN相關之主機或磁碟區群組中的全球連接埠名稱（WWPN）值。
+
安裝新的控制器模組會變更與每個內建FC連接埠相關的WWPN值。

. [[man_install3_step10]如果您的組態使用交換器型分區、請調整分區以反映新的WWPN值。
. [[man_install3_step11]確認節點3現在可以看到陣列LUN：
+
"syssconfig -v"

+
系統會顯示每個FC啟動器連接埠可見的所有陣列LUN。如果陣列LUN不可見、您將無法在本節稍後的部分、將磁碟從節點1重新指派至節點3。

. [[man_install3_step12]按Ctrl-C顯示開機功能表、然後選取維護模式。
. [[man_install3_step13]在維護模式提示字元下、輸入下列命令：
+
《停止》

+
系統會在開機環境提示字元停止。

. [[man_install3_step14]執行下列其中一項動作：
+
[cols="35,65"]
|===
| 如果您要升級的系統位於... | 然後... 


| 雙機箱組態（控制器位於不同機箱） | 前往 <<man_install3_step15,步驟15>>。 


| 單一機箱組態（控制器位於同一個機箱中）  a| 
.. 將主控台纜線從節點3切換至節點4。
.. 開啟節點4的電源、然後在主控台終端按Ctrl-C來存取開機環境提示字元、以中斷開機程序。
+
如果兩個控制器位於同一個機箱中、則電源應該已經開啟。

+
*附註*：在開機環境提示字元下保留node4；您將返回中的node4 link:install_boot_node4.html["安裝及開機節點4"]。

.. 如果您在中看到警告訊息 <<man_install3_step4,步驟4.>>、請依照中的指示進行 <<man_install3_step5,步驟5.>>
.. 將主控台纜線從節點4切換回節點3。
.. 前往 <<man_install3_step15,步驟15>>。


|===
. [[man_install3_step15]]<設定ONTAP 節點3以供參考：
+
「預設值」

. [[man_install3_step16]如果此組態正在使用NetApp儲存加密（NSE）、則必須將「setenv bootarg.storageEncryption.support'命令設定為「true」、並將「kmip.init.maxwait`變數」設定為「Off」、以避免在節點1組態載入後發生開機迴圈：
+
「etenv bootarg.storageencryption。支援true」

+
「kmip.init.maxwait關」

. [[man_install3_step17]如果ONTAP 安裝在節點3上的版本與ONTAP 安裝在節點1上的版本相同或更新、請列出磁碟並重新指派給新節點3：
+
Boot_ONTAP

+

WARNING: *警告*：如果此新節點曾經用於任何其他叢集或HA配對、您必須先執行「wifeconfig」、然後再繼續。否則可能導致服務中斷或資料遺失。如果先前使用的是替換控制器、請聯絡技術支援部門、特別是當控制器以ONTAP 7-Mode執行時。

. [[man_install3_step18]按下CTRL－C以顯示開機功能表。
. [[man_install3_step19]執行下列其中一項動作：
+
[cols="35,65"]
|===
| 如果您要升級的系統... | 然後... 


| 節點3上是否有正確或最新ONTAP 的版本 | 前往 <<man_install3_step20,步驟20>>。 


| 節點3上有正確或最新版本ONTAP 的資訊 | 前往 <<man_install3_step25,步驟25>>。 
|===
. [[man_install3_step20]]選擇下列其中一項動作來設定netboot連線。
+

NOTE: 您應該使用管理連接埠和IP做為netboot連線。請勿使用資料LIF IP、否則在執行升級時可能會發生資料中斷。

+
[cols="35,65"]
|===
| 如果動態主機組態傳輸協定（DHCP）是... | 然後... 


| 執行中 | 在開機環境提示字元中輸入下列命令、即可自動設定連線：「ifconfige0M -auto」 


| 未執行 | 在開機環境提示字元中輸入下列命令、手動設定連線：「ifconfige0M -addr=<filer_addr>-mask=<netmask>-gateway=-DNs=<DNs_addr> domain=<DNs_domain>'<filer_addr>'是儲存系統的IP位址。「網路遮罩」是儲存系統的網路遮罩。「<閘道>」是儲存系統的閘道。'<DNs_addr>'是網路上名稱伺服器的IP位址。'<DNs_domain>'是網域名稱服務（DNS）網域名稱。如果使用此選用參數、則不需要netboot伺服器URL中的完整網域名稱；您只需要伺服器的主機名稱。*附註*：您的介面可能需要其他參數。在韌體提示字元中輸入「Help ifconfig」以取得詳細資料。 
|===
. [[man_install3_step21]]在節點3上執行netboot：
+
[cols="35,65"]
|===
| 適用於... | 然後... 


| FAS / AFF8000系列系統 | “netboot \http://<web_server_ip>/<path_to_webaccessible_directory>/netboot/kernel` 


| 所有其他系統 | “netboot \http://<web_server_ip>/<path_to_webaccessible_directory>/<ontap_version>_image.tgz` 
|===
+
「<path_to_the_web-易於 存取的目錄>」應該會引導您下載「<ONTAP_VERSION >_image.tgz」 link:prepare_for_netboot.html#man_netboot_Step1["步驟1."] 在_Prepare for netboot_一節中。

+

NOTE: 請勿中斷開機。

. [[man_install3_step22]從開機功能表中、選取選項*（7）「Install new software* first（先安裝新軟體*）」。
+
此功能表選項會下載新ONTAP 的功能表映像、並將其安裝至開機裝置。

+

NOTE: 請忽略下列訊息：

+
[listing]
----
This procedure is not supported for Non-Disruptive Upgrade on an HA pair.
----
+
本附註適用於ONTAP 不中斷營運的更新功能、不適用於控制器升級。

+

NOTE: 請務必使用netboot將新節點更新為所需映像。如果您使用另一種方法在新控制器上安裝映像、可能會安裝錯誤的映像。此問題適用於ONTAP 所有版本的更新版本。

. [[man_install3_step23]如果系統提示您繼續此程序、請輸入「y」、並在系統提示您輸入套件時、輸入下列URL：
+
http://<web_server_ip>/<path_to_web-accessible_directory>/<ontap_version_image>.tgz`

. [[man_install3_step24]完成下列子步驟：
+
.. 當您看到下列提示時、請輸入「n」跳過備份恢復：
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. 當您看到下列提示時、輸入「y」重新開機：
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
控制器模組會重新開機、但會在開機功能表停止、因為開機裝置已重新格式化、需要還原組態資料。



. [[man_install3_step25]輸入「5」選取*（5）維護模式開機*、然後在提示繼續開機時輸入「y」。
. [[man_install3_step26]在繼續之前、請前往 link:set_fc_uta_uta2_config_node3.html["在節點3上設定FC或UTA/UTA2組態"] 可對節點上的FC或UTA/UTA2連接埠進行必要的變更。
+
進行這些區段中建議的變更、重新啟動節點、然後進入維護模式。

. [[man_install3_step27]尋找節點3的系統ID：
+
「展示-A'」

+
系統會顯示節點的系統ID及其磁碟的相關資訊、如下列範例所示：

+
[listing]
----
 *> disk show -a
 Local System ID: 536881109
 DISK     OWNER                    POOL  SERIAL   HOME          DR
 HOME                                    NUMBER
 -------- -------------            ----- -------- ------------- -------------
 0b.02.23 nst-fas2520-2(536880939) Pool0 KPG2RK6F nst-fas2520-2(536880939)
 0b.02.13 nst-fas2520-2(536880939) Pool0 KPG3DE4F nst-fas2520-2(536880939)
 0b.01.13 nst-fas2520-2(536880939) Pool0 PPG4KLAA nst-fas2520-2(536880939)
 ......
 0a.00.0               (536881109) Pool0 YFKSX6JG              (536881109)
 ......
----
+

NOTE: 您可能會在輸入命令後看到「磁碟顯示：沒有磁碟符合選項-A.」訊息。這不是錯誤訊息、因此您可以繼續執行程序。

. [[man_install3_step28]重新指派node1的備援磁碟、屬於根的任何磁碟、以及先前未重新部署至節點2的任何非根Aggregate link:relocate_non_root_aggr_node1_node2.html["將非根Aggregate從節點1重新部署到節點2"]。
+
根據您的系統是否有共享磁碟、輸入適當形式的「磁碟重新指派」命令：

+
[cols="35,65"]
|===
| 如果磁碟類型為... | 然後執行命令... 


| 共享磁碟 | "Disk reassign-s <node1_sysid>-d <node3_sysid>-p <node2_sysid>' 


| 無共享磁碟 | "Disk reassign-s <node1_sysid>-d <node3_sysid>' 
|===
+
如需「<節點1_sysid>'」值、請使用中擷取的資訊 link:record_node1_information.html["記錄node1資訊"]。若要取得「<node3_sysid>'」的值、請使用「show config」命令。

+

NOTE: 只有在存在共享磁碟時、維護模式才需要使用「-p」選項。

+
"disk reassign"命令只重新分配那些"<node1_sysid>"是當前擁有者的磁碟。

+
系統會顯示下列訊息：

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?
----
. [[man_install3_step29]輸入「n」。
+
系統會顯示下列訊息：

+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?
----
. [[man_install3_step30]輸入「y」
+
系統會顯示下列訊息：

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)?
----
. [[man_install3_step3]]輸入「y」。
. [[man_install3_step32]]如果您要從具有外部磁碟的系統升級至支援內部和外部磁碟AFF 的系統（例如、E4A800系統）、請將node1 Aggregate設為root、以確保node3從節點1的根Aggregate開機。
+

WARNING: *警告*：您必須依照所示的確切順序執行下列子步驟；否則可能導致中斷運作、甚至資料遺失。

+
下列程序會將node3設定為從節點1的根Aggregate開機：

+
.. 檢查node1 Aggregate的RAID、plex和Checksum資訊：
+
「aggr狀態-r」

.. 檢查node1 Aggregate的狀態：
+
「aggr狀態」

.. 必要時使node1 Aggregate上線：
+
「aggr_online <root_aggr_from節點1>'」

.. 防止節點3從其原始根Aggregate開機：「aggr offline <root_aggr_on_node3>'
.. 將node1根Aggregate設為節點3的新根Aggregate：
+
「aggr選項<aggr_fe_node1> root」

.. 確認節點3的根Aggregate為離線狀態、且從節點1移轉的磁碟根Aggregate為線上狀態、並設定為root：
+
「aggr狀態」

+

NOTE: 如果無法執行上一個子步驟、可能會導致節點3從內部根Aggregate開機、或是導致系統假設有新的叢集組態存在、或提示您識別一個。

+
以下是命令輸出的範例：



+
[listing]
----
 ---------------------------------------------------------------
      Aggr State               Status          Options
 aggr0_nst_fas8080_15 online   raid_dp, aggr   root, nosnap=on
                               fast zeroed
                               64-bit

   aggr0 offline               raid_dp, aggr   diskroot
                               fast zeroed
                               64-bit
 ----------------------------------------------------------------------
----
. [[man_install3_step33]確認控制器和機箱設定為「ha」：
+
《ha-config show》

+
以下範例顯示ha-config show命令的輸出：

+
[listing]
----
 *> ha-config show
    Chassis HA configuration: ha
    Controller HA configuration: ha
----
+
無論系統是在HA配對或獨立組態中、都會記錄在PROm中。獨立式系統或HA配對內的所有元件的狀態必須相同。

+
如果控制器和機箱未設定為「ha」、請使用下列命令修正組態：

+
「ha-config modify控制器ha」

+
「ha-config modify機箱ha」

+
如果您使用MetroCluster 的是不含任何功能的組態、請使用下列命令來修改控制器和機箱：

+
「ha-config modify控制器MCC」

+
「ha-config modify機箱MCC」

. [[man_install3_step34]銷毀節點3上的信箱：
+
《破壞本地的信箱》

+
主控台會顯示下列訊息：

+
[listing]
----
Destroying mailboxes forces a node to create new empty mailboxes, which clears any takeover state, removes all knowledge of out-of-date plexes of mirrored volumes, and will prevent management services from going online in 2-node cluster HA configurations. Are you sure you want to destroy the local mailboxes?
----
. [[man_install3_step35]在提示字元輸入「y」、確認您要銷毀本機信箱。
. [[man_install3_step36]結束維護模式：
+
《停止》

+
系統會在開機環境提示字元停止。

. [[man_install3_step37]在節點2上、檢查系統日期、時間和時區：
+
'日期'

. [[man_install3_step38]在節點3上、請在開機環境提示字元中檢查日期：
+
「如何日期」

. [[man_install3_step39]如有必要、請在節點3上設定日期：
+
「et date <mm/dd/yed>'

. [[man_install3_step40]在節點3上、檢查開機環境提示字元的時間：
+
「時間安排」

. [[man_install3_step41]如有必要、請在節點3上設定時間：
+
「設定時間<hh：mm：ss>」

. [[man_install3_step42]]確認合作夥伴系統ID設定正確、如所述 <<man_install3_step28,步驟28>> 在-p交換器下：
+
《prontenv合作夥伴sysid》

. [[man_install3_step43]如有必要、請在節點3上設定合作夥伴系統ID：
+
「etenv PARTNER-sysid <node2_sysid>'」

+
儲存設定：

+
「aveenv」

. [[man_install3_step44]在開機環境提示字元下存取開機功能表：
+
Boot_ONTAP功能表

. [[man_install3_step45]在開機功能表中、在提示字元中輸入「6」、選取選項*（6）Update flash from Backup config*（從備份組態更新Flash）。
+
系統會顯示下列訊息：

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. [[man_install3_step46]在提示字元中輸入「y」。
+
開機會正常進行、然後系統會要求您確認系統ID不相符。

+

NOTE: 系統可能會重新開機兩次、然後才顯示不相符的警告。

. [[man_install3_step47]確認不相符的情形、如下列範例所示：
+
[listing]
----
WARNING: System id mismatch. This usually occurs when replacing CF or NVRAM cards!
Override system id (y|n) ? [n] y
----
+
在正常開機之前、節點可能會經過一輪重新開機。

. [[man_install3_step48]登入節點3。

