= 
:allow-uri-read: 


在關閉和淘汰節點2之前、您需要記錄叢集網路、管理、FC連接埠及其NVRAM系統ID的相關資訊。稍後將node2對應至node4並重新指派磁碟時、您需要該資訊。

.步驟
. 在節點2上尋找叢集網路、節點管理、叢集間和叢集管理連接埠：
+
「網路介面show -curr-Node <node_name>-role cluster、intercluster、nodemgmt、cluster管理」

+
系統會顯示叢集中該節點和其他節點的lifs、如下列範例所示：

+
[listing]
----
cluster::> network interface show -curr-node node2 -role
cluster,intercluster,node-mgmt,cluster-mgmt
         Logical     Status     Network            Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask       Node        Port    Home
-------- ----------  ---------- ------------------ ----------  ------- ----
node2
         intercluster up/up     192.168.1.202/24   node2       e0e     true
         clus1        up/up     169.254.xx.xx/24   node2       e0a     true
         clus2        up/up     169.254.xx.xx/24   node2       e0b     true
         mgmt1        up/up     192.168.0.xxx/24   node2       e0c     true
4 entries were displayed.
----
+

NOTE: 您的系統可能沒有叢集間的LIF。您只能在節點配對的一個節點上使用叢集管理LIF。叢集管理LIF顯示在的範例輸出中 link:record_node1_information.html#step["步驟1."] 在_Record node1連接埠資訊_中。

. 擷取輸出中的資訊以供區段使用 link:map_ports_node2_node4.html["將連接埠從節點2對應至節點4"]。
+
需要輸出資訊、才能將新的控制器連接埠對應至舊的控制器連接埠。

. 確定節點2上的實體連接埠：
+
「網路連接埠show -node<node_name>-type Physical（實體）」+

+
「node_name」是要移轉的節點。

+
系統會顯示節點2上的實體連接埠、如下列範例所示：

+
[listing]
----
cluster::> network port show -node node2 -type physical

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- -----------
node2
       e0M       Default      IP_address       up       1500  auto/100
       e0a       Default      -                up       1500  auto/1000
       e0b       Default      -                up       1500  auto/1000
       e1a       Cluster      Cluster          up       9000  auto/10000
       e1b       Cluster      Cluster          up       9000  auto/10000
5 entries were displayed.
----
. 記錄連接埠及其廣播網域。
+
稍後的程序將需要將廣播網域對應至新控制器上的連接埠。

. 確定節點2上的FC端口：
+
「網路FCP介面卡顯示」

+
系統會在節點2上顯示FC連接埠、如下列範例所示：

+
[listing]
----
cluster::> network fcp adapter show -node node2
                     Connection  Host
Node         Adapter Established Port Address
------------ ------- ----------- ------------
node2
             0a      ptp         11400
node2
             0c      ptp         11700
node2
             6a      loop        0
node2
             6b      loop        0
4 entries were displayed.
----
. 記錄連接埠。
+
需要輸出資訊、才能在程序稍後的新控制器上對應新的FC連接埠。

. 如果您之前尚未這麼做、請檢查節點2上是否有設定介面群組或VLAN：
+
「ifgrp show」

+
「VLAN show」

+
您將使用本節中的資訊 link:map_ports_node2_node4.html["將連接埠從節點2對應至節點4"]。

. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果您... | 然後... 


| 已在中記錄NVRAM系統ID編號 link:prepare_nodes_for_upgrade.html["準備節點以進行升級"] | 前往 link:retire_node2.html["淘汰節點2"]。 


| 未在中記錄NVRAM系統ID編號 link:prepare_nodes_for_upgrade.html["準備節點以進行升級"] | 完成 <<man_record_2_step9,步驟9.>> 和 <<man_record_2_step10,步驟10>> 接著前往下一節： link:retire_node2.html["淘汰節點2"]。 
|===
. [[man_recipal_2_step9]顯示節點2的屬性：
+
「System Node show -instance -Node node2」

+
[listing]
----
cluster::> system node show -instance -node node2
                            ...
                 NVRAM System ID: system_ID
                           ...
----
. [[man_recipal_2_step10]請在一節中記錄要使用的NVRAM系統ID link:install_boot_node4.html["安裝及開機節點4"]。

