= 
:allow-uri-read: 


您需要在機架中安裝node4、將node2連線傳輸至node4、以及開機node4。您也必須重新指派任何節點2備援磁碟、屬於根的任何磁碟、以及先前未重新部署至節點3的任何非根Aggregate。

如果netboot node4的版本ONTAP 與node2上安裝的版本不相同、則需要netboot node4。安裝node4之後、請從ONTAP 儲存在Web伺服器上的Image9映像啟動節點4。接著、您可以依照中的指示、將正確的檔案下載到開機媒體裝置、以供後續系統開機 link:prepare_for_netboot.html["準備netboot"]

但是、如果netboot node4的Data ONTAP 版本與node2上安裝的更新版本相同、則不需要netboot node4。

*重要*：

* 如果您要升級的是連接FlexArray 至儲存陣列的V系列系統或使用「支援虛擬化軟體」的系統、則必須完成 <<man_install4_Step1,步驟1.>> 透過 <<man_install4_Step7,步驟7.>>請將本節保留在 <<man_install4_Step8,步驟8.>> 並遵循中的指示 link:set_fc_uta_uta2_config_node4.html["在節點4上設定FC或UTA/UTA2組態"] 視需要在維護模式中輸入命令。接著您需要返回本節、並繼續執行中的程序 <<man_install4_Step9,步驟9.>>。
* 不過、如果您要升級具有儲存磁碟的系統、則必須完成本節的完整內容、然後繼續執行本節 link:set_fc_uta_uta2_config_node4.html["在節點4上設定FC或UTA/UTA2組態"]，在叢集提示字元中輸入命令。


.步驟
. [[man_install4_Step1]]請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果node4將位於... | 然後... 


| 與節點3分開的機箱 | 前往 <<man_install4_Step2,步驟2>>。 


| 同一個機箱與節點3 | 跳過步驟2和3、前往 <<man_install4_Step4,步驟4.>>。 
|===
. [[man_install4_Step2]]請確定節點4有足夠的機架空間。
+
如果node4與node3位於不同的機箱中、您可以將node4放在與node2相同的位置。如果節點3和節點4位於同一個機箱中、則節點4已位於適當的機架位置。

. 按照節點機型的安裝與設定說明_中的指示、在機架中安裝節點4。
. [[man_install4_stip4]]纜線節點4、將連線從節點2移至節點4。
+
下列參考資料可協助您建立適當的纜線連線。前往 link:other_references.html["參考資料"] 以連結至他們。

+
** _Installation and Setup Instructions（安裝與設定說明）_或_Estratested FlexArray Virtualization Installation Requirements and Reference（_針對節點4平台的虛擬化安裝要求與參考資料）。
** 適當的磁碟櫃指南。
** 《_》《_》9《高可用度組態指南》_ ONTAP
+
纜線連接下列連接：

** 主控台（遠端管理連接埠）
** 叢集連接埠
** 資料連接埠
** 叢集與節點管理連接埠
** 儲存設備
** SAN組態：iSCSI乙太網路和FC交換器連接埠


+

NOTE: 您不需要將互連卡/FC_VI卡或互連/FC_VI纜線連線從節點2移至節點4、因為大多數平台機型都有獨特的互連卡機型。

. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果節點4位於... | 然後... 


| 與節點3相同的機箱 | 前往 <<man_install4_Step8,步驟8.>>。 


| 與節點3分開的機箱 | 前往 <<man_install4_Step6,步驟6.>>。 
|===
. [[man_install4_Step6]]開啟節點4的電源、然後按「Ctrl-C」來存取開機環境提示字元、以中斷開機。
+

NOTE: 當您啟動節點4時、可能會看到下列訊息：

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. [[man_install4_stept7]]如果您在步驟6中看到警告訊息、請採取下列行動：
+
.. 檢查可能指出NVRAM電池電量不足以外問題的任何主控台訊息、並視需要採取任何必要的修正行動。
.. 讓電池充電並完成開機程序。
+

WARNING: *警告：請勿覆寫延遲。若不讓電池充電、可能會導致資料遺失。*



. [[man_install4_step8]請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果您的系統... | 然後... 


| 具有磁碟、無後端儲存設備 | 跳過步驟9至步驟14、前往 <<man_install4_Step15,步驟15>>。 


| 是V系列系統、或具有FlexArray 「支援虛擬化的軟體」、並連接至儲存陣列  a| 
.. 移至節點4_上的_設定FC或UTA/UTA2組態區段、然後完成區段 link:set_fc_uta_uta2_config_node4.html#configure-fc-ports-on-node4["在節點4上設定FC連接埠"] 和 link:set_fc_uta_uta2_config_node4.html#check-and-configure-utauta2-ports-on-node4["檢查並設定節點4上的UTA/UTA2連接埠"]（視系統而定）。
.. 返回本節、並完成其餘步驟、從開始 <<man_install4_Step9,步驟9.>>。


*重要*：您必須重新設定FC內建連接埠、UTA/UTA2內建連接埠和UTA/UTA2卡、才能在Data ONTAP V系列系統上啟動。

|===
. [[man_install4_Step9]]將新節點的FC啟動器連接埠新增至交換器區域。
+
請參閱儲存陣列與分區文件以取得相關指示。

. 將FC啟動器連接埠新增至儲存陣列做為新主機、將陣列LUN對應至新主機。
+
請參閱儲存陣列與分區文件以取得相關指示。

. 修改與儲存陣列上陣列LUN相關之主機或磁碟區群組中的全球連接埠名稱（WWPN）值。
+
安裝新的控制器模組會變更與每個內建FC連接埠相關的WWPN值。

. 如果您的組態使用交換器型分區、請調整分區以反映新的WWPN值。
. 輸入下列命令並檢查其輸出、確認節點4現在可以看到陣列LUN：
+
"syssconfig -v"

+
系統會顯示每個FC啟動器連接埠可見的所有陣列LUN。如果看不到陣列LUN、您就無法在本節稍後將磁碟從節點2重新指派至節點4。

. 按「Ctrl-C」顯示開機功能表、然後選取「維護模式」。
. [[man_install4_Step15]在維護模式提示字元中、輸入下列命令：
+
《停止》

+
系統會在開機環境提示字元停止。

. 設定node4 ONTAP 以供使用：
+
「預設值」

. 如果在此組態中使用FDE、則必須將「Setenv bootarg.storageencryption支援」變數設為「true」、並將「kmip.init.maxwait`變數」設為「Off」、以避免在節點2組態載入後發生開機迴圈：
+
「etenv bootarg.storageencryption。支援true」

+
「kmip.init.maxwait關」

. 如果ONTAP 節點4上安裝的版本的資訊與ONTAP 節點2上安裝的版本資訊相同或更新、請輸入下列命令：
+
Boot_ONTAP功能表

. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果您要升級的系統... | 然後... 


| 節點4上沒有正確或最新ONTAP 的版本 | 前往 <<man_install4_Step20,步驟20>>。 


| 節點4上有正確或最新版本ONTAP 的資訊 | 前往 <<man_install4_Step25,步驟25>>。 
|===
. [[man_install4_Step20]]選擇下列其中一項動作來設定netboot連線。
+

NOTE: 您應該使用管理連接埠和IP位址做為netboot連線。請勿使用資料LIF IP位址、否則在執行升級時可能會發生資料中斷。

+
[cols="30,70"]
|===
| 如果動態主機組態傳輸協定（DHCP）是... | 然後... 


| 執行中 | 在開機環境提示字元中輸入下列命令、即可自動設定連線：「ifconfige0M -auto」 


| 未執行 | 在開機環境提示字元中輸入下列命令、手動設定連線：「ifconfige0M -addr=<filer_addr> mask=<網路遮罩>-gateway=<DNs_addr> domain=<DNs_domain>''<filer_addr>'是儲存系統的IP位址。「網路遮罩」是儲存系統的網路遮罩。「<閘道>」是儲存系統的閘道。'<DNs_addr>'是網路上名稱伺服器的IP位址。'<DNs_domain>'是網域名稱服務（DNS）網域名稱。如果使用此選用參數、則不需要netboot伺服器URL中的完整網域名稱；您只需要伺服器的主機名稱。*附註*：您的介面可能需要其他參數。在韌體提示字元中輸入「Help ifconfig」以取得詳細資料。 
|===
. 在節點4上執行netboot：
+
[cols="30,70"]
|===
| 適用於... | 然後... 


| FAS / AFF8000系列系統 | “netboot \http://<web_server_ip/path_to_webaccessible_directory>/netboot/kernel` 


| 所有其他系統 | “netboot \http://<web_server_ip/path_to_webaccessible_directory/ontap_version>_image.tgz` 
|===
+
「<path_to_the_web-易於 存取的目錄>」應該會引導您下載「<ONTAP_VERSION >_image.tgz」 link:prepare_for_netboot.html#man_netboot_Step1["步驟1."] 在_Prepare for netboot_一節中。

+

NOTE: 請勿中斷開機。

. 從開機功能表中、選取「Option（7）Install new software first」（選項（7）先安裝新軟體）。
+
此功能表選項會下載新Data ONTAP 的功能表映像、並將其安裝至開機裝置。

+
請忽略下列訊息：

+
「HA配對不支援此程序進行不中斷升級」

+
本附註適用於Data ONTAP 不中斷營運的更新功能、不適用於控制器升級。

. [[man_install4_step23]如果系統提示您繼續此程序、請輸入y、並在系統提示您輸入套件時、輸入URL：
+
http://<web_server_ip/path_to_web-accessible_directory/ontap_version>_image.tgz`

. 完成下列子步驟：
+
.. 當您看到下列提示時、請輸入「n」跳過備份恢復：
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. 當您看到下列提示時、輸入「y」重新開機：
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
控制器模組會重新開機、但會在開機功能表停止、因為開機裝置已重新格式化、需要還原組態資料。



. [[man_install4_Step25]從開機功能表選取維護模式「5」、然後在系統提示您繼續開機時輸入「y」。
. [[man_install4_Step26]在繼續之前、請前往 link:set_fc_uta_uta2_config_node4.html["在節點4上設定FC或UTA/UTA2組態"] 可對節點上的FC或UTA/UTA2連接埠進行必要的變更。進行這些區段中建議的變更、重新啟動節點、然後進入維護模式。
. 輸入以下命令並檢查輸出以找出節點4的系統ID：
+
「展示-A'」

+
系統會顯示節點的系統ID及其磁碟的相關資訊、如下列範例所示：

+
[listing]
----
*> disk show -a
Local System ID: 536881109
DISK         OWNER                       POOL   SERIAL NUMBER   HOME
------------ -------------               -----  -------------   -------------
0b.02.23     nst-fas2520-2(536880939)    Pool0  KPG2RK6F        nst-fas2520-2(536880939)
0b.02.13     nst-fas2520-2(536880939)    Pool0  KPG3DE4F        nst-fas2520-2(536880939)
0b.01.13     nst-fas2520-2(536880939)    Pool0  PPG4KLAA        nst-fas2520-2(536880939)
......
0a.00.0                   (536881109)    Pool0  YFKSX6JG                     (536881109)
......
----
. 重新指派節點2的備援磁碟、屬於根磁碟的磁碟、以及未重新放置到區段前面節點3的任何非根Aggregate link:relocate_non_root_aggr_node2_node3.html["將非根Aggregate從節點2重新部署到節點3"]：
+
[cols="35,65"]
|===
| 磁碟類型... | 執行命令... 


| 共享磁碟 | "Disk reassign-s``<node2_sysid>-d <node4_sysid>-p <node3_sysid>' 


| 無共享 | 「磁碟重新指派-s」、「<節點2_sysid>-d <節點4_sysid>'」 
|===
+
如需「<節點2_sysid>'」值、請使用中擷取的資訊 link:record_node2_information.html#man_node2_info_step10["步驟10"] 的「_Record node2 information_」區段。對於「<節點4_sysid>'」、請使用中擷取的資訊 <<man_install4_step23,步驟23>>。

+

NOTE: 只有在存在共享磁碟時、維護模式才需要使用「-p」選項。

+
「磁碟重新指派」命令只會重新指派目前擁有者為「<節點2_sysid>'」的磁碟。

+
系統會顯示下列訊息：

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n
----
+
當要求中止磁碟重新指派時、請輸入「n」。

+
當系統要求您中止磁碟重新指派時、您必須回答一系列的提示、如下列步驟所示：

+
.. 系統會顯示下列訊息：
+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? y
----
.. 輸入「y」繼續。
+
系統會顯示下列訊息：

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)? y
----
.. 輸入「y」以更新磁碟擁有權。


. 如果您要從具有外部磁碟的系統升級至支援內部和外部磁碟的系統（例如A800系統）、請將node4設為root、以確保從node2的根Aggregate開機。
+

WARNING: *警告：您必須依照所示的確切順序執行下列子步驟；否則可能導致中斷運作、甚至導致資料遺失。*

+
下列程序會將node4設定為從節點2的根Aggregate開機：

+
.. 檢查node2 Aggregate的RAID、plex和Checksum資訊：
+
「aggr狀態-r」

.. 檢查node2 Aggregate的整體狀態：
+
「aggr狀態」

.. 如有必要、請將node2 Aggregate上線：
+
「aggr_online root_aggr_from _」

.. 防止節點4從其原始根Aggregate開機：
+
「aggr offline <root_aggr_on_node4>'」

.. 將node2根Aggregate設為節點4的新根Aggregate：
+
「aggr options aggr_ffrom _」（aggr_from _）<節點2> root（根）



. 輸入下列命令並觀察輸出、確認控制器和機箱已設定為「ha」：
+
《ha-config show》

+
以下範例顯示「ha-config show」命令的輸出：

+
[listing]
----
*> ha-config show
   Chassis HA configuration: ha
   Controller HA configuration: ha
----
+
無論系統是在HA配對或獨立組態中、都會記錄在PROm中。獨立式系統或HA配對內的所有元件的狀態必須相同。

+
如果控制器和機箱未設定為「ha」、請使用下列命令修正組態：

+
「ha-config modify控制器ha」

+
「ha-config modify機箱ha」。

+
如果您使用MetroCluster 的是功能不完全的組態、請使用下列命令來修正組態：

+
「ha-config modify控制器MCC」

+
「ha-config modify機箱MCC」。

. 摧毀節點4上的信箱：
+
《破壞本地的信箱》

. 結束維護模式：
+
《停止》

+
系統會在開機環境提示字元停止。

. 在節點3上、檢查系統日期、時間和時區：
+
'日期'

. 在節點4上、檢查開機環境提示字元的日期：
+
「如何日期」

. 如有必要、請在節點4上設定日期：
+
「et date <mm/dd/yed>'

. 在節點4上、檢查開機環境提示字元的時間：
+
「時間安排」

. 如有必要、請在節點4上設定時間：
+
「設定時間<hh：mm：ss>」

. 請確認合作夥伴系統ID的設定是否正確、如所述 <<man_install4_Step26,步驟26>> 選項下。
+
《prontenv合作夥伴sysid》

. 如有必要、請在節點4上設定合作夥伴系統ID：
+
「etenv PARTNER-sysid <node3_sysid>'」

+
.. 儲存設定：
+
「aveenv」



. 在開機環境提示字元下進入開機功能表：
+
Boot_ONTAP功能表

. 在開機功能表中、於提示字元輸入「6」、從備份組態*選取選項*（6）Update flash。
+
系統會顯示下列訊息：

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. 在提示符下輸入「y」。
+
開機會正常進行、系統會提示您確認系統ID不相符。

+

NOTE: 系統可能會重新開機兩次、然後才顯示不相符的警告。

. 確認不相符。在正常開機之前、節點可能會完成一輪重新開機。
. 登入節點4。

