= 檢查並設定節點3上的UTA/UTA2連接埠
:allow-uri-read: 




== 檢查並設定節點3上的UTA/UTA2連接埠

如果節點3內建UTA/UTA2連接埠或UTA/UTA2卡、您必須檢查連接埠的組態、並視您要使用升級系統的方式而可能重新設定。

UTA/UTA2連接埠必須具備正確的SFP+模組。

如果您要使用統一化目標介面卡（UTA/ UTA2）連接埠來連接FC、必須先確認連接埠的設定方式。


NOTE: NetApp行銷資料可能會使用UTA2一詞來指稱CNA介面卡和連接埠。不過、CLI使用「CNA」一詞。

您可以使用「ucadmin show」命令來驗證目前的連接埠組態：

[listing]
----
*> ucadmin show
          Current  Current    Pending  Pending    Admin
 Adapter  Mode     Type       Mode     Type       Status
 -------  -------  ---------  -------  ---------  -----------
 0e       fc       target     -        initiator  offline
 0f       fc       target     -        initiator  offline
 0g       fc       target     -        initiator  offline
 0h       fc       target     -        initiator  offline
 1a       fc       target     -        -          online
 1b       fc       target     -        -          online
6 entries were displayed.
----
UTA/UTA2連接埠可設定為原生FC模式或UTA/UTA2模式。FC模式支援FC啟動器和FC目標；UTA/UTA2模式允許同時NIC和FCoE流量共用相同的10 GbE SFP+介面、並支援FC目標。

UTA/UTA2連接埠可能位於介面卡或控制器上、並具有下列組態、但您應該檢查節點3上UTA/UTA2連接埠的組態、並視需要加以變更：

* 訂購控制器時所訂購的UTA/UTA2卡、在出貨前已設定為具有您要求的特性設定。
* 與控制器分開訂購的UTA/UTA2卡會隨附預設FC目標特性。
* 新控制器上的內建UTA/UTA2連接埠會在出貨前設定、以符合您要求的特性設定。
+

NOTE: *注意*：如果您的系統有儲存磁碟、除非指示進入維護模式、否則請在叢集提示字元下輸入本節中的命令。如果您有vseries系統或使用FlexArray 了《支援虛擬化的軟體》、並且已連線至儲存陣列、則可在維護模式提示字元下、於本節中輸入命令。您必須處於維護模式、才能設定UTA/UTA2連接埠。



.步驟
. [[step1]]檢查連接埠目前的設定方式、在節點3上輸入下列命令：
+
[cols="35,65"]
|===
| 如果系統... | 然後... 


| 具有儲存磁碟 | 「系統節點硬體統一連線展示」 


| 是V系列系統、或具有FlexArray 「支援虛擬化的軟體」、並連接至儲存陣列 | 「ucadmin show」 
|===
+
系統會顯示類似下列範例的輸出：

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending  Admin
 Node  Adapter  Mode     Type       Mode     Type     Status
 ----  -------  -------  ---------  -------  -------  ------
 f-a   0e       fc       initiator  -        -        online
 f-a   0f       fc       initiator  -        -        online
 f-a   0g       cna      target     -        -        online
 f-a   0h       cna      target     -        -        online
 f-b   0e       fc       initiator  -        -        online
 f-b   0f       fc       initiator  -        -        online
 f-b   0g       cna      target     -        -        online
 f-b   0h       cna      target     -        -        online
 12 entries were displayed.
----
+
[listing]
----
*> ucadmin show
         Current  Current    Pending  Pending  Admin
Adapter  Mode     Type       Mode     Type     Status
-------  -------  ---------  -------  -------  ------
0e       fc       initiator  -        -        online
0f       fc       initiator  -        -        online
0g       cna      target     -        -        online
0h       cna      target     -        -        online
0e       fc       initiator  -        -        online
0f       fc       initiator  -        -        online
0g       cna      target     -        -        online
0h       cna      target     -        -        online
*>
----
. [[step2]]如果目前的SFP+模組與所需用途不符、請以正確的SFP+模組加以更換。
+
請聯絡您的NetApp代表、以取得正確的SFP+模組。

. [[step3]檢查「系統節點硬體統一連線show」或「ucadmin show」命令的輸出、以判斷UTA/UTA2連接埠是否具有您想要的特性。
. [[step4]採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果UTA/UTA2連接埠... | 然後... 


| 沒有您想要的特性 | 前往 <<man_check_3_step5,步驟5.>>。 


| 擁有您想要的個人風格 | 跳過步驟5至步驟12、前往 <<man_check_3_step13,步驟13>>。 
|===
. [[man_check_3_step5]請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果系統... | 然後... 


| 擁有儲存磁碟、並執行叢集Data ONTAP 式的版本8.3 | 開機節點3並進入維護模式：「boot_ONTAP maint」 


| 是V系列系統、或具有FlexArray 「支援虛擬化的軟體」、並連接至儲存陣列 | 前往 <<man_check_3_step6,步驟6.>>。您應該已經處於維護模式。 
|===
. [[man_check_3_step6]]請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果您正在設定... | 然後... 


| UTA/UTA2卡上的連接埠 | 前往 <<man_check_3_step7,步驟7.>>。 


| 內建UTA/UTA2連接埠 | 跳過步驟7、前往 <<man_check_3_step8,步驟8.>>。 
|===
. [man檢查_3_step7]如果介面卡處於啟動器模式、而且UTA / UTA2連接埠處於線上狀態、請將UTA / UTA2連接埠離線：
+
「torage disableAdapter <adapter_name>」（停用介面卡）

+
目標模式中的介面卡會在維護模式中自動離線。

. [[man_check_3_step8]如果目前的組態不符合所需用途、請視需要變更組態：
+
「ucadmin modify -m fc|cna -t啟動器| target <適 配器名稱>'

+
** 「m」是指個人化模式、「光纖通道」或「cna」。
** "-t"是FC4類型、"target（目標）"或"initiator（啟動器）"。
+

NOTE: 您需要使用FC啟動器來處理磁帶機、FlexArray 《不知虛擬化系統與MetroCluster 《不知如何」組態。您需要將FC目標用於SAN用戶端。



. 驗證設定：
+
「ucadmin show」

. 驗證設定：
+
[cols="35,65"]
|===
| 如果系統... | 然後... 


| 具有儲存磁碟  a| 
.. 停止系統：
+
《停止》

+
系統會在開機環境提示字元停止。

.. 輸入下列命令：
+
Boot_ONTAP





| 是V系列系統、或具有FlexArray 「支援虛擬化的軟體」、並連接至儲存陣列 | 重新開機至維護模式：「boot_netapp maint」 
|===
. [[step11]驗證設定：
+
[cols="35,65"]
|===
| 如果系統... | 然後... 


| 具有儲存磁碟 | 「系統節點硬體統一連線展示」 


| 是V系列或FlexArray 具有「支援虛擬化的軟體」、並已連線至儲存陣列 | 「ucadmin show」 
|===
+
下列範例的輸出顯示FC4類型的介面卡「1b」正在變更為「啟動器」、介面卡「2a」和「2b」的模式正在變更為「cna」：

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending      Admin
 Node  Adapter  Mode     Type       Mode     Type         Status
 ----  -------  -------  ---------  -------  -----------  ------
 f-a   1a       fc       initiator  -        -            online
 f-a   1b       fc       target     -        initiator    online
 f-a   2a       fc       target     cna      -            online
 f-a   2b       fc       target     cna      -            online

 4 entries were displayed.
----
+
[listing]
----
*> ucadmin show
         Current  Current    Pending  Pending    Admin
Adapter  Mode     Type       Mode     Type       Status
-------  -------  ---------  -------  ---------  ------
1a       fc       initiator  -        -          online
1b       fc       target     -        initiator  online
2a       fc       target     cna      -          online
2b       fc       target     cna      -          online
*>
----
. [step12a]輸入下列其中一個命令、針對每個連接埠輸入一次、即可將任何目標連接埠置於線上狀態：
+
[cols="35,65"]
|===
| 如果系統... | 然後... 


| 具有儲存磁碟 | 「網路FCP介面卡修改節點<node_name>-Adapter <adapter_name>-state up」 


| 是V系列系統、或具有FlexArray 「支援虛擬化的軟體」、並連接至儲存陣列 | 「FCP config <adapter_name> up」 
|===
. [[man_check_3_step13]連接連接埠。
. [[step14]請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果系統... | 然後... 


| 具有儲存磁碟 | 前往 link:map_ports_node1_node3.html["將連接埠從節點1對應至節點3"]。 


| 是V系列系統、或具有FlexArray 「虛擬化軟體」、並連接至儲存陣列 | 返回_Install and boot node3_並繼續執行 link:install_boot_node3.html#step7["步驟7."]。 
|===

