= 
:allow-uri-read: 


在升級過程中、遠端LIF會處理SAN LUN的流量。在升級期間、移轉SAN LIF對於叢集或服務健全狀況並不必要。除非需要將SAN LIF對應至新連接埠、否則不會移動SAN LIF。將node4聯機後，您將驗證lifs是否正常並位於適當的端口上。

.步驟
. 在任一節點上輸入下列命令並擷取輸出、以列出節點3未擁有的所有NAS資料lifs：
+
「網路介面show -role data -curr-node3 -is主目錄錯誤」

. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果node2... | 說明 


| 已設定介面群組或VLAN | 前往 <<man_lif_verify_4_Step3,步驟3.>>。 


| 未設定介面群組或VLAN | 跳過步驟3、前往 <<man_lif_verify_4_Step4,步驟4.>>。 
|===
. [[man_lif_VERIF_4_Step3]]請採取下列步驟、將原本位於節點2上的介面群組和VLAN上裝載的任何NAS資料LIF、從節點3移轉至節點4。
+
.. [[man_lif_VERIF_4_substepa]將先前屬於介面群組節點2的節點3上裝載的任何LIF移轉至節點4上的連接埠、以便在同一個網路上裝載LIF、方法是針對每個LIF輸入下列命令一次：
+
「網路介面移轉-vserver <vserver_name>-lif<lif_name>-dest-node4–dest-port <netport|ifgrp>`

.. 修改中的lifs主連接埠和主節點 <<man_lif_verify_4_substepa,子步驟A>> 輸入下列命令、針對每個LIF輸入一次、即可移至目前裝載lifs的連接埠和節點：
+
「網路介面修改-vserver <vserver_name>-lif<datalif_name>-home-Node node4 home-port <netport|ifgrp>`

.. [[man_lif_VERIF_4_substepc]將先前屬於VLAN連接埠節點2的節點3上裝載的任何LIF移轉至節點4上的連接埠、以便在同一個網路上裝載LIF、方法是輸入下列命令（每個LIF一次）：
+
「網路介面移轉-vserver <vserver_name>-lif <datalif_name>-dest-Node node4–dest-port <netport|ifgrp>'

.. 修改中的lifs主連接埠和主節點 <<man_lif_verify_4_substepc,子步驟c>> 輸入下列命令、針對每個LIF輸入一次、即可移至目前裝載lifs的連接埠和節點：
+
「網路介面修改-vserver <vserver_name>-lif <datalif_name>-home-Node <node4> home-port <netport|ifgrp>'



. [[man_lif_VERIF_4_Step4]請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果叢集設定為... | 然後... 


| NAS | 完成 <<man_lif_verify_4_Step5,步驟5.>> 透過 <<man_lif_verify_4_Step8,步驟8.>>、跳過步驟9、然後完成 <<man_lif_verify_4_Step10,步驟10>> 透過 <<man_lif_verify_4_Step13,步驟13>>。 


| SAN | 跳過步驟5至步驟8、然後完成 <<man_lif_verify_4_Step9,步驟9.>> 透過 <<man_lif_verify_4_Step13,步驟13>>。 


| NAS和SAN | 完成 <<man_lif_verify_4_Step5,步驟5.>> 透過 <<man_lif_verify_4_Step13,步驟13>>。 
|===
. [[man_lif_VERIF_4_Step5]]如果您的平台上有不同的資料連接埠、請輸入下列命令、將連接埠新增至廣播網域：
+
「網路連接埠廣播網域附加連接埠-IPSpace <IPspace_name>-broadcast網域管理連接埠<node:port>'

+
下列範例將節點「6280-1」上的連接埠「e0a」和節點「8060-1」上的連接埠「e0i」新增至IPspace預設中的廣播網域管理：

+
[listing]
----
cluster::> network port broadcast-domain add-ports -ipspace Default  -broadcast-domain mgmt -ports 6280-1:e0a, 8060-1:e0i
----
. 輸入下列命令、將每個NAS資料LIF移轉至節點4、每個LIF一次：
+
「網路介面移轉-vserver <vserver-name>-lif <datalif-name>-dest-node-node4>-destite-port <netport|ifgrp>-home-node4>'

. 確保資料移轉持續進行：
+
「網路介面修改-vserver <vserver_name>-lif <datalif_name>-home-port <netport|ifgrp>'

. [[man_lif_verify_4_step8]輸入下列命令、以列出所有網路連接埠並檢查其輸出、驗證所有連結的狀態為「up」：
+
「網路連接埠展示」

+
以下範例顯示「網路連接埠show」命令的輸出、其中一些lifs up和其他lifs down：

+
[listing]
----
cluster::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- -----------
node3
       a0a       Default      -                up       1500  auto/1000
       e0M       Default      172.17.178.19/24 up       1500  auto/100
       e0a       Default      -                up       1500  auto/1000
       e0a-1     Default      172.17.178.19/24 up       1500  auto/1000
       e0b       Default      -                up       1500  auto/1000
       e1a       Cluster      Cluster          up       9000  auto/10000
       e1b       Cluster      Cluster          up       9000  auto/10000
node4
       e0M       Default      172.17.178.19/24 up       1500  auto/100
       e0a       Default      172.17.178.19/24 up       1500  auto/1000
       e0b       Default      -                up       1500  auto/1000
       e1a       Cluster      Cluster          up       9000  auto/10000
       e1b       Cluster      Cluster          up       9000  auto/10000
12 entries were displayed.
----
. [[man_lif_VERIF_4_stept9]]如果「網路連接埠show」命令的輸出顯示新節點中沒有可用的網路連接埠、且存在於舊節點中、請完成下列子步驟、刪除舊的網路連接埠：
+
.. 輸入下列命令、輸入進階權限等級：
+
"進階權限"

.. 針對每個舊的網路連接埠輸入下列命令一次：
+
「網路連接埠刪除節點<node_name>-port <port_name>」

.. 輸入下列命令即可返回管理員層級：
+
「et -priv. admin」



. [[man_lif_VERIF_4_Step10]完成下列子步驟、確保SAN LIF位於節點4上的正確連接埠上：
+
.. 輸入下列命令：
+
「網路介面show -data傳輸協定iscsiSCSI|FCP -home-Node node4」

+
系統會傳回類似下列範例的輸出：

+
[listing]
----
cluster::> network interface show -data-protocol iscsi|fcp -home-node node4
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            a0a          up/down  10.63.0.53/24      node3         a0a     true
            data1        up/up    10.63.0.50/18      node3         e0c     true
            rads1        up/up    10.63.0.51/18      node3         e1a     true
            rads2        up/down  10.63.0.52/24      node3         e1b     true
vs1
            lif1         up/up    172.17.176.120/24  node3         e0c     true
            lif2         up/up    172.17.176.121/24  node3
----
.. 如果節點4的SAN生命週期或SAN生命週期群組位於節點2上不存在的連接埠上、請輸入下列其中一個命令、將它們移至節點4上的適當連接埠：
+
... 將LIF狀態設為「關閉」：
+
「網路介面修改-vserver <vserver_name>-lif<lif_name>-STATUS-admin DOUTE」

... 從連接埠集移除LIF：
+
「portset移除-vserver <vserver_name>-portset <portSet_name>-port-name <port_name>」

... 輸入下列其中一個命令：
+
**** 移動單一LIF：
+
「網路介面修改-lif<lif_name>-home-port <new_home_port>`

**** 將單一不存在或不正確連接埠上的所有LIF移至新連接埠：
+
「網路介面修改｛-home-port <port_on_node2>-home-node<node2>-role data｝-home-port <new_home_port_on_node4>'

**** 將lifs新增回連接埠集：
+
「portset add -vserver <vserver_name>-portset <portset_name>-port-name <port_name>'







+

NOTE: 您需要確保將SAN LIF移至與原始連接埠具有相同連結速度的連接埠。

. 輸入下列命令、將所有lifs的狀態修改為「up」、以便lifs可以接受及傳送節點上的流量：
+
「網路介面修改-vserver <vserver_name>-home-port <port_name>-home-node<node4> lif_name>-STATUS-admin up」

. 在任一節點上輸入以下命令並檢查輸出、以確認任何SAN LIF都已移至正確的連接埠、而且該LIF的狀態為「up」（啟動）：
+
「網路介面show -home-Node <node4>-role data」

. [[man_lif_VERIF_4_Step13]如果有任何LIF當機、請輸入下列命令、將LIF的管理狀態設為「UP」、每個LIF一次：
+
「網路介面修改-vserver <vserver_name>-lif<lif_name>-STATUS-admin up」


