= 
:allow-uri-read: 


在移動儲存設備進行升級的過程中、您需要開啟節點3和節點4的電源、開機軟體映像、以及設定節點。原始節點與新節點之間的實體連接埠配置可能有所不同。應在原始節點和替換節點之間對應連接埠、以識別連接埠和連線的適當配置。

.關於這項工作
如果ONTAP 在新節點上執行的版本與原始節點上的版本不同、您必須從NetApp支援網站下載正確的<ONTAP_VERSION >_image.tgz檔案至可從網路存取的目錄（請參閱步驟4）。您需要<ONTAP_VERSION >_image.tgz檔案來執行系統的網路開機。

.步驟
. 開啟節點3的電源、然後立即在主控台終端按Ctrl-C存取載入程式提示。
+
如果節點3和節點4位於同一個機箱中、請前往步驟2。如果沒有、請前往步驟3。

. 如果節點3和節點4位於單一機箱組態中（在同一個機箱中有控制器）：
+
.. 將序列主控台附加至節點4。
.. 如果節點4尚未開啟、請開啟電源、然後在主控台終端按Ctrl-C來存取載入器提示字元、以中斷開機程序。
+
如果兩個控制器位於同一個機箱中、則電源應該已經開啟。

+
在加載器提示符下保留node4；返回此過程並在安裝node3後重複這些步驟。



. 在載入程式提示字元下、輸入下列命令：「et-Defaults」
. 在載入程式提示下、設定管理LIF的netboot連線：
+
[cols="1,2"]
|===
| 如果IP定址是... | 然後... 


 a| 
DHCP
 a| 
 Configure the automatic connection:
「ifconfige0M -auto」



 a| 
 Static a| 
 Configure the manual connection:
"ifconfige0M -addr=ip_addr -mask=netmask"'-gateway=gateway"

|===
. 在載入程式提示字元下、在節點3上執行netboot：
+
[cols="1,2"]
|===
| 適用於... | 然後... 


 a| 
* FAS2200、FAS2500、FAS3200、FAS6200、FAS/AFF8000系列系統*
 a| 
按鍵+ netboot http://web_server_ip/path_to_web-accessible_directory/netboot/kernel+`[]



 a| 
*所有其他系統*
 a| 
按鍵+ netboot http://web_server_ip/path_to_web-accessible_directory/<ontap_version>_image.tgz+`[]

|===
+
path_to_the_web-易於 存取的目錄是下載的<ONTAP_VERSION >_image.tgz檔案的位置。

+

NOTE: 如果您無法從網路開機新的控制器、請聯絡技術支援部門。

. 從開機功能表中、選取選項*（7）Install new software first*（先安裝新軟體*）、將新的軟體映像下載並安裝至開機裝置。
+
請忽略下列訊息：「HA配對上的不中斷升級不支援此程序」。它適用於軟體的不中斷升級、而非控制器的升級。

. 如果系統提示您繼續此程序、請輸入「y」、並在系統提示您輸入套件時、輸入映像檔的URL：「+http://web_server_ip/path_to_web-accessible_directory/<ontap_version>_image.tgz+`」。
+
輸入使用者名稱/密碼（若適用）、或按Enter繼續。

. 當您看到類似下列的提示時、請輸入「n」跳過備份恢復：
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
. 當您看到類似於以下內容的提示時、輸入「y」重新開機：
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
. 在系統提示您時、按Ctrl-C顯示開機功能表、以中斷重新開機程序。
. 從開機功能表中、選取*（5）維護模式開機*以存取維護模式。
. 如有必要、請變更節點上的FC或CNA連接埠、然後將節點重新開機至維護模式。
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html["《SAN管理指南》（英文）ONTAP"]

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30092["尋找Data ONTAP 適用您版本的《SAN管理指南》（SAN Administration Guide）"]

. 您應該確認命令輸出顯示為ha:
+
[listing]
----
*> ha-config show
   Chassis HA configuration: ha
   Controller HA configuration: ha
----
+
無論系統是在HA配對或獨立組態中、都會記錄在PROm中。獨立式系統或HA配對內的所有元件的狀態必須相同

+
ha-config modify控制器ha命令會將ha設定為控制器設定。ha-config modify機箱ha命令會針對機箱設定來設定ha。

+
https://docs.netapp.com/us-en/ontap/high-availability/index.html["HA配對管理"^]

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30092["尋找Data ONTAP 適用於您的版本的《高可用度組態指南》（High Availability Configuration Guide）"]

. 退出維護模式：「halt」
+
系統會在載入程式提示下停止。


