---
permalink: a700/bootmedia-recovery-image-boot-options.html 
sidebar: sidebar 
keywords: aff a700, boot, recovery, image, two, node, metrocluster, configuration, manual, manual boot recovery 
summary: 在AFF A700系統上，從 USB 隨身碟啟動ONTAP恢復映像，以恢復啟動媒體。AFF A700系統僅支援手動啟動媒體復原程式。不支援自動啟動媒體恢復。 
---
= 開機恢復映像 - AFF A700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在AFF A700系統上，從 USB 隨身碟啟動ONTAP恢復映像，以恢復啟動媒體。該過程包括從 USB 隨身碟啟動、恢復檔案系統、驗證環境變數以及使控制器恢復正常運行，具體步驟取決於系統是否處於雙節點MetroCluster配置中。

AFF A700系統僅支援手動啟動媒體復原程式。不支援自動啟動媒體恢復。

從恢復映像開機受損節點的程序、取決於系統是否為雙節點MetroCluster 的版本。



== 選項 1 ：在大多數系統中開機恢復映像

您必須從ONTAP USB磁碟機開機支援的影像、還原檔案系統、並驗證環境變數。

此程序適用於非雙節點MetroCluster 的系統。

.步驟
. 在載入程式提示字元中、從USB快閃磁碟機開機恢復映像：「boot_recovery」
+
映像會從USB隨身碟下載。

. 出現提示時、請輸入映像名稱、或接受螢幕上方括弧內顯示的預設映像。
. 還原「var'檔案系統：
+
[cols="1,2"]
|===
| 如果您的系統有... | 然後... 


 a| 
網路連線
 a| 
.. 系統提示您還原備份組態時、請按「y」。
.. 將健全節點設為進階權限層級：「et -priv榮幸advanc進 階」
.. 執行還原備份命令：「系統節點還原-備份-節點本機-目標位址_減損節點_ip_address_」
.. 將節點恢復為管理層級：「et -priv榮幸admin」
.. 系統提示您使用還原的組態時、請按「y」。
.. 系統提示您重新啟動節點時、請按「y」。




 a| 
無網路連線
 a| 
.. 系統提示您還原備份組態時、請按「n」。
.. 系統出現提示時、請重新啟動系統。
.. 從顯示的功能表中選取*從備份組態更新Flash *（同步Flash）選項。
+
如果系統提示您繼續更新、請按「y」。





 a| 
無網路連線、且為MetroCluster 靜態IP組態
 a| 
.. 系統提示您還原備份組態時、請按「n」。
.. 系統出現提示時、請重新啟動系統。
.. 等待iSCSI儲存設備連線連線。
+
您可以在看到下列訊息後繼續：

+
[listing]
----
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
----
.. 從顯示的功能表中選取*從備份組態更新Flash *（同步Flash）選項。
+
如果系統提示您繼續更新、請按「y」。



|===
. 確保環境變數設定符合預期：
+
.. 將節點移至載入程式提示字元。
.. 使用「prontenv」命令檢查環境變數設定。
.. 如果環境變數未如預期設定、請使用'采 集_環境變數名稱____變更值___命令加以修改。
.. 使用「shavenv」命令儲存變更。


. 下一個取決於您的系統組態：
+
** 如果您的系統已設定內建Keymanager、NSE或NVE、請前往 xref:bootmedia-encryption-restore.adoc[視需要還原OKM、NSE和NVE]
** 如果您的系統未設定內建金鑰管理程式、NSE或NVE、請完成本節中的步驟。


. 在載入程式提示字元中、輸入「boot_ontap」命令。
+
[cols="1,2"]
|===
| *如果您看到... | 然後...* 


 a| 
登入提示
 a| 
前往下一步。



 a| 
正在等待恢復...
 a| 
.. 登入合作夥伴節點。
.. 使用「儲存容錯移轉show」命令確認目標節點已準備好進行還原。


|===
. 將主控台纜線連接至合作夥伴節點。
. 使用"shorage容錯移轉恢復-fromnode"命令歸還節點。
. 在叢集提示字元中、使用「net int -is主目錄假」命令檢查邏輯介面。
+
如果有任何介面被列為「假」、請使用「net int f還原」命令將這些介面還原回其主連接埠。

. 將主控台纜線移至修復的節點、然後執行「vrsion -v」命令來檢查ONTAP 版本。
. 如果您使用「儲存容錯移轉修改節點本機-自動恢復true」命令停用自動恢復。




== 選項2：以雙節點MetroCluster 的功能組態來開機恢復映像

您必須從ONTAP USB磁碟機開機支援的影像、並驗證環境變數。

此程序適用於雙節點MetroCluster 的不二組態系統。

.步驟
. 在載入程式提示字元中、從USB快閃磁碟機開機恢復映像：「boot_recovery」
+
映像會從USB隨身碟下載。

. 出現提示時、請輸入映像名稱、或接受螢幕上方括弧內顯示的預設映像。
. 安裝映像之後、請開始還原程序：
+
.. 系統提示您還原備份組態時、請按「n」。
.. 系統提示重新開機時、按「y」開始使用新安裝的軟體。
+
您應該準備好在系統提示時中斷開機程序。



. 系統開機時、請在看到「Press Ctrl-C for Boot Menu（按Ctrl-C進入開機功能表）」訊息後按「Ctrl-C」、並在顯示「Boot Menu（開機功能表）」時選取選項6。
. 確認環境變數設定符合預期。
+
.. 將節點移至載入程式提示字元。
.. 使用「prontenv」命令檢查環境變數設定。
.. 如果環境變數未如預期設定、請使用'采 集_環境變數名稱____變更值___命令加以修改。
.. 使用「shavenv」命令儲存變更。
.. 重新啟動節點。



