---
permalink: a700/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: aff a700, replace, boot, media, primary, secondary, image, disruptive, nondisruptive, manual, manual boot recovery 
summary: 了解AFF A700系統上的啟動介質更換，並了解不同的更換方法。AFF A700系統僅支援手動啟動媒體復原程式。不支援自動啟動媒體恢復。 
---
= 啟動介質更換概述 - AFF A700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解AFF A700系統上的啟動介質更換，並了解不同的更換方法。啟動媒體儲存系統啟動時使用的主啟動映像檔和輔助啟動映像檔。根據您的網路配置，您可以執行非中斷式更換（使用內部 e0S 連線）或中斷式更換（需要兩次重新啟動）。

AFF A700系統僅支援手動啟動媒體復原程式。不支援自動啟動媒體恢復。

開機媒體會儲存系統在開機時所使用的一組主要和次要系統（開機映像）檔案。視網路組態而定、您可以執行不中斷營運或中斷營運的更換作業。

[NOTE]
====
NetApp 強烈建議您在使用的裝置上啟用主控台記錄功能，並在執行此程序時採取下列行動：

* 在維護期間保持 AutoSupport 啟用狀態。這樣一來，如果發生問題，NetApp 支援人員就能收到診斷資訊。
* 啟用所有 CLI 工作階段的工作階段記錄。這會建立維護活動期間所有命令和系統輸出的完整記錄。如需如何啟用工作階段記錄的指引，請參閱 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["如何設定 PuTTY 以獲得與 ONTAP 系統的最佳連線"^]。


====
您必須擁有一個格式化為FAT32的USB快閃磁碟機、以及適當的儲存容量、才能容納「image_xxx.tgz」。

您也必須將「image_xxx.tgz」檔案複製到USB快閃磁碟機、以供日後在本程序中使用。

* 更換開機媒體的不中斷和破壞性方法、都需要還原「var'檔案系統：
+
** 若要進行不中斷的更換、HA配對不需要連線至網路即可還原「var'檔案系統」。單一機箱中的HA配對具有內部e0S連線、用於在其中傳輸「var'組態」。
** 若要進行中斷更換、您不需要網路連線即可還原「var'檔案系統」、但此程序需要重新開機兩次。


* 您必須使用從供應商處收到的替換FRU元件來更換故障元件。
* 請務必在正確的節點上套用下列步驟中的命令：
+
** _減損_節點是您要執行維護的節點。
** 「_healthy node_」是受損節點的HA合作夥伴。



