---
permalink: fas-70-90/bootmedia-encryption-restore.html 
sidebar: sidebar 
keywords: fas70, fas90, post boot media replacement steps for okm, nse, and nve 
summary: 一旦勾選環境變數、您必須完成特定於已啟用Onboard Key Manager（OKM\）、NetApp Storage Encryption（NSE）或NetApp Volume Encryption（NVE\）的系統的步驟。 
---
= 還原加密： FAS70 和 FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在替換開機媒體上還原加密。



== 步驟 1 ：還原金鑰管理程式

您必須完成特定於已啟用內建金鑰管理程式（ OKM ）、 NetApp 儲存加密（ NSE ）或 NetApp 磁碟區加密（ NVE ）的系統、並使用本程序開始時擷取的設定。


NOTE: 如果 NSE 或 NVE 與 Onboard 或 External Key Manager 一起啟用、您必須還原本程序開始時擷取的設定。

.步驟
. 將主控台纜線連接至目標控制器。
. 從 ONATP 開機功能表中選取下列其中一個選項、以還原內建金鑰管理程式組態。


[role="tabbed-block"]
====
.選項 1 ：具有內建金鑰管理程式伺服器組態的系統
--
從 ONTAP 開機功能表還原內建金鑰管理程式（ OKM ）組態。

.開始之前
* 在還原 OKM 組態時、請確定您擁有下列資訊：
+
** 輸入的叢集範圍複雜密碼 https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-onboard-key-management-96-later-nse-task.html["同時啟用內建金鑰管理"]。
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/backup-key-management-information-manual-task.html["Onboard Key Manager 的備份資訊"]。


* 請先執行 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_verify_onboard_key_management_backup_and_cluster-wide_passphrase["如何驗證內建金鑰管理備份和叢集範圍的複雜密碼"] 程序再繼續。


.步驟
. 將主控台纜線連接至目標控制器。
. 從 ONTAP 開機功能表中選取適當的選項：
+
[cols="1a,2a"]
|===
| 版本ONTAP | 選取此選項 


 a| 
部分9.8或更新版本ONTAP
 a| 
選擇選項 10 。

|===


--
====
....

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 10

....
[]
====
a| ONTAP 9 7 及更早版本 a| 選擇隱藏選項 `recover_onboard_keymanager`

====
....

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
Selection (1-19)? recover_onboard_keymanager

....
[]
====
|===


| + 。確認您要繼續恢復程序。+ 。顯示範例提示 [% 可摺疊 ] 
|===
====
`This option must be used only in disaster recovery procedures. Are you sure? (y or n):`

[]
====
. 輸入叢集範圍的複雜密碼兩次。
+
輸入複雜密碼時、主控台不會顯示任何輸入。



====
`Enter the passphrase for onboard key management:`

`Enter the passphrase again to confirm:`

[]
====
+

. 輸入備份資訊。
+
.. 將整個內容從 BEGIN 備份線貼到終端備份線。




====
....
Enter the backup data:

--------------------------BEGIN BACKUP--------------------------
0123456789012345678901234567890123456789012345678901234567890123
1234567890123456789012345678901234567890123456789012345678901234
2345678901234567890123456789012345678901234567890123456789012345
3456789012345678901234567890123456789012345678901234567890123456
4567890123456789012345678901234567890123456789012345678901234567
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
0123456789012345678901234567890123456789012345678901234567890123
1234567890123456789012345678901234567890123456789012345678901234
2345678901234567890123456789012345678901234567890123456789012345
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

---------------------------END BACKUP---------------------------

....
[]
====
. 在輸入結束時按兩次 ENTER 鍵。
+
恢復程序即告完成。



====
....

Enter the backup data:

Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.wkeydb file.

Successfully recovered keymanager secrets.

***********************************************************************************
* Select option "(1) Normal Boot." to complete recovery process.
*
* Run the "security key-manager onboard sync" command to synchronize the key database after the node reboots.
***********************************************************************************

....
[]
====
+ 警告：如果顯示的輸出不是、請勿繼續 `Successfully recovered keymanager secrets`。執行疑難排解以修正錯誤。

. 從開機功能表中選取選項 1 、以繼續開機至 ONTAP 。


====
....

***********************************************************************************
* Select option "(1) Normal Boot." to complete the recovery process.
*
***********************************************************************************


(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 1

....
[]
====
. 確認控制器的主控台顯示下列項目：
+
`Waiting for giveback...(Press Ctrl-C to abort wait)`

. 從合作夥伴節點、將合作夥伴控制器贈回：
+
`storage failover giveback -fromnode local -only-cfo-aggregates true`。

. 只使用 CFO Aggregate 開機後、請執行下列命令：
+
`security key-manager onboard sync`命令。

. 輸入Onboard Key Manager的全叢集密碼。


====
....

Enter the cluster-wide passphrase for the Onboard Key Manager:

All offline encrypted volumes will be brought online and the corresponding volume encryption keys (VEKs) will be restored automatically within 10 minutes. If any offline encrypted volumes are not brought online automatically, they can be brought online manually using the "volume online -vserver <vserver> -volume <volume_name>" command.

....
[]
====
+ 附註：如果同步成功、就會傳回叢集提示、而不會傳回其他訊息。如果同步失敗、則會在返回叢集提示之前顯示錯誤訊息。在修正錯誤並成功執行同步處理之前、請勿繼續。

. 確認所有金鑰都已同步：
+
`security key-manager key query -restored false`。

+
`There are no entries matching your query.`

+

NOTE: 在還原的參數中篩選 FALSE 時、不應出現任何結果。

. 將合作夥伴的節點歸還：
+
`storage failover giveback -fromnode local`

. 如果您停用了自動恢復功能、請輸入下列命令來還原：
+
`storage failover modify -node local -auto-giveback true`

. 如果啟用 AutoSupport 、請輸入下列命令、以還原自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--

--
從 ONATP 開機功能表還原外部金鑰管理程式組態。

.開始之前
您需要下列資訊來還原外部金鑰管理程式（ EKM ）組態：

* 從另一個叢集節點複本 /ccfcard/kmip/servers.cfg 檔案、或以下資訊：
+
** KMIP 伺服器位址。
** KMIP 連接埠。
** 從其他叢集節點或用戶端憑證複本 /ccfcard/kmip/certs/client.crt 檔案。
** 從其他叢集節點或用戶端金鑰複本 /ccfcard/kmip/certs/client.key 檔案。
** 另一個叢集節點或 KMIP 伺服器 CA 的 /ccfcard/kmip/certs/ca.pem 檔案複本。




.步驟
. 將主控台纜線連接至目標控制器。
. 從 ONTAP 開機功能表中選取選項 11 。


====
....

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 11
....
[]
====
+

. 出現提示時、請確認您已收集必要資訊。


====
....
Do you have a copy of the /cfcard/kmip/certs/client.crt file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/client.key file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/CA.pem file? {y/n}
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
....
[]
====
+

====
....
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
Do you know the KMIP server address? {y/n}
Do you know the KMIP Port? {y/n}
....
[]
====
+

. 出現提示時、請輸入用戶端和伺服器資訊。


====
....
Enter the client certificate (client.crt) file contents:
Enter the client key (client.key) file contents:
Enter the KMIP server CA(s) (CA.pem) file contents:
Enter the server configuration (servers.cfg) file contents:
....
[]
====
+ 。顯示範例

====
....
Enter the client certificate (client.crt) file contents:
-----BEGIN CERTIFICATE-----
MIIDvjCCAqagAwIBAgICN3gwDQYJKoZIhvcNAQELBQAwgY8xCzAJBgNVBAYTAlVT
MRMwEQYDVQQIEwpDYWxpZm9ybmlhMQwwCgYDVQQHEwNTVkwxDzANBgNVBAoTBk5l
MSUbQusvzAFs8G3P54GG32iIRvaCFnj2gQpCxciLJ0qB2foiBGx5XVQ/Mtk+rlap
Pk4ECW/wqSOUXDYtJs1+RB+w0+SHx8mzxpbz3mXF/X/1PC3YOzVNCq5eieek62si
Fp8=
-----END CERTIFICATE-----

Enter the client key (client.key) file contents:
-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAoU1eajEG6QC2h2Zih0jEaGVtQUexNeoCFwKPoMSePmjDNtrU
MSB1SlX3VgCuElHk57XPdq6xSbYlbkIb4bAgLztHEmUDOkGmXYAkblQ=
-----END RSA PRIVATE KEY-----

Enter the KMIP server CA(s) (CA.pem) file contents:
-----BEGIN CERTIFICATE-----
MIIEizCCA3OgAwIBAgIBADANBgkqhkiG9w0BAQsFADCBjzELMAkGA1UEBhMCVVMx
7yaumMQETNrpMfP+nQMd34y4AmseWYGM6qG0z37BRnYU0Wf2qDL61cQ3/jkm7Y94
EQBKG1NY8dVyjphmYZv+
-----END CERTIFICATE-----

Enter the IP address for the KMIP server: 10.10.10.10
Enter the port for the KMIP server [5696]:

System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
kmip_init: configuring ports
Running command '/sbin/ifconfig e0M'
..
..
kmip_init: cmd: ReleaseExtraBSDPort e0M
​​​​....


====

. The recovery process completes.


+
.Show example prompt
[%collapsible]
====
....
系統已準備好使用外部金鑰管理程式。正在嘗試從關鍵伺服器復原金鑰[ 8 月 29 日 21 ： 06 ： 28 ] ： 0x808806100 ： 0 ：偵錯： kmip2 ：：：主： [initOpenssl] ： 460 ：執行初始化 OpenSSL 成功恢復 keymanager 機密。

....



. Select option 1 from the boot menu to continue booting into ONTAP.

+
....
****
* 選取選項「（ 1 ）正常開機」以完成還原程序。*


****
（ 1 ）正常開機。（ 2 ）不使用 /etc/rc 開機。（ 3 ）變更密碼。（ 4 ）清理組態並初始化所有磁碟。（ 5 ）維護模式開機。（ 6 ）從備份組態更新 Flash 。（ 7 ）先安裝新軟體。（ 8 ）重新開機節點。（ 9 ）設定進階磁碟分割。（ 10 ）設定 Onboard Key Manager 恢復機密。（ 11 ）設定節點以進行外部金鑰管理。選擇（ 1-11 ）？1

....
====
+


. Restore automatic giveback, if you disabled it, by entering the following command:
+
`storage failover modify -node local -auto-giveback true` command.

. If AutoSupport is enabled, restore automatic case creation by entering  the following command:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


--

====

== Step 2: Complete the boot media replacement

Complete the boot media replacement process after the normal boot by completing final checks and giving back storage.

. Check the console output:
+
[%header,cols="1,3"]
|===
| If the console displays...| Then...
a|
The login prompt
a|
Go to Step 6.
a|
Waiting for giveback...
a|

 .. Log into the partner controller.
 .. Confirm the target controller is ready for giveback with the _storage failover show_ command.

|===

. Move the console cable to the partner controller and give back the target controller storage using the _storage failover giveback -fromnode local -only-cfo-aggregates true_ command.

 ** If the command fails because of a failed disk, physically disengage the failed disk, but leave the disk in the slot until a replacement is received.

 ** If the command fails because the partner is "not ready", wait 5 minutes for the HA subsystem to synchronize between the partners.
 ** If the command fails because of an NDMP, SnapMirror, or SnapVault process, disable the process. See the appropriate Documentation Center for more information.
. Wait 3 minutes and check the failover status with the _storage failover show_ command.
. At the clustershell prompt, enter the _network interface show -is-home false_ command to list the logical interfaces that are not on their home controller and port.
+
If any interfaces are listed as `false`, revert those interfaces back to their home port using the _net int revert -vserver Cluster -lif _nodename_ command.

. Move the console cable to the target controller and run the _version -v_ command to check the ONTAP versions.

. Use the `storage encryption disk show` to review the output.
. Use the _security key-manager key query_ command to display the key IDs of the authentication keys that are stored on the key management servers.
 ** If the `Restored` column = `yes/true`, you are done and can proceed to complete the replacement process.
 ** If the `Key Manager type` = `external` and the `Restored` column = anything other than `yes/true`, use the _security key-manager external restore_ command to restore the key IDs of the authentication keys.
+
NOTE: If the command fails, contact Customer Support.

 ** If the `Key Manager type` = `onboard` and the `Restored` column = anything other than `yes/true`, use the _security key-manager onboard sync_ command to synchronize the missing onboard keys on the repaired node.
+
Use the _security key-manager key query_ command to verify that the `Restored` column = `yes/true` for all authentication keys.

. Connect the console cable to the partner controller.
. Give back the controller using the `storage failover giveback -fromnode local` command.
. Restore automatic giveback if you disabled it by using the _storage failover modify -node local -auto-giveback true_ command.
. If AutoSupport is enabled, restore/unsuppress automatic case creation by using the _system node autosupport invoke -node * -type all -message MAINT=END_ command.

....