---
permalink: fas-70-90/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: fas70, fas90, verify and set HA state, complete the replacement process 
summary: 重新啟動控制器，驗證系統健康狀況，並將故障零件傳回給NetApp ，以完成 FAS70 和 FAS90 機箱更換程序的最後一步。 
---
= 完成機殼更換 - FAS70 和 FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
重新啟動控制器，驗證系統健康狀況，並將故障零件傳回給NetApp ，以完成 FAS70 和 FAS90 機箱更換程序的最後一步。



== 步驟 1 ：啟動控制器，然後將控制器交回

控制器重新開機後，請啟動 ONTAP ，然後將控制器交回。

.步驟
. 檢查主控台輸出：
+
.. 如果控制器開機至 Loader 提示字元，請使用命令重新啟動控制器 `boot_ontap`。
.. 如果主控台在重新開機後顯示 `waiting for giveback`，請登入合作夥伴控制器，並使用命令檢查更換的控制器是否已準備好可供恢復 `storage failover show`。


. 執行贈品：
+
.. 將主控台纜線連接至合作夥伴控制器。
.. 將受損的控制器歸還其儲存設備，使其恢復正常運作： `storage failover giveback -ofnode _impaired_node_name_`
.. 如果自動交還功能已停用，請重新啟用它： `storage failover modify -node _impaired_node_name_ -auto-giveback _true_`
.. 如果啟用 AutoSupport ，則還原 / 恢復自動建立個案： `system node autosupport invoke -node * -type all -message MAINT=END`






== 步驟 2 ：驗證儲存系統健全狀況

控制器歸還儲存設備後，您應該使用檢查整體健全狀況 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"]。

.步驟
. 恢復完成後，請執行 Active IQ Config Advisor 以驗證儲存系統的健全狀況。
. 修正您遇到的任何問題。




== 步驟3：將故障零件歸還給NetApp

如套件隨附的RMA指示所述、將故障零件退回NetApp。如 https://mysupport.netapp.com/site/info/rma["零件退貨與更換"]需詳細資訊、請參閱頁面。
