---
permalink: fas-70-90/install-prepare.html 
sidebar: sidebar 
keywords: fas70, fas90, prepare installation 
summary: 準備安裝 FAS70 和 FAS90 平台。 
---
= 準備安裝： FAS70 和 FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
準備安裝 FAS70 或 FAS90 儲存系統、方法是準備好場地、打開箱子的包裝箱、將箱子的內容與裝箱單進行比較、並註冊系統以取得支援效益。



== 步驟 1 ：準備網站

若要安裝儲存系統、請確定您計畫使用的站台和機櫃或機架符合您組態的規格。

.步驟
. 用於 https://hwu.netapp.com["NetApp Hardware Universe"^]確認您的站台符合儲存系統的環境和電力需求。
. 請確定您有足夠的機架空間：
+
** 儲存系統的 HA 組態中的 4U
** 2U 適用於每個 NS224 儲存櫃


+
* 注意： * 請參閱link:https://hwu.netapp.com["NetApp Hardware Universe"^]以瞭解其他支援儲存櫃的機架空間需求。

. 安裝所有必要的網路交換器。
+
如需安裝說明及相容性資訊、請參閱 https://docs.netapp.com/us-en/ontap-systems-switches/index.html["交換器文件"^] link:https://hwu.netapp.com["NetApp Hardware Universe"^] 。





== 步驟 2 ：打開包裝盒

確保您打算用於儲存系統的站台和機櫃或機架符合所需規格後、請打開所有包裝箱的包裝、並將內容物與裝箱單上的項目進行比較。

.步驟
. 小心打開所有包裝盒、並以井然有序的方式配置內容物。
. 請比較裝箱單上的清單內容。
+

NOTE: 您可以掃描運送紙箱側邊的 QR 碼、以取得裝箱清單。

+
下列項目是您可能會在方塊中看到的部分內容。

+
確保包裝箱內的所有物品都符合裝箱單上的清單。如果有任何差異、請記下這些差異以採取進一步行動。

+
[cols="12,9,4"]
|===


| *硬體* | * 纜線 * |  


 a| 
** 擋板
** 纜線管理裝置
** 儲存系統
** 軌道套件附說明（選用）
** 儲存櫃

 a| 
** 管理乙太網路纜線（ RJ-45 纜線）
** 網路纜線
** 電源線
** 儲存纜線（如果您訂購額外的儲存設備）
** USB-C 序列連接埠纜線

|  
|===




== 步驟 3 ：註冊您的儲存系統

確保您的網站符合儲存系統規格的要求、並確認您已訂購所有零件之後、您應該註冊系統。

.步驟
. 找到儲存系統的序號。
+
您可以在裝箱單、確認電子郵件或控制器的系統管理模組中找到編號、然後再將其解壓縮。

+
image::../media/drw_ssn_label.svg[系統序號範例]

. 前往 http://mysupport.netapp.com/["NetApp 支援網站"^]。
. 判斷您是否需要註冊儲存系統：
+
[cols="1a,2a"]
|===
| 如果您是... | 請遵循下列步驟... 


 a| 
現有NetApp客戶
 a| 
.. 使用您的使用者名稱和密碼登入。
.. 選擇 * 系統 * > * 我的系統 * 。
.. 確認已列出新的序號。
.. 如果沒有、請依照新NetApp客戶的指示進行。




 a| 
NetApp新客戶
 a| 
.. 按一下*立即註冊*、然後建立帳戶。
.. 選擇 * 系統 * > * 註冊系統 * 。
.. 輸入儲存系統的序號和要求的詳細資料。


註冊核准後、您可以下載任何必要的軟體。核准程序可能需要24小時。

|===


.接下來呢？
準備好安裝 FAS70 或 FAS90 硬體之後link:install-hardware.html["安裝 FAS70 或 FAS90 儲存系統的硬體"]，您就可以了。
