---
permalink: a150/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a150, a150, aff, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: 您必須驗證機箱的HA狀態、並執行系統層級診斷、切換回Aggregate、然後將故障零件歸還給NetApp、如套件隨附的RMA指示所述。 
---
= 還原並驗證組態AFF - VA150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須驗證機箱的HA狀態、並執行系統層級診斷、切換回Aggregate、然後將故障零件歸還給NetApp、如套件隨附的RMA指示所述。



== 步驟1：驗證並設定機箱的HA狀態

您必須驗證機箱的HA狀態、並視需要更新狀態以符合您的系統組態。

. 在維護模式中、從任一控制器模組顯示本機控制器模組和機箱的HA狀態：「ha-config show」
+
所有元件的HA狀態都應該相同。

. 如果所顯示的機箱系統狀態與您的系統組態不符：
+
.. 設定機箱的HA狀態：「ha-config modify chassis _ha-stu__」
+
HA狀態的值可以是下列其中一項：

+
*** 《哈》
*** "Malc"
*** 「抄送給我們」
*** 《MCCIP》
*** 「非哈」


.. 確認設定已變更：「ha-config show」


. 如果您尚未重新設定、請重新設定系統的其他部分。
. 下一步取決於您的系統組態。
+
[cols="1,2"]
|===
| 如果您的系統處於... | 然後... 


 a| 
獨立組態
 a| 
.. 退出維護模式：「halt」
.. 前往 link:chassis_replace.html["「完成更換程序"]。




 a| 
HA與第二個控制器模組配對
 a| 
結束維護模式：「停止」載入程式提示字元出現。

|===




== 步驟2：執行系統層級診斷

安裝新機箱之後、您應該執行互連診斷。

您的系統必須處於載入器提示狀態、才能啟動系統層級診斷。

診斷程序中的所有命令都是由要更換元件的控制器發出。

. 如果要維修的控制器未出現載入程式提示、請執行下列步驟：
+
.. 從顯示的功能表中選取「維護模式」選項。
.. 控制器開機至維護模式後、停止控制器：「halt（停止）」
+
發出命令之後、您應該等到系統在載入程式提示字元停止。

+

NOTE: 在開機過程中、您可以安全地回應「y」提示：



. 如果您使用HA組態、請在第二個控制器上重複上述步驟。
+

NOTE: 兩個控制器都必須處於維護模式、才能執行互連測試。

. 在載入程式提示字元下、存取專為系統層級診斷所設計的特殊驅動程式、以正常運作：「boot_diags'（boot_diags'）
+
在開機過程中、您可以安全地回應提示「y」、直到出現「維護模式」提示（*>）為止。

. 從「維護模式」提示字元「lag」裝置修改-develess互連-sel enable」啟用互連診斷測試
+
互連測試預設為停用、必須啟用才能個別執行。

. 從「維護模式」提示字元「ldiag」執行「互連診斷」測試：「ldiag」裝置執行-develic互 連」
+
您只需要從一個控制器執行互連測試。

. 確認更換機箱後沒有硬體問題：「ldiag設備狀態-deving互連-long -state f失敗」
+
如果沒有測試失敗、系統層級的診斷會返回提示、或列出測試元件所導致的故障完整狀態。

. 請根據上述步驟的結果繼續進行。
+
[cols="1,2"]
|===
| 如果系統層級的診斷測試... | 然後... 


 a| 
已完成、沒有任何故障
 a| 
.. 清除狀態記錄：「ldiag」裝置的清除狀態
.. 確認記錄已清除：「ldiag設備狀態」
+
畫面會顯示下列預設回應：

+
[listing]
----
SLDIAG: No log messages are present.
----
.. 在兩個控制器上退出維護模式：「halt（停止）」
+
系統會顯示載入程式提示。

+

NOTE: 您必須先結束兩個控制器的維護模式、然後再繼續進行。

.. 在兩個控制器上的加載器提示符下輸入以下命令：“bye（再見）”
.. 使控制器恢復正常運作：


|===
+
[cols="1,2"]
|===
| 如果您的系統執行ONTAP 的是 | 然後... 


 a| 
在叢集中有兩個節點
 a| 
發出以下命令：「node:>> cluster ha modify -configured true'node:>> storage Failover modify -node0 -enabled true（節點：叢集ha修改設定的true）」



 a| 
叢集中有兩個以上的節點
 a| 
發出此命令：'node:>> storage容錯移轉修改-node0 -enabled true（已啟用）



 a| 
在雙節點MetroCluster 的不全功能組態中
 a| 
繼續下一步。更新程序的下一項工作是執行此程序。MetroCluster



 a| 
在獨立組態中
 a| 
您在此特定工作中沒有進一步的步驟。

您已完成系統層級的診斷。



 a| 
導致某些測試失敗
 a| 
確定問題的原因。

.. 退出維護模式：「halt」
.. 執行乾淨關機、然後拔下電源供應器。
.. 確認您已注意到執行系統層級診斷所需的所有考量事項、纜線是否穩固連接、以及硬體元件是否已正確安裝在儲存系統中。
.. 重新連接電源供應器、然後開啟儲存系統電源。
.. 重新執行系統層級的診斷測試。


|===




== 步驟3：在雙節點MetroCluster 的不二組態中切換回集合體

完成雙節點MetroCluster 的故障恢復組態中的FRU更換之後、您就可以執行MetroCluster 還原還原作業。這會將組態恢復至正常運作狀態、使先前受損站台上的同步來源儲存虛擬機器（SVM）現在處於作用中狀態、並從本機磁碟集區提供資料。

此工作僅適用於雙節點MetroCluster 的不完整組態。

.步驟
. 驗證所有節點是否都處於「啟用」狀態：MetroCluster 「顯示節點」
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. 確認所有SVM上的重新同步已完成：MetroCluster 「Svserver show」
. 驗證修復作業所執行的任何自動LIF移轉是否已成功完成：「MetroCluster 還原檢查LIF show」
. 從存續叢集中的任何節點使用「MetroCluster 還原」命令執行切換。
. 確認切換作業已完成：MetroCluster 「不顯示」
+
當叢集處於「等待切換」狀態時、切換回復作業仍在執行中：

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
當叢集處於「正常」狀態時、即可完成切換作業：

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
如果切換需要很長時間才能完成、您可以使用「MetroCluster show config-repl複 寫res同步 狀態show」命令來檢查進行中的基準狀態。

. 重新建立任何SnapMirror或SnapVault 不完整的組態。




== 步驟4：將故障零件歸還給NetApp

如套件隨附的RMA指示所述、將故障零件退回NetApp。請參閱 https://mysupport.netapp.com/site/info/rma["產品退貨安培；更換"] 頁面以取得更多資訊。
