---
permalink: a150/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: aff a150, a150, aff, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: 若要更換機箱、您必須關閉控制器。 
---
= 關閉控制器AFF -現象A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用適合您組態的適當程序來關閉或接管受損的控制器。



== 選項1：大多數組態

此程序適用於具有兩個節點組態的系統。有關在服務叢集時正常關機的詳細資訊，請參閱 https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/What_is_the_procedure_for_graceful_shutdown_and_power_up_of_a_storage_system_during_scheduled_power_outage["正常關機並開機儲存系統解決方案指南 - NetApp 知識庫"]。

.開始之前
* 請確定您擁有必要的權限和認證：
+
** ONTAP 的本機系統管理員認證。
** 每個控制器的 BMC 存取權限。


* 請確定您擁有必要的工具和設備以進行更換。


.步驟
. 透過 SSH 登入叢集、或使用本機主控台纜線和筆記型電腦 / 主控台、從叢集中的任何節點登入。
. 停止所有用戶端 / 主機存取 NetApp 系統上的資料。
. 暫停外部備份工作。
. 如果啟用 AutoSupport ，請抑制個案建立，並指出您預期系統離線的時間：
+
`system node autosupport invoke -node * -type all -message "MAINT=2h Replace chassis"`

. 識別所有叢集節點的 SP / BMC 位址：
+
`system service-processor show -node * -fields address`

. 結束叢集 Shell ：
+
`exit`

. 使用上一個步驟中確定的 IP 位址登入每個控制器的 SP/BMC：
+
** 如果您透過 SSH 從 BMC 登入，請使用 SP/BMC 位址（例如 `ssh admin@<SP/BMC_address>`）進行連線，然後輸入命令 `system console`並進行驗證。
** 如果您使用的是直接連接到控制器的本機主控台或筆記型電腦，請使用相同的叢集管理員認證登入。


. 停止位於受損機箱中的兩個節點：
+
`system node halt -node <node1>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: 對於在 StrictSync 模式下使用 SnapMirror 同步操作的叢集： `system node halt -node <node1>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. 當您看到下列項目時，請為叢集中的每個控制器輸入 * y* ：
+
`Warning: Are you sure you want to halt node _<node_name>_? {y|n}:`

. 等待每個控制器停止並顯示載入器提示。




== 選項2：控制器採用MetroCluster 不含資訊的組態


NOTE: 如果您的系統採用雙節點MetroCluster 的功能、請勿使用此程序。

接管並停止故障控制器，以便正常控制器繼續從故障控制器的儲存提供資料。為此，您需要在 AutoSupport 中停用自動建立案例功能、停用自動復原功能，並將故障控制器置於 LOADER 提示字元。LOADER 提示字元是安全的停止狀態，您可以從中更換 FRU。

* 如果叢集有兩個以上的節點、則叢集必須處於仲裁狀態。如果叢集未達到法定人數、或健全的控制器顯示為「假」、表示符合資格和健全狀況、則您必須在關閉受損的控制器之前修正問題；請參閱 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["將節點與叢集同步"^]。
* 如果您使用MetroCluster 的是功能不全的組態、則必須確認MetroCluster 已設定「功能不全」狀態、且節點處於啟用且正常的狀態（「MetroCluster 功能不全」）。


.步驟
. 如果啟用了「支援」功能、請叫用下列消息來禁止自動建立個案AutoSupport AutoSupport ：
+
`system node autosupport invoke -node * -type all -message MAINT=<number of hours down>h`

+
這樣可以防止在您規劃的維護視窗期間自動建立支援案例。最長抑制時間為 72 小時。如果您的維護提前完成，您可以透過呼叫包含 `MAINT=END`的 AutoSupport 訊息來重新啟用案例建立功能。如需詳細資訊，請參閱 https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["如何在排程維護期間抑制自動建立案例"^]。

+
下列AutoSupport 資訊不顯示自動建立案例兩小時：

+
`cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. 停用健全控制器主控台的自動恢復功能：「torage容錯移轉修改–節點本機-自動恢復錯誤」
. 將受損的控制器移至載入器提示：
+
[cols="1,2"]
|===
| 如果受損的控制器正在顯示... | 然後... 


 a| 
載入程式提示
 a| 
前往下一步。



 a| 
正在等待恢復...
 a| 
按Ctrl-C、然後在出現提示時回應「y」。



 a| 
系統提示或密碼提示（輸入系統密碼）
 a| 
從正常控制器接管或停止受損的控制器：「torage容錯移轉接管-節點_受損節點_節點名稱_」

當受損的控制器顯示正在等待恢復...時、請按Ctrl-C、然後回應「y」。

|===

