---
permalink: a150/overview.html 
sidebar: sidebar 
keywords: AFF A150 specifications, AFF A150 specs, NetApp AFF A150, AFF A150 hardware 
summary: AFF A150儲存系統的主要規格 
---
= AFF A150的主要規格
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下是AFF A150的部分規格。訪問 https://hwu.netapp.com["NetApp Hardware Universe"^]（HWU）取得AFF A150規格的完整清單。此頁面反映的是單一高可用性對。



=== AFF A150的主要規格

平台配置： AFF A150 UTA2 單機箱 HA 對

最大原容量：0.5472 PB

記憶體：64.0000 GB

外型尺寸：2U 機箱，配備 2 個 HA 控制器和 24 個驅動器插槽

ONTAP版本：b_startONTAP：9.16.1P2b_end

PCIe 擴充槽：

最低ONTAP版本： ONTAP 9.10.1P12



=== 橫向擴展最大值

|===


| 類型 | HA 對 | 原始容量 | 最大記憶體 


| 網路儲存 | 12 | 6.6 PB / 5.8 PiB | 768GB 


| 儲存區域網絡 | 6 | 3.3 PB / 2.9 PiB | 384GB 


| HA 對 |  | 0.5 PB / 0.5 PiB | 64.0000 
|===


=== 輸入輸出



==== 板載 IO

|===


| 協定 | 連接埠 


| 乙太網路 10 Gbps | 12 


| 光纖通道 16 Gbps | 8 


| SAS 12 Gbps | 4 
|===


==== 總 IO

|===


| 協定 | 連接埠 


| 乙太網路 10 Gbps | 12 


| 光纖通道 16 Gbps | 8 


| SAS 12 Gbps | 4 
|===


==== 管理埠

|===


| 協定 | 連接埠 


| 乙太網路 1 Gbps | 2. 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 2. 
|===


=== 支援的儲存網絡

CIFS；FC；FCoE；iSCSI；NFS v3；NFS v4.0；NFS v4.1；NFS v4.2；NVMe/TCP；S3；附 NAS 的 S3；SMB 2.0；SMB 2.1；SMB 2.x；SMB 3.0；SMB 3.1；



=== 系統環境規格

* 典型功率：1209 BTU/小時
* 最壞情況下的功率：1676 BTU/小時
* 重量：60.8 磅 27.6 公斤
* 高度：2U
* 寬度：19 吋 IEC 機架相容（17.6 吋 44.7 公分）
* 深度：19.0 吋（含電纜管理支架為 24.1 吋）
* 工作溫度/海拔/濕度：5°C 至 45°C（41°F 至 113°F），海拔最高可達 3048 公尺（10000 英尺）；相對濕度 8% 至 90%，無冷凝
* 非工作溫度/濕度：-40°C 至 70°C（-40°F 至 158°F），海拔最高 12192 公尺（40000 英尺），相對濕度 10% 至 95%，無冷凝，原包裝
* 聲學噪音：標稱聲功率 (LwAd)：6.9；聲壓 (LpAm)（旁觀者位置）：51.0 分貝




=== 遵守

* EMC/EMI 認證：AMCA、FCC、ICES、KC、摩洛哥、VCCI
* 安全認證：BIS、CB、CSA、G_K_U-SoR、IRAM、NOM、NRCS、SONCAP、TBS
* 安全/EMC/EMI認證：EAC、UKRSEPRO
* 認證安全/EMC/EMI/RoHS：BSMI、CE DoC、UKCA DoC
* 標準 EMC/EMI：BS-EN-55024、BS-EN55035、CISPR 32、EN55022、EN55024、EN55032、EN55035、EN61000-3-2、EN61000-3-3、KS 第 15 部分 A 3830 33 類
* 標準安全：ANSI/UL60950-1、ANSI/UL62368-1、BS-EN62368-1、CAN/CSA C22.2 No. 60950-1、CAN/CSA C22.2 No. 62368-1、CNS 14336、EN60825-12368-1、CNS 14336、EN60825-6 62368-1、IEC60950-1、IS 13252（第 1 部分）




=== 高可用性

以乙太網路為基礎的基板管理控制器 (BMC) 和ONTAP管理介面；冗餘熱插拔控制器；冗餘熱插拔電源；透過 SAS 連線進行 SAS 帶內管理；
