---
permalink: asa-r2-70-90/maintain-overview.html 
sidebar: sidebar 
keywords: asa r2 a70 asa r2 a90 maintenance, maintenance, repairing asa r2 a70 asa r2 a90, repairing a70 asa r2 a90, replace a70 asa r2 a90 components 
summary: 維護 ASA R2 A70 、 ASA R2 A90 硬體 
---
= 維護程序總覽 - ASA A70 和 ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
維護 ASA A70 和 ASA A90 儲存系統的硬體，以確保長期的可靠性和最佳效能。定期執行維護工作，例如更換故障元件，如此有助於避免停機和資料遺失。

維護程序假設 ASA A70 和 ASA A90 系統已部署為 ONTAP 環境中的儲存節點。



== 系統元件

對於 ASA A70 和 ASA A90 儲存系統、您可以對下列元件執行維護程序。

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["啟動媒體 - 自動恢復"]
 a| 
啟動媒體儲存儲存系統用於啟動的一組主要ONTAP映像檔。在自動復原期間，系統會從合作夥伴節點擷取啟動映像，並自動執行適當的啟動功能表選項以在取代啟動媒體上安裝映像。

自動啟動媒體復原過程僅在ONTAP 9.17.1 及更高版本中支援。如果您的儲存系統運行的是早期版本的ONTAP，請使用link:bootmedia-replace-workflow.html["手動啟動恢復程序"] 。



 a| 
link:bootmedia-replace-workflow.html["啟動媒體-手動恢復"]
 a| 
啟動媒體儲存一組主ONTAP映像檔和一組輔助 ONTAP 映像文件，儲存系統使用這些檔案從 USB 磁碟機啟動映像並從合作夥伴節點恢復配置



 a| 
link:chassis-replace-workflow.html["機箱"]
 a| 
機箱是實體機箱、可容納所有控制器元件、例如控制器 /CPU 單元、電源供應器和 I/O



 a| 
link:controller-replace-workflow.html["控制器"]
 a| 
控制器由主機板、韌體和軟體組成。它控制儲存設備、 I/O 卡、並執行 ONTAP 作業系統軟體。



 a| 
link:dimm-replace.html["DIMM"]
 a| 
雙列直插式記憶體模組（ DIMM ）是一種電腦記憶體類型。它們是為了將系統記憶體新增至控制器主機板而安裝。



 a| 
link:drive-replace.html["磁碟機"]
 a| 
磁碟機是提供資料所需實體儲存設備的裝置。



 a| 
link:fan-swap-out.html["風扇"]
 a| 
風扇可冷卻控制器。



 a| 
link:nvram-replace.html["NVRAM"]
 a| 
NVRAM （非揮發性隨機存取記憶體）是一個模組、可讓控制器在系統斷電時保護及儲存在線上資料。系統 ID 位於 NVRAM 模組中。更換後、控制器會從更換的 NVRAM 模組中取得新的系統 ID 。



 a| 
link:nvdimm-battery-replace.html["非易失電池"]
 a| 
NV 電池負責為 NVRAM 模組提供電力、而在電力中斷後、正在傳輸的資料會被轉至快閃記憶體。



 a| 
link:io-module-overview.html["I/O模組"]
 a| 
I/O 模組（輸入 / 輸出模組）是一種硬體元件、可作為控制器與需要與控制器交換資料的各種裝置或系統之間的中介。



 a| 
link:power-supply-replace.html["電源供應器"]
 a| 
電源供應器在控制器中提供備援電源。



 a| 
link:rtc-battery-replace.html["即時時鐘電池"]
 a| 
即時時鐘電池會在電源關閉時保留系統日期和時間資訊。



 a| 
link:system-management-replace.html["系統管理模組"]
 a| 
系統管理模組提供控制器與主控台或筆記型電腦之間的介面、以供控制器或系統維護之用。系統管理模組包含開機媒體、並儲存系統序號（ SSN ）。

|===