---
permalink: c800/maintain-overview.html 
sidebar: sidebar 
keywords: aff C800 maintenance, maintenance, repairing C800, repairing aff C800, replace aff C800 components, replace aff C800 components 
summary: 維護AFF C800硬體 
---
= 維護 AFF C800 硬體
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
維護AFF C800儲存系統的硬件，以確保長期可靠性和最佳效能。定期執行維護任務（例如更換故障組件），有助於防止停機和資料遺失。

維護過程假定AFF C800儲存系統已部署為ONTAP環境中的儲存節點。



== 系統元件

對於 AFF C800 儲存系統、您可以對下列元件執行維護程序。

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["啟動媒體 - 自動恢復"]
 a| 
啟動媒體儲存儲存系統用於啟動的一組主要ONTAP映像檔。在自動復原期間，系統會從合作夥伴節點擷取啟動映像，並自動執行對應的啟動功能表選項以在取代啟動媒體上安裝映像。自動啟動媒體復原過程僅在ONTAP 9.17.1 及更高版本中支援。如果您的儲存系統運行的是早期版本的ONTAP，請使用link:bootmedia-replace-workflow.html["手動啟動恢復程序"] 。



 a| 
link:bootmedia-replace-workflow.html["啟動媒體 - 手動恢復"]
 a| 
啟動媒體儲存儲存系統用於啟動的一組主要ONTAP映像檔。在手動復原期間，您會從 USB 隨身碟啟動儲存系統並手動還原檔案系統映像和設定。如果您的儲存系統運作的是ONTAP 9.17.1 及更高版本，請使用link:bootmedia-replace-workflow-bmr.html["自動啟動恢復程序"]。



 a| 
link:chassis-replace-overview.html["機箱"]
 a| 
機箱是實體機箱、可容納所有控制器元件、例如控制器 /CPU 單元、電源供應器和 I/O



 a| 
link:controller-replace-overview.html["控制器"]
 a| 
控制器由主機板、韌體和軟體組成。它控制磁碟機並執行 ONTAP 功能。



 a| 
link:dimm-replace.html["DIMM"]
 a| 
如果存在記憶體不相符的情況、或是有故障的DIMM、則必須更換DIMM（雙列直插式記憶體模組）。



 a| 
link:drive-replace.html["磁碟機"]
 a| 
磁碟機是提供資料實體儲存媒體的裝置。



 a| 
link:fan-replace.html["風扇"]
 a| 
風扇會冷卻控制器。



 a| 
link:nvdimm-replace.html["NVDIMM"]
 a| 
NVDIMM （非揮發性雙列直插式記憶體模組）可管理從揮發性記憶體到非揮發性儲存設備的資料傳輸、並在停電或系統關機時維持資料完整性。



 a| 
link:nvdimm-battery-replace.html["NVDIMM電池"]
 a| 
NVDIMM 電池負責維持 NVDIMM 模組的電力。



 a| 
link:pci-cards-and-risers-replace.html["PCIe 卡和轉接卡"]
 a| 
PCIe（外圍組件可互連快速）卡是一種擴充卡，可插入主機板上的 PCIe 插槽或插入主機板的轉接卡。



 a| 
link:power-supply-replace.html["電源供應器"]
 a| 
電源供應器可在控制器機櫃中提供備援電源。



 a| 
link:rtc-battery-replace.html["即時時鐘電池"]
 a| 
即時時鐘電池會在電源關閉時保留系統日期和時間資訊。

|===