---
permalink: asa-r2-a20-30-50/controller-replace-requirements.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, prerequisite, replace the controller module 
summary: 在更換 ASA A20 ， ASA A30 或 ASA A50 系統中的控制器之前，請確定您符合成功更換所需的要求。這包括驗證系統中的所有其他元件是否正常運作，確認您擁有正確的更換控制器，以及將控制器的主控台輸出儲存至文字記錄檔。 
---
= 更換控制器的需求 - ASA A20 ， ASA A30 和 ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在更換 ASA A20 ， ASA A30 或 ASA A50 系統中的控制器之前，請確定您符合成功更換所需的要求。這包括驗證系統中的所有其他元件是否正常運作，確認您擁有正確的更換控制器，以及將控制器的主控台輸出儲存至文字記錄檔。

檢閱控制器更換程序的要求與考量事項。



== 需求

* 所有機櫃都必須正常運作。
* 健全的控制器必須能夠接管要更換的控制器（在本程序中稱為「受損的控制器」）。
* 如果您的系統採用MetroCluster 不必要的組態、您必須檢閱一節 https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["選擇正確的恢復程序"] 判斷您是否應該使用此程序。
* 您必須以相同機型類型的控制器來更換控制器。您無法只更換控制器來升級系統。
* 在此程序中，您無法變更任何磁碟機或磁碟櫃。
* 您必須永遠擷取控制器的主控台輸出至文字記錄檔。
+
主控台輸出會記錄您在更換程序中可能遇到的問題，以便用來疑難排解的程序。





== 考量

* 請務必將本程序中的命令套用至正確的控制器：
+
** _減損_控制器是要更換的控制器。
** _replacement控制器是取代受損控制器的新控制器。
** _Healthy控制器是正常運作的控制器。


* 如有需要，您可以開啟儲存系統位置（藍色） LED ，以協助實際定位受影響的儲存系統。使用 SSH 登入 BMC ，然後輸入 `system location-led _on_`命令。
+
儲存系統有三個位置 LED ：一個在操作員顯示面板上，一個在每個控制器上。位置LED會持續亮起30分鐘。

+
您可以輸入命令將其關閉 `system location-led _off_`。如果您不確定 LED 是否亮起或熄滅，可以輸入命令來檢查其狀態 `system location-led show`。



.接下來呢？
在您審查了更換受損控制器的要求之後link:controller-replace-shutdown.html["關閉受損的控制器"]，您需要。
