---
permalink: asa-c250/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: asa c250, shutdown the controllers 
summary: 若要更換機箱、您必須關閉控制器。 
---
= 關閉控制器 - ASA C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
關閉 AFF ASA C250 儲存系統中的控制器，以防止資料遺失並確保更換機箱時的系統穩定性。

此程序適用於具有兩個節點組態的系統。有關在服務叢集時正常關機的詳細資訊，請參閱 https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/What_is_the_procedure_for_graceful_shutdown_and_power_up_of_a_storage_system_during_scheduled_power_outage["正常關機並開機儲存系統解決方案指南 - NetApp 知識庫"]。

.開始之前
* 請確定您擁有必要的權限和認證：
+
** ONTAP 的本機系統管理員認證。
** 每個控制器的 BMC 存取權限。


* 請確定您擁有必要的工具和設備以進行更換。


.步驟
. 透過 SSH 登入叢集、或使用本機主控台纜線和筆記型電腦 / 主控台、從叢集中的任何節點登入。
. 停止所有用戶端 / 主機存取 NetApp 系統上的資料。
. 暫停外部備份工作。
. 如果啟用 AutoSupport ，請抑制個案建立，並指出您預期系統離線的時間：
+
`system node autosupport invoke -node * -type all -message "MAINT=2h Replace chassis"`

. 識別所有叢集節點的 SP / BMC 位址：
+
`system service-processor show -node * -fields address`

. 結束叢集 Shell ：
+
`exit`

. 使用上一個步驟中確定的 IP 位址登入每個控制器的 SP/BMC：
+
** 如果您透過 SSH 從 BMC 登入，請使用 SP/BMC 位址（例如 `ssh admin@<SP/BMC_address>`）進行連線，然後輸入命令 `system console`並進行驗證。
** 如果您使用的是直接連接到控制器的本機主控台或筆記型電腦，請使用相同的叢集管理員認證登入。


. 停止位於受損機箱中的兩個節點：
+
`system node halt -node <node1>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: 對於在 StrictSync 模式下使用 SnapMirror 同步操作的叢集： `system node halt -node <node1>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. 當您看到下列項目時，請為叢集中的每個控制器輸入 * y* ：
+
`Warning: Are you sure you want to halt node _<node_name>_? {y|n}:`

. 等待每個控制器停止並顯示載入器提示。


.接下來呢？
關閉控制器後、您需要link:chassis-replace-move-hardware.html["將硬體移至新機箱"]
