---
permalink: ns224/hot-remove-shelf.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, drive, aggregate, ha, pair, serving, data, i/o, hot-remove an ns224 
summary: 您可以熱移除NS224磁碟機櫃、其中的集合體已從磁碟機移除、在HA配對中開啟並提供資料（I/O正在進行中）。 
---
= 熱移除機櫃- NS224機櫃
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以熱移除NS224磁碟機櫃、其中的集合體已從磁碟機移除、在HA配對中開啟並提供資料（I/O正在進行中）。

.開始之前
* 您的HA配對無法處於接管狀態。
* 您必須從要移除的磁碟機櫃中移除所有的集合體（磁碟機必須是備用磁碟機）。
+

NOTE: 如果您嘗試在要移除的機櫃上使用Aggregate執行此程序、則可能會在多磁碟故障時使系統故障。

+
您可以使用「shorage aggregate offline -Aggregate _Aggregate name_」命令、然後使用「shorage aggregate delete -Aggregate _name_」命令。

* 如果您的系統是在系統機櫃中出貨、則需要使用十字螺絲起子來移除將機櫃固定至機櫃後端的螺絲。


.關於這項工作
* 如果您要熱移除多個機櫃、一次只能移除一個機櫃。
* *最佳實務做法：*最佳實務做法是在移除磁碟櫃中的集合體後、移除磁碟機所有權。
+
從備用磁碟機移除擁有權資訊、可將磁碟機正確整合至另一個節點（視需要）。

+
移除磁碟機所有權的程序可在磁碟和集合體內容中找到：

+
https://docs.netapp.com/us-en/ontap/disks-aggregates/index.html["磁碟與集合體總覽"^]




NOTE: 此程序需要停用自動磁碟指派。您可在本程序結束時（熱移除磁碟櫃之後）重新啟用自動磁碟指派。

* 如有需要、您可以開啟機櫃的位置（藍色）LED、以協助實際找出受影響的機櫃：「儲存櫃位置導向的修改-機櫃名稱_bidle_name_-leide-Status on」
+
如果您不知道受影響的機櫃的「_shider_name_」、請執行「shorage sh儲存 櫃show」命令。

+
機櫃有三個位置LED：一個在操作員顯示面板上、一個在每個NSM模組上。位置LED會持續亮起30分鐘。您可以輸入相同的命令、但使用「關閉」選項來關閉這些命令。

* 從非專屬的RoCE連接埠（主機板上的控制器、具備RoCE功能的PCIe卡、兩者的組合、或I/O模組）中斷連接機櫃之後、您可以選擇重新設定這些連接埠以供網路使用。
+

NOTE: 如果HA配對執行ONTAP 的是版本的32位版本、您必須一次重新啟動一個控制器。如果HA配對執行ONTAP 的是NetApp 9.7或更新版本、則不需要重新啟動控制器、除非其中一個或兩個控制器都處於維護模式。此程序假設兩個控制器都未處於維護模式。



.步驟
. 請妥善接地。
. 確認您要移除的磁碟機沒有集合體（為備用磁碟機）、而且所有權已移除：
+
.. 輸入下列命令、列出您要移除磁碟櫃中的所有磁碟機：「torage disk show -ball_bider_number_」
+
您可以在任一控制器模組上輸入命令。

.. 檢查輸出、確認磁碟機上沒有集合體。
+
沒有集合體的磁碟機在「Container Name」（容器名稱）欄位中會有破折號。

.. 檢查輸出、確認磁碟機已移除所有權。
+
沒有擁有權的磁碟機在「擁有者」欄位中會有一個破折號。

+

NOTE: 如果您有故障的磁碟機、它們會在「Container Type（容器類型）」欄中顯示「中斷」。（故障磁碟機沒有所有權。）

+
下列輸出顯示正在移除磁碟櫃（磁碟櫃2）上的磁碟機處於移除磁碟櫃的正確狀態。所有磁碟機上的集合體都會移除、因此每個磁碟機的「Container Name」（容器名稱）欄會出現一個破折號。所有磁碟機的擁有權也會被移除、因此每個磁碟機的「擁有者」欄會出現破折號。



+
[listing]
----
cluster1::> storage disk show -shelf 2

           Usable           Disk     Container   Container
Disk         Size Shelf Bay Type     Type        Name       Owner
-------- -------- ----- --- ------   ----------- ---------- ---------
...
2.2.4           -     2   4 SSD-NVM  spare                -         -
2.2.5           -     2   5 SSD-NVM  spare                -         -
2.2.6           -     2   6 SSD-NVM  broken               -         -
2.2.7           -     2   7 SSD-NVM  spare                -         -
...
----
. 實際找到您要移除的機櫃。
. 從您要移除的機櫃拔下纜線：
+
.. 如果電源線是AC電源供應器、請打開電源線固定器、以從電源供應器拔下電源線、如果是DC電源供應器、請拆下兩個指旋螺絲、然後從電源供應器拔下電源線。
+
電源供應器沒有電源開關。

.. 拔下儲存設備纜線（從機櫃到控制器）。


. 從機架或機櫃實際移除機櫃。
+

NOTE: 滿載的NS224機櫃可重達66、78磅（30、29公斤）、需要兩個人才能舉升或使用液壓起重裝置。避免移除機櫃元件（從機櫃正面或背面）、以降低機櫃重量、因為機櫃重量會不平衡。

+

NOTE: 如果您的系統是在機櫃中出貨、則必須先將固定機櫃的兩顆十字螺絲轉開、使其固定在後端的權利上方。螺絲位於底部NSM模組的機櫃內側。您應該同時移除兩個NSM模組、以存取螺絲。

. 如果您要移除多個機櫃、請重複步驟2至5。
+
否則、請前往下一步。

. 如果您在移除磁碟機所有權時停用自動磁碟機指派、請重新啟用：「torage disk option modify -autodassign on（磁碟選項修改自動指派開啟）」
+
您可以在兩個控制器模組上執行命令。

. 您可以選擇完成下列子步驟、重新設定非專屬的RoCE連接埠以供網路使用。
+
否則、您將完成此程序。

+
.. 驗證目前設定用於儲存用途的非專屬連接埠名稱：「儲存連接埠顯示」
+
您可以在任一控制器模組上輸入命令。

+

NOTE: 輸出中會顯示設定用於儲存用途的非專屬連接埠、如下所示：如果HA配對執行ONTAP 的是版本號為2、9.8或更新版本、則非專屬連接埠會在「模式」欄中顯示「儲存」。如果您的HA配對執行ONTAP 的是32或9.6、則非專用連接埠在「專用」中顯示「假」 欄位、也會在「tate」欄位中顯示「啟用」。

.. 完成適用於ONTAP HA配對所執行版本的一系列步驟：
+
[cols="1,2"]
|===
| 如果HA配對正在執行... | 然後... 


 a| 
部分9.8或更新版本ONTAP
 a| 
... 在第一個控制器模組上重新設定非專屬連接埠以供網路使用：「torage port modify -node-node-node-name_-port _port name_-mode network」
+
您必須針對要重新設定的每個連接埠執行此命令。

... 重複上述步驟、重新設定第二個控制器模組上的連接埠。
... 前往子步驟8c以驗證所有連接埠變更。




 a| 
更新ONTAP
 a| 
... 在第一個控制器模組上重新設定非專用連接埠以供網路使用：「torage port disable-node-node-node-name_-port _port name_」
+
您必須針對要重新設定的每個連接埠執行此命令。

... 重複上述步驟、重新設定第二個控制器模組上的連接埠。
... 前往子步驟8c以驗證所有連接埠變更。




 a| 
版本的32 ONTAP
 a| 
... 在第一個控制器模組上重新設定具備RoCE功能的連接埠以供網路使用：「torage port disable -node/node/node/node/-port _port name_」
+
您必須針對要重新設定的每個連接埠執行此命令。

... 重新啟動控制器模組、使連接埠變更生效：
+
「系統節點重新開機-節點節點名稱_-重新開機原因_」

+

NOTE: 重新開機必須先完成、才能繼續下一步。重新開機最多可能需要15分鐘。

... 重複第一步（A）、重新設定第二個控制器模組上的連接埠。
... 重複第二個步驟（b）、重新啟動第二個控制器、使連接埠變更生效。
... 前往子步驟8c以驗證所有連接埠變更。


|===
.. 確認兩個控制器模組的非專屬連接埠已重新設定為網路使用：「torage port show」（儲存連接埠顯示）
+
您可以在任一控制器模組上輸入命令。

+
如果HA配對執行ONTAP 的是NetApp 9.8或更新版本、非專屬連接埠會在「模式」欄位中顯示「network」（網路）。

+
如果您的HA配對執行ONTAP 的是32或9.6、則非專用連接埠在「專用」中顯示「假」 欄位、也會在「tate」欄位中顯示「停用」。




