---
permalink: ns224/install-hot-add-shelf.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, install, hot-add an ns224 drive shelf 
summary: 當HA配對符合特定需求、且已完成適用於HA配對的準備工作之後、您可以熱新增NS224磁碟機櫃。 
---
= 安裝熱新增的機櫃 - NS224 機櫃
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您需要在機櫃或電信機架中安裝 NS224 機櫃、連接電源線（會自動開啟機櫃電源）、並設定機櫃 ID 。

.開始之前
* 請確定您的有一個迴紋針、一邊拉直、或是一支窄尖的圓珠筆。
+
若要變更機櫃 ID 、您可以使用迴紋針或圓珠筆來存取「操作員顯示面板」（ ODP ）後面的機櫃 ID 按鈕、以進行變更機櫃 ID 步驟。

* 請瞭解，使用 NSM100 模組時，完全負載的 NS224 機櫃可重達 66.78 磅（ 30.29 公斤），使用 NSM100B 模組時平均可重達 56.8 磅（ 25.8 公斤），需要兩個人才能抬起或使用液壓起重。避免移除機櫃元件（從機櫃正面或背面）、以降低機櫃重量、因為機櫃重量會不平衡。


.步驟
. 根據需要、使用套件隨附的說明、安裝機架的軌道套件。
+

NOTE: 請務必使用適當的滑軌套件，將機櫃安裝在機架或機櫃中。

. 安裝機櫃：
+
.. 將機架背面放在軌道上、然後從底部支撐機架、並將其滑入機櫃或電信機架。
+
如果您要安裝多個機櫃、請將第一個機櫃直接放在控制器上方。將第二個機櫃直接放在控制器下方。對任何其他層架重複此模式。

.. 使用套件隨附的安裝螺絲、將機櫃固定在機櫃或電信機架上。


. 連接電源：
+
.. 將電源線連接至機櫃、並將其固定到位。
+
如果它們是 AC 電源供應器、請使用電源線固定器將它們固定到位。

+
如果是直流電源、請使用兩個拇指螺絲將它們固定到位。

.. 將電源線連接至不同的電源、以獲得恢復能力。
+
機櫃連接電源時會啟動、但沒有電源開關。當電源供應器正常運作時、雙色LED會亮起綠燈。



. 將機櫃ID設為HA配對內的唯一編號：
+
如需更多詳細指示、請參閱 link:change-shelf-id.html["變更機櫃ID - NS224機櫃"^]。

+
.. 取下左端蓋、找到LED右側的小孔。
.. 將回形針或類似工具的一端插入小孔、以觸及機櫃ID按鈕。
.. 按住按鈕（長達15秒）、直到數位顯示器上的第一個數字開始閃爍、然後釋放按鈕。
+
如果ID需要15秒以上的時間才能開始閃燈、請再次按住按鈕、確定一定要完全按下。

.. 按下並釋放按鈕、將號碼往前移、直到達到所需的0到9。
.. 重複子步驟4c和4d、設定機櫃ID的第二個編號。
+
最多可能需要三秒（而非15秒）、才能讓號碼開始閃燈。

.. 按住按鈕、直到第二個數字停止閃爍。
+
約五秒鐘後、兩個數字都會開始閃爍、ODP上的黃色LED會亮起。

.. 重新啟動機櫃、使機櫃ID生效。
+
您必須從機櫃拔下兩根電源線、等待10秒鐘、然後重新插回。

+
電源恢復供電時、二色LED會亮起綠色。





.接下來呢？
連接熱插拔機櫃。前往 link:cable-overview-hot-add-shelf.html["熱新增的纜線總覽"]。
