---
permalink: ns224/prepare-hot-add-shelf.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, requirement, preparation, applicable, complete, drive, hot-add an ns224 drive shelf 
summary: 當HA配對符合特定需求、且已完成適用於HA配對的準備工作之後、您可以熱新增NS224磁碟機櫃。 
---
= 準備熱新增 - NS224 機櫃
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在熱新增 NS224 機櫃之前、請先完成適用於 HA 配對的準備工作。

完成適用的準備工作後、請前往 link:prepare-hot-add-shelf.html["安裝用於熱新增的機櫃"]。



== 安裝具備 ROCE 功能的 PCIe 卡或 I/O 模組

如果您的平台機型支援使用具備 ROCE 功能的 PCIe 卡或 I/O 模組、則您的 HA 配對必須有足夠的可用 Roce 功能乙太網路連接埠、以支援您要熱新增的機櫃數量。

.步驟
. 針對您要熱新增的每個機櫃、請確認每個控制器上有兩個具備 ROCE 功能的連接埠。
+
這些連接埠可在控制器上、具備RoCE功能的PCIe卡上、兩者的組合、或是具備RoCE功能的I/O模組上、如您的平台機型所支援。

. 如果您的 HA 配對沒有足夠的可用具備 ROCE 功能的連接埠、請將額外的 PCIe 卡或 I/O 模組安裝到正確的控制器插槽中、視您的平台機型所支援。
+
.. 識別適用於您平台機型的正確控制器插槽。請參閱。 https://hwu.netapp.com["NetApp Hardware Universe"^]
.. 請參閱您的平台機型文件、瞭解 PCIe 卡或 I/O 模組安裝說明。






== 設定具備 ROCE 功能的連接埠以供儲存使用

如果您的 HA 配對具有非專屬的具備 ROCE 功能的乙太網路連接埠、而您使用這些連接埠來熱新增 NS224 機櫃、則必須設定連接埠以供儲存使用（而非網路使用）。

.開始之前
* 請確定您在每個控制器中安裝任何其他具備 ROCE 功能的 PCIe 卡或 I/O 模組。


.關於這項工作
* 在某些平台機型中、當具有 Roce 功能的 PCIe 卡或 I/O 模組安裝在控制器上支援的插槽中時、連接埠會自動預設為使用儲存設備（而非網路）； 不過、建議您完成下列程序、以驗證具備 ROCE 功能的連接埠是否已設定供儲存使用。
* 如果您確定HA配對中的非專用的RoCE連接埠未設定為供儲存使用、則設定這些連接埠是不中斷營運的程序。您不需要重新啟動控制器，除非其中一個或兩個控制器都處於維護模式。此程序假設兩個控制器都未處於維護模式。
* 如果將來需要將端口從存儲使用更改爲網絡使用，請輸入命令。 `storage port modify -node _node_name_ -port _port_name_ -mode network`


.步驟
. 使用 SSH 或序列主控台連接埠登入叢集。
. 輸入下列命令、確認 HA 配對中的非專屬連接埠是否已設定供儲存使用：
+
`storage port show`

+
** 如果HA配對執行ONTAP 的是NetApp 9.8或更新版本、則非專屬連接埠會在「模式」欄中顯示「儲存」。
** 如果 HA 配對執行的是 ONTAP 9.7 ，則會在 `State`欄 `enabled`中 `Is Dedicated?`顯示非專屬連接埠 `false`。
+
[NOTE]
====
如果未將非專屬連接埠設定為供儲存使用、命令輸出會顯示下列項目：

*** 如果HA配對執行ONTAP 的是NetApp 9.8或更新版本、非專屬連接埠會在「模式」欄位中顯示「network」（網路）。
*** 如果 HA 配對執行的是 ONTAP 9.7 ，則會在 `State`欄 `disabled`中 `Is Dedicated?``顯示非專屬連接埠 `false`。


====


. 如果將非專屬連接埠設定為供儲存使用、則您必須完成此程序。
+
否則，您需要按照以下步驟配置連接埠。

. 在其中一個控制器上設定用於儲存設備的非專用連接埠：
+
您必須針對所設定的每個連接埠重複執行適用的命令。

+
[cols="1,3"]
|===
| 如果HA配對正在執行... | 使用此命令... 


 a| 
部分9.8或更新版本ONTAP
 a| 
`storage port modify -node _node_name_ -port _port_name_ -mode storage`



 a| 
更新ONTAP
 a| 
`storage port enable -node _node_name_ -port _port_name_`

|===
. 對第二個控制器重複上述步驟。
. 確認兩個控制器上的非專屬連接埠均已設定為用於儲存設備： `storage port show`
+
** 如果HA配對執行ONTAP 的是NetApp 9.8或更新版本、則非專屬連接埠會在「模式」欄中顯示「儲存」。
** 如果 HA 配對執行的是 ONTAP 9.7 ，則會在 `State`欄 `enabled`中 `Is Dedicated?`顯示非專屬連接埠 `false`。






== 可重新配置現有的機櫃

根據您的平台機型而定、在熱新增額外的機櫃之前、您可能需要在不同插槽中的兩組連接埠之間重新配置現有的機櫃（在安裝額外的具備 ROCE 功能的 PCIe 卡或 I/O 模組之後）、以避免插槽故障。

.開始之前
* 請確定您在每個控制器中安裝任何其他具備 ROCE 功能的 PCIe 卡或 I/O 模組。
* 請確定您安裝的具備切換功能的 PCIe 卡或 I/O 模組上的非專用連接埠已設定為用於儲存設備。


.關於這項工作
* 如果您的機櫃具有多重路徑HA連線功能、則重新啟用連接埠連線是不中斷營運的程序。
* 在本程序中、您一次移動一條纜線、以永遠保持與機櫃的連線。
+

NOTE: 移動纜線時、從一個連接埠拔下纜線、然後將纜線插入另一個連接埠、不需要任何等待時間。

* 如有需要、請參閱中平台機型的機櫃佈線圖示 link:cable-overview-hot-add-shelf.html["熱新增的纜線總覽"]。


.步驟
. 可將現有機櫃的連線重新連接至不同插槽中的兩組具備切換功能的連接埠、以適用於您的平台機型。


* 對於 AFF 系統：
+
[role="tabbed-block"]
====
.AFF A1K
--
如果您要熱新增第二個機櫃或第四個機櫃、請執行下列其中一項操作。


NOTE: 如果您有 AFF A1K HA 配對、而且您正在熱新增第三個機櫃、並在每個控制器中安裝第三個或第四個具備 ROCE 功能的 I/O 模組、則第三個機櫃只能連接到第三個或第三個和第四個 I/O 模組。您不需要重新配置任何現有的機櫃。

** 如果您要熱新增第二個機櫃、請在每個控制器的插槽 11 和插槽 10 中、將第一個機櫃重新放置在具有切換功能的 I/O 模組上。
+
子步驟假設現有機櫃已連接至每個控制器上插槽 11 中具有切入功能的 I/O 模組。

+
... 在控制器A上、將纜線從插槽11連接埠b（e11b）移至插槽10連接埠b（e10b）。
... 在控制器B上重複相同的纜線移動


** 如果您要熱新增第四個機櫃、請在每個控制器的插槽 9 和插槽 8 中、將第三個機櫃重新放置在具有切換功能的 I/O 模組上。
+
子步驟假設第三個機櫃已連接至每個控制器上插槽 9 中具有切入功能的 I/O 模組。

+
... 在控制器A上、將纜線從插槽9連接埠b（e9b）移至插槽8連接埠b（e8b）。
... 在控制器B上重複相同的纜線移動




--
.AFF A70 、 AFF A90 或 AFF C80
--
如果您要熱新增第二個機櫃、請在每個控制器的插槽 11 和插槽 8 中、將第一個機櫃重新放置在具有切換功能的 I/O 模組上。

子步驟假設現有機櫃已連接至每個控制器上插槽 11 中具有切入功能的 I/O 模組。

.. 在控制器A上、將纜線從插槽11連接埠b（e11b）移至插槽8連接埠b（e8b）。
.. 在控制器B上重複相同的纜線移動


--
.AFF A800 或 AFF C800
--
如果您要熱新增第二個機櫃、請在每個控制器的插槽 5 和插槽 3 的兩組具備切換功能的連接埠中重新放置第一個機櫃。

以下步驟假設現有的機櫃已連接至每個控制器插槽5中的可操作PCIe卡。

.. 在控制器A上、將纜線從插槽5連接埠b（e5b）移至插槽3連接埠b（e3b）。
.. 在控制器B上重複相同的纜線移動


--
.部分A700 AFF
--
如果您要熱新增第二個機櫃、請在每個控制器的插槽 3 和插槽 7 的兩組具備切換功能的連接埠中重新放置第一個機櫃。

這些子步驟假設現有機櫃已連接至每個控制器插槽3中具有資源相容的I/O模組。

.. 在控制器A上、將纜線從插槽3連接埠b（e3b）移至插槽7連接埠b（e7b）。
.. 在控制器B上重複相同的纜線移動


--
.AFF A400 或 AFF C400
--
如果您要熱新增第二個機櫃、請根據您的平台模式執行下列其中一項：

** 在 AFF A400 上：
+
可在每個控制器的兩組具備 ROCE 功能的連接埠（內建 e0c/e0d 和插槽 5 ）中、重新放置第一個機櫃。

+
子步驟假設現有機櫃已連接至每個控制器上具有 ROCE 功能的板載連接埠 e0c/e0d 。

+
... 在控制器A上、將纜線從連接埠e0d移至插槽5連接埠b（e5b）。
... 在控制器B上重複相同的纜線移動


** 在 AFF C400 上：
+
在每個控制器的插槽 4 和插槽 5 中、將第一個機櫃放在兩組具備切換功能的連接埠上。

+
子步驟假設現有機櫃已連接至每個控制器插槽 4 中具有切入功能的連接埠。

+
... 在控制器A上、將纜線從插槽4連接埠A（E4A）移至插槽5連接埠b（e5b）。
... 在控制器B上重複相同的纜線移動




--
.解答900 AFF
--
如果您要熱新增第二個機櫃或第四個機櫃、請執行下列其中一項操作。

** 如果您要熱新增第二個機櫃、請在每個控制器的插槽 2 和插槽 10 中、將第一個機櫃重新放置在具有切換功能的 I/O 模組上。
+
子步驟假設現有機櫃已連接至每個控制器上插槽 2 中具有切入功能的 I/O 模組。

+
... 在控制器A上、將纜線從插槽2連接埠b（e2b）移至插槽10連接埠b（e10b）。
... 在控制器B上重複相同的纜線移動


** 如果您要熱新增第四個機櫃、請在每個控制器的插槽 1 和插槽 11 中、將第三個機櫃重新放置在具有切換功能的 I/O 模組上。
+
子步驟假設第三個機櫃已連接至每個控制器上插槽 1 中具有切入功能的 I/O 模組。

+
... 在控制器A上、將纜線從插槽1連接埠b（e1b）移至插槽11連接埠b（e11b）。
... 在控制器B上重複相同的纜線移動




--
.AFF A30 ， AFF C30 ， AFF A50 或 AFF C60
--
如果您要熱新增第二個機櫃、請在每個控制器的插槽 3 和插槽 1 中、將第一個機櫃重新放置在具有切換功能的 I/O 模組上。

子步驟假設現有機櫃已連接至每個控制器上插槽 3 中具有切入功能的 I/O 模組。

.. 在控制器A上、將纜線從插槽3連接埠b（e3b）移至插槽1連接埠b（e1b）。
.. 在控制器B上重複相同的纜線移動


--
====


* 對於 ASA 系統：
+
[role="tabbed-block"]
====
.ASA A1K
--
如果您要熱新增第二個機櫃或第四個機櫃、請執行下列其中一項操作。


NOTE: 如果您有 ASA A1K HA 配對、而且您正在熱新增第三個機櫃、並在每個控制器中安裝第三個或第四個具備 ROCE 功能的 I/O 模組、則第三個機櫃只能連接到第三個或第三個和第四個 I/O 模組。您不需要重新配置任何現有的機櫃。

** 如果您要熱新增第二個機櫃、請在每個控制器的插槽 11 和插槽 10 中、將第一個機櫃重新放置在具有切換功能的 I/O 模組上。
+
子步驟假設現有機櫃已連接至每個控制器上插槽 11 中具有切入功能的 I/O 模組。

+
... 在控制器A上、將纜線從插槽11連接埠b（e11b）移至插槽10連接埠b（e10b）。
... 在控制器B上重複相同的纜線移動


** 如果您要熱新增第四個機櫃、請在每個控制器的插槽 9 和插槽 8 中、將第三個機櫃重新放置在具有切換功能的 I/O 模組上。
+
子步驟假設第三個機櫃已連接至每個控制器上插槽 9 中具有切入功能的 I/O 模組。

+
... 在控制器A上、將纜線從插槽9連接埠b（e9b）移至插槽8連接埠b（e8b）。
... 在控制器B上重複相同的纜線移動




--
.ASA A70 或 ASA A90
--
如果您要熱新增第二個機櫃、請在每個控制器的插槽 11 和插槽 8 中、將第一個機櫃重新放置在具有切換功能的 I/O 模組上。

子步驟假設現有機櫃已連接至每個控制器上插槽 11 中具有切入功能的 I/O 模組。

.. 在控制器A上、將纜線從插槽11連接埠b（e11b）移至插槽8連接埠b（e8b）。
.. 在控制器B上重複相同的纜線移動


--
.ASA A800 或 ASA C800
--
如果您要熱新增第二個機櫃、請在每個控制器的插槽 5 和插槽 3 的兩組具備切換功能的連接埠中重新放置第一個機櫃。

以下步驟假設現有的機櫃已連接至每個控制器插槽5中的可操作PCIe卡。

.. 在控制器A上、將纜線從插槽5連接埠b（e5b）移至插槽3連接埠b（e3b）。
.. 在控制器B上重複相同的纜線移動


--
.ASA A400 或 ASA C400
--
如果您要熱新增第二個機櫃、請根據您的平台模式執行下列其中一項：

** 在 ASA A400 上：
+
可在每個控制器的兩組具備 ROCE 功能的連接埠（內建 e0c/e0d 和插槽 5 ）中、重新放置第一個機櫃。

+
子步驟假設現有機櫃已連接至每個控制器上具有 ROCE 功能的板載連接埠 e0c/e0d 。

+
... 在控制器A上、將纜線從連接埠e0d移至插槽5連接埠b（e5b）。
... 在控制器B上重複相同的纜線移動


** 在 ASA C400 上：
+
在每個控制器的插槽 4 和插槽 5 中、將第一個機櫃放在兩組具備切換功能的連接埠上。

+
子步驟假設現有機櫃已連接至每個控制器插槽 4 中具有切入功能的連接埠。

+
... 在控制器A上、將纜線從插槽4連接埠A（E4A）移至插槽5連接埠b（e5b）。
... 在控制器B上重複相同的纜線移動




--
.ASA A900
--
如果您要熱新增第二個機櫃或第四個機櫃、請執行下列其中一項操作。

** 如果您要熱新增第二個機櫃、請在每個控制器的插槽 2 和插槽 10 中、將第一個機櫃重新放置在具有切換功能的 I/O 模組上。
+
子步驟假設現有機櫃已連接至每個控制器上插槽 2 中具有切入功能的 I/O 模組。

+
... 在控制器A上、將纜線從插槽2連接埠b（e2b）移至插槽10連接埠b（e10b）。
... 在控制器B上重複相同的纜線移動


** 如果您要熱新增第四個機櫃、請在每個控制器的插槽 1 和插槽 11 中、將第三個機櫃重新放置在具有切換功能的 I/O 模組上。
+
子步驟假設第三個機櫃已連接至每個控制器上插槽 1 中具有切入功能的 I/O 模組。

+
... 在控制器A上、將纜線從插槽1連接埠b（e1b）移至插槽11連接埠b（e11b）。
... 在控制器B上重複相同的纜線移動




--
.ASA A30 或 ASA A50
--
如果您要熱新增第二個機櫃、請在每個控制器的插槽 3 和插槽 1 中、將第一個機櫃重新放置在具有切換功能的 I/O 模組上。

子步驟假設現有機櫃已連接至每個控制器上插槽 3 中具有切入功能的 I/O 模組。

.. 在控制器A上、將纜線從插槽3連接埠b（e3b）移至插槽1連接埠b（e1b）。
.. 在控制器B上重複相同的纜線移動


--
====


. 使用驗證已重新連接的機架是否已正確連接 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]。
+
如果產生任何纜線錯誤、請遵循所提供的修正行動。





== 停用自動磁碟機指派

如果您要手動指派您要熱新增的 NS224 機櫃的磁碟機擁有權、則需要停用自動磁碟機指派（如果已啟用）。

如果您不確定應該手動指派磁碟機擁有權、或想要瞭解儲存系統的磁碟機擁有權原則自動指派、請前往 https://docs.netapp.com/us-en/ontap/disks-aggregates/disk-autoassignment-policy-concept.html["關於自動指派磁碟擁有權"^]。

.步驟
. 驗證是否已啟用自動磁碟指派：「torage disk option show」
+
您可以在任一節點上輸入命令。

+
如果啟用自動磁碟機指派、則輸出會顯示在 `on` 欄中 `Auto Assign` （針對每個節點）。

. 如果已啟用自動磁碟指派、請停用此功能：「torage disk option modify -node_node_name_-autodassign Off」（磁碟選項修改-node_node_name_-autodassign Off）
+
您必須停用兩個節點上的自動磁碟機指派。


