---
permalink: ns224/service-replace-nsm100.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, replace, impair, nvme, module, nsm, nondisruptive, drive, i/o, nsm, replace an nsm module 
summary: 您可以在開啟電源的NS224磁碟機櫃中、在不中斷營運的情況下、在I/O進行中、更換功能受損的NVMe磁碟櫃模組（NSM）。 
---
= 更換NSM模組- NS224磁碟櫃
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在開啟電源的NS224磁碟機櫃中、在不中斷營運的情況下、在I/O進行中、更換功能受損的NVMe磁碟櫃模組（NSM）。

.開始之前
* 磁碟櫃的合作夥伴NSM模組必須已啟動且正在執行、而且纜線必須正確連接、以便在移除故障的NSM模組時、磁碟櫃仍能維持連線。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp下載Config Advisor"^]

* 系統中的所有其他元件必須正常運作。


.關於這項工作
* 更換NSM模組需要將DIMM、風扇和電源供應器從受損的NSM模組移至更換的NSM模組。
+
您不會移動即時時鐘（RTc）電池或開機媒體。它們已預先安裝在替換的NSM模組中。

* 在移除和安裝NVMe機櫃模組（NSM）之間、請至少等待70秒。
+
這讓ONTAP 我們有足夠的時間來處理NSM移除事件。

* *最佳實務做法：*最佳實務做法是在更換FRU元件之前、先在系統上安裝最新版本的NVMe機櫃模組（NSM）韌體和磁碟機韌體。
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp下載：磁碟櫃韌體"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp下載：磁碟機韌體"^]

+
[NOTE]
====
請勿將韌體還原至不支援機櫃及其元件的版本。

====
* 機櫃（NSM）韌體會在新的NSM模組上自動更新（不中斷營運）、該模組的韌體版本為非最新版本。
+
NSM模組韌體檢查每10分鐘進行一次。NSM模組韌體更新最多可能需要30分鐘。

* 如有需要、您可以開啟機櫃的位置（藍色）LED、以協助實際找出受影響的機櫃：「儲存櫃位置導向的修改-機櫃名稱_bidle_name_-leide-Status on」
+
如果您不知道受影響機櫃的「shelf_name」、請執行「shorage shelage show」命令。

+
機櫃有三個位置LED：一個在操作員顯示面板上、一個在每個NSM模組上。位置LED會持續亮起30分鐘。您可以輸入相同的命令來關閉它們、但可以使用「Off」（關閉）選項。

* 當您打開替換NSM模組的包裝時、請保留所有包裝材料、以便在退回故障的NSM模組時使用。
+
如果您需要RMA號碼或更換程序的其他協助、請聯絡技術支援部門： https://mysupport.netapp.com/site/global/dashboard["NetApp支援"^]電話：888-463-8277（北美）、00-800-44-638277（歐洲）或+800-800-80-800（亞太地區）。

* 您可以使用下列影片或書面步驟來更換NSM模組。
+
.動畫-更換NS224磁碟機櫃中的NSM模組
video::f57693b3-b164-4014-a827-aa86002f4b34[panopto]


.步驟
. 請妥善接地。
. 實體識別受損的NSM模組。
+
系統會將警告訊息記錄到系統主控台、指出哪個模組受損。此外、磁碟機櫃操作員顯示面板和受損模組上的警示（黃色）LED會亮起。

. 從受損的NSM模組拔下纜線：
+
.. 打開電源線固定器、從電源供應器拔下電源線、然後從電源供應器拔下電源線。
+
電源供應器沒有電源開關。

.. 從NSM模組連接埠拔下儲存設備纜線。
+
記下每條纜線所連接的NSM模組連接埠。您可以將纜線重新連接至替換NSM模組上的相同連接埠、稍後將在本程序中進行。



. 從機櫃中移除NSM模組：
+
.. 將您的索引手指繞過NSM模組兩側閉鎖機制的指孔。
+

NOTE: 如果您要移除底部NSM模組、而且底部軌道阻礙了鎖定機制的存取、請將指標手指從內側的指孔中（手臂交叉）放置。

.. 用您的拇指按住鎖定機制頂端的橘色彈片。
+
鎖定機制會舉起、清除機櫃上的鎖定銷。

.. 輕拉直到NSM模組離開機櫃約三分之一、用兩隻手抓住NSM模組兩側以支撐其重量、然後將其放在平穩的表面上。
+
當您開始拉動時、閉鎖機制臂會從NSM模組延伸、並鎖定在完全展開的位置。



. 打開替換NSM模組的包裝、並將其放置在靠近受損NSM模組的水平表面。
. 打開受損NSM模組和替換NSM模組的機箱蓋、方法是鬆開每個機箱蓋的指旋螺絲。
+

NOTE: NSM模組護蓋上的FRU標籤會顯示DIMM和風扇的位置。

. 將DIMM從受損的NSM模組移至替換的NSM模組。
+
.. 請注意插槽中的DIMM方向、以便您可以使用相同方向將DIMM插入替換的NSM模組。
.. 緩慢地將DIMM插槽兩端的彈出彈出彈片分開、然後將DIMM從插槽中取出。
+

NOTE: 小心拿住DIMM的邊角或邊緣、避免對DIMM電路板元件造成壓力。推出式彈片仍保持在開啟位置。

.. 拿住DIMM的邊角、然後將DIMM正面插入替換NSM模組的插槽。
+
DIMM底部插針之間的槽口應與插槽中的卡舌對齊。

+
正確插入時、DIMM應可輕鬆插入、但應緊密插入插槽中。如果沒有、請重新插入DIMM。

.. 小心地向下推DIMM頂端邊緣、但穩固地推入、直到彈出彈片卡入DIMM兩端的槽口為止。
.. 對其餘的DIMM重複執行步驟7a到7d。


. 將受損的NSM模組中的風扇移至更換的NSM模組。
+
.. 從藍色接觸點所在的側邊牢牢抓住風扇、然後垂直提起風扇、將其從插槽拔下。
+
您可能需要前後輕搖風扇、才能將其拔除、然後再將其取出。

.. 將風扇對準替換NSM模組中的導軌、然後向下推、直到風扇模組連接器完全插入插槽。
.. 對其餘風扇重複執行步驟8a和8b。


. 合上每個NSM模組的機箱蓋、然後鎖緊每個指旋螺絲。
. 將電源供應器從受損的NSM模組移至更換的NSM模組。
+
.. 將CAM握把旋轉至其開啟（水平）位置、然後加以抓住。
.. 用您的姆指按下藍色彈片以釋放鎖定機制。
.. 將電源供應器從NSM模組中拉出、同時用另一隻手支撐其重量。
.. 用手支撐並將電源供應器邊緣與替換NSM模組的開孔對齊。
.. 將電源供應器輕推入NSM模組、直到鎖定機制卡入定位。
+

NOTE: 請勿過度施力、否則可能會損壞內部接頭。

.. 將CAM握把旋轉至閉模位置。


. 將替換的NSM模組插入機櫃：
+
.. 確定鎖定機制臂鎖定在完全延伸位置。
.. 用兩隻手將NSM模組輕推入機櫃、直到機櫃完全支撐NSM模組的重量為止。
.. 將NSM模組推入機櫃、直到停止為止（距離機櫃背面約半英吋）。
+
您可以將拇指放在每個指環（鎖定機制臂）前方的橘色彈片上、以推入NSM模組。

.. 將您的索引手指繞過NSM模組兩側閉鎖機制的指孔。
+

NOTE: 如果您要插入底部NSM模組、而且底部軌道阻礙了鎖定機制的存取、請將指標手指從內側的指孔中（手臂交叉）放置。

.. 用您的拇指按住鎖定機制頂端的橘色彈片。
.. 向前輕推、將栓鎖移到停止點上方。
.. 從鎖定機制頂端釋放您的指稱、然後繼續推動、直到鎖定機制卡入定位為止。
+
NSM模組應完全插入機櫃、並與機櫃邊緣齊平。



. 將纜線重新連接至NSM模組：
+
.. 將儲存設備纜線重新連接至相同的兩個NSM模組連接埠。
+
插入纜線時、連接器拉片朝上。正確插入纜線時、會卡入定位。

.. 將電源線重新連接至電源供應器、然後使用電源線固定器固定電源線。
+
當電源供應器正常運作時、雙色LED會亮起綠燈。

+
此外、NSM模組連接埠LnK（綠色）LED也會亮起。如果LNO LED未亮起、請重新拔插纜線。



. 確認機櫃操作員顯示面板上的警示（黃色）LED不再亮起。
+
NSM模組重新開機後、操作員顯示面板注意LED會關閉。這可能需要三到五分鐘的時間。

. 執行Active IQ Config Advisor 下列動作、確認NSM模組的纜線正確連接。
+
如果產生任何纜線錯誤、請遵循所提供的修正行動。

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp下載Config Advisor"^]


