---
permalink: ns224/service-replace-rtc-battery.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, replace, fail, real-time, clock, rtc, battery, nondisruptive, power, i/o, replace the real-time clock battery 
summary: 您可以在開啟電源的NS224磁碟機櫃中、以及I/O進行中、不中斷地更換故障的即時時鐘（RTC\）電池。 
---
= 更換即時時鐘電池- NS224磁碟櫃
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在開啟電源的NS224磁碟機櫃中、以及I/O進行中、不中斷地更換故障的即時時鐘（RTC）電池。

.開始之前
* 磁碟櫃的合作夥伴NSM模組必須已啟動且正在執行、而且纜線必須正確連接、以便在移除故障FRU的NSM模組（目標NSM模組）時、磁碟櫃仍能維持連線。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp下載Config Advisor"^]

* 系統中的所有其他元件必須正常運作。


.關於這項工作
* 在移除和安裝NVMe機櫃模組（NSM）之間、請至少等待70秒。
+
這讓ONTAP 我們有足夠的時間來處理NSM移除事件。

* *最佳實務做法：*最佳實務做法是在更換FRU元件之前、先在系統上安裝最新版本的NVMe機櫃模組（NSM）韌體和磁碟機韌體。
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp下載：磁碟櫃韌體"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp下載：磁碟機韌體"^]

+
[NOTE]
====
請勿將韌體還原至不支援機櫃及其元件的版本。

====
* 如有需要、您可以開啟機櫃的位置（藍色）LED、以協助實際找出受影響的機櫃：「儲存櫃位置導向的修改-機櫃名稱_bidle_name_-leide-Status on」
+
如果您不知道受影響機櫃的「shelf_name」、請執行「shorage shelage show」命令。

+
機櫃有三個位置LED：一個在操作員顯示面板上、一個在每個NSM模組上。位置LED會持續亮起30分鐘。您可以輸入相同的命令來關閉它們、但可以使用「Off」（關閉）選項。

* 當您打開更換的RTC電池時、請保留所有包裝材料、以便在退回故障的RTC電池時使用。
+
如果您需要RMA號碼或更換程序的其他協助、請聯絡技術支援部門： https://mysupport.netapp.com/site/global/dashboard["NetApp支援"^]電話：888-463-8277（北美）、00-800-44-638277（歐洲）或+800-800-80-800（亞太地區）。

* 您可以使用下列視訊或書面步驟來更換RTC電池。
+
.動畫-在NS224磁碟機櫃中更換一顆RTC電池
video::df7a12f4-8554-4448-a3df-aa86002f2de8[panopto]


.步驟
. 請妥善接地。
. 從包含您要更換之FRU的NSM模組拔下纜線：
+
.. 打開電源線固定器、從電源供應器拔下電源線、然後從電源供應器拔下電源線。
+
電源供應器沒有電源開關。

.. 從NSM模組連接埠拔下儲存設備纜線。
+
記下每條纜線所連接的NSM模組連接埠。重新插入NSM模組時、請將纜線重新連接至相同的連接埠、稍後再執行此程序。



. 從機櫃中移除NSM模組：
+
.. 將您的索引手指繞過NSM模組兩側閉鎖機制的指孔。
+

NOTE: 如果您要移除底部NSM模組、而且底部軌道阻礙了鎖定機制的存取、請將指標手指從內側的指孔中（手臂交叉）放置。

.. 用您的拇指按住鎖定機制頂端的橘色彈片。
+
鎖定機制會舉起、清除機櫃上的鎖定銷。

.. 輕拉直到NSM模組離開機櫃約三分之一、用兩隻手抓住NSM模組兩側以支撐其重量、然後將其放在平穩的表面上。
+
當您開始拉動時、閉鎖機制臂會從NSM模組延伸、並鎖定在完全展開的位置。



. 鬆開NSM模組護蓋指旋螺絲、然後打開護蓋。
+
NSM模組護蓋上的FRU標籤顯示了RTC電池的位置、靠近NSM模組正面和電源供應器右側。

. 實體識別故障的RTC電池。
+
位於電池插槽旁的主機板上的「RTC電池注意（黃色）」LED會亮起。

+

NOTE: 從機櫃中取出NSM模組後、故障的RTC電池LED會持續亮起10分鐘。

. 更換RTC電池：
+
.. 從電池座中輕推電池、直到電池呈斜角（從電池座上斜放）、然後將其從電池座中取出。
.. 將替換電池以斜角（從電池座向外傾斜）插入電池座、將電池推入直立位置、然後將電池穩固地壓入連接器、直到電池完全就位。
+

NOTE: 電池的正向側（標有加號）朝向外（遠離電池座）、對應於NSM模組板上標示的加號。



. 合上NSM模組護蓋、然後鎖緊指旋螺絲。
. 將NSM模組重新插入機櫃：
+
.. 確定鎖定機制臂鎖定在完全延伸位置。
.. 用兩隻手將NSM模組輕推入機櫃、直到機櫃完全支撐NSM模組的重量為止。
.. 將NSM模組推入機櫃、直到停止為止（距離機櫃背面約半英吋）。
+
您可以將拇指放在每個指環（鎖定機制臂）前方的橘色彈片上、以推入NSM模組。

.. 將您的索引手指繞過NSM模組兩側閉鎖機制的指孔。
+

NOTE: 如果您要插入底部NSM模組、而且底部軌道阻礙了鎖定機制的存取、請將指標手指從內側的指孔中（手臂交叉）放置。

.. 用您的拇指按住鎖定機制頂端的橘色彈片。
.. 向前輕推、將栓鎖移到停止點上方。
.. 從鎖定機制頂端釋放您的指稱、然後繼續推動、直到鎖定機制卡入定位為止。
+
NSM模組應完全插入機櫃、並與機櫃邊緣齊平。



. 將纜線重新連接至NSM模組：
+
.. 將儲存設備纜線重新連接至相同的兩個NSM模組連接埠。
+
插入纜線時、連接器拉片朝上。正確插入纜線時、會卡入定位。

.. 將電源線重新連接至電源供應器、然後使用電源線固定器固定電源線。
+
當電源供應器正常運作時、雙色LED會亮起綠燈。

+
此外、NSM模組連接埠LnK（綠色）LED也會亮起。如果LNO LED未亮起、請重新拔插纜線。



. 確認NSM模組上包含故障的RTC電池和機櫃操作員顯示面板的警示（黃色）LED不再亮起
+
NSM模組重新開機後、NSM模組警示LED會關閉、而且不會再偵測到任何RTC電池問題。這可能需要三到五分鐘的時間。

. 執行Active IQ Config Advisor 下列動作、確認NSM模組的纜線正確連接。
+
如果產生任何纜線錯誤、請遵循所提供的修正行動。

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp下載Config Advisor"^]


