---
permalink: ns224/service-replace-boot-media.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, boot, media, run, ontap, nvme, module, nsm, firmware, version, nondisruptive, i/o 
summary: 當在執行ONTAP 更新版本的HA配對中、NS224磁碟機櫃上的開機媒體故障、或磁碟櫃執行NVMe機櫃模組（NSM\）韌體版本1.1x或更新版本時、您可以更換開機媒體。更換開機媒體時、磁碟機櫃電源開啟且I/O正在進行中、無需中斷營運即可完成。 
---
= 更換開機媒體- NS224磁碟櫃
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當在執行ONTAP 更新版本的HA配對中、NS224磁碟機櫃上的開機媒體故障、或磁碟櫃執行NVMe機櫃模組（NSM）韌體版本0111或更新版本時、您可以更換開機媒體。更換開機媒體時、磁碟機櫃電源開啟且I/O正在進行中、無需中斷營運即可完成。

.開始之前
* 您的HA配對必須已執行ONTAP 支援NSM韌體最低版本的更新版本、或者HA配對必須已執行ONTAP NSM韌體版本0111或更新版本的版本。
+
您可以在任一控制器的主控台輸入「儲存櫃show -module'命令、以驗證機櫃上的NSM韌體版本。

+
[NOTE]
====
如果您的機櫃未執行NSM韌體版本0111或更新版本、則無法更換開機媒體、您必須更換NSM模組。

link:service-replace-nsm100.html["更換NSM模組- NS224磁碟櫃"^]

====
* 您需要一把飛利浦#1螺絲起子。
+
用於將開機媒體固定至主機板的螺絲需要使用一號十字螺絲起子；使用不同類型的螺絲起子可能會使螺絲脫開。

* 磁碟櫃的合作夥伴NSM模組必須已啟動且正在執行、而且纜線必須正確連接、以便在移除故障FRU的NSM模組（目標NSM模組）時、磁碟櫃仍能維持連線。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp下載Config Advisor"^]

* 系統中的所有其他元件必須正常運作。


.關於這項工作
* 更換開機媒體之後、磁碟櫃的合作夥伴NSM模組的開機映像會自動複製到更換的開機媒體。
+
這可能需要五分鐘的時間。

* 在移除和安裝NVMe機櫃模組（NSM）之間、請至少等待70秒。
+
這讓ONTAP 我們有足夠的時間來處理NSM移除事件。

* 如有需要、您可以開啟機櫃的位置（藍色）LED、以協助實際找出受影響的機櫃：「儲存櫃位置導向的修改-機櫃名稱_bidle_name_-leide-Status on」
+
如果您不知道受影響的機櫃的「_shider_name_」、請執行「shorage sh儲存 櫃show」命令。

+
機櫃有三個位置LED：一個在操作員顯示面板上、一個在每個NSM模組上。位置LED會持續亮起30分鐘。您可以輸入相同的命令來關閉它們、但可以使用「Off」（關閉）選項。

* 更換開機媒體之後、您可以依照套件隨附的RMA指示、將故障零件退回NetApp。
+
如果您需要RMA號碼或更換程序的其他協助、請聯絡技術支援部門： https://mysupport.netapp.com/site/global/dashboard["NetApp支援"^]電話：888-463-8277（北美）、00-800-44-638277（歐洲）或+800-800-80-800（亞太地區）。

* 您可以使用下列動畫或書面步驟來取代開機媒體。
+
.動畫-更換NS224磁碟機櫃中的開機媒體
video::20ed85f9-1f80-4e0e-9219-ab4600070d8a[panopto]


.步驟
. 確定機櫃中的兩個NSM模組都執行相同版本的韌體：0200版或更新版本。
. 請妥善接地。
. 從包含您要更換之FRU的NSM模組拔下纜線：
+
.. 如果電源線是AC電源供應器、請打開電源線固定器、將電源線從電源供應器拔下；如果是DC電源供應器、請打開兩個指旋螺絲、然後從電源供應器拔下電源線。
+
電源供應器沒有電源開關。

.. 從NSM模組連接埠拔下儲存設備纜線。
+
記下每條纜線所連接的NSM模組連接埠。重新插入NSM模組時、請將纜線重新連接至相同的連接埠、稍後再執行此程序。



. 從機櫃中移除NSM模組：
+
.. 將您的索引手指繞過NSM模組兩側閉鎖機制的指孔。
+

NOTE: 如果您要移除底部NSM模組、而且底部軌道阻礙了鎖定機制的存取、請將指標手指從內側的指孔中（手臂交叉）放置。

.. 用您的拇指按住鎖定機制頂端的橘色彈片。
+
鎖定機制會舉起、清除機櫃上的鎖定銷。

.. 輕拉直到NSM模組離開機櫃約三分之一、用兩隻手抓住NSM模組兩側以支撐其重量、然後將其放在平穩的表面上。
+
當您開始拉動時、閉鎖機制臂會從NSM模組延伸、並鎖定在完全展開的位置。



. 鬆開NSM模組護蓋指旋螺絲、然後打開護蓋。
. 實際找到故障的開機媒體。
+
開機媒體位於與電源供應器相對的機櫃機箱牆上。

. 更換開機媒體：
+
.. 使用1號十字螺絲起子、小心地移除將開機媒體底部（有缺口）端固定至主機板的螺絲。
.. 將開機媒體稍微向上旋轉、然後朝自己的方向輕拉、直到其從插槽中釋放、即可將其取出。
+
您可以將姆指和手指放在側邊邊緣的缺口末端、以容納開機媒體

.. 從防靜電袋中打開開機媒體的包裝。
.. 將替換的開機媒體輕推入插槽、直到它完全和正面地插入插槽。
+
您可以將姆指和手指放在側邊邊緣的缺口末端、以容納開機媒體請確定散熱片的一側朝上。

+
當正確就位、當您離開開機媒體時、開機媒體的缺口端會向上調整、使其遠離主機板、因為它尚未使用螺絲固定。

.. 插入開機媒體時、請輕壓開機媒體的缺口端、然後使用螺絲起子鎖緊螺絲、將開機媒體固定到位。
+

NOTE: 將螺絲鎖緊至足以將開機媒體牢牢固定到位的程度、但請勿過度鎖緊。



. 合上NSM模組護蓋、然後鎖緊指旋螺絲。
. 將NSM模組重新插入機櫃：
+
.. 確定鎖定機制臂鎖定在完全延伸位置。
.. 用兩隻手將NSM模組輕推入機櫃、直到機櫃完全支撐NSM模組的重量為止。
.. 將NSM模組推入機櫃、直到停止為止（距離機櫃背面約半英吋）。
+
您可以將拇指放在每個指環（鎖定機制臂）前方的橘色彈片上、以推入NSM模組。

.. 將您的索引手指繞過NSM模組兩側閉鎖機制的指孔。
+

NOTE: 如果您要插入底部NSM模組、而且底部軌道阻礙了鎖定機制的存取、請將指標手指從內側的指孔中（手臂交叉）放置。

.. 用您的拇指按住鎖定機制頂端的橘色彈片。
.. 向前輕推、將栓鎖移到停止點上方。
.. 從鎖定機制頂端釋放您的指稱、然後繼續推動、直到鎖定機制卡入定位為止。
+
NSM模組應完全插入機櫃、並與機櫃邊緣齊平。



. 將纜線重新連接至NSM模組：
+
.. 將儲存設備纜線重新連接至相同的兩個NSM模組連接埠。
+
插入纜線時、連接器拉片朝上。正確插入纜線時、會卡入定位。

.. 將電源線重新連接至電源供應器、如果是AC電源供應器、請將電源線與電源線固定器固定、如果是DC電源供應器、請將兩顆指旋螺絲鎖緊。
+
當電源供應器正常運作時、雙色LED會亮起綠燈。

+
此外、NSM模組連接埠LnK（綠色）LED也會亮起。如果LNO LED未亮起、請重新拔插纜線。



. 確認NSM模組上包含故障開機媒體和機櫃操作員顯示面板的警示（黃色）LED不再亮起。
+
注意LED可能需要5到10分鐘的時間才能關閉。這是NSM模組重新開機和開機媒體映像複本完成所需的時間。

+
如果故障LED持續亮起、表示開機媒體可能未正確就位、或是有其他問題、您應聯絡技術支援部門以尋求協助。

. 執行Active IQ Config Advisor 下列動作、確認NSM模組的纜線正確連接。
+
如果產生任何纜線錯誤、請遵循所提供的修正行動。

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp下載Config Advisor"^]


