---
permalink: ns224/service-replace-dimm.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, replace, nondisruptive, dimm, i/o, replace a dimm 
summary: 您可以在開啟電源的NS224磁碟機櫃中、以及I/O進行中、不中斷地更換故障的DIMM。 
---
= 更換DIMM - NS224磁碟櫃
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在開啟電源的NS224磁碟機櫃中、以及I/O進行中、不中斷地更換故障的DIMM。

.開始之前
* 磁碟櫃的合作夥伴NSM模組必須已啟動且正在執行、而且纜線必須正確連接、以便在移除故障FRU的NSM模組（目標NSM模組）時、磁碟櫃仍能維持連線。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp下載Config Advisor"^]

* 系統中的所有其他元件、包括其他三個DIMM、都必須正常運作。


.關於這項工作
* 在移除和安裝NVMe機櫃模組（NSM）之間、請至少等待70秒。
+
這讓ONTAP 我們有足夠的時間來處理NSM移除事件。

* *最佳實務做法：*最佳實務做法是在更換FRU元件之前、先在系統上安裝最新版本的NVMe機櫃模組（NSM）韌體和磁碟機韌體。
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp下載：磁碟櫃韌體"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp下載：磁碟機韌體"^]

+
[NOTE]
====
請勿將韌體還原至不支援機櫃及其元件的版本。

====
* 如有需要、您可以開啟機櫃的位置（藍色）LED、以協助實際找出受影響的機櫃：「儲存櫃位置導向的修改-機櫃名稱_bidle_name_-leide-Status on」
+
如果您不知道受影響的機櫃的「_shider_name_」、請執行「shorage sh儲存 櫃show」命令。

+
機櫃有三個位置LED：一個在操作員顯示面板上、一個在每個NSM模組上。位置LED會持續亮起30分鐘。您可以輸入相同的命令來關閉它們、但可以使用「Off」（關閉）選項。

* 當您打開更換的DIMM的包裝時、請保留所有包裝材料、以便在退回故障的DIMM時使用。
+
如果您需要RMA號碼或更換程序的其他協助、請聯絡技術支援部門： https://mysupport.netapp.com/site/global/dashboard["NetApp支援"^]電話：888-463-8277（北美）、00-800-44-638277（歐洲）或+800-800-80-800（亞太地區）。

* 您可以使用下列動畫或書面步驟來更換DIMM。
+
.更換 NS224 機櫃中的 DIMM
video::eef28b10-ed93-4aa7-bfce-aa86002f20a2[panopto]


.步驟
. 請妥善接地。
. 從包含您要更換之FRU的NSM模組拔下纜線：
+
.. 如果電源線是AC電源供應器、請打開電源線固定器、將電源線從電源供應器拔下；如果是DC電源供應器、請打開兩個指旋螺絲、然後從電源供應器拔下電源線。
+
電源供應器沒有電源開關。

.. 從NSM模組連接埠拔下儲存設備纜線。
+
記下每條纜線所連接的NSM模組連接埠。重新插入NSM模組時、請將纜線重新連接至相同的連接埠、稍後再執行此程序。



. 從機櫃中移除NSM模組：
+
.. 將您的索引手指繞過NSM模組兩側閉鎖機制的指孔。
+

NOTE: 如果您要移除底部NSM模組、而且底部軌道阻礙了鎖定機制的存取、請將指標手指從內側的指孔中（手臂交叉）放置。

.. 用您的拇指按住鎖定機制頂端的橘色彈片。
+
鎖定機制會舉起、清除機櫃上的鎖定銷。

.. 輕拉直到NSM模組離開機櫃約三分之一、用兩隻手抓住NSM模組兩側以支撐其重量、然後將其放在平穩的表面上。
+
當您開始拉動時、閉鎖機制臂會從NSM模組延伸、並鎖定在完全展開的位置。



. 鬆開NSM模組護蓋指旋螺絲、然後打開護蓋。
+
NSM模組護蓋上的FRU標籤顯示四個DIMM的位置、兩個位於散熱器兩側的NSM模組中央。

. 實體識別故障的DIMM。
+
當DIMM故障時、系統會將警告訊息記錄到系統主控台、指出哪個DIMM故障。

. 更換故障DIMM：
+
.. 請注意插槽中的DIMM方向、以便您可以使用相同方向插入替換的DIMM。
.. 緩慢地將DIMM插槽兩端的彈出彈出彈片分開、然後將DIMM從插槽中提出、藉此將DIMM從插槽中退出。
+

NOTE: 小心拿住DIMM的邊角或邊緣、避免對DIMM電路板元件造成壓力。

+
推出式彈片仍保持在開啟位置。

.. 從防靜電包裝袋中取出備用DIMM。
.. 拿住DIMM的邊角、然後將DIMM正面插入插槽。
+
DIMM底部插針之間的槽口應與插槽中的卡舌對齊。

+
正確插入時、DIMM應可輕鬆插入、但應緊密插入插槽中。如果沒有、請重新插入DIMM。

.. 小心地向下推DIMM頂端邊緣、但穩固地推入、直到彈出彈片卡入DIMM兩端的槽口為止。


. 合上NSM模組護蓋、然後鎖緊指旋螺絲。
. 將NSM模組重新插入機櫃：
+
.. 確定鎖定機制臂鎖定在完全延伸位置。
.. 用兩隻手將NSM模組輕推入機櫃、直到機櫃完全支撐NSM模組的重量為止。
.. 將NSM模組推入機櫃、直到停止為止（距離機櫃背面約半英吋）。
+
您可以將拇指放在每個指環（鎖定機制臂）前方的橘色彈片上、以推入NSM模組。

.. 將您的索引手指繞過NSM模組兩側閉鎖機制的指孔。
+

NOTE: 如果您要插入底部NSM模組、而且底部軌道阻礙了鎖定機制的存取、請將指標手指從內側的指孔中（手臂交叉）放置。

.. 用您的拇指按住鎖定機制頂端的橘色彈片。
.. 向前輕推、將栓鎖移到停止點上方。
.. 從鎖定機制頂端釋放您的指稱、然後繼續推動、直到鎖定機制卡入定位為止。
+
NSM模組應完全插入機櫃、並與機櫃邊緣齊平。



. 將纜線重新連接至NSM模組：
+
.. 將儲存設備纜線重新連接至相同的兩個NSM模組連接埠。
+
插入纜線時、連接器拉片朝上。正確插入纜線時、會卡入定位。

.. 將電源線重新連接至電源供應器、如果是AC電源供應器、請將電源線與電源線固定器固定、如果是DC電源供應器、請將兩顆指旋螺絲鎖緊。
+
當電源供應器正常運作時、雙色LED會亮起綠燈。

+
此外、NSM模組連接埠LnK（綠色）LED也會亮起。如果LNO LED未亮起、請重新拔插纜線。



. 確認包含故障DIMM的NSM模組上的警示（黃色）LED和機櫃操作員顯示面板不再亮起。
+
NSM模組重新開機後、NSM模組警示LED會關閉、而且不會再偵測到DIMM問題。這可能需要三到五分鐘的時間。

. 執行Active IQ Config Advisor 下列動作、確認NSM模組的纜線正確連接。
+
如果產生任何纜線錯誤、請遵循所提供的修正行動。

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp下載Config Advisor"^]


